Repository Samsung/TizenFX, pull requests merged in 2018-08, with the labels that each got.

#359 [MediaPlayer] modify the precondition of Start method
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
Labels: API5

#360 [NUI] Change Parameter type of KeyboardRepeatInfo APIs
  src/Tizen.NUI/src/internal/ManualPINVOKE.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: ACR Required, API5

#362 [NUI] nui version 503
  packaging/version.txt
  src/Tizen.NUI/src/internal/VersionCheck.cs
Labels: API5

#364 typo correction
  src/Tizen.System/Device/Haptic.cs
Labels: API5

#368 [Tizen.Applications.Common] [RPCPort] Fix a bug about calling wrong native API
  src/Tizen.Applications.Common/Tizen.Applications.RPCPort/StubBase.cs
Labels: API5

#367 [MediaContent] Added exception handling to catch p/invoke error return
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/PlaylistCommand.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/StorageCommand.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/TagCommand.cs
Labels: API5

#358 [Connection] Remove deprecated API
  src/Tizen.Network.Connection/Interop/Interop.Connection.cs
Labels: API5

#370 Add AvailableSpace property and deprecate AvaliableSpace
  src/Tizen.System.Storage/Storage/Storage.cs
Labels: ACR Required, API5

#369 [OpenTK] Don't call 'LoadAll' on Tizen for discreasing the launching time
  external/src/OpenTK/OpenTK/GameWindow.cs
Labels: API5

#376 Revert "[NUI] NUI Integration (#361)"
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API5

#375 [ElmSharp] Fix Spinner Style on TV
  src/ElmSharp/ElmSharp/Spinner.cs
Labels: API5

#378 [ElmSharp] Add Save method in EvasImage
  src/ElmSharp/ElmSharp/EvasImage.cs
Labels: ACR Required, API5

#385 [Connection][WiFi] Remove duplicate codes
  src/Tizen.Network.Connection/Interop/Interop.Libraries.cs
  src/Tizen.Network.Connection/Tizen.Network.Connection/IAddressInformation.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAddressInformation.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiErrorFactory.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetworkChange.cs
Labels: API5

#383 [Storage][Fix api version]
  src/Tizen.System.Storage/Storage/Storage.cs
Labels: API5

#386 Fix issues detected by codacy
  src/Tizen.Content.Download/Tizen.Content.Download/DownloadErrorFactory.cs
  src/Tizen.Content.Download/Tizen.Content.Download/Notification.cs
  src/Tizen.Content.Download/Tizen.Content.Download/Request.cs
Labels: API5

#387 [NUI] Add friend assembly for Tizen.DA.NUI.UIComponents (inhouse API)
  src/Tizen.NUI/src/internal/FriendAssembly.cs
Labels: API4

#382 [Device]Add new apis
  src/Tizen.System/Device/Display.cs
  src/Tizen.System/Device/Power.cs
  src/Tizen.System/Interop/Interop.Device.cs
Labels: ACR Required, API5

#388 [Device][Deprecate RequestCpuLock and ReleaseCpuLock]
  src/Tizen.System/Device/Power.cs
Labels: API5

#390 [NUI] Support software styling
  src/Tizen.NUI/src/internal/ManualPINVOKE.cs
  src/Tizen.NUI/src/public/FontClient.cs
Labels: API5

#389 [ElmSharp] Add efl_util window property APIs in ElmSharp
  src/ElmSharp/ElmSharp/Window.cs
  src/ElmSharp/Interop/Interop.Eutil.WindowProperty.cs
  src/ElmSharp/Interop/Interop.Libraries.cs
  test/ElmSharp.Test/TC/WindowUtilTest.cs
  test/ElmSharp.Test/tizen-manifest.xml
Labels: ACR Required, API5

#381 [Tizen.Applications.DataControl] Fix wrong intprt check
  src/Tizen.Applications.DataControl/Tizen.Applications.DataControl/Consumer.cs
Labels: API5

#384 [ElmSharp] Cleanup code of ElmSharp
  src/ElmSharp/ElmSharp/AccessibleObject.cs
  src/ElmSharp/ElmSharp/Background.cs
  src/ElmSharp/ElmSharp/Calendar.cs
  src/ElmSharp/ElmSharp/Color.cs
  src/ElmSharp/ElmSharp/ColorSelector.cs
  src/ElmSharp/ElmSharp/Container.cs
  src/ElmSharp/ElmSharp/EdjeObject.cs
  src/ElmSharp/ElmSharp/FlipSelector.cs
  src/ElmSharp/ElmSharp/GenGrid.cs
  src/ElmSharp/ElmSharp/GenList.cs
  src/ElmSharp/ElmSharp/Hoversel.cs
  src/ElmSharp/ElmSharp/Index.cs
  src/ElmSharp/ElmSharp/ItemObject.cs
  src/ElmSharp/ElmSharp/MultiButtonEntry.cs
  src/ElmSharp/ElmSharp/NamedHint.cs
  src/ElmSharp/ElmSharp/Naviframe.cs
  src/ElmSharp/ElmSharp/Toolbar.cs
  src/ElmSharp/ElmSharp/Transit.cs
  src/ElmSharp/Interop/Interop.Ecore.cs
  src/ElmSharp/Interop/Interop.Elementary.Bg.cs
  src/ElmSharp/Interop/Interop.Elementary.Image.cs
  src/ElmSharp/Interop/Interop.Libdl.cs
Labels: ACR Required, API5

#392 [WiFi] Fix infinite recursion
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
Labels: API5

#394 Add exception handler for rpc-port-parcel
  src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs
Labels: API5

#399 [NUI] Integration from dalihub to Samsung
  src/Tizen.NUI/src/internal/Layouting/GridLayout.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutPINVOKE.cs
  src/Tizen.NUI/src/public/Animation.cs
  src/Tizen.NUI/src/public/BaseComponents/FlexContainer.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/GestureDetector.cs
  src/Tizen.NUI/src/public/LongPressGestureDetector.cs
  src/Tizen.NUI/src/public/PanGestureDetector.cs
  src/Tizen.NUI/src/public/PinchGestureDetector.cs
  src/Tizen.NUI/src/public/Property.cs
  src/Tizen.NUI/src/public/TapGestureDetector.cs
  src/Tizen.NUI/src/public/UIComponents/Slider.cs
  src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
Labels: ACR Required, API5

#400 [NUI] Gallery App button position issue
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API5

#373 [MediaVision] Fix an issue that callback was made on a garbage collected delegate
  src/Tizen.Multimedia.Vision/MediaVision/MovementDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/PersonAppearanceDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/PersonRecognizer.cs
  src/Tizen.Multimedia.Vision/MediaVision/SurveillanceEngine.cs
Labels: API5

#401 [ElmSharp] Fix SetNextFocusObject issue
  src/ElmSharp/ElmSharp/Widget.cs
Labels: API5, Need to merge API4

#403 [Build] Remove Generator.Rewrite
  tools/Tools.sln
  tools/bin/ABIChecker/ABIChecker.deps.json
  tools/bin/ABIChecker/ABIChecker.dll
  tools/bin/ABIChecker/ABIChecker.pdb
  tools/bin/ABIChecker/Newtonsoft.Json.dll
  tools/bin/GenDummy.Tasks/GenDummy.Tasks.dll
  tools/bin/GenDummy.Tasks/GenDummy.Tasks.pdb
  tools/bin/GenDummy.Tasks/GenDummy.dll
  tools/bin/GenDummy.Tasks/GenDummy.pdb
  tools/bin/GenDummy.Tasks/System.Linq.Parallel.dll
  tools/bin/Generator.Rewrite/CommandLine.dll
  tools/bin/Generator.Rewrite/Generator.Rewrite.deps.json
  tools/bin/Generator.Rewrite/Generator.Rewrite.dll
  tools/bin/Generator.Rewrite/Generator.Rewrite.pdb
  tools/bin/Generator.Rewrite/Generator.Rewrite.runtimeconfig.json
  tools/bin/Generator.Rewrite/Mono.Cecil.Mdb.dll
  tools/bin/Generator.Rewrite/Mono.Cecil.Pdb.dll
  tools/bin/Generator.Rewrite/Mono.Cecil.Rocks.dll
  tools/bin/Generator.Rewrite/Mono.Cecil.dll
  tools/build-tools.sh
  tools/src/Generator.Rewrite/CountAttribute.cs
  tools/src/Generator.Rewrite/GeneratedVariableIdentifier.cs
  tools/src/Generator.Rewrite/Generator.Rewrite.NETCore.csproj
  tools/src/Generator.Rewrite/OpenTKAssemblyResolver.cs
  tools/src/Generator.Rewrite/Options.cs
  tools/src/Generator.Rewrite/Program.cs
  tools/src/Generator.Rewrite/Properties/AssemblyInfo.cs
Labels: API5

#398 [Multimedia.MediaTool] Add APIs for rotation and flip
  src/Tizen.Multimedia/Common.Internal/RotationFlip.cs
  src/Tizen.Multimedia/Interop/Interop.MediaTool.cs
  src/Tizen.Multimedia/MediaTool/MediaPacket.cs
Labels: ACR Required, API5

#407 [NUI] Make vulkan constructor as InhouseAPI, Fix Codacy errors
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/NUIApplication.cs
Labels: ACR Required, API5

#406 [NUI] VisualMap, friend assembly, InputMethodContext related changes
  src/Tizen.NUI/src/internal/FriendAssembly.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/NUIConstants.cs
  src/Tizen.NUI/src/public/VisualMaps.cs
  test/NUITestSample/NUITestSample/examples/visual-test.cs
Labels: ACR Required, API5

#409 [AudioManager] Revise ToString() of AudioDevice class
  src/Tizen.Multimedia/AudioManager/AudioDevice.cs
Labels: API5

#410 [Device][Remove unused exception]
  src/Tizen.System/Device/Power.cs
Labels: API5

#379 [Camera] Add new preview data format and type
  src/Tizen.Multimedia.Camera/Camera/CameraEnums.cs
  src/Tizen.Multimedia.Camera/Camera/CameraException.cs
  src/Tizen.Multimedia.Camera/Camera/DepthPlane.cs
  src/Tizen.Multimedia.Camera/Camera/PreviewFrame.cs
  src/Tizen.Multimedia.Camera/Interop/Interop.Camera.cs
Labels: ACR Required, API5

#408 [NUI] Fix only to give children a layout in an explicit layout
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API5

#371 [Tizen.Network.Connection][Tizen.Network.WiFi][TCSACR-167] Add API to get DHCP lease duration
  src/Tizen.Network.Connection/Interop/Interop.Connection.cs
  src/Tizen.Network.Connection/Tizen.Network.Connection/IAddressInformation.cs
  src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAddressInformation.cs
Labels: ACR Required, API5

#413 [NUI] Fix RaiseToTop error
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/Container.cs
  src/Tizen.NUI/src/public/Layer.cs
  src/Tizen.NUI/src/public/Window.cs
  test/NUITestSample/NUITestSample/examples/RaiseToTopTest.cs
Labels: API5

#414 [NUI] Remove the unused resource-change callback.
  src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API5

#419 Revert "[NUI] Fix RaiseToTop error (#413)"
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/Container.cs
  src/Tizen.NUI/src/public/Layer.cs
  src/Tizen.NUI/src/public/Window.cs
  test/NUITestSample/NUITestSample/examples/RaiseToTopTest.cs
Labels: API5

#429 [Tizen.Applications] Add finalizer in TizenSyncronizationContext
  src/Tizen.Applications.Common/Interop/Interop.Glib.cs
  src/Tizen.Applications.Common/Tizen.Applications/TizenSynchronizationContext.cs
Labels: API5

#425 [AudioManager] Fix to use sound_manager_is_device_running_by_id() for…
  src/Tizen.Multimedia/AudioManager/AudioDevice.cs
  src/Tizen.Multimedia/Interop/Interop.Device.cs
Labels: API5

#415 English review for ApplicationInfoFilter.cs
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationInfoFilter.cs
Labels: API5

#437 Add description of shared/data policy
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationInfo.cs
Labels: API5

#430 [NUI] Fix raise top issue
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/Container.cs
  src/Tizen.NUI/src/public/Layer.cs
  src/Tizen.NUI/src/public/Window.cs
  test/NUITestSample/NUITestSample/examples/RaiseToTopTest.cs
Labels: API5

#426 Review of Storage
  src/Tizen.System.Storage/Storage/Storage.cs
  src/Tizen.System.Storage/Storage/StorageArea.cs
  src/Tizen.System.Storage/Storage/StorageDevice.cs
  src/Tizen.System.Storage/Storage/StorageManager.cs
Labels: API5

#431 English review
  src/Tizen.Multimedia/AudioManager/AudioManager.cs
Labels: API5
