Repository Samsung/TizenFX, pull requests merged in 2018-03, with the labels that each got.

#136 [Connection][WiFi]Apply TizenSynchronizationContext for event handling
  src/Tizen.Network.Connection/Tizen.Network.Connection.csproj
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi.csproj
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetworkChange.cs
Labels: API5

#137 [Tizen.Applications.DataControl] Fixed a bug for checking if IntPtr is null
  src/Tizen.Applications.DataControl/Tizen.Applications.DataControl/Consumer.cs
Labels: API4

#140 [Notification] Save the hidetime, deletetime value
  src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationStyleBinder.cs
Labels: API4

#139 [Notification] Save the hidetime, deletetime value
  src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationStyleBinder.cs
Labels: API5

#121 [TEEC] Make SharedMemory disposable
  src/Tizen.Security.TEEC/Tizen.Security.TEEC/Libteec.cs
Labels: API5

#138 [Connection][WiFi]Apply TizenSynchronizationContext for event handling
  src/Tizen.Network.Connection/Tizen.Network.Connection.csproj
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi.csproj
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetworkChange.cs
Labels: API4

#143 [NUI] Delete deprecated APIs
  src/Tizen.NUI/src/internal/Size.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/FocusManager.cs
  src/Tizen.NUI/src/public/Layer.cs
  src/Tizen.NUI/src/public/NUIConstants.cs
  src/Tizen.NUI/src/public/VisualFactory.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API5

#141 [NUI] Fix parent get issue
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API4

#146 [Connection][WiFi] Use TizenSynchronizationContext.Post for asynchron…
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetworkChange.cs
Labels: API5

#147 [Connection][WiFi] Use TizenSynchronizationContext.Post for asynchronous methods
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetworkChange.cs
Labels: API4

#150 [WiFi] Fix Dispose
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiConfiguration.cs
Labels: API5

#153 [Connection][WiFi] Ignore exception within event add/remove
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetworkChange.cs
Labels: API5

#154 [Connection][WiFi] Fix exception handling in async methods
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
Labels: API5

#158 [Connection][WiFi] Handling exception for event and async methods
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiConfiguration.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetworkChange.cs
Labels: API4

#160 [Connection][Network] Change Debug to Info for some Logs
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
Labels: API4

#163 Add build option for asan
  packaging/csapi-tizenfx.spec
Labels: API5

#164 Add build option for asan
  packaging/csapi-tizenfx.spec
Labels: API4

#165 [NUI] Make GetParent() protected
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/Container.cs
  src/Tizen.NUI/src/public/Layer.cs
Labels: API5

#167 Update csapi-tizenfx.spec.in to support asan
  packaging/csapi-tizenfx.spec.in
Labels: API4

#166 Update csapi-tizenfx.spec.in to support asan
  packaging/csapi-tizenfx.spec.in
Labels: API5

#168 Fix issue for multithreads
  src/Tizen.Applications.DataControl/Tizen.Applications.DataControl/Consumer.cs
Labels: API5

#162 [ElmSharp] Fix TrackObject issue
  src/ElmSharp/ElmSharp/ItemObject.cs
  src/ElmSharp/Interop/Interop.Elementary.Item.cs
  test/ElmSharp.Test/TC/ItemEvasObjectTest.cs
Labels: API5

#170 [ElmSharp] Modified to call Deleted event when EvasObject Unrealized
  src/ElmSharp/ElmSharp/EvasObject.cs
Labels: API5

#171 [Tizen.Applications.DataControl] Fix issue for multithreads
  src/Tizen.Applications.DataControl/Tizen.Applications.DataControl/Consumer.cs
Labels: API4

#172 [Information] Consider AV device as TV product
  src/Tizen.System.Information/RuntimeInfo/TvProductHelper.cs
Labels: API4

#173 [ElmSharp] fixed to parent.Handle for preventing potential bug
  src/ElmSharp/ElmSharp/GestureLayer.cs
  src/ElmSharp/ElmSharp/Image.cs
  src/ElmSharp/ElmSharp/Naviframe.cs
  src/ElmSharp/ElmSharp/Panel.cs
  src/ElmSharp/ElmSharp/Table.cs
Labels: API4

#175 [NUI] Fix widget application crash issue
  src/Tizen.NUI/src/internal/Registry.cs
Labels: API4

#176 Update GenDummy tool
  tools/GenDummy/GenDummy.dll
Labels: API5

#177 [NUI] Add _parent in Container
  packaging/version.txt
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/internal/DaliEnumConstants.cs
  src/Tizen.NUI/src/internal/FrameBuffer.cs
  src/Tizen.NUI/src/internal/ManualPINVOKE.cs
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
  src/Tizen.NUI/src/internal/Registry.cs
  src/Tizen.NUI/src/internal/VersionCheck.cs
  src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
  src/Tizen.NUI/src/public/BaseComponents/TableView.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/Container.cs
  src/Tizen.NUI/src/public/FocusManager.cs
  src/Tizen.NUI/src/public/Layer.cs
  src/Tizen.NUI/src/public/UIComponents/Popup.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API5

#183 [System][Usb] apply NotSupportedException
  src/Tizen.System.Usb/Usb/UsbManager.cs
Labels: API5

#184 [MediaPlayer] Modify the precondition of SetRoi method
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerDisplaySettings.cs
Labels: ACR Accepted, API5

#174 [ElmSharp] cherry-pick from API4 (#28)(#42)(#58)
  src/ElmSharp/ElmSharp/Background.cs
  src/ElmSharp/ElmSharp/GenItemClass.cs
  src/ElmSharp/ElmSharp/GestureLayer.cs
  src/ElmSharp/ElmSharp/Image.cs
Labels: API5

#187 Fix wrong code
  src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationStyleBinder.cs
Labels: API5

#188 Revert "[NUI] Delete deprecated APIs (#143)"
  src/Tizen.NUI/src/internal/Size.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/FocusManager.cs
  src/Tizen.NUI/src/public/Layer.cs
  src/Tizen.NUI/src/public/NUIConstants.cs
  src/Tizen.NUI/src/public/VisualFactory.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API5

#194 Revert "[NUI] Make GetParent() protected (#165)"
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/internal/DaliEnumConstants.cs
  src/Tizen.NUI/src/internal/FrameBuffer.cs
  src/Tizen.NUI/src/internal/ManualPINVOKE.cs
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
  src/Tizen.NUI/src/internal/Registry.cs
  src/Tizen.NUI/src/internal/VersionCheck.cs
  src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
  src/Tizen.NUI/src/public/BaseComponents/TableView.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/Container.cs
  src/Tizen.NUI/src/public/FocusManager.cs
  src/Tizen.NUI/src/public/Layer.cs
  src/Tizen.NUI/src/public/UIComponents/Popup.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API5

#192 Fix wrong code
  src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationStyleBinder.cs
Labels: API4

#193 Remove callback function exception handling
  src/Tizen.Applications.Shortcut/Tizen.Applications.Shortcut/ShortcutManager.cs
Labels: API5

#197 Remove unused option from the packaging script
  packaging/makespec.sh
Labels: API4

#199 Update GenDummy
  tools/GenDummy/CommandLine.dll
  tools/GenDummy/GenDummy.deps.json
  tools/GenDummy/GenDummy.dll
  tools/GenDummy/GenDummy.pdb
Labels: API5
