Repository Samsung/TizenFX, pull requests merged in 2018-11, with the labels that each got.

#522 [NUI] Add WebView event handlers
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
  src/Tizen.NUI/src/internal/WebView.cs
  src/Tizen.NUI/src/internal/WebViewLite.cs
  src/Tizen.NUI/src/internal/WebViewLiteSignal.cs
  src/Tizen.NUI/src/internal/WebViewSignal.cs
Labels: ACR Required, API6, Internal API Changed

#531 [NUI] NUI Version 505
  packaging/csapi-tizenfx.spec
  packaging/version.txt
  src/Tizen.NUI/src/internal/VersionCheck.cs
Labels: API5

#532 [NUI] NUI Version 505
  packaging/csapi-tizenfx.spec
  packaging/version.txt
  src/Tizen.NUI/src/internal/VersionCheck.cs
Labels: API6

#529 [MediaPlayer] Fix not to set callback in case of using MedaiStreamSource
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
Labels: API6

#534 [NUI] Fix Svace issue
  src/Tizen.NUI/src/internal/Xaml/ApplyPropertiesVisitor.cs
  src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
  src/Tizen.NUI/src/internal/Xaml/MarkupExpressionParser.cs
  src/Tizen.NUI/src/internal/XamlBinding/BindablePropertyConverter.cs
  src/Tizen.NUI/src/internal/XamlBinding/BindingExpression.cs
  src/Tizen.NUI/src/internal/XamlBinding/SynchronizedList.cs
  src/Tizen.NUI/src/internal/XamlBinding/TizenPlatformServices.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API5

#535 [NUI] Fix Svace issue
  src/Tizen.NUI/src/internal/Xaml/ApplyPropertiesVisitor.cs
  src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
  src/Tizen.NUI/src/internal/Xaml/MarkupExpressionParser.cs
  src/Tizen.NUI/src/internal/XamlBinding/BindablePropertyConverter.cs
  src/Tizen.NUI/src/internal/XamlBinding/BindingExpression.cs
  src/Tizen.NUI/src/internal/XamlBinding/SynchronizedList.cs
  src/Tizen.NUI/src/internal/XamlBinding/TizenPlatformServices.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API6

#527 [NUI] Remove an incorrect comment in the license.
  src/Tizen.NUI/src/public/Widget.cs
Labels: API6

#533 [WIP][NUI] Add EnvironmentVariable interface (internal API)
  src/Tizen.NUI/src/internal/EnvironmentVariable.cs
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
Labels: API6

#537 [NUI] Fix to make null assigning to ResourceUrl possible
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
Labels: API6

#538 [NUI] Fix to make null assigning to ResourceUrl possible
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
Labels: API5

#540 [NUI] Fix VD CSFS crash issue
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API5

#541 [NUI] Fix VD CSFS Crash issue
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API6

#548 [NUI] Sync dalihub/TizenFX and Samsung/TizenFX[NUI
  src/Tizen.NUI/src/internal/Layouting/LayoutGroup.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutItem.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/Layer.cs
  src/Tizen.NUI/src/public/PinchGesture.cs
  src/Tizen.NUI/src/public/ScrollViewPagePathEffect.cs
  src/Tizen.NUI/src/public/TypeRegistry.cs
  src/Tizen.NUI/src/public/UIComponents/ScrollBar.cs
Labels: API5, Internal API Changed

#549 [NUI] Sync dalihub/TizenFX and Samsung/TizenFX
  src/Tizen.NUI/src/internal/Layouting/LayoutGroup.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutItem.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/Layer.cs
  src/Tizen.NUI/src/public/PinchGesture.cs
  src/Tizen.NUI/src/public/ScrollViewPagePathEffect.cs
  src/Tizen.NUI/src/public/TypeRegistry.cs
  src/Tizen.NUI/src/public/UIComponents/ScrollBar.cs
Labels: API6, Internal API Changed

#553 [AudioManager] Apply GC.SuppressFinalize()
  src/Tizen.Multimedia/AudioManager/AudioStreamPolicy.cs
Labels: API6

#555 [NUI] Fix SizeWidth/Height issue
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API5

#550 [PrivacyPrivilegeManager] Add new API for checking & requesting multiple privileges
  src/Tizen.Security.PrivacyPrivilegeManager/Interop/Interop.PrivacyPrivilegeManager.cs
  src/Tizen.Security.PrivacyPrivilegeManager/Tizen.Security.PrivacyPrivilegeManager.sln
  src/Tizen.Security.PrivacyPrivilegeManager/Tizen.Security/PermissionRequestResponse.cs
  src/Tizen.Security.PrivacyPrivilegeManager/Tizen.Security/PrivacyPrivilegeManager.cs
  src/Tizen.Security.PrivacyPrivilegeManager/Tizen.Security/RequestResponseEventArgs.cs
  src/Tizen.Security.PrivacyPrivilegeManager/Tizen.Security/RequestResponseMultipleEventArgs.cs
Labels: ACR Required, API6

#552 [NUI] Remove using keyword
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/internal/DisposeQueue.cs
  src/Tizen.NUI/src/internal/NUICoreBackend.cs
  src/Tizen.NUI/src/internal/WatchApplication.cs
Labels: API5

#544 [Tizen.Network.WiFi][TCSACR-192] Add new API to check wifi scan state
  src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/ScanStateChangedEventArgs.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiEnumerations.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetworkChange.cs
Labels: ACR Required, API6

#559 [NUI] Fix e.Application null issue
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/internal/NUICoreBackend.cs
Labels: API5

#561 [Tizen.Applications.DataControl] Fix the issue for native handle
  src/Tizen.Applications.DataControl/Interop/Interop.DataControl.cs
  src/Tizen.Applications.DataControl/Tizen.Applications.DataControl/Provider.cs
Labels: API6

#554 [MediaPlayer] Apply GC.SuppressFinalize()
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
Labels: API6

#558 [NLP] Add new nlp feature
  pkg/PlatformFileList.txt
  src/Tizen.Nlp/Tizen.Nlp.csproj
  src/Tizen.Nlp/Tizen.Nlp.sln
  src/Tizen.Nlp/Tizen.Nlp/NaturalLanguageProcess.cs
Labels: API5

#565 [NUI] Remove version check, temporary workaround for VK app crash issue
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/internal/NUICoreBackend.cs
Labels: API5

#564 [Tizen.Applications.DataControl] Fix the issue for native handle
  src/Tizen.Applications.DataControl/Interop/Interop.DataControl.cs
  src/Tizen.Applications.DataControl/Tizen.Applications.DataControl/Provider.cs
Labels: API5

#562 Revert "[NUI] Fix to make null assigning to ResourceUrl possible (#538)"
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  test/NUITestSample/NUITestSample/examples/ImageViewResourceUrlSetNullTest.cs
Labels: API5

#570 [Tizen.Applications.Common] Restrict concurrent access
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs
Labels: API5

#572 [Build] Remove retry command from build.sh
  build.sh
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
  tools/scripts/timeout.sh
Labels: API6

#575 [Build] Remove retry command from build.sh (#572)
  build.sh
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
  tools/scripts/timeout.sh
Labels: API5

#573 [Packagemanager] Lock internal handle before set/unset event callback
  src/Tizen.Applications.PackageManager/Interop/Interop.PackageManager.cs
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Labels: API6

#576 [Packagemanager] Lock internal handle before set/unset event callback
  src/Tizen.Applications.PackageManager/Interop/Interop.PackageManager.cs
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Labels: API5

#539 [MediaTool] Add duration and maxBps
  src/Tizen.Multimedia/Interop/Interop.MediaTool.cs
  src/Tizen.Multimedia/MediaTool/MediaPacket.cs
  src/Tizen.Multimedia/MediaTool/VideoMediaFormat.cs
Labels: ACR Accepted, API6

#581 [NUI] Add WindowPositionSize property
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: ACR Required, API5, Internal API Changed

#579 [Build] Enhance ABI Checker
  tools/bin/ABIChecker/ABIChecker.dll
  tools/bin/ABIChecker/ABIChecker.pdb
  tools/bin/GenDummy.Tasks/GenDummy.Tasks.deps.json
  tools/bin/GenDummy.Tasks/GenDummy.Tasks.dll
  tools/bin/GenDummy.Tasks/GenDummy.Tasks.pdb
  tools/bin/GenDummy.Tasks/GenDummy.dll
  tools/bin/GenDummy.Tasks/GenDummy.pdb
  tools/bin/GenDummy.Tasks/Microsoft.Build.Framework.dll
  tools/bin/GenDummy.Tasks/Microsoft.Build.Utilities.Core.dll
  tools/bin/GenDummy.Tasks/System.Diagnostics.Contracts.dll
  tools/bin/GenDummy.Tasks/System.Private.DataContractSerialization.dll
  tools/bin/GenDummy.Tasks/System.Runtime.Serialization.Xml.dll
  tools/bin/GenDummy.Tasks/System.Xml.XmlSerializer.dll
  tools/bin/GenDummy.Tasks/runtimes/linux/lib/netstandard1.4/System.Diagnostics.Process.dll
  tools/bin/GenDummy.Tasks/runtimes/osx/lib/netstandard1.4/System.Diagnostics.Process.dll
  tools/bin/GenDummy.Tasks/runtimes/unix/lib/netstandard1.3/Microsoft.Win32.Registry.dll
  tools/bin/GenDummy.Tasks/runtimes/unix/lib/netstandard1.3/System.Diagnostics.TraceSource.dll
  tools/bin/GenDummy.Tasks/runtimes/win/lib/netstandard1.3/Microsoft.Win32.Registry.dll
  tools/bin/GenDummy.Tasks/runtimes/win/lib/netstandard1.3/System.Diagnostics.TraceSource.dll
  tools/bin/GenDummy.Tasks/runtimes/win/lib/netstandard1.4/System.Diagnostics.Process.dll
  tools/src/ABIChecker/ABIChecker.cs
  tools/src/ABIChecker/AssemblyChecker.cs
Labels: API6

#580 [Build] Enhance ABI Checker
  tools/bin/ABIChecker/ABIChecker.dll
  tools/bin/ABIChecker/ABIChecker.pdb
  tools/bin/GenDummy.Tasks/GenDummy.Tasks.deps.json
  tools/bin/GenDummy.Tasks/GenDummy.Tasks.dll
  tools/bin/GenDummy.Tasks/GenDummy.Tasks.pdb
  tools/bin/GenDummy.Tasks/GenDummy.dll
  tools/bin/GenDummy.Tasks/GenDummy.pdb
  tools/bin/GenDummy.Tasks/Microsoft.Build.Framework.dll
  tools/bin/GenDummy.Tasks/Microsoft.Build.Utilities.Core.dll
  tools/bin/GenDummy.Tasks/System.Diagnostics.Contracts.dll
  tools/bin/GenDummy.Tasks/System.Private.DataContractSerialization.dll
  tools/bin/GenDummy.Tasks/System.Runtime.Serialization.Xml.dll
  tools/bin/GenDummy.Tasks/System.Xml.XmlSerializer.dll
  tools/bin/GenDummy.Tasks/runtimes/linux/lib/netstandard1.4/System.Diagnostics.Process.dll
  tools/bin/GenDummy.Tasks/runtimes/osx/lib/netstandard1.4/System.Diagnostics.Process.dll
  tools/bin/GenDummy.Tasks/runtimes/unix/lib/netstandard1.3/Microsoft.Win32.Registry.dll
  tools/bin/GenDummy.Tasks/runtimes/unix/lib/netstandard1.3/System.Diagnostics.TraceSource.dll
  tools/bin/GenDummy.Tasks/runtimes/win/lib/netstandard1.3/Microsoft.Win32.Registry.dll
  tools/bin/GenDummy.Tasks/runtimes/win/lib/netstandard1.3/System.Diagnostics.TraceSource.dll
  tools/bin/GenDummy.Tasks/runtimes/win/lib/netstandard1.4/System.Diagnostics.Process.dll
  tools/src/ABIChecker/ABIChecker.cs
  tools/src/ABIChecker/AssemblyChecker.cs
Labels: API5

#586 [NUI] Fix layout issue
  src/Tizen.NUI/src/internal/NUICoreBackend.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API5
