Repository Samsung/TizenFX, pull requests merged in 2018-05, with the labels that each got.

#220 [ElmSharp] Add RenderOperation property in EvasObject
  src/ElmSharp/ElmSharp/EvasObject.cs
  src/ElmSharp/Interop/Interop.Evas.cs
  test/ElmSharp.Test/TC/RenderOpTest.cs
Labels: ACR Required, API5

#231 [Privilege] Add privacy feature and deprecate redundant API
  src/Tizen.Security/Tizen.Security/Privilege.cs
Labels: ACR Required, API5

#238 [NUI][TCSACR-130] Add new NUI APIs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/NUIConstants.cs
  src/Tizen.NUI/src/public/VisualMaps.cs
Labels: API5

#237 [Camera] Dispose MediaPacket after callback is completed
  src/Tizen.Multimedia.Camera/Camera/Camera.cs
Labels: API5

#239 [Camera] refactoring
  src/Tizen.Multimedia.Camera/Camera/Camera.cs
  src/Tizen.Multimedia.Camera/Camera/CameraCapabilities.cs
  src/Tizen.Multimedia.Camera/Camera/CameraDisplaySettings.cs
  src/Tizen.Multimedia.Camera/Camera/CameraError.cs
  src/Tizen.Multimedia.Camera/Camera/CameraSettings.cs
Labels: API5

#240 [ElmSharp] Fix BoxReomve issue
  src/ElmSharp/ElmSharp/Layout.cs
Labels: API4

#243 Revert "[NUI] Refractor ImfManager to InputMethodContext (#229)"
  src/Tizen.NUI/src/internal/ActivatedSignalType.cs
  src/Tizen.NUI/src/internal/ImfEventSignalType.cs
  src/Tizen.NUI/src/internal/KeyboardTypeSignalType.cs
  src/Tizen.NUI/src/internal/ManualPINVOKE.cs
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/ImfManager.cs
  src/Tizen.NUI/src/public/InputMethodContext.cs
Labels: ACR Required, API5

#242 [ElmSharp] Update namespace summary
  src/ElmSharp.Wearable/doc/api/ElmSharp.Wearable.md
  src/ElmSharp/doc/api/ElmSharp.md
Labels: API5

#241 [ElmSharp] Update namespace summary
  src/ElmSharp.Wearable/doc/api/ElmSharp.Wearable.md
  src/ElmSharp/doc/api/ElmSharp.md
Labels: API4

#114 [NUI] Change Registry as concurrent collection for protection code
  src/Tizen.NUI/src/internal/Registry.cs
Labels: API5

#251 [Build] Add RIDs of Tizen platform to Tizen.NET nuget
  pkg/Tizen.NET.nuspec
  pkg/runtime.json
Labels: API5

#247 [NUI] Enable Window's mouse wheel event
  src/Tizen.NUI/src/public/Window.cs
Labels: API5

#252 [NUI] Fix TextField GetInputMethodContext issue
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
Labels: API5

#253 [MediaCodec] Add error type
  src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodecError.cs
Labels: API5

#254 [NUI]Fix build warnings
  src/Tizen.NUI/src/internal/Alignment.cs
  src/Tizen.NUI/src/internal/GaussianBlurView.cs
  src/Tizen.NUI/src/internal/ItemView.cs
  src/Tizen.NUI/src/internal/Model3dView.cs
  src/Tizen.NUI/src/internal/PageTurnView.cs
  src/Tizen.NUI/src/internal/Size.cs
  src/Tizen.NUI/src/internal/WebViewLite.cs
  src/Tizen.NUI/src/internal/XamlBinding/Application.cs
  src/Tizen.NUI/src/internal/XamlBinding/Internals/IDataTemplate.cs
  src/Tizen.NUI/src/internal/XamlBinding/Layout.cs
  src/Tizen.NUI/src/internal/XamlBinding/Registrar.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/BaseHandle.cs
  src/Tizen.NUI/src/public/Container.cs
  src/Tizen.NUI/src/public/NUIConstants.cs
  src/Tizen.NUI/src/public/PixelBuffer.cs
  src/Tizen.NUI/src/public/Property.cs
  src/Tizen.NUI/src/public/Timer.cs
  src/Tizen.NUI/src/public/UIComponents/Slider.cs
  src/Tizen.NUI/src/public/VisualMaps.cs
  src/Tizen.NUI/src/public/WidgetView.cs
  src/Tizen.NUI/src/public/Xaml/ViewExtensions.cs
  src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
  src/Tizen.NUI/src/public/XamlBinding/BindableProperty.cs
  src/Tizen.NUI/src/public/XamlBinding/BindablePropertyKey.cs
  src/Tizen.NUI/src/public/XamlBinding/BindingBase.cs
  src/Tizen.NUI/src/public/XamlBinding/BindingMode.cs
  src/Tizen.NUI/src/public/XamlBinding/Command.cs
  src/Tizen.NUI/src/public/XamlBinding/ContentPage.cs
  src/Tizen.NUI/src/public/XamlBinding/ControlTemplate.cs
  src/Tizen.NUI/src/public/XamlBinding/Effect.cs
  src/Tizen.NUI/src/public/XamlBinding/Element.cs
  src/Tizen.NUI/src/public/XamlBinding/ElementTemplate.cs
  src/Tizen.NUI/src/public/XamlBinding/IConfigElement.cs
  src/Tizen.NUI/src/public/XamlBinding/IConfigPlatform.cs
  src/Tizen.NUI/src/public/XamlBinding/IEffectControlProvider.cs
  src/Tizen.NUI/src/public/XamlBinding/INavigation.cs
  src/Tizen.NUI/src/public/XamlBinding/IPlatform.cs
  src/Tizen.NUI/src/public/XamlBinding/IPlatformElementConfiguration.cs
  src/Tizen.NUI/src/public/XamlBinding/NavigationEventArgs.cs
  src/Tizen.NUI/src/public/XamlBinding/NavigationPage.cs
  src/Tizen.NUI/src/public/XamlBinding/NavigationProxy.cs
  src/Tizen.NUI/src/public/XamlBinding/NavigationRequestedEventArgs.cs
  src/Tizen.NUI/src/public/XamlBinding/Page.cs
  src/Tizen.NUI/src/public/XamlBinding/SizeRequest.cs
  src/Tizen.NUI/src/public/XamlBinding/TemplatedPage.cs
  src/Tizen.NUI/src/public/XamlBinding/Thickness.cs
Labels: API5

#256 [Docs] Fix document css styles
  docs/template/tizen/styles/docfx.css
  docs/template/tizen/styles/docfx.vendor.css
Labels: API5

#255 [NUI] Add EditorBrowsable Attribute
  src/Tizen.NUI/src/public/Xaml/ViewExtensions.cs
  src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
  src/Tizen.NUI/src/public/XamlBinding/BindableProperty.cs
  src/Tizen.NUI/src/public/XamlBinding/BindablePropertyKey.cs
  src/Tizen.NUI/src/public/XamlBinding/BindingBase.cs
  src/Tizen.NUI/src/public/XamlBinding/BindingMode.cs
  src/Tizen.NUI/src/public/XamlBinding/Command.cs
  src/Tizen.NUI/src/public/XamlBinding/ContentPage.cs
  src/Tizen.NUI/src/public/XamlBinding/ControlTemplate.cs
  src/Tizen.NUI/src/public/XamlBinding/Effect.cs
  src/Tizen.NUI/src/public/XamlBinding/Element.cs
  src/Tizen.NUI/src/public/XamlBinding/ElementTemplate.cs
  src/Tizen.NUI/src/public/XamlBinding/IConfigElement.cs
  src/Tizen.NUI/src/public/XamlBinding/IConfigPlatform.cs
  src/Tizen.NUI/src/public/XamlBinding/IEffectControlProvider.cs
  src/Tizen.NUI/src/public/XamlBinding/INavigation.cs
  src/Tizen.NUI/src/public/XamlBinding/IPlatformElementConfiguration.cs
  src/Tizen.NUI/src/public/XamlBinding/NavigationEventArgs.cs
  src/Tizen.NUI/src/public/XamlBinding/NavigationPage.cs
  src/Tizen.NUI/src/public/XamlBinding/Page.cs
  src/Tizen.NUI/src/public/XamlBinding/SizeRequest.cs
  src/Tizen.NUI/src/public/XamlBinding/TemplatedPage.cs
  src/Tizen.NUI/src/public/XamlBinding/Thickness.cs
Labels: API5

#257 [Multimedia.Common/Radio] Remove deprecated internal API of sound-man…
  src/Tizen.Multimedia.Radio/Radio/Radio.cs
  src/Tizen.Multimedia/Common.Internal/CompatibilitySupport.cs
  src/Tizen.Multimedia/Interop/Interop.SoundManager.cs
Labels: API5

#259 [NUI] Fix TCT fail issue, remove debugging code
  src/Tizen.NUI/src/internal/Registry.cs
Labels: API5

#261 [Docs] Present the default privilege level - public
  docs/docfx.json
  docs/template/tizen/ManagedReference.extension.js
  src/Tizen.Network.WiFi/doc/api/Tizen.Network.WiFi.WiFiEap.md
  src/Tizen.Network.WiFi/doc/api/Tizen.Network.WiFi.WiFiEapConfiguration.md
Labels: API4

#260 [Docs] Present the default privilege level - public
  docs/docfx.json
  docs/template/tizen/ManagedReference.extension.js
  src/Tizen.Network.WiFi/doc/api/Tizen.Network.WiFi.WiFiEap.md
  src/Tizen.Network.WiFi/doc/api/Tizen.Network.WiFi.WiFiEapConfiguration.md
Labels: API5

#262 Add account-manager for TV profile
  pkg/PlatformFileList.txt
Labels: API5

#236 [MediaPlayer] add API related to 360 video
  src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerFeatures.cs
  src/Tizen.Multimedia.MediaPlayer/Player/SphericalVideo.cs
Labels: ACR Required, API5

#263 [NUI] fix SVACE issues 2nd trial
  src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
  src/Tizen.NUI/src/internal/Xaml/MarkupExtensionParser.cs
  src/Tizen.NUI/src/internal/Xaml/MarkupExtensions/StaticResourceExtension.cs
  src/Tizen.NUI/src/internal/XamlBinding/Interactivity/EventTrigger.cs
  src/Tizen.NUI/src/internal/XamlBinding/ObservableWrapper.cs
  src/Tizen.NUI/src/public/CustomViewRegistry.cs
  src/Tizen.NUI/src/public/XamlBinding/Element.cs
Labels: API5

#264 Modify feature for font classes.
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEventArgs.cs
Labels: API5

#265 [Tizen.System.SystemSettings] Add feature telephoney for AutomaticTimeUpdate and its EventArgs.
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEventArgs.cs
Labels: API5

#266 [Information] Sync with API4 branch
  src/Tizen.System.Information/RuntimeInfo/RuntimeInfoEventHandler.cs
  src/Tizen.System.Information/RuntimeInfo/TvProductHelper.cs
Labels: API5

#267 [NUI] Fix SVACE issue, 3rd trial
  src/Tizen.NUI/src/internal/Xaml/ExpandMarkupsVisitor.cs
  src/Tizen.NUI/src/internal/Xaml/MarkupExtensions/StaticResourceExtension.cs
  src/Tizen.NUI/src/public/Property.cs
Labels: API5

#268 [NUI] Fix SVACE issue, 4th trial
  src/Tizen.NUI/src/internal/Xaml/MarkupExtensions/StaticResourceExtension.cs
Labels: API5

#269 [NUI] Fix SVACE issue, 5th trial
  src/Tizen.NUI/src/internal/Xaml/MarkupExtensions/StaticResourceExtension.cs
Labels: API5
