Repository Samsung/TizenFX, pull requests merged in 2018-07, with the labels that each got.

#319 [Feedback][Device][Add new vibration feature]
  src/Tizen.System.Feedback/Feedback/Feedback.cs
  src/Tizen.System/Device/Haptic.cs
Labels: API5

#312 [NUI] Add AllowTextPrediction/IsTextPredictionAllowed Api For InputMethodContext
  src/Tizen.NUI/src/internal/ManualPINVOKE.cs
  src/Tizen.NUI/src/public/InputMethodContext.cs
Labels: ACR Required, API5

#310 [NUI] Add KeyboardRepeatInfo APIs to Window
  src/Tizen.NUI/src/internal/ManualPINVOKE.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: ACR Required, API5

#321 [WiFi] Remove ArgumentException
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetwork.cs
Labels: API5

#324 [NUI] Remove apis which are using internal APIs
  src/Tizen.NUI/src/internal/AsyncImageLoader.cs
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
  src/Tizen.NUI/src/internal/TypeRegistry.cs
  src/Tizen.NUI/src/internal/ViewImpl.cs
  src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
  src/Tizen.NUI/src/public/PixelBuffer.cs
  src/Tizen.NUI/src/public/Texture.cs
  src/Tizen.NUI/src/public/TransitionData.cs
  src/Tizen.NUI/src/public/VisualBase.cs
Labels: ACR Required, API5

#318 [MediaPlayer] add API to set/get replaygain
  src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
Labels: ACR Required, API5

#327 [NUI] Modify Resources to XamlResources
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/internal/Xaml/MarkupExtensions/StaticResourceExtension.cs
  src/Tizen.NUI/src/internal/XamlBinding/Application.cs
  src/Tizen.NUI/src/internal/XamlBinding/ResourcesExtensions.cs
  src/Tizen.NUI/src/internal/XamlBinding/StyleSheets/StyleSheetExtensions.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/XamlBinding/ContentPage.cs
  src/Tizen.NUI/src/public/XamlBinding/IResourcesProvider.cs
Labels: ACR Required, API5

#328 [NUI] Add window size/position setting into NUIApplication constructor
  src/Tizen.NUI/src/public/NUIApplication.cs
Labels: ACR Required, API5

#325 [Connection][TCSACR-156] Remove ArgumentException
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfileManager.cs
Labels: API5

#323 [WiFi][TCSACR-155] Remove ArgumentException descriptions
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiEap.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiEapConfiguration.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiNetwork.cs
Labels: ACR Required, API5

#331 [NUI] Fix NUI nested layout issue
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API5

#329 [MediaPlayer] add API to set zoom with field of view for spherical video
  src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/SphericalVideo.cs
Labels: ACR Required, API5

#334 Fix handle leak
  src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationReplyAction.cs
Labels: API4

#330 [Appfw] Add APIs for RPC
  src/Tizen.Applications.Common/Interop/Interop.Libraries.cs
  src/Tizen.Applications.Common/Interop/Interop.RPCPort.cs
  src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Exceptions.cs
  src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs
  src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Port.cs
  src/Tizen.Applications.Common/Tizen.Applications.RPCPort/ProxyBase.cs
  src/Tizen.Applications.Common/Tizen.Applications.RPCPort/StubBase.cs
Labels: API5

#332 [Wifi] [TCSACR-160] Add ForgetAPAsync
  src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
Labels: ACR Required, API5

#345 [Inputmethod][TCSACR-161] Add API to hide IME
  src/Tizen.Uix.InputMethod/Interop/Interop.InputMethod.cs
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
Labels: ACR Required, API5

#344 [Inputmethod][TCSACR-163] Add APIs for floating keyboard
  src/Tizen.Uix.InputMethod/Interop/Interop.InputMethod.cs
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
Labels: ACR Required, API5

#350 [Tizen.Multimedia.Util] Fix callback function lifecycle bug
  src/Tizen.Multimedia.Util/ThumbnailExtractor/ThumbnailExtractor.cs
Labels: API4

#340 [ElmSharp] Fix description of API
  src/ElmSharp/ElmSharp/Entry.cs
Labels: API4

#337 [MediaPlayer] add API about playback time to set/get in nonoseconds
  src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.ErrorHandler.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerDisplaySettings.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerTrackInfo.cs
  src/Tizen.Multimedia.MediaPlayer/Player/StreamInfo.cs
Labels: ACR Required, API5

#353 [NUI] nui-vulkan backend support
  src/Tizen.NUI/src/internal/Layouting/LayoutPINVOKE.cs
  src/Tizen.NUI/src/internal/ManualPINVOKE.cs
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
  src/Tizen.NUI/src/public/NUIApplication.cs
Labels: API5

#354 [Tizen.Network.Bluetooth] Fix ValueChanged callback function bug
  src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothEventArgs.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
Labels: API4

#355 [Tizen.Network.Bluetooth] Fix ValueChanged callback function bug
  src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothEventArgs.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
Labels: API5

#356 [Build] Rollup Tizen.NET.API4
  pkg/Tizen.NET.nuspec
Labels: API5

#357 [Storage][Get DeviceType using StorageGetTypeDev]
  src/Tizen.System.Storage/Interop/Interop.Storage.cs
  src/Tizen.System.Storage/Storage/Storage.cs
Labels: API5
