Repository Samsung/TizenFX, pull requests merged in 2018-04, with the labels that each got.

#204 [ElmSharp] modified eo api name according to efl 1.2.0 api name
  src/ElmSharp/ElmSharp/EvasObject.cs
  src/ElmSharp/ElmSharp/Layout.cs
  src/ElmSharp/Interop/Interop.Elementary.cs
  src/ElmSharp/Interop/Interop.Eo.cs
  test/ElmSharp.Test/TC/Wearable/ButtonTest1.cs
Labels: API5

#195 [ElmSharp] fixed to parent.Handle for preventing potential bug (#173)
  src/ElmSharp/ElmSharp/GestureLayer.cs
  src/ElmSharp/ElmSharp/Image.cs
  src/ElmSharp/ElmSharp/Naviframe.cs
  src/ElmSharp/ElmSharp/Panel.cs
  src/ElmSharp/ElmSharp/Table.cs
Labels: API5

#200 [NUI] Add thread id in NUIWidgetApplication for avoid crash
  src/Tizen.NUI/src/internal/Registry.cs
  src/Tizen.NUI/src/public/NUIWidgetApplication.cs
Labels: API4

#202 [SystemSettings] Add Vibration, AutomaticTimeUpdate, DeveloperOptionS…
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEnums.cs
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEventArgs.cs
Labels: ACR Required, API5

#203 [MediaCodec] Fix error enum bug
  src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodecError.cs
Labels: API4

#208 [ElmSharp] GetTextBlockGeometryByLineNumber is obsolete
  src/ElmSharp/ElmSharp/EvasObject.cs
Labels: API5

#209 [ElmSharp] Added remarks for Popup and Layout
  src/ElmSharp/ElmSharp/Layout.cs
  src/ElmSharp/ElmSharp/Popup.cs
Labels: API5

#210 Delete .travis.yml
  .travis.yml
Labels: API4

#201 [Camera] Add new enum(camera device) and properties(hue)
  src/Tizen.Multimedia.Camera/Camera/Camera.cs
  src/Tizen.Multimedia.Camera/Camera/CameraCapabilities.cs
  src/Tizen.Multimedia.Camera/Camera/CameraEnums.cs
  src/Tizen.Multimedia.Camera/Camera/CameraSettings.cs
  src/Tizen.Multimedia.Camera/Camera/Location.cs
  src/Tizen.Multimedia.Camera/Interop/Interop.CameraSettings.cs
Labels: ACR Accepted, API5

#214 Update README.md
  README.md
Labels: API5

#211 [MediaCodec] Add exception handling code
  src/Tizen.Multimedia.MediaCodec/Interop/Interop.Libraries.cs
  src/Tizen.Multimedia.MediaCodec/Interop/Interop.MediaCodec.cs
  src/Tizen.Multimedia.MediaCodec/Interop/Interop.MediaTool.cs
  src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodec.cs
  src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodecError.cs
  src/Tizen.Multimedia.Recorder/Interop/Interop.Recorder.cs
Labels: API4

#215 [MediaCodec] Fix error enum bug
  src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodecError.cs
Labels: API5

#217 Update common.props
  build/common.props
Labels: API5

#216 [MediaCodec] Add exception handling code
  src/Tizen.Multimedia.MediaCodec/Interop/Interop.Libraries.cs
  src/Tizen.Multimedia.MediaCodec/Interop/Interop.MediaCodec.cs
  src/Tizen.Multimedia.MediaCodec/Interop/Interop.MediaTool.cs
  src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodec.cs
  src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodecError.cs
  src/Tizen.Multimedia.Recorder/Interop/Interop.Recorder.cs
Labels: API5

#219 [Multimedia] Modify MediaPlayer for product reuse
  src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.ErrorHandler.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Events.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerError.cs
Labels: API5

#222 [ElmSharp] Add namespace summary
  src/ElmSharp.Wearable/doc/api/ElmSharp.Wearable.md
  src/ElmSharp/doc/api/ElmSharp.md
Labels: API5

#221 [ElmSharp] Add namespace summary
  src/ElmSharp.Wearable/doc/api/ElmSharp.Wearable.md
  src/ElmSharp/doc/api/ElmSharp.md
Labels: API4

#224 [ElmSharp] Merge bug fix commit from master to API4
  src/ElmSharp/ElmSharp/EvasObject.cs
  src/ElmSharp/ElmSharp/ItemObject.cs
  src/ElmSharp/ElmSharp/Layout.cs
  src/ElmSharp/ElmSharp/Popup.cs
  src/ElmSharp/Interop/Interop.Elementary.Item.cs
  test/ElmSharp.Test/TC/ItemEvasObjectTest.cs
Labels: API4

#225 [Information] Fix invalid mapping key for TV product
  src/Tizen.System.Information/RuntimeInfo/TvProductHelper.cs
Labels: API4

#235 [Connection][WiFi] Assign zero to Handle only when Interop.Destroy()
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
Labels: API4

#234 [Connection][WiFi] Assign zero to Handle only when Interop.Destroy()
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
Labels: API5

#207 [MediaPlayer] add API to set audio-only mode
  src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
Labels: ACR Required, API5
