Repository Samsung/TizenFX, pull requests merged in 2018-10, with the labels that each got.

#491 [NUI] Fix Svace issue
  src/Tizen.NUI/src/internal/Xaml/MarkupExtensions/StaticResourceExtension.cs
Labels: API5

#492 [NUI] Integration from dalihub/TizenFX to Samsung/TizenFX
  src/Tizen.NUI/src/internal/Layouting/LayoutGroup.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutItem.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutLength.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutPINVOKE.cs
  src/Tizen.NUI/src/internal/VersionCheck.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/NUIConstants.cs
Labels: API5

#493 [MediaController] fix bugs
  src/Tizen.Multimedia.Remoting/MediaController/CommandCompletedEventArgs.cs
  src/Tizen.Multimedia.Remoting/MediaController/CustomCommandReceivedEventArgs.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlCommand.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlPlaylist.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlServerStartedEventArgs.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlServerStoppedEventArgs.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
  src/Tizen.Multimedia.Remoting/MediaController/MetadataUpdatedEventArgs.cs
  src/Tizen.Multimedia.Remoting/MediaController/PlaybackActionCommandReceivedEventArgs.cs
  src/Tizen.Multimedia.Remoting/MediaController/PlaybackPositionCommandReceivedEventArgs.cs
  src/Tizen.Multimedia.Remoting/MediaController/PlaylistCommandReceivedEventArgs.cs
  src/Tizen.Multimedia.Remoting/MediaController/PlaylistUpdatedEventArgs.cs
  src/Tizen.Multimedia.Remoting/MediaController/RepeatModeCapabilityUpdatedEventArgs.cs
  src/Tizen.Multimedia.Remoting/MediaController/RepeatModeCommandReceivedEventArgs.cs
  src/Tizen.Multimedia.Remoting/MediaController/SearchCommandReceivedEventArgs.cs
  src/Tizen.Multimedia.Remoting/MediaController/ShuffleModeCapabilityUpdatedEventArgs.cs
  src/Tizen.Multimedia.Remoting/MediaController/ShuffleModeCommandReceivedEventArgs.cs
Labels: ACR Required, API5

#498 [ElmSharp] Fix Spinner Style on TV
  src/ElmSharp/ElmSharp/Spinner.cs
Labels: API4

#499 [NUI] Add BackgroundResourceLoaded,ResourceLoaded events as internal API
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API5

#500 [ElmSharp] Adds ScrollbarVisiblePolicy to GenList
  src/ElmSharp/ElmSharp/GenList.cs
Labels: API5

#501 [MultimediaUtil] Prevent collecting callback before it's called.
  src/Tizen.Multimedia.Util/ThumbnailExtractor/ThumbnailExtractor.cs
Labels: API5

#502 [Pims.Calendar] Fix for local time difference in Tizen emulators
  src/Tizen.Pims.Calendar/Interop/Interop.Filter.cs
  src/Tizen.Pims.Calendar/Interop/Interop.Record.cs
  src/Tizen.Pims.Calendar/Tizen.Pims.Calendar/CalendarFilter.cs
  src/Tizen.Pims.Calendar/Tizen.Pims.Calendar/CalendarRecord.cs
Labels: API5

#503 [Packagemanager] Fix lifetime of callback delegate
  src/Tizen.Applications.PackageManager/Tizen.Applications/Package.cs
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Labels: API5

#504 modify spelling error
  README.md
Labels: API5

#489 [Shortcut] Update add, delete func
  src/Tizen.Applications.Shortcut/Tizen.Applications.Shortcut/ShortcutManager.cs
  src/Tizen.Applications.Shortcut/interop/Interop.Shortcut.cs
Labels: API4

#505 [NUI] Support software styling
  src/Tizen.NUI/src/internal/ManualPINVOKE.cs
  src/Tizen.NUI/src/public/FontClient.cs
Labels: API4

#506 [Tools] Fix code checker
  tools/scripts/CodeChecker/main.py
Labels: API5

#510 [ElmSharp] Fix Focus Clearing issue
  src/ElmSharp/ElmSharp/Widget.cs
  src/ElmSharp/Interop/Interop.Elementary.cs
Labels: API5

#511 [NUI] Fix SVACE issue
  src/Tizen.NUI/src/internal/XamlBinding/ObservableWrapper.cs
Labels: API5

#515 Push
  src/Tizen.Messaging.Push/Tizen.Messaging.Push/PushClient.cs
  src/Tizen.Messaging.Push/Tizen.Messaging.Push/PushImpl.cs
Labels: API5

#513 [Build] Cleanup build and packaging files
  build/GlobalSuppressions.cs
  build/analyzers.props
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
  packaging/makespec.sh
  packaging/version.txt
Labels: API5

#517 [ElmSharp] Fix typo
  src/ElmSharp/ElmSharp/Window.cs
Labels: API5

#518 [ElmSharp] Fix typo
  src/ElmSharp/ElmSharp/Window.cs
Labels: API4

#519 [NUI] Remove APIs which should not be public-opened
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
  src/Tizen.NUI/src/public/ImageLoading.cs
Labels: API5, Internal API Changed
