Repository Samsung/TizenFX, pull requests merged in 2018-12, with the labels that each got.

#525 [WidgetControl] Add MainAppId, PackageId properties and modify required feature
  src/Tizen.Applications.WidgetControl/Interop/Interop.WidgetService.cs
  src/Tizen.Applications.WidgetControl/Tizen.Applications/WidgetControl.cs
Labels: ACR Required, API6

#589 [NUI] Add EnvironmentVariable interface (internal API) (#533)
  src/Tizen.NUI/src/internal/EnvironmentVariable.cs
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
Labels: API5, Internal API Changed

#584 [MediaTool] Add ctor for VideoMediaFormat
  src/Tizen.Multimedia/MediaTool/VideoMediaFormat.cs
Labels: ACR Accepted, API6

#545 [Tizen.Applications.Common] Add SendLaunchRequestAsync Method
  src/Tizen.Applications.Common/Interop/Interop.AppControl.cs
  src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
  src/Tizen.Applications.Common/Tizen.Applications/AppControlResult.cs
Labels: ACR Required, API6

#590 [WidgetControl] Add documentation about param, return
  src/Tizen.Applications.WidgetControl/Tizen.Applications/WidgetControl.cs
Labels: API6

#546 [WidgeApplication] Modify WidgetBase internal Id memeber to property
  src/Tizen.Applications.WidgetApplication/Tizen.Applications/WidgetBase.cs
Labels: ACR Required, API6

#591 [WebView] Remove unused API
  src/Tizen.WebView/Tizen.WebView/SmartCallbackArgs.cs
Labels: API6

#526 [DataControl] Add current caller client appid and current provider id property
  src/Tizen.Applications.DataControl/Interop/Interop.DataControl.cs
  src/Tizen.Applications.DataControl/Tizen.Applications.DataControl/Provider.cs
Labels: ACR Required, API6

#560 [Application] Add CurrentDeviceOrientation property on CoreUIApplication
  src/Tizen.Applications.UI/Interop/Interop.Application.cs
  src/Tizen.Applications.UI/Tizen.Applications/CoreUIApplication.cs
Labels: ACR Required, API6

#593 Revert "[Application] Add CurrentDeviceOrientation property on CoreUIApplication"
  src/Tizen.Applications.UI/Interop/Interop.Application.cs
  src/Tizen.Applications.UI/Tizen.Applications/CoreUIApplication.cs
Labels: ACR Required, API6

#547 [Applications.Common] Add missing application APIs
  src/Tizen.Applications.Common/Interop/Interop.AppControl.cs
  src/Tizen.Applications.Common/Interop/Interop.Bundle.cs
  src/Tizen.Applications.Common/Interop/Interop.Glib.cs
  src/Tizen.Applications.Common/Interop/Interop.Libc.cs
  src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
  src/Tizen.Applications.Common/Tizen.Applications/AppControlData.cs
  src/Tizen.Applications.Common/Tizen.Applications/AppControlLaunchMode.cs
  src/Tizen.Applications.Common/Tizen.Applications/AppControlOperations.cs
  src/Tizen.Applications.Common/Tizen.Applications/AppControlReceivedEventArgs.cs
  src/Tizen.Applications.Common/Tizen.Applications/AppControlReplyCallback.cs
  src/Tizen.Applications.Common/Tizen.Applications/AppControlReplyResult.cs
  src/Tizen.Applications.Common/Tizen.Applications/Application.cs
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationInfo.cs
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationInfoMetadataFilter.cs
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationLaunchedEventArgs.cs
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationRunningContext.cs
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationTerminatedEventArgs.cs
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationType.cs
  src/Tizen.Applications.Common/Tizen.Applications/Bundle.cs
  src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
  src/Tizen.Applications.Common/Tizen.Applications/DeviceOrientation.cs
  src/Tizen.Applications.Common/Tizen.Applications/DeviceOrientationEventArgs.cs
  src/Tizen.Applications.Common/Tizen.Applications/DirectoryInfo.cs
  src/Tizen.Applications.Common/Tizen.Applications/LocaleChangedEventArgs.cs
  src/Tizen.Applications.Common/Tizen.Applications/LowBatteryEventArgs.cs
  src/Tizen.Applications.Common/Tizen.Applications/LowBatteryStatus.cs
  src/Tizen.Applications.Common/Tizen.Applications/LowMemoryEventArgs.cs
  src/Tizen.Applications.Common/Tizen.Applications/LowMemoryStatus.cs
  src/Tizen.Applications.Common/Tizen.Applications/ReceivedAppControl.cs
  src/Tizen.Applications.Common/Tizen.Applications/RecentApplicationControl.cs
  src/Tizen.Applications.Common/Tizen.Applications/RecentApplicationInfo.cs
  src/Tizen.Applications.Common/Tizen.Applications/RegionFormatChangedEventArgs.cs
  src/Tizen.Applications.Common/Tizen.Applications/ResourceManager.cs
  src/Tizen.Applications.Common/Tizen.Applications/SafeAppControlHandle.cs
  src/Tizen.Applications.Common/Tizen.Applications/SafeBundleHandle.cs
Labels: ACR Required, API6

#594 [Application] Add device orientation property
  src/Tizen.Applications.UI/Interop/Interop.Application.cs
  src/Tizen.Applications.UI/Tizen.Applications/CoreUIApplication.cs
Labels: ACR Required, API6

#597 [NUI] revert workaround for vulkan
  src/Tizen.NUI/src/internal/NUICoreBackend.cs
Labels: API5

#596 [STT/TTS] Fix desctructor to call dispose
  src/Tizen.Uix.Stt/Tizen.Uix.Stt/SttClient.cs
  src/Tizen.Uix.Tts/Tizen.Uix.Tts/TtsClient.cs
Labels: API5

#599 [Application] Use ConfigureAwait(false) when await a Task
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs
Labels: API6

#582 Add new APIs to update input panel event
  src/Tizen.Uix.InputMethod/Interop/Interop.InputMethod.cs
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/EditorWindow.cs
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
Labels: ACR Required, API6

#588 [TCSACR-203][WiFi] Add new Exceptions
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/InvalidKeyException.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/NowInProgressException.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiAP.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiErrorFactory.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
Labels: ACR Required, API6

#600 [NUI] Disconnect all native signals of Window class when application …
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API5

#587 [doc] Add WatchfaceComplication to the doc index
  docs/api/index.md
  src/Tizen.Applications.WatchfaceComplication/doc/api/Tizen.Applications.WatchfaceComplication.md
Labels: API6

#605 Fix the crash issue when marshalling Intptr with a string
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
Labels: API6

#602 Fix pause policy bug because of mismatched enum index (#601)
  src/Tizen.Sensor/Tizen.Sensor/SensorEnumerations.cs
Labels: API5

#603 Fix pause policy bug because of mismatched enum index (#601)
  src/Tizen.Sensor/Tizen.Sensor/SensorEnumerations.cs
Labels: API6

#578 [NFC] fix typo
  src/Tizen.Network.Nfc/Tizen.Network.Nfc/NfcManager.cs
Labels: API5

#563 [NFC] Fix typo
  src/Tizen.Network.Nfc/Tizen.Network.Nfc/NfcManager.cs
Labels: API6

#574 [Bluetooth] Add BluetoothHidDevice APIs
  src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothData.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothDevice.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothEnumerations.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothError.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothEventArgs.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothHidDevice.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothHidDeviceImpl.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
Labels: API6, Internal API Changed

#609 [MediaController] Replace native api with new one
  src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerClient.cs
  src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerServer.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.Events.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
Labels: API6

#613 [NUI] ResizePolicy UseNaturalSize mapped to WrapContent
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API5

#617 [NUI] Sync with API5
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/internal/DisposeQueue.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutGroup.cs
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
  src/Tizen.NUI/src/internal/NUICoreBackend.cs
  src/Tizen.NUI/src/internal/WatchApplication.cs
  src/Tizen.NUI/src/internal/Xaml/MarkupExtensions/StaticExtension.cs
  src/Tizen.NUI/src/internal/XamlBinding/Binding.cs
  src/Tizen.NUI/src/internal/XamlBinding/SynchronizedList.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API6, Internal API Changed

#606 [Applications] [ProxyBase,StubBase] Fix visibility for method 'Dispose'
  src/Tizen.Applications.Common/Tizen.Applications.RPCPort/ProxyBase.cs
  src/Tizen.Applications.Common/Tizen.Applications.RPCPort/StubBase.cs
Labels: API6

#618 [ElmSharp] Fix crash issue for GetTextBlockGeometryByLineNumber()
  src/ElmSharp/ElmSharp/EvasObject.cs
Labels: API6

#619 [ElmSharp] Add new APIs for automation test
  src/ElmSharp/ElmSharp/Elementary.cs
  src/ElmSharp/ElmSharp/EvasObject.cs
  test/ElmSharp.Test/TestRunner.cs
Labels: ACR Required, API6

#612 [Alarm] Add property setter for WeekFlag, Period, ScheduledDate
  src/Tizen.Applications.Alarm/Interop/Interop.Alarm.cs
  src/Tizen.Applications.Alarm/Tizen.Applications/Alarm.cs
Labels: ACR Accepted, API6

#598 [Bluetooth] Add Bluetooth Internal APIs
  src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAdapter.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAdapterImpl.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAudio.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAudioImpl.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothData.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothDevice.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothEventArgs.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothOpp.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothServerSocket.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothSocket.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
Labels: ACR Required, API6, Internal API Changed

#626 [Build] Use regexp in CodeChecker for parsing the unified diff lines
  .gitignore
  tools/scripts/CodeChecker/PRManager.py
Labels: API6

#627 [NUI] Add C# binding for MatchSystemLanguageDirection
  src/Tizen.NUI/src/internal/ManualPINVOKE.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
Labels: API5, Internal API Changed

#622 [MediaPlayer] Add descriptions for preparing state
  src/Tizen.Multimedia.MediaPlayer/Player/DownloadProgress.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerEnums.cs
Labels: API6

#630 [NUI] Workaround of Vulkan backend csfs crash issue
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
  src/Tizen.NUI/src/internal/VersionCheck.cs
  src/Tizen.NUI/src/public/NUIApplication.cs
Labels: API5

#611 [AccountManager] Improving resource handling - Issues 67,68 & 69
  src/Tizen.Account.AccountManager/Tizen.Account.AccountManager/Account.cs
  src/Tizen.Account.AccountManager/Tizen.Account.AccountManager/AccountService.cs
  src/Tizen.Account.AccountManager/Tizen.Account.AccountManager/SafeAccountHandle.cs
Labels: API6
