Repository Samsung/TizenFX, pull requests merged in 2019-10, with the labels that each got.

#1040 [ComponentBased][TCSACR-282] Add Release method to IWindowInfo interface
  src/Tizen.Applications.ComponentBased.Default/Tizen.Applications.ComponentBased.Default/EFLWindowInfo.cs
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/FrameComponentStateManager.cs
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/IWindowInfo.cs
Labels: ACR Required, API6

#985 [MediaVision] Add APIs for inference detectors and classifier
  src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Common.cs
  src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Inference.cs
  src/Tizen.Multimedia.Vision/MediaVision/EngineConfiguration.cs
  src/Tizen.Multimedia.Vision/MediaVision/FaceDetectionResult.cs
  src/Tizen.Multimedia.Vision/MediaVision/FaceDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/FaceRecognitionModel.cs
  src/Tizen.Multimedia.Vision/MediaVision/FaceTrackingModel.cs
  src/Tizen.Multimedia.Vision/MediaVision/FacialLandmarkDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/ImageClassificationResult.cs
  src/Tizen.Multimedia.Vision/MediaVision/ImageClassifier.cs
  src/Tizen.Multimedia.Vision/MediaVision/ImageObject.cs
  src/Tizen.Multimedia.Vision/MediaVision/ImageTrackingModel.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceModelConfiguration.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceType.cs
  src/Tizen.Multimedia.Vision/MediaVision/MediaVisionError.cs
  src/Tizen.Multimedia.Vision/MediaVision/MediaVisionSource.cs
  src/Tizen.Multimedia.Vision/MediaVision/ObjectDetectionResult.cs
  src/Tizen.Multimedia.Vision/MediaVision/ObjectDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/VisionFeatures.cs
Labels: ACR Accepted, API6

#1046 [NUI] Fix Bug in GetParent()
  src/Tizen.NUI/src/public/Window.cs
Labels: API6

#1045 Patch for Email Emulator TCT issues
  src/Tizen.Messaging/Tizen.Messaging.Email/EmailSender.cs
Labels: API6

#1042 [MediaPlayer] Fix descriptions
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
Labels: API6

#1043 [MediaPlayer] Add API for setting audio codec type
  src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/AudioEffect.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerEnums.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerError.cs
Labels: ACR Required, API6

#895 [SystemSettings][TCSACR-247][Add] Add RotaryEventEnabled
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEnums.cs
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/SystemSettings.UnitTest.csproj
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSSystemSettings.cs
Labels: ACR Required, API6

#1049 [SystemSettings]Add feature RotaryEventEnabled
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEventArgs.cs
Labels: ACR Required, API6

#1051 [MediaTool] Add missed exception for bitDepth
  src/Tizen.Multimedia/MediaTool/AudioMediaFormat.cs
Labels: API6

#1048 [MediaController] Add capability method for subtitle, 360 mode
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
Labels: ACR Accepted, API6

#1044 [NUI] Deprecate Tizen.NUI.UIComponents
  src/Tizen.NUI/src/public/UIComponents/Button.cs
  src/Tizen.NUI/src/public/UIComponents/CheckBoxButton.cs
  src/Tizen.NUI/src/public/UIComponents/Popup.cs
  src/Tizen.NUI/src/public/UIComponents/ProgressBar.cs
  src/Tizen.NUI/src/public/UIComponents/PushButton.cs
  src/Tizen.NUI/src/public/UIComponents/RadioButton.cs
  src/Tizen.NUI/src/public/UIComponents/ScrollBar.cs
  src/Tizen.NUI/src/public/UIComponents/ScrollView.cs
  src/Tizen.NUI/src/public/UIComponents/Slider.cs
  src/Tizen.NUI/src/public/UIComponents/ToggleButton.cs
Labels: ACR Accepted, API6, Internal API Changed

#1053 [NUI] Enable View.ScaleBy (#33)
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API6, Internal API Changed

#1031 [VoiceControlManager] Add tags for missing feature and privilege
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/VoiceCommand.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/VoiceCommandsGroup.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/VoiceControlManagerClient.cs
Labels: ACR Accepted, API6

#1055 [Network.Stc] Fix Build issue and Update PlatformFileList
  packaging/PlatformFileList.txt
  src/Tizen.Network.Stc/Tizen.Network.Stc.sln
Labels: API6

#1061 [NUI] Open public apis of NUI.Components for TCSACR-248
  src/Tizen.NUI.Components/Attributes/DropDownAttributes.cs
  src/Tizen.NUI.Components/Attributes/LoadingAttributes.cs
  src/Tizen.NUI.Components/Attributes/PaginationAttributes.cs
  src/Tizen.NUI.Components/Attributes/TabAttributes.cs
  src/Tizen.NUI.Components/Attributes/ViewAttributes.cs
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/GridLayoutManager.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/OrientationHelper.cs
  src/Tizen.NUI.Components/Controls/Loading.cs
  src/Tizen.NUI.Components/Controls/Pagination.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/SelectButton.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Controls/Toast.cs
  src/Tizen.NUI/src/public/Position.cs
  src/Tizen.NUI/src/public/Size.cs
Labels: ACR Required, API6, Internal API Changed

#1062 [NUI] Fix the return value of logicalKey
  src/Tizen.NUI/src/public/Key.cs
Labels: API6

#1063 [MediaController] Fix typo
  src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
Labels: ACR Required, API6

#1050 [MediaPlayer] change the error code related with AudioOffload
  src/Tizen.Multimedia.MediaPlayer/Player/AudioEffect.cs
  src/Tizen.Multimedia.MediaPlayer/Player/AudioOffload.cs
  src/Tizen.Multimedia.MediaPlayer/Player/EqualizerBand.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerTrackInfo.cs
Labels: API6

#1052 [AudioManager] Add new exception to the doxygen of ApplyStreamRouting()
  src/Tizen.Multimedia/AudioManager/AudioStreamPolicy.cs
Labels: API6

#1058 [NUI] Add Window.TransitionEffect event
  src/Tizen.NUI/src/internal/Interop/Interop.WindowEffectEventSignal.cs
  src/Tizen.NUI/src/internal/WindowEffectSignal.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API6, Internal API Changed

#1054 Update UafClient.cs
  src/Tizen.Account.FidoClient/Tizen.Account.FidoClient/UafClient.cs
Labels: API6

#1064 [NUI] some change in VectorAnimationViewTBD
  src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs
Labels: API6

#1065 [NUI] Removing PropertyBuffer.SetData()'s obsolete attribute
  src/Tizen.NUI/src/public/PropertyBuffer.cs
Labels: API6, Internal API Changed

#1067 [NUI] Integration from dalihub
  src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs
  src/Tizen.NUI/src/public/LongPressGestureDetector.cs
  src/Tizen.NUI/src/public/PanGestureDetector.cs
  src/Tizen.NUI/src/public/PinchGestureDetector.cs
  src/Tizen.NUI/src/public/TapGestureDetector.cs
Labels: API6, Internal API Changed

#1008 [EflSharp] Update Circle and efl cs files
  internals/src/EflSharp/EflSharp/Circle/CircleGenlist.cs
  internals/src/EflSharp/EflSharp/Circle/CircleScroller.cs
  internals/src/EflSharp/EflSharp/Circle/RotarySelector.cs
  internals/src/EflSharp/EflSharp/efl/efl_access_object.eo.cs
  internals/src/EflSharp/EflSharp/efl/efl_ui_animation_view.eo.cs
Labels: API6

#1068 [NUI] Change WindowTransitionEffect interface
  src/Tizen.NUI/src/internal/Interop/Interop.WindowEffectEventSignal.cs
  src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API6, Internal API Changed

#1070 [NUI] Update documentation on View class
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API6

#1076 [AudioManager] Update description suggested by ducoment team
  src/Tizen.Multimedia/AudioManager/AudioDucking.cs
  src/Tizen.Multimedia/AudioManager/AudioDuckingStateChangedEventArgs.cs
Labels: API6

#1074 [NUI] Add GetContentInfo() to get lottie file's layer information
  src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
  src/Tizen.NUI/src/public/VisualConstants.cs
Labels: API6, Internal API Changed

#1077 [Tizen.Network.Connection] Init/deinit without ManagedThreadId
  src/Tizen.Network.Connection/Interop/Interop.Connection.cs
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs
Labels: API6

#1078 [NUI] fix Document related the part of window
  src/Tizen.NUI/src/public/Window.cs
  src/Tizen.NUI/src/public/WindowEvent.cs
Labels: API6

#1079 [NUI] Fix Gallery Crash issue
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API6

#1075 Apply TCSACR-288 Tizen.Telephony
  src/Tizen.Telephony/Tizen.Telephony/Modem.cs
  src/Tizen.Telephony/Tizen.Telephony/Sim.cs
Labels: ACR Accepted, API6

#1072 [MediaTool] specify the unit
  src/Tizen.Multimedia/MediaTool/MediaPacket.cs
Labels: API6

#1080 [NUI] Fix Svace issue
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/SelectButton.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Controls/Toast.cs
  src/Tizen.NUI/src/internal/AccessibilityActionSignal.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
  src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
  src/Tizen.NUI/src/public/Layouting/LayoutTransition.cs
  src/Tizen.NUI/src/public/Rectangle.cs
  src/Tizen.NUI/src/public/WatchTime.cs
Labels: API6

#1082 [MediaController] Fix build warning
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.Events.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs
Labels: API6

#1083 [MediaPlayer] Fix build warning
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerEnums.cs
Labels: API6

#1081 [NUI] Split large files
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
  src/Tizen.NUI/src/public/KeyValue.cs
  src/Tizen.NUI/src/public/Property.cs
  src/Tizen.NUI/src/public/PropertyArray.cs
  src/Tizen.NUI/src/public/PropertyKey.cs
  src/Tizen.NUI/src/public/PropertyMap.cs
  src/Tizen.NUI/src/public/PropertyValue.cs
  src/Tizen.NUI/src/public/UIComponents/ScrollView.cs
  src/Tizen.NUI/src/public/UIComponents/ScrollViewBindableProperty.cs
  src/Tizen.NUI/src/public/UIComponents/ScrollViewEvent.cs
Labels: API6

#1084 [NUI] Fix build warnings
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/Toast.cs
  src/Tizen.NUI.Components/Utils/StyleManager.cs
  src/Tizen.NUI/src/internal/ItemView.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
  src/Tizen.NUI/src/public/Accessibility.cs
  src/Tizen.NUI/src/public/Size.cs
Labels: ACR Required, API6

#1086 Revert "[Tizen.Network.Connection] Init/deinit without ManagedThreadId"
  src/Tizen.Network.Connection/Interop/Interop.Connection.cs
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionProfile.cs
Labels: API6

#1090 [MediaPlayer] fix descriptions
  src/Tizen.Multimedia.MediaPlayer/Player/AudioEffect.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
Labels: API6

#1094 Deprecate of Tizen.Account.OAuth2
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/AccessToken.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/AuthenticationScheme.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/AuthorizationRequest.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/AuthorizationResponse.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/Authorizer.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ClientCredentials.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ClientCredentialsAuthorizer.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ClientCredentialsTokenRequest.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/CodeGrantAuthorizationRequest.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/CodeGrantAuthorizer.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/CodeGrantTokenRequest.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ImplicitGrantAuthorizationRequest.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ImplicitGrantAuthorizer.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/OAuth2ErrorResponse.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/RefreshToken.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/RefreshTokenRequest.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ResourceOwnerPwdCredentialsAuthorizer.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ResourceOwnerPwdCredentialsTokenRequest.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/TokenRequest.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/TokenResponse.cs
Labels: ACR Required, API6

#1092 [IoTConnectivity] Handle the exception for getting Dictionary item
  src/Tizen.Network.IoTConnectivity/Tizen.Network.IoTConnectivity/RemoteResource.cs
Labels: API6

#1095 [ImageUtil] Fix descriptions
  src/Tizen.Multimedia.Util/ThumbnailExtractor/ThumbnailExtractor.cs
Labels: API6

#1096 [NUI] Refine codes to reduce code duplication
  src/Tizen.NUI/src/internal/ArgumentHelper.cs
  src/Tizen.NUI/src/internal/EnumHelper.cs
  src/Tizen.NUI/src/internal/Extensions.cs
  src/Tizen.NUI/src/internal/FrameBuffer.cs
  src/Tizen.NUI/src/internal/NDalic.cs
  src/Tizen.NUI/src/internal/RotationGestureDetectedSignal.cs
  src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
  src/Tizen.NUI/src/public/AlphaFunction.cs
  src/Tizen.NUI/src/public/Animation.cs
  src/Tizen.NUI/src/public/BaseComponents/TableView.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
  src/Tizen.NUI/src/public/BaseComponents/VisualView.cs
  src/Tizen.NUI/src/public/CubeTransitionEffect.cs
  src/Tizen.NUI/src/public/FocusManager.cs
  src/Tizen.NUI/src/public/Layer.cs
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
  src/Tizen.NUI/src/public/NUIConstants.cs
  src/Tizen.NUI/src/public/Renderer.cs
  src/Tizen.NUI/src/public/TextureSet.cs
  src/Tizen.NUI/src/public/Touch.cs
  src/Tizen.NUI/src/public/UIComponents/Popup.cs
  src/Tizen.NUI/src/public/VisualMaps.cs
  src/Tizen.NUI/src/public/Visuals/AnimatedImageVisual.cs
  src/Tizen.NUI/src/public/Visuals/BorderVisual.cs
  src/Tizen.NUI/src/public/Visuals/ColorVisual.cs
  src/Tizen.NUI/src/public/Visuals/GradientVisual.cs
  src/Tizen.NUI/src/public/Visuals/ImageVisual.cs
  src/Tizen.NUI/src/public/Visuals/MeshVisual.cs
  src/Tizen.NUI/src/public/Visuals/NPatchVisual.cs
  src/Tizen.NUI/src/public/Visuals/PrimitiveVisual.cs
  src/Tizen.NUI/src/public/Visuals/SVGVisual.cs
  src/Tizen.NUI/src/public/Visuals/TextVisual.cs
  src/Tizen.NUI/src/public/Visuals/VisualAnimator.cs
  src/Tizen.NUI/src/public/XamlBinding/ContentPage.cs
Labels: API6

#1098 [Network.Stc] [Fix] Correct exception handling
  src/Tizen.Network.Stc/Tizen.Network.Stc/StcError.cs
  src/Tizen.Network.Stc/Tizen.Network.Stc/StcManager.cs
  src/Tizen.Network.Stc/Tizen.Network.Stc/StcManagerImpl.cs
Labels: API6

#1088 [PackageManager] Modify description for DependencyTo/From properties
  src/Tizen.Applications.PackageManager/Tizen.Applications/Package.cs
Labels: API6

#1099 [NUI] revert the patch for flexibleview animation
  src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs
Labels: API6, Internal API Changed

#1100 [NUI] Remove IME_F31 PredictiveString in NUI sample
  test/NUITestSample/NUITestSample/examples/text-test2.cs
Labels: API6

#1101 [NUI] Fix svace issue
  src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs
Labels: API6

#1102 [MediaPlayer] change the error code following the API's change
  src/Tizen.Multimedia.MediaPlayer/Player/AudioOffload.cs
Labels: API6

#1091 [NUI] NUIWidgetApplication constructor for multi widget
  src/Tizen.NUI/src/internal/WidgetApplication.cs
  src/Tizen.NUI/src/public/NUIWidgetApplication.cs
Labels: API6, Internal API Changed

#1097 [NUI] Property setter is changed
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/Color.cs
  src/Tizen.NUI/src/public/Extents.cs
  src/Tizen.NUI/src/public/Rectangle.cs
  src/Tizen.NUI/src/public/RelativeVector4.cs
  src/Tizen.NUI/src/public/Vector2.cs
  src/Tizen.NUI/src/public/Vector3.cs
  src/Tizen.NUI/src/public/Vector4.cs
  test/NUITestSample/NUITestSample/examples/PropertyCascadeCheckTest.cs
  test/NUITestSample/NUITestSample/examples/PropertyCascadeSpeedTest.cs
Labels: API6

#1108 [NUI] Remove 'EditorBrowsable' to HeightSpecification
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: ACR Required, API6

#1109 [NUI] Add VectorAnimationView
  src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs
Labels: API6, Internal API Changed
