Repository Samsung/TizenFX, pull requests merged in 2019-12, with the labels that each got.

#1155 [NUI] Binding VideoView::New with swCodec parameter
  src/Tizen.NUI/src/internal/Interop/Interop.VideoView.cs
  src/Tizen.NUI/src/public/BaseComponents/VideoView.cs
Labels: API7, Internal API Changed

#1157 [NUI] Add Component Application (#1148)
  src/Tizen.Applications.ComponentBased/AssemblyAttr.cs
  src/Tizen.NUI/Tizen.NUI.csproj
  src/Tizen.NUI/Tizen.NUI.sln
  src/Tizen.NUI/src/internal/ComponentApplication.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ComponentApplication.cs
  src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
  src/Tizen.NUI/src/internal/NUIComponentCoreBackend.cs
  src/Tizen.NUI/src/internal/NUIWindowInfo.cs
  src/Tizen.NUI/src/public/NUIComponentApplication.cs
  src/Tizen.NUI/src/public/NUIFrameComponent.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API6, Internal API Changed

#1160 [NUI] DropDownButton to use Layout scrolling
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/LayoutScroller.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
Labels: API7, Internal API Changed

#1161 [NUI.Components] Api6 drop down uses layout scroller
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/LayoutScroller.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
Labels: API6, Internal API Changed

#1162 [NUI] Binding VideoView::New with swCodec parameter (#1155)
  src/Tizen.NUI/src/internal/Interop/Interop.VideoView.cs
  src/Tizen.NUI/src/public/BaseComponents/VideoView.cs
Labels: API6, Internal API Changed

#1163 [NUI] Fix NUI.Components svace issue
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/ImageControl.cs
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/SelectButton.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Controls/Toast.cs
Labels: API6

#1164 [NUI] To fix OSV check
  src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/GridLayoutManager.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/OrientationHelper.cs
Labels: API7, Internal API Changed

#1167 [NUI] Fix Svace issue
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
Labels: API6

#1166 [NUI.Components] Refine DropDown control
  src/Tizen.NUI.Components/Attributes/DropDownAttributes.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Tizen.NUI.Components.sln
Labels: API7, Internal API Changed

#1171 [NUI.Components] Refine DropDown control
  src/Tizen.NUI.Components/Attributes/DropDownAttributes.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Tizen.NUI.Components.sln
Labels: API6, Internal API Changed

#1169 [NUI.Components]Fix svace issue
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/ImageControl.cs
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI.Components/Controls/Loading.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/SelectButton.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Controls/Toast.cs
Labels: API7

#1172 [NUI] Fix svace issue
  src/Tizen.NUI.Components/Controls/DropDown.cs
Labels: API6

#1168 [Sensor] Add rotation sensor internal API
  src/Tizen.Sensor/Tizen.Sensor/EventArgs/AutoRotationSensorDataUpdatedEventArgs.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/AutoRotationSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/SensorEnumerations.cs
Labels: API6, Internal API Changed

#1174 [NUI] Fix wrong API comments in xml
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API6

#1175 [NUI] Fix wrong API comments in xml
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API7

#1176 [NUI] Fixed TCT failed issues
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI/src/public/Extents.cs
Labels: API7

#1177 [NUI] Fixed TCT failed issues
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI/src/public/Extents.cs
Labels: API6

#1173 [Sensor] Fix invalid value matching between native and csharp API
  src/Tizen.Sensor/Tizen.Sensor/EventArgs/AutoRotationSensorDataUpdatedEventArgs.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/AutoRotationSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/SensorEnumerations.cs
Labels: API6, Internal API Changed

#1178 [NUI] Add checking if the Timer is used in main thread
  src/Tizen.NUI/src/public/Timer.cs
Labels: API6

#1180 [NUI] Upgrade gesture handler
  src/Tizen.NUI/Tizen.NUI.sln
  src/Tizen.NUI/src/public/LongPressGestureDetector.cs
  src/Tizen.NUI/src/public/PanGestureDetector.cs
  src/Tizen.NUI/src/public/PinchGestureDetector.cs
  src/Tizen.NUI/src/public/RotationGestureDetector.cs
  src/Tizen.NUI/src/public/TapGestureDetector.cs
Labels: API6

#1147 [ElmSharp] Add internal Evas Image APIs
  src/ElmSharp/Interop/Interop.Evas.Image.cs
Labels: API6

#1146 [ElmSharp] Add internal Evas Image APIs
  src/ElmSharp/Interop/Interop.Evas.Image.cs
Labels: API7

#1179 [NUI] Add checking if the Timer is used in main thread
  src/Tizen.NUI/src/public/Timer.cs
Labels: API7

#1182 [NUI] Fix ICustomFocusAlgorithm exception
  src/Tizen.NUI/src/public/FocusManager.cs
Labels: API8

#1188 [NUI] Fix ICustomFocusAlgorithm exception
  src/Tizen.NUI/src/public/FocusManager.cs
Labels: API6

#1187 [NUI] Fix ICustomFocusAlgorithm exception
  src/Tizen.NUI/src/public/FocusManager.cs
Labels: API7

#1191 [NUI] Fix crash issue when create popup
  src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
Labels: API6

#1183 Refine background property of control
  src/Tizen.NUI.Components/Attributes/ButtonAttributes.cs
  src/Tizen.NUI.Components/Attributes/ControlStyle.cs
  src/Tizen.NUI.Components/Attributes/ImageControlStyle.cs
  src/Tizen.NUI.Components/Attributes/PopupAttributes.cs
  src/Tizen.NUI.Components/Attributes/SelectButtonAttributes.cs
  src/Tizen.NUI.Components/Attributes/SliderAttributes.cs
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/CheckBox.cs
  src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/ImageControl.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/RadioButton.cs
  src/Tizen.NUI.Components/Controls/RadioButtonGroup.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/SelectButton.cs
  src/Tizen.NUI.Components/Controls/SelectGroup.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewAttributes.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
Labels: API8, Internal API Changed

#1153 [Sensor] Addition of initial sensor values
  src/Tizen.Sensor/Interop/Interop.Sensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/Accelerometer.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/FaceDownGestureDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/GravitySensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/Gyroscope.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/GyroscopeRotationVectorSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/HeartRateMonitor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/HumiditySensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/InVehicleActivityDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/LightSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/LinearAccelerationSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/Magnetometer.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/MagnetometerRotationVectorSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/OrientationSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/Pedometer.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/PickUpGestureDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/PressureSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/ProximitySensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/RotationVectorSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/RunningActivityDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/SleepMonitor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/StationaryActivityDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/TemperatureSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/UltravioletSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/UncalibratedGyroscope.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/UncalibratedMagnetometer.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/WalkingActivityDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/WristUpGestureDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Sensor.cs
Labels: API7

#1198 [Sensor] Fix type on auto rotation sensor property
  src/Tizen.Sensor/Tizen.Sensor/EventArgs/AutoRotationSensorDataUpdatedEventArgs.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/AutoRotationSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/SensorEnumerations.cs
Labels: API6, Internal API Changed

#1196 Refine background property of control (#1183)
  src/Tizen.NUI.Components/Attributes/ButtonAttributes.cs
  src/Tizen.NUI.Components/Attributes/ControlStyle.cs
  src/Tizen.NUI.Components/Attributes/ImageControlStyle.cs
  src/Tizen.NUI.Components/Attributes/PopupAttributes.cs
  src/Tizen.NUI.Components/Attributes/SelectButtonAttributes.cs
  src/Tizen.NUI.Components/Attributes/SliderAttributes.cs
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/CheckBox.cs
  src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/ImageControl.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/RadioButton.cs
  src/Tizen.NUI.Components/Controls/RadioButtonGroup.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/SelectButton.cs
  src/Tizen.NUI.Components/Controls/SelectGroup.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewAttributes.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
Labels: API7, Internal API Changed

#1199 [NUI] Refine Toast and Remove Toast from the Window after hidden
  src/Tizen.NUI.Components/Attributes/ToastAttributes.cs
  src/Tizen.NUI.Components/Controls/Toast.cs
Labels: API8, Internal API Changed

#1200 [NUI.Components]Sync master to api6 1218
  src/Tizen.NUI.Components/Attributes/ButtonAttributes.cs
  src/Tizen.NUI.Components/Attributes/ControlStyle.cs
  src/Tizen.NUI.Components/Attributes/ImageControlStyle.cs
  src/Tizen.NUI.Components/Attributes/PopupAttributes.cs
  src/Tizen.NUI.Components/Attributes/SelectButtonAttributes.cs
  src/Tizen.NUI.Components/Attributes/SliderAttributes.cs
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/CheckBox.cs
  src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/GridLayoutManager.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/OrientationHelper.cs
  src/Tizen.NUI.Components/Controls/ImageControl.cs
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI.Components/Controls/Loading.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/RadioButton.cs
  src/Tizen.NUI.Components/Controls/RadioButtonGroup.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/SelectButton.cs
  src/Tizen.NUI.Components/Controls/SelectGroup.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Controls/Toast.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewAttributes.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
Labels: API6, Internal API Changed

#1201 [NUI.Components] Fix components issue api6
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/ImageControl.cs
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Style/ButtonStyle.cs
  src/Tizen.NUI.Components/Style/ControlStyle.cs
  src/Tizen.NUI.Components/Style/DropDownStyle.cs
  src/Tizen.NUI.Components/Style/ImageControlStyle.cs
  src/Tizen.NUI.Components/Style/InputFieldStyle.cs
  src/Tizen.NUI.Components/Style/LoadingStyle.cs
  src/Tizen.NUI.Components/Style/PaginationStyle.cs
  src/Tizen.NUI.Components/Style/PopupStyle.cs
  src/Tizen.NUI.Components/Style/ProgressStyle.cs
  src/Tizen.NUI.Components/Style/ScrollbarStyle.cs
  src/Tizen.NUI.Components/Style/SliderStyle.cs
  src/Tizen.NUI.Components/Style/SwitchStyle.cs
  src/Tizen.NUI.Components/Style/TabStyle.cs
  src/Tizen.NUI.Components/Style/ToastStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
Labels: API6, Internal API Changed

#1203 [NUI.Components] Fix components issue 1216 (#1194)
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/ImageControl.cs
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Style/ButtonStyle.cs
  src/Tizen.NUI.Components/Style/ControlStyle.cs
  src/Tizen.NUI.Components/Style/DropDownStyle.cs
  src/Tizen.NUI.Components/Style/ImageControlStyle.cs
  src/Tizen.NUI.Components/Style/InputFieldStyle.cs
  src/Tizen.NUI.Components/Style/LoadingStyle.cs
  src/Tizen.NUI.Components/Style/PaginationStyle.cs
  src/Tizen.NUI.Components/Style/PopupStyle.cs
  src/Tizen.NUI.Components/Style/ProgressStyle.cs
  src/Tizen.NUI.Components/Style/ScrollbarStyle.cs
  src/Tizen.NUI.Components/Style/SliderStyle.cs
  src/Tizen.NUI.Components/Style/SwitchStyle.cs
  src/Tizen.NUI.Components/Style/TabStyle.cs
  src/Tizen.NUI.Components/Style/ToastStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
Labels: API7, Internal API Changed

#1205 [NUI] Merge master#1199 to API7
  src/Tizen.NUI.Components/Controls/Toast.cs
  src/Tizen.NUI.Components/Style/ToastStyle.cs
Labels: API7, Internal API Changed

#1206 [NUI] Sync the whole codes to master
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/ButtonGroup.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/GridLayoutManager.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/OrientationHelper.cs
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Style/PopupStyle.cs
  src/Tizen.NUI.Components/Utils/StyleManager.cs
  src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/XamlBinding/BindableProperty.cs
Labels: API8, Internal API Changed

#1208 [NUI] Merge mater#1206 to API6
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/ButtonGroup.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/GridLayoutManager.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/OrientationHelper.cs
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Style/PopupStyle.cs
  src/Tizen.NUI.Components/Utils/StyleManager.cs
  src/Tizen.NUI/src/public/XamlBinding/BindableProperty.cs
Labels: API6, Internal API Changed

#1209 [NUI] Merge master#1206 to API7
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/ButtonGroup.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/GridLayoutManager.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/LinearLayoutManager.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/OrientationHelper.cs
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Style/PopupStyle.cs
  src/Tizen.NUI.Components/Utils/StyleManager.cs
  src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/XamlBinding/BindableProperty.cs
Labels: API7, Internal API Changed

#1210 [NUI] Add SetMinMaxFrameByMarker() in LottieAnimationView
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
Labels: API8, Internal API Changed

#1215 [NUI] Support adding multiple callback to gesture
  src/Tizen.NUI/src/public/LongPressGestureDetector.cs
  src/Tizen.NUI/src/public/PanGestureDetector.cs
  src/Tizen.NUI/src/public/PinchGestureDetector.cs
  src/Tizen.NUI/src/public/RotationGestureDetector.cs
  src/Tizen.NUI/src/public/TapGestureDetector.cs
Labels: API7, Internal API Changed

#1216 [NUI] Support adding multiple callback to gesture
  src/Tizen.NUI/src/public/LongPressGestureDetector.cs
  src/Tizen.NUI/src/public/PanGestureDetector.cs
  src/Tizen.NUI/src/public/PinchGestureDetector.cs
  src/Tizen.NUI/src/public/RotationGestureDetector.cs
  src/Tizen.NUI/src/public/TapGestureDetector.cs
Labels: API8

#1211 [NUI] Fix textfield color issue
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
Labels: API8, Internal API Changed

#1213 [NUI] Fix textfield color issue
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
Labels: API7, Internal API Changed

#1212 [NUI] Fix textfield color issue
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
Labels: API6, Internal API Changed

#1221 [NUI] Add NoOrientationPreference
  src/Tizen.NUI/src/public/Window.cs
Labels: API6, Internal API Changed

#1219 [NUI] Add NoOrientationPreference
  src/Tizen.NUI/src/public/Window.cs
Labels: API8, Internal API Changed

#1220 [NUI] Add NoOrientationPreference
  src/Tizen.NUI/src/public/Window.cs
Labels: API7, Internal API Changed

#1184 [NUI.Components] Layout scroller/Scrollable Horizontal support and Pages
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/LayoutScroller.cs
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
Labels: API8, Internal API Changed

#1185 [NUI] Layout scroller pages api6
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/LayoutScroller.cs
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
Labels: API6, Internal API Changed

#1186 [NUI] Layout scroller pages api7
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/LayoutScroller.cs
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
Labels: API7, Internal API Changed

#1227 [NUI] Add AnimatedImageView for AGIF and Image-Array as HiddenAPI
  src/Tizen.NUI/src/public/BaseComponents/AnimatedImageView.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AnimatedImageViewTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-001.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-002.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-003.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-004.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-005.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-006.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-007.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-008.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-009.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-010.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-011.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-012.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-013.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-014.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-015.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim.gif
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-001.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-002.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-003.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-004.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-005.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-006.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-007.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-008.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim.gif
Labels: API8, Internal API Changed

#1229 [NUI] Add AnimatedImageView for AGIF and Image-Array as HiddenAPI
  src/Tizen.NUI/src/public/BaseComponents/AnimatedImageView.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AnimatedImageViewTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-001.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-002.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-003.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-004.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-005.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-006.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-007.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-008.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-009.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-010.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-011.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-012.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-013.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-014.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-015.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim.gif
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-001.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-002.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-003.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-004.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-005.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-006.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-007.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-008.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim.gif
Labels: API6, Internal API Changed

#1228 [NUI] Add AnimatedImageView for AGIF and Image-Array as HiddenAPI
  src/Tizen.NUI/src/public/BaseComponents/AnimatedImageView.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AnimatedImageViewTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-001.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-002.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-003.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-004.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-005.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-006.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-007.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-008.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-009.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-010.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-011.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-012.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-013.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-014.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim-015.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dali-logo-anim.gif
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-001.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-002.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-003.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-004.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-005.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-006.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-007.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim-008.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/AGIF/dog-anim.gif
Labels: API7

#1230 [NUI] Fix Dropdown runtime error
  src/Tizen.NUI.Components/Controls/DropDown.cs
Labels: API6

#1231 [NUI] Fix Dropdown runtime error
  src/Tizen.NUI.Components/Controls/DropDown.cs
Labels: API7, Internal API Changed

#1232 [NUI] Fix Dropdown runtime error
  src/Tizen.NUI.Components/Controls/DropDown.cs
Labels: API8

#1234 [Camera] Fix null reference bug
  src/Tizen.Multimedia.Camera/Camera/CameraCapabilities.cs
Labels: API6

#1223 [NUI] Implement shadow in View
  src/Tizen.NUI/src/internal/Interop/Interop.PropertyMap.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
  src/Tizen.NUI/src/public/PropertyMap.cs
  src/Tizen.NUI/src/public/PropertyValue.cs
  src/Tizen.NUI/src/public/Rectangle.cs
  src/Tizen.NUI/src/public/Size.cs
  src/Tizen.NUI/src/public/Vector2.cs
  src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
  src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
  src/Tizen.NUI/src/public/ViewProperty/TransformablePropertyMap.cs
Labels: API8, Internal API Changed

#1235 [NUI] Implement shadow in View
  src/Tizen.NUI/src/internal/Interop/Interop.PropertyMap.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
  src/Tizen.NUI/src/public/PropertyMap.cs
  src/Tizen.NUI/src/public/PropertyValue.cs
  src/Tizen.NUI/src/public/Rectangle.cs
  src/Tizen.NUI/src/public/Size.cs
  src/Tizen.NUI/src/public/Vector2.cs
  src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
  src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
  src/Tizen.NUI/src/public/ViewProperty/TransformablePropertyMap.cs
Labels: API6, Internal API Changed

#1236 [NUI] Implement shadow in View
  src/Tizen.NUI/src/internal/Interop/Interop.PropertyMap.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
  src/Tizen.NUI/src/public/PropertyMap.cs
  src/Tizen.NUI/src/public/PropertyValue.cs
  src/Tizen.NUI/src/public/Rectangle.cs
  src/Tizen.NUI/src/public/Size.cs
  src/Tizen.NUI/src/public/Vector2.cs
  src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
  src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
  src/Tizen.NUI/src/public/ViewProperty/TransformablePropertyMap.cs
Labels: API7, Internal API Changed

#1233 [NUI.Components] Fix build warnings
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/ButtonGroup.cs
  src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI.Components/Controls/Loading.cs
  src/Tizen.NUI.Components/Controls/Pagination.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/RadioButtonGroup.cs
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/SelectGroup.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Controls/Toast.cs
  src/Tizen.NUI.Components/Style/ButtonStyle.cs
  src/Tizen.NUI.Components/Style/DropDownStyle.cs
  src/Tizen.NUI.Components/Style/SliderStyle.cs
  src/Tizen.NUI.Components/Style/ToastStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
Labels: API8

#1237 [NUI.Components] Fix build warnings (#1233)
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/ButtonGroup.cs
  src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI.Components/Controls/Loading.cs
  src/Tizen.NUI.Components/Controls/Pagination.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/RadioButtonGroup.cs
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/SelectGroup.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Controls/Toast.cs
  src/Tizen.NUI.Components/Style/ButtonStyle.cs
  src/Tizen.NUI.Components/Style/DropDownStyle.cs
  src/Tizen.NUI.Components/Style/SliderStyle.cs
  src/Tizen.NUI.Components/Style/ToastStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
Labels: API6

#1238 [NUI.Components] Fix build warnings (#1233)
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/ButtonGroup.cs
  src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI.Components/Controls/Loading.cs
  src/Tizen.NUI.Components/Controls/Pagination.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/RadioButtonGroup.cs
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/SelectGroup.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Controls/Toast.cs
  src/Tizen.NUI.Components/Style/ButtonStyle.cs
  src/Tizen.NUI.Components/Style/DropDownStyle.cs
  src/Tizen.NUI.Components/Style/SliderStyle.cs
  src/Tizen.NUI.Components/Style/ToastStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
Labels: API7, Internal API Changed

#1240 [NUI.Components] Fix BackgroundImage doesn't works issue
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/ButtonGroup.cs
  src/Tizen.NUI.Components/Controls/CheckBox.cs
  src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/ImageControl.cs
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI.Components/Controls/Loading.cs
  src/Tizen.NUI.Components/Controls/Pagination.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/RadioButton.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/SelectButton.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Controls/Toast.cs
Labels: API8

#1243 [NUI.Components] Fix BackgroundImage doesn't works issue (#1240)
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/ButtonGroup.cs
  src/Tizen.NUI.Components/Controls/CheckBox.cs
  src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/ImageControl.cs
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI.Components/Controls/Loading.cs
  src/Tizen.NUI.Components/Controls/Pagination.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/RadioButton.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/SelectButton.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Controls/Toast.cs
Labels: API7, Internal API Changed

#1242 [NUI.Components] Fix BackgroundImage doesn't works issue (#1240)
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/ButtonGroup.cs
  src/Tizen.NUI.Components/Controls/CheckBox.cs
  src/Tizen.NUI.Components/Controls/CheckBoxGroup.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/ImageControl.cs
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI.Components/Controls/Loading.cs
  src/Tizen.NUI.Components/Controls/Pagination.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/RadioButton.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/SelectButton.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Controls/Toast.cs
Labels: API6

#1244 [NUI] Add SetMinMaxFrameByMarker() in LottieAnimationView
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
Labels: API7, Internal API Changed

#1245 [NUI] Add SetMinMaxFrameByMarker() in LottieAnimationView
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
Labels: API6, Internal API Changed

#1246 [NUI.Components] Fix Background Image not works issue
  src/Tizen.NUI.Components/Style/ButtonStyle.cs
  src/Tizen.NUI.Components/Style/ControlStyle.cs
  src/Tizen.NUI.Components/Style/DropDownStyle.cs
  src/Tizen.NUI.Components/Style/ImageControlStyle.cs
  src/Tizen.NUI.Components/Style/InputFieldStyle.cs
  src/Tizen.NUI.Components/Style/LoadingStyle.cs
  src/Tizen.NUI.Components/Style/PaginationStyle.cs
  src/Tizen.NUI.Components/Style/PopupStyle.cs
  src/Tizen.NUI.Components/Style/ProgressStyle.cs
  src/Tizen.NUI.Components/Style/ScrollbarStyle.cs
  src/Tizen.NUI.Components/Style/SliderStyle.cs
  src/Tizen.NUI.Components/Style/SwitchStyle.cs
  src/Tizen.NUI.Components/Style/TabStyle.cs
  src/Tizen.NUI.Components/Style/ToastStyle.cs
Labels: API8

#1247 [NUI.Components] Fix Background Image not works issue (#1246)
  src/Tizen.NUI.Components/Style/ButtonStyle.cs
  src/Tizen.NUI.Components/Style/ControlStyle.cs
  src/Tizen.NUI.Components/Style/DropDownStyle.cs
  src/Tizen.NUI.Components/Style/ImageControlStyle.cs
  src/Tizen.NUI.Components/Style/InputFieldStyle.cs
  src/Tizen.NUI.Components/Style/LoadingStyle.cs
  src/Tizen.NUI.Components/Style/PaginationStyle.cs
  src/Tizen.NUI.Components/Style/PopupStyle.cs
  src/Tizen.NUI.Components/Style/ProgressStyle.cs
  src/Tizen.NUI.Components/Style/ScrollbarStyle.cs
  src/Tizen.NUI.Components/Style/SliderStyle.cs
  src/Tizen.NUI.Components/Style/SwitchStyle.cs
  src/Tizen.NUI.Components/Style/TabStyle.cs
  src/Tizen.NUI.Components/Style/ToastStyle.cs
Labels: API6

#1248 [NUI.Components] Fix Background Image not works issue (#1246)
  src/Tizen.NUI.Components/Style/ButtonStyle.cs
  src/Tizen.NUI.Components/Style/ControlStyle.cs
  src/Tizen.NUI.Components/Style/DropDownStyle.cs
  src/Tizen.NUI.Components/Style/ImageControlStyle.cs
  src/Tizen.NUI.Components/Style/InputFieldStyle.cs
  src/Tizen.NUI.Components/Style/LoadingStyle.cs
  src/Tizen.NUI.Components/Style/PaginationStyle.cs
  src/Tizen.NUI.Components/Style/PopupStyle.cs
  src/Tizen.NUI.Components/Style/ProgressStyle.cs
  src/Tizen.NUI.Components/Style/ScrollbarStyle.cs
  src/Tizen.NUI.Components/Style/SliderStyle.cs
  src/Tizen.NUI.Components/Style/SwitchStyle.cs
  src/Tizen.NUI.Components/Style/TabStyle.cs
  src/Tizen.NUI.Components/Style/ToastStyle.cs
Labels: API7, Internal API Changed

#1249 [NUI] Add to get current window orientation.
  src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API8, Internal API Changed

#1251 [NUI] Add to get current window orientation.
  src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API7, Internal API Changed

#1250 [NUI] Add to get current window orientation.
  src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API6, Internal API Changed

#1254 [NUI] fix crash when cube transition effect sample is launched.
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CubeTransitionEffectSample.cs
Labels: API8
