Repository Samsung/TizenFX, pull requests merged in 2019-07, with the labels that each got.

#913 [Applications.Common] Add an exception
  src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Labels: API6

#915 [Applications.Common] Add an exception
  src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Labels: API5

#909 [NUI] Add AutofillContainer and autofill implementation
  src/Tizen.NUI/src/internal/AuthenticationSignalType.cs
  src/Tizen.NUI/src/internal/Interop/Interop.AuthenticationSignalType.cs
  src/Tizen.NUI/src/internal/Interop/Interop.AutofillContainer.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ListEventSignalType.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs
  src/Tizen.NUI/src/internal/ListEventSignalType.cs
  src/Tizen.NUI/src/public/AutofillContainer.cs
Labels: API6, Internal API Changed

#917 [NUI] Fix ImageView bug
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
Labels: API6

#918 [NUI] Temporary checking if Lottie file is set in ImageView
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
Labels: API6

#919 [ImageUtil] Fix crash issue
  src/Tizen.Multimedia.Util/ImageUtil/ImageDecoder.cs
  src/Tizen.Multimedia.Util/Interop/Interop.ImageUtil.Decode.cs
Labels: API6

#923 [ImageUtil] Fix crash issue
  src/Tizen.Multimedia.Util/ImageUtil/ImageDecoder.cs
  src/Tizen.Multimedia.Util/Interop/Interop.ImageUtil.Decode.cs
Labels: API5

#924 [NUI] Add View.Color property and SetRenderRefreshRate method
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/NUIApplication.cs
Labels: API6, Internal API Changed

#925 [ImageUtil] Fix crash issue
  src/Tizen.Multimedia.Util/ImageUtil/ImageDecoder.cs
  src/Tizen.Multimedia.Util/Interop/Interop.ImageUtil.Decode.cs
Labels: API4

#927 [NUI] Add API for GetWindowList()
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/internal/Interop/Interop.Application.cs
Labels: API6

#926 [NUI] Change BackgroundImageSynchronosLoading property as public
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API6, Internal API Changed

#929 [ImageUtil] Replace deprecated decode pinvoke func.
  src/Tizen.Multimedia.Util/ImageUtil/ColorSpaceTransform.cs
  src/Tizen.Multimedia.Util/ImageUtil/CropTransform.cs
  src/Tizen.Multimedia.Util/ImageUtil/FlipTransform.cs
  src/Tizen.Multimedia.Util/ImageUtil/ImageDecoder.cs
  src/Tizen.Multimedia.Util/ImageUtil/ImageEncoder.cs
  src/Tizen.Multimedia.Util/ImageUtil/ImageTransform.cs
  src/Tizen.Multimedia.Util/ImageUtil/ImageTransformGroup.cs
  src/Tizen.Multimedia.Util/ImageUtil/ImageUtil.cs
  src/Tizen.Multimedia.Util/ImageUtil/ResizeTransform.cs
  src/Tizen.Multimedia.Util/ImageUtil/RotateTransform.cs
  src/Tizen.Multimedia.Util/Interop/Interop.ImageUtil.Decode.cs
  src/Tizen.Multimedia.Util/Interop/Interop.ImageUtil.Encode.cs
  src/Tizen.Multimedia.Util/Interop/Interop.ImageUtil.Transform.cs
  src/Tizen.Multimedia.Util/Interop/Interop.ImageUtil.cs
Labels: API6

#922 [MediaContent] Add face Insert API
  src/Tizen.Content.MediaContent/Interop/Interop.Face.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/FaceInfoCommand.cs
Labels: ACR Required, API6

#928 [ImageUtil] Add sync thumbnail extract API
  src/Tizen.Multimedia.Util/Interop/Interop.ThumbnailExtractor.cs
  src/Tizen.Multimedia.Util/ThumbnailExtractor/ThumbnailExtractionResult.cs
  src/Tizen.Multimedia.Util/ThumbnailExtractor/ThumbnailExtractor.cs
Labels: ACR Required, API6

#930 [MediaPlayer] Add API to export audio PCM data
  src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/AudioDataDecodedEventArgs.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Events.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerEnums.cs
Labels: ACR Required, API6

#931 [MediaPlayer] fix it to not try getting handle when format is null
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
Labels: API6

#932 [ThumbnailExtractor] Add description for Extract method
  src/Tizen.Multimedia.Util/ThumbnailExtractor/ThumbnailExtractor.cs
  src/Tizen.Multimedia.Util/ThumbnailExtractor/ThumbnailExtractorError.cs
Labels: API6

#937 [NUI] Update CommonUI
  src/Tizen.NUI.CommonUI/Attributes/PopupAttributes.cs
  src/Tizen.NUI.CommonUI/Controls/FlexibleView/FlexibleView.cs
  src/Tizen.NUI.CommonUI/Controls/Switch.cs
  src/Tizen.NUI.CommonUI/Utils/Selector.cs
Labels: API6, Internal API Changed

#938 [MediaCodec] Fix the bug of callback registration
  src/Tizen.Multimedia.MediaCodec/Interop/Interop.MediaCodec.cs
  src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodec.cs
Labels: API6

#942 [MediaCodec] Fix the bug of callback registration
  src/Tizen.Multimedia.MediaCodec/Interop/Interop.MediaCodec.cs
  src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodec.cs
Labels: API4

#941 [MediaCodec] Fix the bug of callback registration
  src/Tizen.Multimedia.MediaCodec/Interop/Interop.MediaCodec.cs
  src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodec.cs
Labels: API5

#935 [NUI] Add to set MIME type to the input panel and its callback
  src/Tizen.NUI/src/internal/ContentReceivedSignalType.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ContentReceivedSignalType.cs
  src/Tizen.NUI/src/internal/Interop/Interop.InputMethodContext.cs
  src/Tizen.NUI/src/public/InputMethodContext.cs
Labels: API6, Internal API Changed

#936 [NUI] Add KeyString in Key.cs
  src/Tizen.NUI/src/internal/Interop/Interop.Key.cs
  src/Tizen.NUI/src/public/Key.cs
Labels: API6, Internal API Changed

#943 [MediaContent] Fix grammatical error in description
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/AlbumCommand.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/BookmarkCommand.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/FaceInfoCommand.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/FolderCommand.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaCommand.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaDatabase.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfoCommand.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/PlaylistCommand.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/StorageCommand.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/TagCommand.cs
Labels: API6

#946 [NUI] Add StopBehavior, LoopingMode of AnimatedVectorImageView
  src/Tizen.NUI/src/internal/DaliEnumConstants.cs
  src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs
  src/Tizen.NUI/src/public/NUIConstants.cs
Labels: API6, Internal API Changed

#947 [NUI] Add Say, PauseResume of Dali-ATSPI
  src/Tizen.NUI/src/internal/Interop/Interop.Accessibility.cs
  src/Tizen.NUI/src/public/Accessibility.cs
  test/NUITestSample/NUITestSample/examples/AtspiTest.cs
Labels: API6

#948 Add WidgetApplication, WidgetControl, RemoteView to common profile
  packaging/PlatformFileList.txt
Labels: API6

#949 [NUI] Fix Svace issue
  src/Tizen.NUI.CommonUI/Controls/DropDown.cs
  src/Tizen.NUI.CommonUI/Controls/FlexibleView/LinearLayoutManager.cs
  src/Tizen.NUI.CommonUI/Controls/Tab.cs
  src/Tizen.NUI.CommonUI/Controls/Toast.cs
  src/Tizen.NUI/src/internal/Xaml/PruneIgnoredNodesVisitor.cs
Labels: API6

#950 [NUI] Change CommonUI APIs
  src/Tizen.NUI.CommonUI/Attributes/ImageAttributes.cs
  src/Tizen.NUI.CommonUI/Controls/Button.cs
  src/Tizen.NUI.CommonUI/Controls/Control.cs
  src/Tizen.NUI.CommonUI/Controls/DropDown.cs
  src/Tizen.NUI.CommonUI/Controls/FlexibleView/FlexibleView.cs
  src/Tizen.NUI.CommonUI/Controls/InputField.cs
  src/Tizen.NUI.CommonUI/Controls/Popup.cs
  src/Tizen.NUI.CommonUI/Controls/Progress.cs
  src/Tizen.NUI.CommonUI/Controls/Scrollbar.cs
  src/Tizen.NUI.CommonUI/Controls/SelectButton.cs
  src/Tizen.NUI.CommonUI/Controls/Slider.cs
  src/Tizen.NUI.CommonUI/Controls/Switch.cs
  src/Tizen.NUI.CommonUI/Controls/Toast.cs
  src/Tizen.NUI/src/internal/DefaultItemLayoutProperty.cs
  src/Tizen.NUI/src/internal/DefaultItemLayoutType.cs
  src/Tizen.NUI/src/internal/DefaultRuler.cs
  src/Tizen.NUI/src/internal/FixedRuler.cs
  src/Tizen.NUI/src/internal/Interop/Interop.CubeTransitionEffect.cs
  src/Tizen.NUI/src/internal/Interop/Interop.FrameCallback.cs
  src/Tizen.NUI/src/internal/Item.cs
  src/Tizen.NUI/src/internal/ItemContainer.cs
  src/Tizen.NUI/src/internal/ItemFactory.cs
  src/Tizen.NUI/src/internal/ItemIdContainer.cs
  src/Tizen.NUI/src/internal/ItemLayout.cs
  src/Tizen.NUI/src/internal/ItemRange.cs
  src/Tizen.NUI/src/internal/ItemView.cs
  src/Tizen.NUI/src/internal/NUICoreBackend.cs
  src/Tizen.NUI/src/internal/RefObject.cs
  src/Tizen.NUI/src/internal/Ruler.cs
  src/Tizen.NUI/src/internal/RulerDomain.cs
  src/Tizen.NUI/src/internal/RulerPtr.cs
  src/Tizen.NUI/src/public/BaseComponents/TableView.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/CubeTransitionEffect.cs
  src/Tizen.NUI/src/public/FrameCallback.cs
  src/Tizen.NUI/src/public/Layer.cs
  src/Tizen.NUI/src/public/TapGestureDetector.cs
  src/Tizen.NUI/src/public/UIComponents/ScrollView.cs
  src/Tizen.NUI/src/public/UIComponents/Slider.cs
Labels: API6, Internal API Changed

#944 [MediaPlayer] Add API to be able to cancel preparing it
  src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Events.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
Labels: ACR Required, API6
