Repository Samsung/TizenFX, pull requests merged in 2019-04, with the labels that each got.

#773 [NUI] Add to get LogicalKey and KeyPressed
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
  src/Tizen.NUI/src/public/Key.cs
Labels: API6, Internal API Changed

#774 [DevicePolicyManager] Fix typo of property name
  src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager/PasswordPolicy.cs
Labels: ACR Required, API6

#769 [MediaController] Add new API for Season, Episode, Resolution
  src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerPlaylist.cs
  src/Tizen.Multimedia.Remoting/MediaController/InternalEnums.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlMetadata.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlPlaylist.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs
Labels: ACR Accepted, API6

#780 [MediaController] Remove useless method call and fix the bug of forea…
  src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerPlaylist.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlPlaylist.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
Labels: API6

#781 [NUI] Add FriendAssembly for FLUX
  src/Tizen.NUI/src/internal/FriendAssembly.cs
Labels: API6

#768 [System.Information] Remove RuntimeInfo key convert logic for TV product
  src/Tizen.System.Information/RuntimeInfo/RuntimeInfo.cs
  src/Tizen.System.Information/RuntimeInfo/RuntimeInfoEventHandler.cs
  src/Tizen.System.Information/RuntimeInfo/TvProductHelper.cs
Labels: API6

#779 [Bluetooth][TCSACR-237] Add BluetoothLeDevice APIs
  src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapter.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapterImpl.cs
Labels: ACR Required, API6

#785 [NUI] Fix WatchApplication crash issue
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API6

#789 Fix type mismatch
  src/Tizen.Applications.WatchfaceComplication/Tizen.Applications/ComplicationData.cs
  src/Tizen.Applications.WatchfaceComplication/Tizen.Applications/Interop/Interop.WatchfaceComplication.cs
Labels: API6

#788 [MediaContent] Add missing description and its related code
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfoCommand.cs
Labels: API6

#787 [Bluetooth][Non-ACR] Fix no data exception issue
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapterImpl.cs
Labels: API6

#790 [MediaController] Remove useless method call and fix the bug of foreach method
  src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerPlaylist.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlPlaylist.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
Labels: API5

#782 [MediaContent] Add exception and change p/invoke function
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfoCommand.cs
Labels: ACR Accepted, API6

#775 [Location]Modified Stop() for StopBatch() functionality
  src/Tizen.Location/Tizen.Location/Locator.cs
Labels: API6

#610 [WebView] [TCSACR-219] Add WebView Settings API
  src/Tizen.WebView/Interop/Interop.ChromiumEwk.Settings.cs
  src/Tizen.WebView/Tizen.WebView/Settings.cs
Labels: ACR Required, API6, Internal API Changed

#643 [WebView] [TCSACR-219] Add Context API
  src/Tizen.WebView/Interop/Interop.ChromiumEwk.Context.cs
  src/Tizen.WebView/Tizen.WebView/Context.cs
Labels: ACR Required, API6, Internal API Changed

#674 [WebView] [TCSACR-219] Add Context Menu API
  src/Tizen.WebView/Interop/Interop.ChromiumEwk.ContextMenu.cs
  src/Tizen.WebView/Tizen.WebView/ContextMenu.cs
  src/Tizen.WebView/Tizen.WebView/WebView.cs
Labels: ACR Required, API6

#689 [WebView] [TCSACR-219] Add Policy Decision APIs
  src/Tizen.WebView/Interop/Interop.ChromiumEwk.PolicyDecision.cs
  src/Tizen.WebView/Tizen.WebView/PolicyDecisionEventArgs.cs
  src/Tizen.WebView/Tizen.WebView/WebView.cs
Labels: ACR Required, API6, Internal API Changed

#675 [WebView] [TCSACR-219] Add view APIs
  src/Tizen.WebView/Interop/Interop.ChromiumEwk.View.cs
  src/Tizen.WebView/Interop/Interop.Eina.cs
  src/Tizen.WebView/Tizen.WebView/WebView.cs
Labels: ACR Required, API6

#792 [NUI] Fix svace issue
  src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
Labels: API6

#784 [ImageUtil] Deprecate useless CalculateBufferSize
  src/Tizen.Multimedia.Util/ImageUtil/ImageUtil.cs
Labels: ACR Required, API6

#783 [MediaPlayer] add APIs for controlling an audio pitch
  src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
  src/Tizen.Multimedia.MediaPlayer/Player/SphericalVideo.cs
Labels: ACR Required, API6

#793 [MediaController] Change P/Invoke function of playlist
  src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerPlaylist.cs
  src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerServer.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
Labels: API6

#801 [NUI] Add FriendAssembly for FLUX
  src/Tizen.NUI/src/internal/FriendAssembly.cs
Labels: API5

#803 [Camera] Fix preview buffer size
  src/Tizen.Multimedia.Camera/Camera/PreviewFrame.cs
Labels: API6

#800 [STT/TTS] Fix desctructor to call dispose (#596)
  src/Tizen.Uix.Stt/Tizen.Uix.Stt/SttClient.cs
  src/Tizen.Uix.Tts/Tizen.Uix.Tts/TtsClient.cs
Labels: ACR Required, API6

#794 [MediaPlayer] Modify the pre-condition of streaming function
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
Labels: ACR Required, API6

#807 [MediaContent] Deprecate Storage API
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent.csproj
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/Columns.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/Folder.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfo.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfoCommand.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/QueryArguments.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/Storage.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/StorageCommand.cs
Labels: ACR Required, API6

#805 [WebView] Replace eina_list_* with eina_iterator_*
  src/Tizen.WebView/Interop/Interop.Eina.cs
  src/Tizen.WebView/Tizen.WebView/BackForwardList.cs
Labels: API6

#810 [NUI] Add VectorAnimationView (DALi Lottie)
  src/Tizen.NUI/src/internal/Registry.cs
  src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs
Labels: API6, Internal API Changed
