Repository Samsung/TizenFX, pull requests merged in 2019-01, with the labels that each got.

#634 [NUI] Revert "Workaround of Vulkan backend csfs crash issue (#630)"
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
  src/Tizen.NUI/src/internal/VersionCheck.cs
  src/Tizen.NUI/src/public/NUIApplication.cs
Labels: API5

#638 [NUI] Remove version check
  src/Tizen.NUI/src/internal/Application.cs
Labels: API6

#637 [Inputmethod] Fix API description
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/EditorWindow.cs
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
Labels: API6

#641 [Bluetooth] Fix GetProfile API issue
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothDevice.cs
Labels: API6

#642 [NUI] Improve the performance when firstly create the View
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/Scrollable.cs
  src/Tizen.NUI/src/public/BaseComponents/TableView.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/BaseComponents/VideoView.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API5

#640 [ElmSharp] Modify EvasObjectRealized event triggering time
  src/ElmSharp/ElmSharp/EvasObject.cs
Labels: API6

#625 [Metadata] Add new API and deprecate old one
  src/Tizen.Multimedia.Metadata/MetadataExtractor/Metadata.cs
  src/Tizen.Multimedia.Metadata/MetadataExtractor/MetadataExtractorAttr.cs
Labels: ACR Required, API6

#645 Remove OPP Event handler (#645)
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothOppImpl.cs
Labels: API6

#647 [Inputmethod][TCSACR-212] Add missing APIs
  src/Tizen.Uix.InputMethod/Interop/Interop.InputMethod.cs
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/MimeTypeUpdateRequestedEventArgs.cs
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/PredictionHintDataUpdatedEventArgs.cs
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/PredictionHintUpdatedEventArgs.cs
Labels: ACR Required, API6

#649 [NUI] Remove GL/VK if-else, reduce dll size
  src/Tizen.NUI/src/internal/Layouting/LayoutPINVOKE.cs
  src/Tizen.NUI/src/internal/ManualPINVOKE.cs
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
  src/Tizen.NUI/src/public/NUIApplication.cs
Labels: API5

#653 [NUI] Manual merge from tizen50
  src/Tizen.NUI/src/internal/Layouting/LayoutPINVOKE.cs
  src/Tizen.NUI/src/internal/ManualPINVOKE.cs
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/Scrollable.cs
  src/Tizen.NUI/src/public/BaseComponents/TableView.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/BaseComponents/VideoView.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/NUIApplication.cs
Labels: API6

#654 [NUI] Sync with dalihub - Modify GetHashCode()
  src/Tizen.NUI/src/internal/Layouting/LayoutLength.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutMeasureSpec.cs
  src/Tizen.NUI/src/internal/Layouting/MeasuredSize.cs
  src/Tizen.NUI/src/internal/XamlBinding/TemplateUtilities.cs
  src/Tizen.NUI/src/public/Position.cs
  src/Tizen.NUI/src/public/Position2D.cs
  src/Tizen.NUI/src/public/RelativeVector2.cs
  src/Tizen.NUI/src/public/RelativeVector3.cs
  src/Tizen.NUI/src/public/RelativeVector4.cs
  src/Tizen.NUI/src/public/Size.cs
  src/Tizen.NUI/src/public/Size2D.cs
  src/Tizen.NUI/src/public/Vector2.cs
  src/Tizen.NUI/src/public/Vector3.cs
  src/Tizen.NUI/src/public/Vector4.cs
  src/Tizen.NUI/src/public/Window.cs
  src/Tizen.NUI/src/public/XamlBinding/Element.cs
  test/NUITestSample/NUIXAMLTestSample/res/images/Backward.png
  test/NUITestSample/NUIXAMLTestSample/res/images/Forward.png
  test/NUITestSample/NUIXAMLTestSample/res/images/Pause.png
  test/NUITestSample/NUIXAMLTestSample/res/images/icon-play.png
  test/NUITestSample/NUIXAMLTestSample/res/layout/VideoViewPage.xaml
  test/NUITestSample/NUIXAMLTestSample/res/videos/demoVideo.mp4
  test/NUITestSample/NUIXAMLTestSample/res/videos/sample.wav
Labels: API6

#657 [NUI] Fix VD Svace issue
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
  src/Tizen.NUI/src/internal/Xaml/MarkupExtensions/StyleSheetExtension.cs
  src/Tizen.NUI/src/internal/Xaml/PruneIgnoredNodesVisitor.cs
  src/Tizen.NUI/src/internal/Xaml/XamlParser.cs
  src/Tizen.NUI/src/internal/XamlBinding/Application.cs
  src/Tizen.NUI/src/internal/XamlBinding/ResourcesExtensions.cs
  src/Tizen.NUI/src/public/Window.cs
  src/Tizen.NUI/src/public/XamlBinding/ResourceDictionary.cs
Labels: API5

#659 [Applications] Fix static analysis issue
  src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Labels: API5

#660 [Notification] Fix Deref after as.instant issue
  src/Tizen.Applications.NotificationEventListener/Tizen.Applications.NotificationEventListener/NotificationButtonActionArgsBinder.cs
  src/Tizen.Applications.NotificationEventListener/Tizen.Applications.NotificationEventListener/NotificationReplyActionArgsBinder.cs
Labels: API6

#662 [Applications] Modify args handling
  src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Labels: API6

#633 [Application] Fix SynchronizationContext issue
  src/Tizen.Applications.WatchApplication/Tizen.Applications.CoreBackend/WatchCoreBackend.cs
  src/Tizen.Applications.WidgetApplication/Tizen.Applications.CoreBackend/WidgetCoreBackend.cs
Labels: API6

#665 [Notification] Fix Deref after as.instant issue
  src/Tizen.Applications.NotificationEventListener/Tizen.Applications.NotificationEventListener/NotificationButtonActionArgsBinder.cs
  src/Tizen.Applications.NotificationEventListener/Tizen.Applications.NotificationEventListener/NotificationReplyActionArgsBinder.cs
Labels: API5

#663 [Bluetooth] Fix API document
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAdapter.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAudio.cs
Labels: API6

#661 Revert "[Applications] Fix static analysis issue"
  src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Labels: API5

#670 Fix SynchronizationContext issue
  src/Tizen.Applications.WatchApplication/Tizen.Applications.CoreBackend/WatchCoreBackend.cs
  src/Tizen.Applications.WidgetApplication/Tizen.Applications.CoreBackend/WidgetCoreBackend.cs
Labels: API5

#668 [Calendar] Fix svace defect WGID#14567
  src/Tizen.Pims.Calendar/Tizen.Pims.Calendar/CalendarStructs.cs
Labels: API6

#669 [InputMethod] Remove lock from InputMethodEditor
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
Labels: API5

#673 [Calendar] Fix svace defect WGID#14567
  src/Tizen.Pims.Calendar/Tizen.Pims.Calendar/CalendarStructs.cs
Labels: API5

#671 [InputMethod] Remove lock from InputMethodEditor
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
Labels: API6

#676 [NUI] Add |AddJavaScriptInterface| API for WebView
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
  src/Tizen.NUI/src/internal/WebView.cs
Labels: API6, Internal API Changed

#677 Readme: Fix Travis Build Status badge
  README.md
Labels: API6

#679 [SystemSettings] Add SystemSettings.UnitTest
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest.sln
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/SystemSettings.UnitTest.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/SystemSettings.UnitTest.csproj
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/TizenProfiler/DotNET-20190102-143802/Session.cps
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/TizenProfiler/DotNET-20190102-153950/Session.cps
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/TizenProfiler/DotNET-20190102-154041/Session.cps
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/TizenProfiler/DotNET-20190102-163018/Session.cps
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/TizenProfiler/DotNET-20190118-165948/Session.cps
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/TizenProfiler/DotNET-20190118-170030/Session.cps
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/TizenProfiler/DotNET-20190118-170105/Session.cps
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/copy_binary.bat
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/shared/res/SystemSettings_UnitTest.png
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/Assert.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSData3GNetworkSettingChangedEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSEmailAlertRingtoneChangedEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSFontSizeChangedEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSFontTypeChangedEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSIncomingCallRingtoneChangedEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSLocaleCountryChangedEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSLocaleLanguageChangedEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSLocaleTimeFormat24HourSettingChangedEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSLocaleTimeZoneChangedEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSLockStateChangedEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSLockscreenAppChangedEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSMotionActivationSettingChangedEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSScreenBacklightTimeChangedEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSSoundNotificationChangedEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSSoundNotificationRepetitionPeriodChangedEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSSystemSettings.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSWallpaperHomeScreenChangedEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSWallpaperLockScreenChangedEventArgs.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/tizen-manifest.xml
Labels: API6

#678 [Bluetooth] Fix the wirte value request callback's parameter order (#678)
  src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
Labels: API6

#687 [NUI] Fix svace issue
  src/Tizen.NUI/src/internal/XamlBinding/ObservableWrapper.cs
Labels: API5

#646 [ElmSharp] Added Parent property to ItemObject and new event for automation test
  src/ElmSharp/ElmSharp/ColorSelector.cs
  src/ElmSharp/ElmSharp/ColorSelectorItem.cs
  src/ElmSharp/ElmSharp/ContextPopup.cs
  src/ElmSharp/ElmSharp/ContextPopupItem.cs
  src/ElmSharp/ElmSharp/Elementary.cs
  src/ElmSharp/ElmSharp/FlipSelector.cs
  src/ElmSharp/ElmSharp/FlipSelectorItem.cs
  src/ElmSharp/ElmSharp/GenGrid.cs
  src/ElmSharp/ElmSharp/GenGridItem.cs
  src/ElmSharp/ElmSharp/GenItem.cs
  src/ElmSharp/ElmSharp/GenList.cs
  src/ElmSharp/ElmSharp/GenListItem.cs
  src/ElmSharp/ElmSharp/Hoversel.cs
  src/ElmSharp/ElmSharp/HoverselItem.cs
  src/ElmSharp/ElmSharp/Index.cs
  src/ElmSharp/ElmSharp/IndexItem.cs
  src/ElmSharp/ElmSharp/ItemObject.cs
  src/ElmSharp/ElmSharp/List.cs
  src/ElmSharp/ElmSharp/ListItem.cs
  src/ElmSharp/ElmSharp/MultiButtonEntry.cs
  src/ElmSharp/ElmSharp/MultiButtonEntryItem.cs
  src/ElmSharp/ElmSharp/NaviItem.cs
  src/ElmSharp/ElmSharp/Naviframe.cs
  src/ElmSharp/ElmSharp/Popup.cs
  src/ElmSharp/ElmSharp/PopupItem.cs
  src/ElmSharp/ElmSharp/Toolbar.cs
  src/ElmSharp/ElmSharp/ToolbarItem.cs
  test/ElmSharp.Test/TestRunner.cs
Labels: ACR Required, API6

#695 [ElmSharp] Fix EcoreMainloop PostAndWakeUp behavior
  src/ElmSharp/ElmSharp/EcoreMainloop.cs
Labels: API6

#690 [Bluetooth] Add new API to destroy Gatt server
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
Labels: ACR Required, API6

#696 [NUI] Fix VD Svace issue
  src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
  src/Tizen.NUI/src/internal/XamlBinding/Interactivity/XamlPropertyCondition.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API5
