Repository Samsung/TizenFX, pull requests merged in 2019-08, with the labels that each got.

#954 [ElmSharp] Obsolete ContextPopup.IsAvailableDirection
  src/ElmSharp/ElmSharp/ContextPopup.cs
  src/ElmSharp/Interop/Interop.Elementary.CtxPopup.cs
Labels: API6

#956 [NUI]Change GetWindowList() to static
  src/Tizen.NUI/src/internal/Application.cs
Labels: API6

#957 [NUI] Change API for Window Creation
  src/Tizen.NUI/src/public/Window.cs
Labels: API6, Internal API Changed

#955 [MediaPlayer] fix descriptions
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerEnums.cs
Labels: API6

#959 [EflSharp] Fix constructor of MoreOption and RotarySelector
  internals/src/EflSharp/EflSharp/Circle/MoreOption.cs
  internals/src/EflSharp/EflSharp/Circle/RotarySelector.cs
Labels: API6

#952 [MediaController] Add constructor of MediaControlSearchCondition
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlSearchCondition.cs
Labels: ACR Required, API6

#961 [NUI] Add method to destroy a window
  src/Tizen.NUI/src/public/Window.cs
Labels: API6, Internal API Changed

#967 [NUI] integration from dalihub
  src/Tizen.NUI/src/internal/Builder.cs
  src/Tizen.NUI/src/internal/GaussianBlurView.cs
  src/Tizen.NUI/src/internal/Interop/Interop.Adaptor.cs
  src/Tizen.NUI/src/internal/Interop/Interop.Builder.cs
  src/Tizen.NUI/src/internal/Interop/Interop.PageTurnView.cs
  src/Tizen.NUI/src/internal/Interop/Interop.View.cs
  src/Tizen.NUI/src/internal/Layouting/FlexLayout.cs
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.FlexLayout.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
  src/Tizen.NUI/src/internal/Layouting/LinearLayout.cs
  src/Tizen.NUI/src/internal/PageTurnView.cs
  src/Tizen.NUI/src/public/Adaptor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/NUIApplication.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API6

#968 [NUI] Merge Layout related changes from dalihub
  src/Tizen.NUI/src/internal/Layouting/FlexLayout.cs
  src/Tizen.NUI/src/internal/Layouting/GridLayout.cs
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.AbsoluteLayout.cs
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.GridLayout.cs
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.Layout.cs
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.LayoutGroupWrapper.cs
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.LayoutGroupWrapperImpl.cs
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.LayoutItemPtr.cs
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.LayoutItemWrapper.cs
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.LayoutLength.cs
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.LayoutParent.cs
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.LayoutSize.cs
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.LinearLayout.cs
  src/Tizen.NUI/src/internal/Layouting/Interop/LayoutPINVOKE.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutData.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutGroup.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutItem.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutTransition.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API6, Internal API Changed

#969 [NUI] Sync with dalihub
  src/Tizen.NUI/src/internal/GaussianBlurView.cs
  src/Tizen.NUI/src/internal/Interop/Interop.Button.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ImageView.cs
  src/Tizen.NUI/src/internal/Interop/Interop.PushButton.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ViewImpl.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ViewInternal.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutData.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutTransition.cs
  src/Tizen.NUI/src/internal/ViewImpl.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/UIComponents/Button.cs
Labels: API6

#970 [NUI] Sync with dalihub
  src/Tizen.NUI/src/internal/DefaultItemLayoutProperty.cs
  src/Tizen.NUI/src/internal/DefaultItemLayoutType.cs
  src/Tizen.NUI/src/internal/DragAndDropDetector.cs
  src/Tizen.NUI/src/internal/Interop/Interop.Adaptor.cs
  src/Tizen.NUI/src/internal/Interop/Interop.DragAndDropDetector.cs
  src/Tizen.NUI/src/internal/Interop/Interop.WindowInternal.cs
  src/Tizen.NUI/src/internal/Item.cs
  src/Tizen.NUI/src/internal/ItemContainer.cs
  src/Tizen.NUI/src/internal/ItemFactory.cs
  src/Tizen.NUI/src/internal/ItemIdContainer.cs
  src/Tizen.NUI/src/internal/ItemLayout.cs
  src/Tizen.NUI/src/internal/ItemRange.cs
  src/Tizen.NUI/src/internal/ItemView.cs
  src/Tizen.NUI/src/internal/RefObject.cs
  src/Tizen.NUI/src/internal/Ruler.cs
  src/Tizen.NUI/src/internal/RulerDomain.cs
  src/Tizen.NUI/src/internal/RulerPtr.cs
  src/Tizen.NUI/src/internal/SWIGTYPE_p_Dali__SignalT_void_fDali__DragAndDropDetectorF_t.cs
  src/Tizen.NUI/src/public/Adaptor.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API6

#975 [NUI] Fix TV Gallary crash
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API6

#976 [AudioManager] Add 'Network' audio device type
  src/Tizen.Multimedia/AudioManager/AudioDeviceType.cs
Labels: ACR Required, API6

#953 [MediaCodec] Remove feature description and tag in EventArgs class
  src/Tizen.Multimedia.MediaCodec/MediaCodec/BufferStatusChangedEventArgs.cs
  src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodecErrorOccurredEventArgs.cs
Labels: ACR Required, API6

#971 [Application.Common][TCSACR-260][Add] Add SuspendedState Event
  src/Tizen.Applications.Common/Interop/Interop.AppCommon.cs
  src/Tizen.Applications.Common/Tizen.Applications.CoreBackend/DefaultCoreBackend.cs
  src/Tizen.Applications.Common/Tizen.Applications.CoreBackend/EventType.cs
  src/Tizen.Applications.Common/Tizen.Applications/SuspendedState.cs
  src/Tizen.Applications.Common/Tizen.Applications/SuspendedStateEventArgs.cs
Labels: ACR Required, API6, Internal API Changed

#978 [Applications.Common] Fix exception messages
  src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
Labels: API6

#973 [ComponentManager] Add new APIs to handle components of the component…
  src/Tizen.Applications.ComponentManager/Interop/Interop.ComponentManager.cs
  src/Tizen.Applications.ComponentManager/Interop/Interop.Libraries.cs
  src/Tizen.Applications.ComponentManager/Tizen.Applications.ComponentManager.csproj
  src/Tizen.Applications.ComponentManager/Tizen.Applications.ComponentManager.sln
  src/Tizen.Applications.ComponentManager/Tizen.Applications/ComponentInfo.cs
  src/Tizen.Applications.ComponentManager/Tizen.Applications/ComponentManager.cs
  src/Tizen.Applications.ComponentManager/Tizen.Applications/ComponentRunningContext.cs
  src/Tizen.Applications.ComponentManager/Tizen.Applications/ComponentType.cs
Labels: ACR Required, API6, Internal API Changed

#986 change province name in language enum
  src/Tizen.PhonenumberUtils/Tizen.PhonenumberUtils/PhonenumberUtilsEnumerations.cs
Labels: API6

#974 [MediaPlayer] add APIs to use AudioOffload
  src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/AudioEffect.cs
  src/Tizen.Multimedia.MediaPlayer/Player/AudioOffload.cs
  src/Tizen.Multimedia.MediaPlayer/Player/EqualizerBand.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerFeatures.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerTrackInfo.cs
Labels: ACR Required, API6

#990 [MediaPlayer] fix APIs to get the list of really supported formats
  src/Tizen.Multimedia.MediaPlayer/Interop/Interop.Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/MediaStreamSource.cs
Labels: API6

#992 [NUI] Add SetParent interface
  src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API6, Internal API Changed

#993 [MediaPlayer] fix descriptions to reflect comments
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
Labels: API6

#994 [MediaController] Replace deprecated pinvoke function
  src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerClient.cs
  src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerServer.cs
  src/Tizen.Multimedia.Remoting/MediaController/InternalEnums.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControllerManager.Events.cs
Labels: API6

#989 [ComponentManager] Change namespace
  src/Tizen.Applications.ComponentBased.ComponentManager/Interop/Interop.ComponentManager.cs
  src/Tizen.Applications.ComponentBased.ComponentManager/Interop/Interop.Libraries.cs
  src/Tizen.Applications.ComponentBased.ComponentManager/Tizen.Applications.ComponentBased.ComponentManager.csproj
  src/Tizen.Applications.ComponentBased.ComponentManager/Tizen.Applications.ComponentBased.ComponentManager.sln
  src/Tizen.Applications.ComponentBased.ComponentManager/Tizen.Applications/ComponentInfo.cs
  src/Tizen.Applications.ComponentBased.ComponentManager/Tizen.Applications/ComponentManager.cs
  src/Tizen.Applications.ComponentBased.ComponentManager/Tizen.Applications/ComponentRunningContext.cs
  src/Tizen.Applications.ComponentBased.ComponentManager/Tizen.Applications/ComponentType.cs
Labels: ACR Required, API6, Internal API Changed
