Repository Samsung/TizenFX, pull requests merged in 2019-05, with the labels that each got.

#806 [NUI] Fix build warnings
  src/Tizen.NUI/src/internal/XamlBinding/NavigationPage.cs
  src/Tizen.NUI/src/internal/XamlBinding/RotationTypeConverter.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/UIComponents/ToggleButton.cs
Labels: API6

#815 [NUI] Make DrawModeType.Stencil deprecated
  src/Tizen.NUI/src/public/NUIConstants.cs
Labels: ACR Required, API6

#817 [WebView] Copy the managed string into unmanaged memory for eina_hash…
  src/Tizen.WebView/Interop/Interop.Eina.cs
  src/Tizen.WebView/Tizen.WebView/WebView.cs
Labels: API6

#816 [NUI] Sync dalihub - Add C# layout
  src/Tizen.NUI/src/internal/Layouting/AbsoluteLayout.cs
  src/Tizen.NUI/src/internal/Layouting/FlexLayout.cs
  src/Tizen.NUI/src/internal/Layouting/GridLayout.cs
  src/Tizen.NUI/src/internal/Layouting/GridLocations.cs
  src/Tizen.NUI/src/internal/Layouting/ILayoutParent.cs
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.LayoutGroupWrapperImpl.cs
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.LayoutItemWrapperImpl.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutData.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutGroup.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutGroupWrapper.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutGroupWrapperImpl.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutItem.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutItemPtr.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutItemWrapper.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutItemWrapperImpl.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutLength.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutLengthEx.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutMeasureSpec.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutSize.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutSizeEx.cs
  src/Tizen.NUI/src/internal/Layouting/LinearLayout.cs
  src/Tizen.NUI/src/internal/Layouting/MeasureSpecification.cs
  src/Tizen.NUI/src/internal/Layouting/MeasuredSize.cs
  src/Tizen.NUI/src/internal/Layouting/MeasuredSizeEx.cs
  src/Tizen.NUI/src/internal/NDalic.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/Layer.cs
  src/Tizen.NUI/src/public/Window.cs
  test/NUITestSample/NUITestSample/examples/layouting/custom-layout-root-layer-test.cs
  test/NUITestSample/NUITestSample/examples/layouting/custom-layout-test-2.cs
  test/NUITestSample/NUITestSample/examples/layouting/custom-layout-test.cs
  test/NUITestSample/NUITestSample/examples/layouting/custom-layout-without-absoluteLayout-test.cs
  test/NUITestSample/NUITestSample/examples/layouting/root-problem-fix-adding-several-layers.cs
Labels: API6, Internal API Changed

#820 [Tizen.Applications.EventManager] Request to add EventManager dll
  packaging/PlatformFileList.txt
Labels: API6

#822 [MediaController] Removed p/invoke function, which is not used anymore
  src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerServer.cs
Labels: API6

#821 [NUI] Add GraphicsTypeManager for Density Independent Pixel
  src/Tizen.NUI/src/internal/XamlBinding/BindableProperty.cs
  src/Tizen.NUI/src/internal/XamlBinding/PositionTypeConverter.cs
  src/Tizen.NUI/src/internal/XamlBinding/SizeTypeConverter.cs
  src/Tizen.NUI/src/internal/XamlBinding/Style.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/FocusManager.cs
  src/Tizen.NUI/src/public/GraphicsTypeConverter.cs
  src/Tizen.NUI/src/public/GraphicsTypeManager.cs
  src/Tizen.NUI/src/public/Layer.cs
  src/Tizen.NUI/src/public/Position2D.cs
Labels: API6, Internal API Changed

#825 [NUI] Comment modifying in GraphicsTypeManager
  src/Tizen.NUI/src/public/GraphicsTypeConverter.cs
  src/Tizen.NUI/src/public/GraphicsTypeManager.cs
Labels: API6

#826 [MediaPlayer] Change documentation for streaming APIs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
Labels: API6

#828 [NUI] Remove throw exception for WidgetView, Enable NameScopeExtensio…
  src/Tizen.NUI/src/internal/Registry.cs
  src/Tizen.NUI/src/internal/Xaml/XamlLoader.cs
  src/Tizen.NUI/src/public/Layer.cs
Labels: API6, Internal API Changed

#829 [MediaController] Fix description
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlMetadata.cs
Labels: API6

#833 [Bluetooth][Non-ACR] Fix API document
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapter.cs
Labels: API6

#812 [STT/TTS] support multi handle for event
  src/Tizen.Uix.Stt/Tizen.Uix.Stt/SttClient.cs
  src/Tizen.Uix.Tts/Tizen.Uix.Tts/TtsClient.cs
Labels: API6

#823 [NUI] Implement WebView APIs
  src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
  src/Tizen.NUI/src/internal/WebView.cs
  src/Tizen.NUI/src/internal/WebViewPageLoadErrorEventArgs.cs
  src/Tizen.NUI/src/internal/WebViewPageLoadErrorSignal.cs
  src/Tizen.NUI/src/internal/WebViewPageLoadEventArgs.cs
  src/Tizen.NUI/src/internal/WebViewPageLoadSignal.cs
  src/Tizen.NUI/src/public/NUIConstants.cs
Labels: API6, Internal API Changed

#835 [NUI] Change name of VectorAnimationView, Fix VD build error
  src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
Labels: API6, Internal API Changed

#836 [NUI] Add EditorBrowableState.Never attribute to NUI.WebView properties
  src/Tizen.NUI/src/internal/WebView.cs
Labels: API6

#837 [PackageManager] Fix thread safety issue
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Labels: API6

#838 [PackageManager] Fix thread safety issue
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Labels: API5

#839 [NUI] Fix View.HasFocus crash issue
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API6

#840 [NUI] Fix View.HasFocus crash issue
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API5

#843 [NUI] Fix NUIWatchApplication OnPause
  packaging/version.txt
  src/Tizen.NUI.Wearable/src/public/NUIWatchApplication.cs
Labels: API6

#844 Fix messaging exception
  src/Tizen.Messaging/Tizen.Messaging.Messages/MessagesManagerImpl.cs
Labels: API6

#845 [NUI] Fix LayoutController Crash issue
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
Labels: API6

#834 [NUI] Add XAML intellisense support
  pkg/Tizen.NET.API6.nuspec
  src/Tizen.NUI.Design/Properties/AssemblyInfo.cs
  src/Tizen.NUI.Design/Tizen.NUI.Design.csproj
  src/Tizen.NUI.Design/Tizen.NUI.Design.sln
  src/Tizen.NUI.Design/Tizen.NUI.Design/AttributeTableBuilder.cs
  src/Tizen.NUI.Design/Tizen.NUI.Design/RegisterMetadata.cs
  src/Tizen.NUI.Design/Tizen.NUI/AttributeTableBuilder.cs
  src/Tizen.NUI.Design/Tizen.NUI/RegisterMetadata.cs
  src/Tizen.NUI.Design/lib/Microsoft.Windows.Design.Extensibility.dll
  src/Tizen.NUI.Design/lib/System.Xaml.dll
  src/Tizen.NUI/Properties/AssemblyInfo.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: **NO MERGE**, API6

#849 Remove Uncovered API's From OAuth2
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/AuthorizationResponse.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/Authorizer.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ClientCredentialsAuthorizer.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/CodeGrantAuthorizer.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ImplicitGrantAuthorizer.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ResourceOwnerPwdCredentialsAuthorizer.cs
Labels: ACR Required, API6

#831 [NUI] Delete throw from Registry
  src/Tizen.NUI/src/internal/Registry.cs
Labels: API6

#850 Deprecate Uncovered API's of Oauth2
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/AuthorizationResponse.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/Authorizer.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/CodeGrantAuthorizer.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ImplicitGrantAuthorizer.cs
Labels: ACR Accepted, API5

#841 [VoiceControlManager][TCSACR-213] Add VoiceControlManager APIs
  src/Tizen.Uix.VoiceControlManager/Interop/Interop.Libraries.cs
  src/Tizen.Uix.VoiceControlManager/Interop/Interop.Manager.cs
  src/Tizen.Uix.VoiceControlManager/Interop/Interop.VoiceControlCommand.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager.csproj
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager.sln
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/AllRecognitionResultEventArgs.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/ConversationRequestedEventArgs.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/CurrentLanguageChangedEventArgs.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/ErrorOccurerdEventArgs.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/ExceptionFactory.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/FeedbackAudioFormatEventArgs.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/FeedbackStreamingEventArgs.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/PreRecognitionResultUpdatedEventArgs.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/PrivateDataUpdatedEventArgs.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/RecognitionResultUpdatedEventArgs.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/ServiceStateChangedEventArgs.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/SpecificEngineResultEventArgs.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/StateChangedEventArgs.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/VcTtsStreamingEventArgs.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/VoiceCommand.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/VoiceCommandsGroup.cs
  src/Tizen.Uix.VoiceControlManager/Tizen.Uix.VoiceControlManager/VoiceControlManagerClient.cs
Labels: ACR Required, API6

#832 [MediaContent] Deprecate filter keyword
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/Columns.cs
Labels: ACR Required, API6

#864 Fix API reference for RPC port
  src/Tizen.Applications.Common/Tizen.Applications.RPCPort/ProxyBase.cs
  src/Tizen.Applications.Common/Tizen.Applications.RPCPort/StubBase.cs
Labels: API6

#866 [MediaContent] Fix description of Delete method
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfoCommand.cs
Labels: API6

#852 [OAuth2] Remove reference to AuthorizeAsync method from documentation
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/CodeGrantAuthorizer.cs
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2/ImplicitGrantAuthorizer.cs
Labels: API6

#867 [NUI] Add NUI.Xaml into Platform binary
  packaging/PlatformFileList.txt
Labels: API6

#868 [Doc] Fix documentation warnings
  src/Tizen.Account.SyncManager/Tizen.Account.SyncManager/SyncAdapter.cs
  src/Tizen.Multimedia.MediaPlayer/Player/SphericalVideo.cs
  src/Tizen.Nlp/Tizen.Nlp/NaturalLanguageProcess.cs
  src/Tizen.Uix.InputMethodManager/Tizen.Uix.InputMethodManager/InputMethodManager.cs
  src/Tizen.WebView/Tizen.WebView/WebView.cs
Labels: API6

#869 [Build] Suppress CS0618 warnings due to internal reference
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/Folder.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfo.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/QueryArguments.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/Storage.cs
  src/Tizen.Multimedia.Metadata/MetadataExtractor/Metadata.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.Events.cs
  src/Tizen.Multimedia/AudioManager/AudioManager.cs
  src/Tizen.Multimedia/Interop/Interop.Device.cs
Labels: API6

#870 [MediaPlayer] Change descriptions of audio pitch APIs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
Labels: API6

#871 [NUI] Add Renderer Ranges
  src/Tizen.NUI/src/internal/Interop/Interop.Renderer.cs
  src/Tizen.NUI/src/public/Renderer.cs
Labels: API6, Internal API Changed
