Repository Samsung/TizenFX, pull requests merged in 2019-02, with the labels that each got.

#698 Add Tizen.Security.DevicePolicyManager.dll
  packaging/PlatformFileList.txt
Labels: API6

#699 [NUI] Make some apis as inhouse, will be internal later
  src/Tizen.NUI/src/internal/AdaptorSignalType.cs
  src/Tizen.NUI/src/internal/KeyboardTypeSignalType.cs
  src/Tizen.NUI/src/internal/SWIGTYPE_p_bundle.cs
  src/Tizen.NUI/src/internal/WidgetViewSignal.cs
  src/Tizen.NUI/src/public/Animation.cs
  src/Tizen.NUI/src/public/BaseComponents/FlexContainer.cs
  src/Tizen.NUI/src/public/BaseComponents/Scrollable.cs
  src/Tizen.NUI/src/public/PropertyBuffer.cs
  src/Tizen.NUI/src/public/PropertyNotification.cs
  src/Tizen.NUI/src/public/PropertyNotifySignal.cs
  src/Tizen.NUI/src/public/Renderer.cs
  src/Tizen.NUI/src/public/Shader.cs
  src/Tizen.NUI/src/public/UIComponents/ScrollView.cs
  src/Tizen.NUI/src/public/UIComponents/ToggleButton.cs
Labels: ACR Required, API6, Internal API Changed

#700 Add Tizen.Security.PrivacyPrivilegeManager to doc index page
  docs/api/index.md
Labels: API6

#701 [Bluetooth][TCSACR-216] Add missing feature tag on document
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGatt.cs
Labels: API6

#704 [NUI] Fix NUI Manual TCT issue
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API6

#685 [Account] Unmanaged resource handling
  src/Tizen.Account.AccountManager/Interop/Interop.Account.cs
  src/Tizen.Account.AccountManager/Tizen.Account.AccountManager/AccountService.cs
Labels: API6

#708 [NUI] Fix PropertyMap setting issue
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
Labels: API6

#707 [Inputmethod] Remove useless exception
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
Labels: API6

#710 [Tizen.Applications.Common] Add a timer for handling GC collection
  src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Labels: API6

#713 [NUI] Fix SynchronouseLoading and OrientationCorrection to be applied…
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
Labels: API6

#709 [Bluetooth] Fix the socket callback issue
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothServerSocket.cs
Labels: API6

#703 Add WatchfaceComplication.dll and fix some bugs
  packaging/PlatformFileList.txt
  src/Tizen.Applications.WatchfaceComplication/Tizen.Applications/Complication.cs
  src/Tizen.Applications.WatchfaceComplication/Tizen.Applications/ComplicationProvider.cs
  src/Tizen.Applications.WatchfaceComplication/Tizen.Applications/EditablesContainer.cs
  src/Tizen.Applications.WatchfaceComplication/Tizen.Applications/RangedValueData.cs
Labels: API6

#714 Change class description
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/InvalidKeyException.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/NowInProgressException.cs
Labels: API6

#716 [Tizen.Applications.Common] Add a timer for handling GC collection
  src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Labels: API5

#717 [NUI] Fix svace issue
  src/Tizen.NUI/src/internal/Xaml/ApplyPropertiesVisitor.cs
  src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
Labels: API5

#684 [SystemSettings][TCSACR-215] Add properties
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEnums.cs
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEventArgs.cs
Labels: ACR Accepted, API6

#718 [NUI] sync with dalihub
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutPINVOKE.cs
  src/Tizen.NUI/src/internal/ManualPINVOKE.cs
  src/Tizen.NUI/src/internal/NDalicPINVOKE.cs
  src/Tizen.NUI/src/internal/Xaml/ApplyPropertiesVisitor.cs
  src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
  src/Tizen.NUI/src/internal/XamlBinding/ObservableWrapper.cs
  src/Tizen.NUI/src/internal/XamlBinding/StyleSheets/StyleSheetExtensions.cs
  src/Tizen.NUI/src/public/ImageLoading.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API6, Internal API Changed

#711 [AudioManager] Add HasStreamOnDevice method to AudioStreamPolicy
  src/Tizen.Multimedia/AudioManager/AudioStreamPolicy.cs
  src/Tizen.Multimedia/Interop/Interop.StreamPolicy.cs
Labels: ACR Required, API6

#724 [NUI] Fix GetHashCode Crash issue
  src/Tizen.NUI/src/internal/Layouting/LayoutLength.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutMeasureSpec.cs
  src/Tizen.NUI/src/internal/Layouting/MeasuredSize.cs
  src/Tizen.NUI/src/public/Position.cs
  src/Tizen.NUI/src/public/Position2D.cs
  src/Tizen.NUI/src/public/RelativeVector2.cs
  src/Tizen.NUI/src/public/RelativeVector3.cs
  src/Tizen.NUI/src/public/RelativeVector4.cs
  src/Tizen.NUI/src/public/Size.cs
  src/Tizen.NUI/src/public/Size2D.cs
  src/Tizen.NUI/src/public/Vector2.cs
  src/Tizen.NUI/src/public/Vector3.cs
  src/Tizen.NUI/src/public/Vector4.cs
Labels: API6

#725 [SystemSetting] Add setter for AccessibilityTtsEnabled
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/SystemSettings.UnitTest.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/SystemSettings.UnitTest.csproj
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSSystemSettings.cs
Labels: API6

#720 [ElmSharp] Fix memory leak on Image.LoadAsync method
  src/ElmSharp/ElmSharp/EvasObject.cs
  src/ElmSharp/ElmSharp/EvasObjectEvent.cs
  src/ElmSharp/ElmSharp/Image.cs
  src/ElmSharp/ElmSharp/SmartEvent.cs
Labels: API6

#682 [SystemSettings] Fix UnitTest error for TM1 target.
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/SystemSettings.UnitTest.cs
  test/Tizen.System.SystemSettings.UnitTest/SystemSettings.UnitTest/test/TSSystemSettings.cs
Labels: API6

#726 Handle NotSupportedException on SetChangedEvent and UnsetChangedEvent…
  src/Tizen.System.Storage/Storage/Storage.cs
  src/Tizen.System.Storage/Storage/StorageManager.cs
Labels: API6

#727 [NUI] Fix Svace issue
  src/Tizen.NUI/src/internal/Xaml/MarkupExtensionParser.cs
  src/Tizen.NUI/src/internal/XamlBinding/Interactivity/AttachedCollection.cs
Labels: API5

#728 [ElmSharp] Fix memory leak on Image.LoadAsync method
  src/ElmSharp/ElmSharp/EvasObject.cs
  src/ElmSharp/ElmSharp/EvasObjectEvent.cs
  src/ElmSharp/ElmSharp/Image.cs
  src/ElmSharp/ElmSharp/SmartEvent.cs
Labels: API5

#729 [Elmsharp.Wearable]add remarks of marker properties
  src/ElmSharp.Wearable/ElmSharp.Wearable/CircleDatetimeSelector.cs
  src/ElmSharp.Wearable/ElmSharp.Wearable/CircleSpinner.cs
Labels: API4

#730 [Elmsharp.Wearable] add remarks of marker properties
  src/ElmSharp.Wearable/ElmSharp.Wearable/CircleDatetimeSelector.cs
  src/ElmSharp.Wearable/ElmSharp.Wearable/CircleSpinner.cs
Labels: API5

#731 [NUI] Fix ABI break
  src/Tizen.NUI/src/internal/DaliEnumConstants.cs
  src/Tizen.NUI/src/internal/KeyboardTypeSignalType.cs
  src/Tizen.NUI/src/internal/SWIGTYPE_p_bundle.cs
  src/Tizen.NUI/src/internal/WidgetViewSignal.cs
  src/Tizen.NUI/src/public/Animation.cs
  src/Tizen.NUI/src/public/BaseComponents/FlexContainer.cs
  src/Tizen.NUI/src/public/BaseComponents/Scrollable.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/Layer.cs
  src/Tizen.NUI/src/public/NUIConstants.cs
  src/Tizen.NUI/src/public/PropertyBuffer.cs
  src/Tizen.NUI/src/public/PropertyNotification.cs
  src/Tizen.NUI/src/public/PropertyNotifySignal.cs
  src/Tizen.NUI/src/public/Renderer.cs
  src/Tizen.NUI/src/public/Shader.cs
  src/Tizen.NUI/src/public/UIComponents/ScrollView.cs
  src/Tizen.NUI/src/public/UIComponents/ToggleButton.cs
Labels: ACR Required, API6, Internal API Changed
