Repository Samsung/TizenFX, pull requests merged in 2019-09, with the labels that each got.

#998 [NUI] Add Window Creation API for setting name
  src/Tizen.NUI/src/public/Window.cs
Labels: API6, Internal API Changed

#987 [AudioManager] Add properties for the preferred device
  src/Tizen.Multimedia/AudioManager/AudioStreamPolicy.cs
  src/Tizen.Multimedia/Interop/Interop.StreamPolicy.cs
Labels: ACR Required, API6

#977 [Tizen.Applications.ComponentBased][TCSACR-265][Add] Add ComponentBased application APIs
  src/Tizen.Applications.ComponentBased.Default/Interop/Interop.EflCbApplication.cs
  src/Tizen.Applications.ComponentBased.Default/Interop/Interop.Elementary.cs
  src/Tizen.Applications.ComponentBased.Default/Interop/Interop.Libraries.cs
  src/Tizen.Applications.ComponentBased.Default/Tizen.Applications.ComponentBased.Default.csproj
  src/Tizen.Applications.ComponentBased.Default/Tizen.Applications.ComponentBased.Default/EFLComponentBasedApplication.cs
  src/Tizen.Applications.ComponentBased.Default/Tizen.Applications.ComponentBased.Default/EFLWindowInfo.cs
  src/Tizen.Applications.ComponentBased/Interop/Interop.AppControl.cs
  src/Tizen.Applications.ComponentBased/Interop/Interop.CBApplication.cs
  src/Tizen.Applications.ComponentBased/Interop/Interop.Libraries.cs
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/BaseComponent.cs
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/ComponentBasedApplication.cs
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/ComponentStateManger.cs
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/DisplayStatus.cs
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/FrameComponent.cs
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/FrameComponentStateManager.cs
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/IWindowInfo.cs
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/ServiceComponent.cs
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/ServiceComponentStateManager.cs
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.csproj
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.sln
Labels: ACR Required, API6

#996 [Tizen.Applications.PackageManager][TCSACR-272][Add] Add Dependency Info APIs
  src/Tizen.Applications.PackageManager/Interop/Interop.Package.cs
  src/Tizen.Applications.PackageManager/Interop/Interop.PackageArchive.cs
  src/Tizen.Applications.PackageManager/Tizen.Applications/Package.cs
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageArchive.cs
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageDependencyInformation.cs
Labels: ACR Required, API6

#979 [AudioManager] Add new class for audio ducking
  src/Tizen.Multimedia/AudioManager/AudioDucking.cs
  src/Tizen.Multimedia/AudioManager/AudioDuckingStateChangedEventArgs.cs
  src/Tizen.Multimedia/Interop/AudioDuckingHandle.cs
  src/Tizen.Multimedia/Interop/Interop.Ducking.cs
Labels: ACR Required, API6

#999 [NUI] Integration from dalihub (DALi 1.4.34)
  src/Tizen.NUI/src/internal/Camera.cs
  src/Tizen.NUI/src/internal/ItemView.cs
  src/Tizen.NUI/src/internal/LinearConstrainer.cs
  src/Tizen.NUI/src/internal/Model3dView.cs
  src/Tizen.NUI/src/internal/PageTurnView.cs
  src/Tizen.NUI/src/internal/PathConstrainer.cs
  src/Tizen.NUI/src/internal/RenderTask.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/Scrollable.cs
  src/Tizen.NUI/src/public/PanGestureDetector.cs
  src/Tizen.NUI/src/public/Renderer.cs
  src/Tizen.NUI/src/public/Shader.cs
  src/Tizen.NUI/src/public/UIComponents/ScrollView.cs
  src/Tizen.NUI/src/public/UIComponents/ToggleButton.cs
Labels: ACR Required, API6, Internal API Changed

#1003 [NUI] Open VectorAnimationView API
  src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs
Labels: API6, Internal API Changed

#1004 [ComponentBased] Update PlatformFileList
  packaging/PlatformFileList.txt
Labels: API6

#1005 [ComponentBased] Fix interop libraries
  src/Tizen.Applications.ComponentBased.Default/Interop/Interop.Libraries.cs
  src/Tizen.Applications.ComponentBased/Interop/Interop.Libraries.cs
Labels: API6

#1002 [Applications.Common] Add a new property of AppControl
  src/Tizen.Applications.Common/Interop/Interop.AppControl.cs
  src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
Labels: ACR Required, API6

#1007 [Tizen.Applications.ComponentBased] Modify native API name
  src/Tizen.Applications.ComponentBased/Interop/Interop.AppControl.cs
Labels: API6

#1006 Revert "[NUI] Open VectorAnimationView API (#1003)"
  src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs
Labels: API6, Internal API Changed

#1009 Add argument check logic
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/BaseComponent.cs
Labels: API6

#1000 [MediaTool] Add audio channel mapping APIs for PCM format
  src/Tizen.Multimedia/Interop/Interop.MediaTool.cs
  src/Tizen.Multimedia/MediaTool/AudioMediaFormat.cs
  src/Tizen.Multimedia/MediaTool/MediaFormatChannelPosition.cs
  src/Tizen.Multimedia/MediaTool/MediaPacket.Lock.cs
  src/Tizen.Multimedia/MediaTool/MediaPacket.cs
  src/Tizen.Multimedia/MediaTool/MediaPacketVideoPlane.cs
Labels: ACR Required, API6

#1001 [AudioIO] Add new APIs for Sample and channel type
  src/Tizen.Multimedia.AudioIO/AudioIO/AudioChannel.cs
  src/Tizen.Multimedia.AudioIO/AudioIO/AudioSampleType.cs
Labels: ACR Required, API6

#1013 [NUI] Change rotation APIs from internal to public
  src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
  src/Tizen.NUI/src/internal/Interop/Interop.WindowInternal.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API6, Internal API Changed

#1011 [Build] Remove files of VS
  .gitignore
  build.sh
  build/build.proj
  build/directories.props
  src/Tizen.NUI.Design/Tizen.NUI.Design.csproj
  src/Tizen.NUI.Design/lib/Microsoft.Windows.Design.Extensibility.dll
  src/Tizen.NUI.Design/lib/System.Xaml.dll
Labels: API6

#1016 [ComponentBased.ComponentManager][Adds an exception handling]
  src/Tizen.Applications.ComponentBased.ComponentManager/Tizen.Applications/ComponentManager.cs
Labels: API6

#1015 [NUI] Temporal fix of not animating dali-lottie when the URL is only changed
  src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/VectorAnimationView.cs
Labels: API6

#983 [MediaPlayer] add API to export video frames
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Events.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
Labels: ACR Required, API6

#1021 [NUI] Add dali-atspi
  src/Tizen.NUI/src/internal/Interop/Interop.Accessibility.cs
  src/Tizen.NUI/src/public/Accessibility.cs
Labels: API6, Internal API Changed

#1017 [MediaPlayer] Update descriptions according to the guideline
  src/Tizen.Multimedia.MediaPlayer/Player/AudioEffect.cs
  src/Tizen.Multimedia.MediaPlayer/Player/AudioOffload.cs
  src/Tizen.Multimedia.MediaPlayer/Player/EqualizerBand.cs
Labels: API6

#1012 [Tizen.Multimedia.Camera] Fixed exception bug
  src/Tizen.Multimedia.Camera/Camera/Camera.cs
Labels: API6

#1023 [MediaController] Changed pinvoke function
  src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerClient.cs
  src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerServer.cs
Labels: API6

#1024 [AudioIO] Fix crash issue
  src/Tizen.Multimedia.AudioIO/WavPlayer/WavPlayer.cs
Labels: API6

#1027 [AudioManager] Changed handle type to marshal from unmanaged
  src/Tizen.Multimedia/AudioManager/AudioDucking.cs
  src/Tizen.Multimedia/Interop/Interop.Ducking.cs
Labels: API6

#1020 [NUI] Changed the APIs related to MultiWIndow to public
  src/Tizen.NUI/src/public/Window.cs
Labels: ACR Required, API6

#1030 [ComponentBased] Fix Log Tags
  src/Tizen.Applications.ComponentBased.Default/Tizen.Applications.ComponentBased.Default/EFLComponentBasedApplication.cs
  src/Tizen.Applications.ComponentBased.Default/Tizen.Applications.ComponentBased.Default/EFLWindowInfo.cs
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/ComponentBasedApplication.cs
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/FrameComponentStateManager.cs
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/ServiceComponent.cs
Labels: API6

#1033 Fix SuspendedState documentation
  src/Tizen.Applications.Common/Tizen.Applications/SuspendedState.cs
  src/Tizen.Applications.Common/Tizen.Applications/SuspendedStateEventArgs.cs
Labels: API6

#1038 [AudioIO] Add ConfigureAwait to task
  src/Tizen.Multimedia.AudioIO/WavPlayer/WavPlayer.cs
Labels: API6

#1037 [NUI] Modify GetWindowList for getting Native Ptr
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API6

#1039 [NUI] Integration from dalihub
  src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutItem.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/Touch.cs
Labels: API6, Internal API Changed

#1034 [NUI] Add to set the position of input panel
  src/Tizen.NUI/src/internal/Interop/Interop.InputMethodContext.cs
  src/Tizen.NUI/src/public/InputMethodContext.cs
Labels: API6, Internal API Changed

#984 [STC] Add C# API wrapper for Stc CAPIs
  src/Tizen.Network.Stc/Interop/Interop.Libraries.cs
  src/Tizen.Network.Stc/Interop/Interop.Stc.cs
  src/Tizen.Network.Stc/Tizen.Network.Stc.csproj
  src/Tizen.Network.Stc/Tizen.Network.Stc.sln
  src/Tizen.Network.Stc/Tizen.Network.Stc/StcEnumerations.cs
  src/Tizen.Network.Stc/Tizen.Network.Stc/StcError.cs
  src/Tizen.Network.Stc/Tizen.Network.Stc/StcManager.cs
  src/Tizen.Network.Stc/Tizen.Network.Stc/StcManagerImpl.cs
  src/Tizen.Network.Stc/Tizen.Network.Stc/StcStatistics.cs
  src/Tizen.Network.Stc/Tizen.Network.Stc/StcStatsFilter.cs
Labels: ACR Accepted, API6, Internal API Changed

#1041 [IoTConnectivity] Fix wrong callback management
  src/Tizen.Network.IoTConnectivity/Tizen.Network.IoTConnectivity/RemoteResource.cs
Labels: API6

#1026 [NUI] Layouting API made public
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.MeasureSpec.cs
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.MeasuredSize.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutData.cs
  src/Tizen.NUI/src/internal/Layouting/LayoutSize.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/Layouting/AbsoluteLayout.cs
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
  src/Tizen.NUI/src/public/Layouting/ILayoutParent.cs
  src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
  src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
  src/Tizen.NUI/src/public/Layouting/LayoutLength.cs
  src/Tizen.NUI/src/public/Layouting/LayoutTransition.cs
  src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
  src/Tizen.NUI/src/public/Layouting/MeasureSpecification.cs
  src/Tizen.NUI/src/public/Layouting/MeasuredSize.cs
  src/Tizen.NUI/src/public/Window.cs
  test/NUITestSample/NUITestSample/examples/layouting/custom-layout-root-layer-test.cs
  test/NUITestSample/NUITestSample/examples/layouting/custom-layout-test-2.cs
  test/NUITestSample/NUITestSample/examples/layouting/custom-layout-test.cs
  test/NUITestSample/NUITestSample/examples/layouting/custom-layout-without-absoluteLayout-test.cs
  test/NUITestSample/NUITestSample/examples/layouting/root-problem-fix-adding-several-layers.cs
Labels: ACR Required, API6, Internal API Changed

#1032 [NUI] TCSACR-226 code change
  src/Tizen.NUI/src/internal/KeyboardTypeSignalType.cs
  src/Tizen.NUI/src/internal/SWIGTYPE_p_bundle.cs
  src/Tizen.NUI/src/internal/WidgetViewSignal.cs
  src/Tizen.NUI/src/public/Animation.cs
  src/Tizen.NUI/src/public/BaseComponents/FlexContainer.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/PropertyBuffer.cs
  src/Tizen.NUI/src/public/PropertyNotification.cs
  src/Tizen.NUI/src/public/PropertyNotifySignal.cs
  src/Tizen.NUI/src/public/UIComponents/ScrollView.cs
Labels: ACR Required, API6
