Repository Samsung/TizenFX, pull requests merged in 2020-09, with the labels that each got.

#1960 [NUI] Add WatchView
  src/Tizen.NUI.Wearable/src/public/WatchView.cs
  src/Tizen.NUI/src/internal/Interop/Interop.WatchView.cs
Labels: API8, Internal API Changed

#1965 [NUI] replace NUI.ISelectorItem with System.ICloneable
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ISelectorItem.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
  src/Tizen.NUI/src/public/Color.cs
  src/Tizen.NUI/src/public/Extents.cs
  src/Tizen.NUI/src/public/Position.cs
  src/Tizen.NUI/src/public/Position2D.cs
  src/Tizen.NUI/src/public/Rectangle.cs
  src/Tizen.NUI/src/public/Size.cs
  src/Tizen.NUI/src/public/Size2D.cs
  src/Tizen.NUI/src/public/Vector2.cs
  src/Tizen.NUI/src/public/Vector3.cs
  src/Tizen.NUI/src/public/Vector4.cs
  src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
  src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
  src/Tizen.NUI/src/public/ViewProperty/TextShadow.cs
Labels: API8, Internal API Changed

#1966 [NUI] use auto-property initializer for StyleManager.ThemeMap
  src/Tizen.NUI.Components/Utils/StyleManager.cs
Labels: API8

#1968 [Tizen.Applications.Common] [RPCPort] Fix wrong EntryPoint of SetPrivateSharing
  src/Tizen.Applications.Common/Interop/Interop.RPCPort.cs
Labels: API8

#1949 [NUI] Update NUI after removing Window::ResizedSignal
  src/Tizen.NUI/src/internal/Interop/Interop.ResizedSignal.cs
  src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
  src/Tizen.NUI/src/internal/ResizedSignal.cs
  src/Tizen.NUI/src/public/WindowEvent.cs
Labels: API8

#1947 [NUI] Updating PropertyBuffer interop
  src/Tizen.NUI/src/internal/Interop/Interop.PropertyBuffer.cs
  src/Tizen.NUI/src/public/PropertyBuffer.cs
Labels: API8

#1971 [NUI] Version update
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: API8

#1972 Revert "[NUI] Add Selector constructor with SelectorChangedCallback i…
  src/Tizen.NUI.Components/Utils/Selector.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
Labels: API8

#1933 [Internal] Add Tizen.Inspection internal API
  internals/src/Tizen.Inspections/Interop/Interop.Inspections.cs
  internals/src/Tizen.Inspections/Interop/Interop.Libraries.cs
  internals/src/Tizen.Inspections/Tizen.Inspections.csproj
  internals/src/Tizen.Inspections/Tizen.Inspections.sln
  internals/src/Tizen.Inspections/Tizen.Inspections/EventReceivedEventArgs.cs
  internals/src/Tizen.Inspections/Tizen.Inspections/ExceptionFactory.cs
  internals/src/Tizen.Inspections/Tizen.Inspections/Inspections.cs
Labels: API8

#1973 [NUI] Fix Components.Switch Thumb animation defect
  src/Tizen.NUI.Components/Controls/Extension/SlidingSwitchExtension.cs
Labels: API8

#1945 [NUI] Add GlWindow
  src/Tizen.NUI/src/internal/GLWindowResizedSignal.cs
  src/Tizen.NUI/src/internal/Interop/Interop.GLWindow.cs
  src/Tizen.NUI/src/internal/Interop/Interop.GLWindowFocusChangeSignal.cs
  src/Tizen.NUI/src/internal/Interop/Interop.GLWindowResizedSignal.cs
  src/Tizen.NUI/src/internal/Interop/interop.GLWindowVisibilityChangedSignal.cs
  src/Tizen.NUI/src/public/GLWindow.cs
  src/Tizen.NUI/src/public/GLWindowEvent.cs
  src/Tizen.NUI/src/public/GLWindowVisibilityChangedEvent.cs
Labels: API8, Internal API Changed

#1969 [NUI] Add KeyInputFocus property to View
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
Labels: API8, Internal API Changed

#1955 [NUI] Add OnSceneConnection and OnSceneDisconnection methods in NUI CustomView
  src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
  src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
Labels: ACR Accepted, ACR Required, API8

#1979 [Connection]Use the changed privilege to check Exception
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
Labels: API8

#1880 [NUI] Open new FlexLayout APIs
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Labels: ACR Accepted, ACR Required, API8, Internal API Changed

#1976 [NUI] Fix NUIWidget View thread error message
  src/Tizen.NUI/src/public/NUIWidgetApplication.cs
Labels: API8

#1978 [NUI] Fix exception error when sub Window is disposed
  src/Tizen.NUI/src/public/Window.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SubWindowTest.cs
Labels: API8

#1980 [Connection]Add logs
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
Labels: API8

#1986 [NUI] Removed OnHoverEvent() and OnWheelEvent()
  src/Tizen.NUI/src/internal/CustomActorImpl.cs
  src/Tizen.NUI/src/internal/Interop/Interop.CustomActorImpl.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ViewImplSignal.cs
  src/Tizen.NUI/src/internal/ViewImpl.cs
Labels: API8

#1985 [NUI] Remove Internal and unused methods in Adaptor
  src/Tizen.NUI/src/internal/AdaptorSignalType.cs
  src/Tizen.NUI/src/internal/Interop/Interop.Adaptor.cs
  src/Tizen.NUI/src/public/Adaptor.cs
Labels: API8

#1974 [NUI] Removing ContextLoss bindings and internal API
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/internal/SWIGTYPE_p_Configuration__ContextLoss.cs
Labels: API8

#1991 [Camera] Fix ObjectDisposedException bug
  src/Tizen.Multimedia.Camera/Camera/CameraCapabilities.cs
Labels: API8

#1982 [NUI] Fix Gaussian Blur View Size setting issue.
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API8

#1992 [NUI] Sync the director number with the csharp-binder
  src/Tizen.NUI/src/internal/Interop/Interop.ViewImpl.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ViewWrapperImpl.cs
  src/Tizen.NUI/src/internal/ViewImpl.cs
  src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
Labels: API8

#1989 [NUI] Update Key, Hover and Wheel code after event pimpling in DALi native
  src/Tizen.NUI/src/internal/Interop/Interop.Hover.cs
  src/Tizen.NUI/src/internal/Interop/Interop.Key.cs
  src/Tizen.NUI/src/internal/Interop/Interop.Wheel.cs
  src/Tizen.NUI/src/public/Hover.cs
  src/Tizen.NUI/src/public/Key.cs
  src/Tizen.NUI/src/public/Wheel.cs
Labels: API8

#1984 [NUI] Fix Switch bugs
  src/Tizen.NUI.Components/Controls/Extension/SlidingSwitchExtension.cs
  src/Tizen.NUI.Components/res/Theme/Tizen.NUI.Components_Tizen.NUI.Theme.Common.xaml
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API8

#1994 [NUI] Version update
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: API8

#1995 [MachineLearning.Inference] Fix the bug for double type of GetValue<T>
  src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/Pipeline.cs
Labels: API8

#1998 [NUI] add support for parameterized constructor in xaml
  src/Tizen.NUI/src/internal/Xaml/XamlLoader.cs
  src/Tizen.NUI/src/public/Xaml/XamlServiceProvider.cs
Labels: API8

#1996 [NUI] Create valid handle from Gesture constructors
  src/Tizen.NUI/src/internal/Interop/Interop.LongPressGesture.cs
  src/Tizen.NUI/src/internal/Interop/Interop.PanGestureDetector.cs
  src/Tizen.NUI/src/internal/Interop/Interop.PinchGesture.cs
  src/Tizen.NUI/src/internal/Interop/Interop.RotationGesture.cs
  src/Tizen.NUI/src/internal/Interop/Interop.TapGesture.cs
  src/Tizen.NUI/src/public/LongPressGesture.cs
  src/Tizen.NUI/src/public/PanGesture.cs
  src/Tizen.NUI/src/public/PinchGesture.cs
  src/Tizen.NUI/src/public/RotationGesture.cs
  src/Tizen.NUI/src/public/TapGesture.cs
Labels: API8

#2004 [NUI] enhance FlexLayout documentation
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Labels: API8

#2001 [NUI] Change parent class of Hover, Key, Wheel and Gesture to BaseHandle
  src/Tizen.NUI/src/internal/Interop/Interop.Gesture.cs
  src/Tizen.NUI/src/public/Gesture.cs
  src/Tizen.NUI/src/public/Hover.cs
  src/Tizen.NUI/src/public/Key.cs
  src/Tizen.NUI/src/public/LongPressGesture.cs
  src/Tizen.NUI/src/public/PanGesture.cs
  src/Tizen.NUI/src/public/PinchGesture.cs
  src/Tizen.NUI/src/public/RotationGesture.cs
  src/Tizen.NUI/src/public/TapGesture.cs
  src/Tizen.NUI/src/public/Wheel.cs
Labels: ACR Required, API8

#1983 [NUI] Adding VertexBuffer to replace PropertyBuffer
  src/Tizen.NUI/src/internal/Interop/Interop.VertexBuffer.cs
  src/Tizen.NUI/src/public/Geometry.cs
  src/Tizen.NUI/src/public/VertexBuffer.cs
Labels: ACR Required, API8, Internal API Changed

#2005 [Bluetooth][Non-ACR] Define Interop callback to global variable
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAdapterImpl.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAudioImpl.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothDevice.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothGattImpl.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothHidDeviceImpl.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothOppImpl.cs
Labels: API8

#2011 [Build] Fix directory permissions of csapi-tizen-full.rpm
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
Labels: API8

#2012 [NUI] Fix tct fail issues
  src/Tizen.NUI/src/internal/Interop/Interop.Gesture.cs
  src/Tizen.NUI/src/internal/Interop/Interop.VertexBuffer.cs
  src/Tizen.NUI/src/public/Geometry.cs
  src/Tizen.NUI/src/public/Gesture.cs
  src/Tizen.NUI/src/public/Hover.cs
  src/Tizen.NUI/src/public/Key.cs
  src/Tizen.NUI/src/public/LongPressGesture.cs
  src/Tizen.NUI/src/public/PanGesture.cs
  src/Tizen.NUI/src/public/PinchGesture.cs
  src/Tizen.NUI/src/public/RotationGesture.cs
  src/Tizen.NUI/src/public/TapGesture.cs
  src/Tizen.NUI/src/public/VertexBuffer.cs
  src/Tizen.NUI/src/public/Wheel.cs
Labels: ACR Required, API8, Internal API Changed

#1939 Add Tizen.Peripheral API
  internals/src/Tizen.Peripheral/Interop/Adc.cs
  internals/src/Tizen.Peripheral/Interop/Gpio.cs
  internals/src/Tizen.Peripheral/Interop/I2c.cs
  internals/src/Tizen.Peripheral/Interop/Libraries.cs
  internals/src/Tizen.Peripheral/Interop/Pwm.cs
  internals/src/Tizen.Peripheral/Interop/Spi.cs
  internals/src/Tizen.Peripheral/Interop/Uart.Enum.cs
  internals/src/Tizen.Peripheral/Interop/Uart.cs
  internals/src/Tizen.Peripheral/Tizen.Peripheral.csproj
  internals/src/Tizen.Peripheral/Tizen.Peripheral.sln
  internals/src/Tizen.Peripheral/Tizen.Peripheral/Adc.cs
  internals/src/Tizen.Peripheral/Tizen.Peripheral/ExceptionFactory.cs
  internals/src/Tizen.Peripheral/Tizen.Peripheral/Gpio.cs
  internals/src/Tizen.Peripheral/Tizen.Peripheral/I2c.cs
  internals/src/Tizen.Peripheral/Tizen.Peripheral/PinUpdatedEventArgs.cs
  internals/src/Tizen.Peripheral/Tizen.Peripheral/Pwm.cs
  internals/src/Tizen.Peripheral/Tizen.Peripheral/Spi.cs
  internals/src/Tizen.Peripheral/Tizen.Peripheral/Uart.cs
Labels: API8

#2015 [NUI] revert #2012 and add #1983 again by review of #2012
  src/Tizen.NUI/src/internal/Interop/Interop.VertexBuffer.cs
  src/Tizen.NUI/src/public/Geometry.cs
  src/Tizen.NUI/src/public/VertexBuffer.cs
Labels: ACR Required, API8, Internal API Changed

#2016 [Build] Install Tizen.Peripheral to all profiles temporarily
  internals/src/Tizen.Peripheral/Tizen.Peripheral.csproj
Labels: API8

#2009 [NUI] remove redundant interanl get/set methods in FlexLayout
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Labels: API8, ready to merge

#2018 [NUI] Fix Svace issues
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/FocusManager.cs
  src/Tizen.NUI/src/public/XamlBinding/ContentPage.cs
Labels: API8

#2007 [NUI] add Set/GetAttachedValue method
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
  src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
Labels: API8, Internal API Changed, ready to merge

#1975 [NUI] remove StateValueCollection from Selector
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/StateValueCollection.cs
Labels: API8, Internal API Changed, ready to merge

#2017 Revert "[NUI] Fix tct fail issues (#2012)"
  src/Tizen.NUI/src/internal/Interop/Interop.Gesture.cs
  src/Tizen.NUI/src/public/Gesture.cs
  src/Tizen.NUI/src/public/Hover.cs
  src/Tizen.NUI/src/public/Key.cs
  src/Tizen.NUI/src/public/LongPressGesture.cs
  src/Tizen.NUI/src/public/PanGesture.cs
  src/Tizen.NUI/src/public/PinchGesture.cs
  src/Tizen.NUI/src/public/RotationGesture.cs
  src/Tizen.NUI/src/public/TapGesture.cs
  src/Tizen.NUI/src/public/Wheel.cs
Labels: ACR Required, API8, ready to merge

#2022 [ElmSharp] Fix elm_transit_paused_get to return boolean correctly
  src/ElmSharp/Interop/Interop.Elementary.cs
Labels: API8

#2014 [ElmSharp] Fix Transit.Go to start transition immediately
  src/ElmSharp/ElmSharp/Transit.cs
Labels: API8

#2023 [Docs] Remove unnecessary docs directory
  docs/.gitignore
  docs/api/index.md
  docs/docfx.json
  docs/filterConfig.yml
  docs/images/Feedback.gif
  docs/images/tizen_favicon.ico
  docs/images/tizen_logo.png
  docs/index.md
  docs/templates/material/LICENSE
  docs/templates/material/partials/head.tmpl.partial
  docs/templates/material/styles/main.css
  docs/templates/tizen/favicon.ico
  docs/templates/tizen/partials/affix.tmpl.partial
  docs/templates/tizen/partials/class.header.tmpl.partial
  docs/templates/tizen/partials/class.tmpl.partial
  docs/templates/tizen/partials/footer.tmpl.partial
  docs/templates/tizen/partials/head.tmpl.partial
  docs/templates/tizen/partials/logo.tmpl.partial
  docs/templates/tizen/plugins/Tizen.DocFX.Plugins.MetadataProvider.dll
  docs/templates/tizen/styles/tizen.css
  docs/templates/tizen/token.json
  docs/toc.yml
  internals/docs/guides/inspections.md
  internals/docs/index.md
Labels: API8

#2024 [Docs] Add toc files for internal modules
  internals/docs/guides/toc.md
  internals/docs/toc.md
Labels: API8

#2021 [Bluetooth][Non-ACR] Add the exception handling logic
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAudioImpl.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAvrcpControlImpl.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAvrcpImpl.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothDevice.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothHidDeviceImpl.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothHidImpl.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothOppImpl.cs
Labels: API8

#2027 [NUI] Add experimental API to Pagination
  src/Tizen.NUI.Components/Controls/Pagination.cs
Labels: API8, Internal API Changed

#2025 [NUI]Add static constructor to confirm the static dictionary will be …
  src/Tizen.NUI/src/public/XamlBinding/BindableProperty.cs
Labels: API8, ready to merge

#2029 [NUI] Make Scrollable finish when Gesture.StateType is Cancelled
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API8, ready to merge

#2028 [Bluetooth][Non-ACR] Add the exception handling logic
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAudioImpl.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAvrcpImpl.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothDevice.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothHidDeviceImpl.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothHidImpl.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothOppImpl.cs
Labels: API7

#2032 [NUI] Switch do not animate on selection when it is not on Window
  src/Tizen.NUI.Components/Controls/Extension/SlidingSwitchExtension.cs
Labels: API8, ready to merge

#2006 [NUI] Add Transition Animation Effects
  src/Tizen.NUI/src/internal/FrameBroker/DefaultFrameBroker.cs
  src/Tizen.NUI/src/internal/FrameBroker/FrameBrokerBase.cs
  src/Tizen.NUI/src/internal/FrameBroker/FrameBrokerBaseErrorFactory.cs
  src/Tizen.NUI/src/internal/FrameBroker/FrameBrokerBaseResult.cs
  src/Tizen.NUI/src/internal/FrameBroker/FrameData.cs
  src/Tizen.NUI/src/internal/FrameBroker/FrameError.cs
  src/Tizen.NUI/src/internal/FrameBroker/SafeFrameBrokerHandle.cs
  src/Tizen.NUI/src/internal/FrameProvider/FrameProvider.cs
  src/Tizen.NUI/src/internal/FrameProvider/FrameProviderErrorFactory.cs
  src/Tizen.NUI/src/internal/FrameProvider/SafeFrameProviderHandle.cs
  src/Tizen.NUI/src/internal/Interop/Interop.FrameBroker.cs
  src/Tizen.NUI/src/internal/Interop/Interop.FrameProvider.cs
  src/Tizen.NUI/src/internal/Interop/Interop.Libraries.cs
  src/Tizen.NUI/src/public/NUIApplication.cs
  src/Tizen.NUI/src/public/TransitionAnimations/TransitionAnimations.cs
  src/Tizen.NUI/src/public/TransitionOptions/TransitionOptions.cs
  test/Tizen.NUI.Seamless/NUISimpleCallee/NUISimpleCallee.cs
  test/Tizen.NUI.Seamless/NUISimpleCallee/NUISimpleCallee.csproj
  test/Tizen.NUI.Seamless/NUISimpleCallee/shared/res/NUISimpleCallee.png
  test/Tizen.NUI.Seamless/NUISimpleCallee/tizen-manifest.xml
  test/Tizen.NUI.Seamless/NUISimpleCaller/NUISimpleCaller.cs
  test/Tizen.NUI.Seamless/NUISimpleCaller/NUISimpleCaller.csproj
  test/Tizen.NUI.Seamless/NUISimpleCaller/shared/res/NUISimpleCaller.png
  test/Tizen.NUI.Seamless/NUISimpleCaller/tizen-manifest.xml
Labels: API8, Internal API Changed

#2035 [Internal] Change API ref for Inspections
  internals/src/Tizen.Inspections/Tizen.Inspections/EventReceivedEventArgs.cs
Labels: API8

#2036 [SystemSettings] Add lock for EventHandler
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs
Labels: API8, Bug

#2041 [Build] Fix build errors in github actions
  .github/workflows/build-branches.yml
  .github/workflows/build-pull-request.yml
Labels: API8

#1950 [NUI] Add Tizen.NUI.Binding into XAML namespace
  src/Tizen.NUI.Design/Tizen.NUI/AttributeTableBuilder.cs
Labels: API8, ready to merge

#1964 [NUI] Fix ObjectDump can't output logs
  src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
Labels: API8, ready to merge

#1977 [NUI] Fix fitting mode issue of ImageView
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
Labels: API8, ready to merge

#2043 [NUI] Update MeasureCallback interface for latest Dali::Toolkit
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Labels: API8, ready to merge

#1997 [NUI] Deprecate Adaptor class
  src/Tizen.NUI/src/public/Adaptor.cs
Labels: ACR Accepted, ACR Required, API8, Internal API Changed, ready to merge

#2000 [NUI] Deprecate the callback of OnTouch
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
Labels: ACR Accepted, ACR Required, API8, ready to merge

#2002 [NUI] Add ControlStateTypeConverter for xaml
  src/Tizen.NUI/src/public/BaseComponents/ControlState.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
Labels: API8, Internal API Changed, ready to merge

#2008 [NUI] add enum validation for Grid,FlexLayout
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
  src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
Labels: API8, ready to merge

#2044 [NUI] Version update : nui-21930
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: API8

#2045 [NUI] correct logical operator in enum validation
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Labels: API8

#2046 [NUI] Modify preload
  src/Tizen.NUI/src/public/NUIApplication.cs
Labels: API8

#2047 Revert "[NUI] Add ControlStateTypeConverter for xaml (#2002)"
  src/Tizen.NUI/src/public/BaseComponents/ControlState.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
Labels: API8, Internal API Changed

#2051 [NUI] Fix ScrollableBase maxScrollDistance issue
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API8

#2037 [Sensor] Change tizen feature of AutoRotationSensor
  src/Tizen.Sensor/Tizen.Sensor/Plugins/AutoRotationSensor.cs
Labels: ACR Required, API8

#2026 [Build] Set TFM supported by Tizen to vconf
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
  packaging/makespec.sh
  packaging/maketfm.py
Labels: API8

#2039 [Build] change nitool to dotnettool
  build.sh
Labels: API8

#2054 [ElmSharp] Fix elm_more_option_open_get to return bool correctly
  src/ElmSharp.Wearable/Interop/Interop.Eext.MoreOption.cs
Labels: API8

#2033 Tizen.Peripheral move all classes to it's namespaces.
  internals/src/Tizen.Peripheral/Tizen.Peripheral/Adc.cs
  internals/src/Tizen.Peripheral/Tizen.Peripheral/Gpio.cs
  internals/src/Tizen.Peripheral/Tizen.Peripheral/I2c.cs
  internals/src/Tizen.Peripheral/Tizen.Peripheral/Pwm.cs
  internals/src/Tizen.Peripheral/Tizen.Peripheral/Spi.cs
  internals/src/Tizen.Peripheral/Tizen.Peripheral/Uart.cs
Labels: API8

#2040 [Internal] Add guide for Inspections
  internals/docs/guides/inspections.md
Labels: API8

#2058 [Build] Fix permission of makespec.sh
  packaging/makespec.sh
Labels: API8

#2059 [Build] Fix wrong relative path in maketfm.py
  packaging/maketfm.py
Labels: API8

#2062 [Build] Suppress build warnings
  internals/src/Tizen.Peripheral/Tizen.Peripheral/Gpio.cs
  src/ElmSharp/ElmSharp.csproj
  src/Tizen.Account.OAuth2/Tizen.Account.OAuth2.csproj
  src/Tizen.NUI.Components/Tizen.NUI.Components.csproj
  src/Tizen.NUI.Wearable/Tizen.NUI.Wearable.csproj
  src/Tizen.NUI/Tizen.NUI.csproj
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
  src/Tizen.NUI/src/public/Position2D.cs
  src/Tizen.NUI/src/public/Size2D.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAvrcpControl.cs
  src/Tizen.Security.DevicePolicyManager/Tizen.Security.DevicePolicyManager.csproj
  src/Tizen.Sensor/Tizen.Sensor/Sensor.cs
Labels: API8
