Repository Samsung/TizenFX, pull requests merged in 2020-10, with the labels that each got.

#2065 [Messaging] Native GC callback fix
  src/Tizen.Messaging/Tizen.Messaging.Messages/MessagesManagerImpl.cs
Labels: API8

#2068 Check if the feature key is supported at AutoRotationSensor.
  src/Tizen.Sensor/Tizen.Sensor/Plugins/AutoRotationSensor.cs
Labels: API8

#2069 [NUI] Add defense code for BaseHandle
  src/Tizen.NUI/src/public/BaseHandle.cs
Labels: API8

#2072 [NUI] Delete unnecessary log
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API8

#2073 [Build] Add workflow files for actions
  .github/workflows/build-branches.yml
  .github/workflows/build-pull-request.yml
  .github/workflows/check-api-level.yml
Labels: API6

#2074 [NUI] Version update : nui-21932
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: API8

#2077 [NUI] Remove duplicate code
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Labels: API8

#2053 [Internal] Add Docs for Peripheral.
  internals/docs/guides/media/peri_api_cert_author.png
  internals/docs/guides/media/peri_api_cert_author_details.png
  internals/docs/guides/media/peri_api_cert_manager.png
  internals/docs/guides/media/peri_api_cert_new.png
  internals/docs/guides/media/peri_api_cert_platform_privilege.png
  internals/docs/guides/media/peri_api_cert_profile.png
  internals/docs/guides/media/peri_api_devices.png
  internals/docs/guides/media/peri_api_duty_cycle.png
  internals/docs/guides/media/peri_api_duty_cycle_voltage.png
  internals/docs/guides/media/peri_api_gpio.png
  internals/docs/guides/media/peri_api_i2c_diagram.png
  internals/docs/guides/media/peri_api_raspberry4.png
  internals/docs/guides/media/peri_api_spi_diagram.png
  internals/docs/guides/media/peri_api_spi_mode.png
  internals/docs/guides/media/peri_api_uart_data.png
  internals/docs/guides/media/peri_api_uart_diagram.png
  internals/docs/guides/peripheral-gpio.md
  internals/docs/guides/peripheral-i2c.md
  internals/docs/guides/peripheral-pwm.md
  internals/docs/guides/peripheral-spi.md
  internals/docs/guides/peripheral-uart.md
  internals/docs/guides/peripheral.md
  internals/docs/guides/toc.md
Labels: API8

#2081 [NUI] Delete unnecessary log in BaseHandle
  src/Tizen.NUI/src/public/BaseHandle.cs
Labels: API8

#2084 [System] Add comments in DisplayState and PowerLock
  src/Tizen.System/Device/Display.cs
  src/Tizen.System/Device/Power.cs
Labels: API7

#2085 [System] Add comments in DisplayState and PowerLock
  src/Tizen.System/Device/Display.cs
  src/Tizen.System/Device/Power.cs
Labels: API8

#2049 [NUI] Change the values of some enumeration types of InputMethod
  src/Tizen.NUI/src/public/InputMethod.cs
Labels: ACR Required, API8

#2075 [NUI] Modify Seamless sample code
  test/Tizen.NUI.Seamless/NUISimpleCallee/NUISimpleCallee.cs
  test/Tizen.NUI.Seamless/NUISimpleCaller/NUISimpleCaller.cs
Labels: API8

#2076 [NUI] Add RemoveAllChildren() in ScrollableBase
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RemoveAllChildrenTest.cs
Labels: API8, Internal API Changed

#2086 [NUI] Add class SelectedChangedEventArgs to public
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/SelectButton.cs
Labels: ACR Required, API8, Internal API Changed

#2088 [System][Non-ACR] Change comments in DisplayState and PowerLock
  src/Tizen.System/Device/Display.cs
  src/Tizen.System/Device/Power.cs
Labels: API7

#2087 [System][Non-ACR] Change comments in DisplayState and PowerLock
  src/Tizen.System/Device/Display.cs
  src/Tizen.System/Device/Power.cs
Labels: API8

#2080 [Sensor] Remove document warning.
  src/Tizen.Sensor/Tizen.Sensor/BatchSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/HeartRateMonitorBatch.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/HeartRateMonitorLEDGreenBatch.cs
Labels: ACR Required, API8

#2082 [NUI] Deprecate set properties of Color, Rectangle, and etc
  src/Tizen.NUI/src/public/Color.cs
  src/Tizen.NUI/src/public/Extents.cs
  src/Tizen.NUI/src/public/Position.cs
  src/Tizen.NUI/src/public/Position2D.cs
  src/Tizen.NUI/src/public/Rectangle.cs
  src/Tizen.NUI/src/public/RelativeVector2.cs
  src/Tizen.NUI/src/public/RelativeVector3.cs
  src/Tizen.NUI/src/public/RelativeVector4.cs
  src/Tizen.NUI/src/public/Size.cs
  src/Tizen.NUI/src/public/Size2D.cs
  src/Tizen.NUI/src/public/Vector2.cs
  src/Tizen.NUI/src/public/Vector3.cs
  src/Tizen.NUI/src/public/Vector4.cs
Labels: ACR Accepted, API8

#2048 [NUI] Handle XF86Back in BackKeyManager
  src/Tizen.NUI/src/internal/BackKeyManager.cs
Labels: API8

#2092 [Peripheral] Update toc needed by namespace change.
  internals/docs/toc.md
Labels: API8

#2094 [Bluetooth][Non-ACR] Fix TrackInfoChanged not invoked issue
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAvrcpControlImpl.cs
Labels: API8

#2095 [ElmSharp] Added vd theme file path in ThemeOverlay for product tv
  src/ElmSharp/ElmSharp/Elementary.cs
Labels: API8

#2096 [Bluetooth][Non-ACR] Fix Track data converting logic
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAvrcpControlImpl.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothEventArgs.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
Labels: API8

#2097 [NUI] Add Component Application sample
  test/Tizen.NUI.ComponentApplication/NUIComponentApplication/NUIComponentApplication.cs
  test/Tizen.NUI.ComponentApplication/NUIComponentApplication/NUIComponentApplication.csproj
  test/Tizen.NUI.ComponentApplication/NUIComponentApplication/shared/res/NUIComponentApplication.png
  test/Tizen.NUI.ComponentApplication/NUIComponentApplication/tizen-manifest.xml
Labels: API8

#1932 [NUI] Modify to pass userData object to GestureDetectorManager
  src/Tizen.NUI/src/public/Events/GestureDetectorManager.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TouchGestureSample.cs
Labels: API8, Internal API Changed

#2050 [NUI] Add null pointer check for Scrollbar
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API8

#2099 [NUI] Fix Registry's memory leak
  src/Tizen.NUI/src/internal/Registry.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/BaseHandle.cs
  test/Tizen.NUI.Tests/Tizen.NUI.TCT/Tizen.NUI.Components.Tests.sln
  test/Tizen.NUI.Tests/Tizen.NUI.TCT/testcase/ViewMemoryLeakTest.cs
Labels: API8

#2098 [NUI] Add InterceptTouchEvent
  src/Tizen.NUI/src/internal/InterceptTouchSignal.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ActorSignal.cs
  src/Tizen.NUI/src/internal/Interop/Interop.TouchSignal.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Labels: API8, Internal API Changed

#2102 [NUI] Modify seamless bug & update sample
  src/Tizen.NUI/src/internal/FrameBroker/DefaultFrameBroker.cs
  src/Tizen.NUI/src/public/TransitionAnimations/TransitionAnimations.cs
  src/Tizen.NUI/src/public/TransitionOptions/TransitionOptions.cs
  test/Tizen.NUI.Seamless/NUISimpleCallee/NUISimpleCallee.cs
  test/Tizen.NUI.Seamless/NUISimpleCaller/NUISimpleCaller.cs
Labels: API8

#2107 [Camera] Remove feature check
  src/Tizen.Multimedia.Camera/Camera/Camera.cs
Labels: API8

#2106 [NUI] Add FrameComponent dll sample
  test/Tizen.NUI.ComponentApplication/FrameComponentDll/FrameComponentDll.cs
  test/Tizen.NUI.ComponentApplication/FrameComponentDll/FrameComponentDll.csproj
  test/Tizen.NUI.ComponentApplication/FrameComponentDll/shared/res/FrameComponentDll.png
  test/Tizen.NUI.ComponentApplication/NUIComponentApplication/NUIComponentApplication.cs
Labels: API8

#2103 [NUI] Add Seamless MusicPlayer sample
  test/Tizen.NUI.Seamless/NUIBrokerSample/NUIBrokerSample.cs
  test/Tizen.NUI.Seamless/NUIBrokerSample/NUIBrokerSample.csproj
  test/Tizen.NUI.Seamless/NUIBrokerSample/TransitionEffect/SeamlessAnimator.cs
  test/Tizen.NUI.Seamless/NUIBrokerSample/UICreator.cs
  test/Tizen.NUI.Seamless/NUIBrokerSample/res/NUIBrokerSample.png
  test/Tizen.NUI.Seamless/NUIBrokerSample/res/images/add.png
  test/Tizen.NUI.Seamless/NUIBrokerSample/res/images/arrow-89-128.png
  test/Tizen.NUI.Seamless/NUIBrokerSample/res/images/bar-chart-5-128.png
  test/Tizen.NUI.Seamless/NUIBrokerSample/res/images/clock-128.png
  test/Tizen.NUI.Seamless/NUIBrokerSample/res/images/familyboard_setting_bg1.png
  test/Tizen.NUI.Seamless/NUIBrokerSample/res/images/familyboard_setting_bg2.png
  test/Tizen.NUI.Seamless/NUIBrokerSample/res/images/familyboard_setting_bg3.png
  test/Tizen.NUI.Seamless/NUIBrokerSample/res/images/iu_1.jpg
  test/Tizen.NUI.Seamless/NUIBrokerSample/res/images/pic_1.jpg
  test/Tizen.NUI.Seamless/NUIBrokerSample/res/images/play-128.png
  test/Tizen.NUI.Seamless/NUIBrokerSample/res/images/profile.jpg
  test/Tizen.NUI.Seamless/NUIBrokerSample/res/images/video-play-64.png
  test/Tizen.NUI.Seamless/NUIBrokerSample/shared/res/NUIBrokerSample.png
  test/Tizen.NUI.Seamless/NUIBrokerSample/tizen-manifest.xml
  test/Tizen.NUI.Seamless/NUIMusicPlayer/NUIMusicPlayer.cs
  test/Tizen.NUI.Seamless/NUIMusicPlayer/NUIMusicPlayer.csproj
  test/Tizen.NUI.Seamless/NUIMusicPlayer/UICreator.cs
  test/Tizen.NUI.Seamless/NUIMusicPlayer/res/images/add.png
  test/Tizen.NUI.Seamless/NUIMusicPlayer/res/images/arrow-89-128.png
  test/Tizen.NUI.Seamless/NUIMusicPlayer/res/images/bar-chart-5-128.png
  test/Tizen.NUI.Seamless/NUIMusicPlayer/res/images/clock-128.png
  test/Tizen.NUI.Seamless/NUIMusicPlayer/res/images/iu_1.jpg
  test/Tizen.NUI.Seamless/NUIMusicPlayer/res/images/pic_1.jpg
  test/Tizen.NUI.Seamless/NUIMusicPlayer/res/images/play-128.png
  test/Tizen.NUI.Seamless/NUIMusicPlayer/res/images/profile.jpg
  test/Tizen.NUI.Seamless/NUIMusicPlayer/res/images/video-play-64.png
  test/Tizen.NUI.Seamless/NUIMusicPlayer/shared/res/NUIMusicPlayer.png
  test/Tizen.NUI.Seamless/NUIMusicPlayer/tizen-manifest.xml
Labels: API8

#2111 [NUI] Bug fixed about TextPageUtil
  src/Tizen.NUI/src/public/Utility/TextPageUtil.cs
Labels: API8

#2113 [NUI] Add frameBroker default setting value
  src/Tizen.NUI/src/internal/FrameBroker/DefaultFrameBroker.cs
  src/Tizen.NUI/src/public/TransitionAnimations/TransitionAnimations.cs
  test/Tizen.NUI.Seamless/NUIBrokerSample/NUIBrokerSample.cs
  test/Tizen.NUI.Seamless/NUIBrokerSample/TransitionEffect/SeamlessAnimator.cs
  test/Tizen.NUI.Seamless/NUIBrokerSample/TransitionEffect/SeamlessBackwardAnimation.cs
  test/Tizen.NUI.Seamless/NUIBrokerSample/TransitionEffect/SeamlessForwardAnimation.cs
  test/Tizen.NUI.Seamless/NUIBrokerSample/UICreator.cs
  test/Tizen.NUI.Seamless/NUIMusicPlayer/UICreator.cs
Labels: API8, Internal API Changed

#2114 [NUI] Fix Size2D to work correctly in Loading
  src/Tizen.NUI.Components/Controls/Loading.cs
  src/Tizen.NUI.Components/Style/LoadingStyle.cs
Labels: API8

#2124 [Build] Fix typo in Tizen.NET.API7.nuspec
  pkg/Tizen.NET.API7/Tizen.NET.API7.nuspec
Labels: API7

#2121 [Tizen.Network.Connection] Make callbacks to member variable (#1608)
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
Labels: API7

#2127 [NUI] Fix typo in comments
  src/Tizen.NUI.Components/Controls/Slider.cs
Labels: API8

#2135 [Build] Add DevelNUI branch to workflows
  .github/branch-metadata.yml
  .github/workflows/build-branches.yml
  .github/workflows/build-pull-request.yml
Labels: API8

#2136 [NUI] Fix build warning: CS0105
  src/Tizen.NUI/src/internal/ViewImpl.cs
  src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
  src/Tizen.NUI/src/public/Capture.cs
Labels: Devel-NUI

#2137 [NUI] Fix build warning CS1573
  src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
Labels: Devel-NUI, Internal API Changed

#2130 [NUI] Fix Dispose warning error[CA1001]
  src/Tizen.NUI/src/internal/Disposable.cs
  src/Tizen.NUI/src/internal/DisposeQueue.cs
  src/Tizen.NUI/src/internal/FrameBroker/FrameData.cs
  src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/KeyValue.cs
  src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
  src/Tizen.NUI/src/public/Layouting/LayoutTransition.cs
  src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
  src/Tizen.NUI/src/public/ViewProperty/BackgroundExtraData.cs
  src/Tizen.NUI/src/public/ViewProperty/TextShadow.cs
  src/Tizen.NUI/src/public/VisualMaps.cs
Labels: ACR Required, API8, Internal API Changed

#2083 [NUI] remove unused parameter docs tag
  src/Tizen.NUI.Components/Controls/Button.Internal.cs
  src/Tizen.NUI.Wearable/src/public/WearableList.cs
Labels: API8

#2089 [NUI] remove unused exception parameters
  src/Tizen.NUI.WindowSystem/src/public/QuickPanelClient.cs
  src/Tizen.NUI.WindowSystem/src/public/QuickPanelService.cs
  src/Tizen.NUI.WindowSystem/src/public/TizenRegion.cs
  src/Tizen.NUI.WindowSystem/src/public/TizenShell.cs
Labels: API8

#2079 [NUI] add null checking for equality operator of ControlState
  src/Tizen.NUI/src/public/BaseComponents/ControlState.cs
Labels: API8

#2052 [NUI] add exception docs of layout classes
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Labels: API8

#2141 Revert "[NUI] Fix Dispose warning error[CA1001] (#2130)"
  src/Tizen.NUI/src/internal/Disposable.cs
  src/Tizen.NUI/src/internal/DisposeQueue.cs
  src/Tizen.NUI/src/internal/FrameBroker/FrameData.cs
  src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/KeyValue.cs
  src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
  src/Tizen.NUI/src/public/Layouting/LayoutTransition.cs
  src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
  src/Tizen.NUI/src/public/ViewProperty/BackgroundExtraData.cs
  src/Tizen.NUI/src/public/ViewProperty/TextShadow.cs
  src/Tizen.NUI/src/public/VisualMaps.cs
Labels: ACR Required, API8, Internal API Changed

#2109 [NUI] Add DisallowInterceptTouchEvent
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
Labels: API8, Internal API Changed

#2066 [NUI] TextField/TextEditor: Add SelectedTextStart, SelectedTextEnd pr…
  src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
  src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
Labels: API8, Internal API Changed

#2139 [NUI] Fix build warning CA1507
  src/Tizen.NUI/src/internal/ItemContainer.cs
  src/Tizen.NUI/src/internal/ItemIdContainer.cs
  src/Tizen.NUI/src/internal/TouchPointContainer.cs
  src/Tizen.NUI/src/internal/XamlBinding/DataTemplate.cs
  src/Tizen.NUI/src/internal/XamlBinding/ElementTemplate.cs
  src/Tizen.NUI/src/internal/XamlBinding/EnumerableExtensions.cs
  src/Tizen.NUI/src/internal/XamlBinding/Interactivity/AttachedCollection.cs
  src/Tizen.NUI/src/internal/XamlBinding/MergedStyle.cs
  src/Tizen.NUI/src/internal/XamlBinding/TemplateBinding.cs
  src/Tizen.NUI/src/internal/XamlBinding/TypeTypeConverter.cs
  src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
  src/Tizen.NUI/src/public/BaseComponents/FlexContainer.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/Scrollable.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/TableView.cs
  src/Tizen.NUI/src/public/BaseComponents/VideoView.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/NUIComponentApplication.cs
  src/Tizen.NUI/src/public/UIComponents/Button.cs
  src/Tizen.NUI/src/public/UIComponents/PopupBindableProperty.cs
  src/Tizen.NUI/src/public/UIComponents/ProgressBar.cs
  src/Tizen.NUI/src/public/UIComponents/PushButton.cs
  src/Tizen.NUI/src/public/UIComponents/ScrollBar.cs
  src/Tizen.NUI/src/public/UIComponents/ScrollViewBindableProperty.cs
  src/Tizen.NUI/src/public/UIComponents/Slider.cs
  src/Tizen.NUI/src/public/UIComponents/ToggleButton.cs
  src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
  src/Tizen.NUI/src/public/XamlBinding/BindableObjectExtensions.cs
  src/Tizen.NUI/src/public/XamlBinding/BindableProperty.cs
  src/Tizen.NUI/src/public/XamlBinding/BindablePropertyKey.cs
  src/Tizen.NUI/src/public/XamlBinding/Binding.cs
  src/Tizen.NUI/src/public/XamlBinding/Element.cs
  src/Tizen.NUI/src/public/XamlBinding/ElementEventArgs.cs
  src/Tizen.NUI/src/public/XamlBinding/Interactivity/Behavior.cs
  src/Tizen.NUI/src/public/XamlBinding/Internals/NameScope.cs
  src/Tizen.NUI/src/public/XamlBinding/Page.cs
  src/Tizen.NUI/src/public/XamlBinding/Setter.cs
  src/Tizen.NUI/src/public/XamlBinding/Style.cs
  src/Tizen.NUI/src/public/XamlBinding/TriggerAction.cs
  src/Tizen.NUI/src/public/XamlBinding/TriggerBase.cs
Labels: Devel-NUI

#2110 [NUI] add ScrollOutOfBound event handler.
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API8, Internal API Changed

#2122 [NUI] avoid duplicated elements in Selector
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
Labels: API8, Internal API Changed

#2126 [NUI] fix ScrollableBase wrong size issue
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI/src/internal/DaliEnumConstants.cs
  src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
  src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
Labels: API8, Internal API Changed

#2142 [NUI] Make Selector.StateValueList public temporarily
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
Labels: API8, Internal API Changed

#2143 [NUI] Handle null inputs in shadow
  src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
  src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
Labels: API8

#2071 [NUI] TextField/TextEditor: Add EnableEditing properties
  src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
  src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
Labels: API8, Internal API Changed

#2149 [NUI] Change type of Selector.StateValueList to IList
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
Labels: API8, Internal API Changed

#2150 Revert "[NUI] fix ScrollableBase wrong size issue (#2126)"
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI/src/internal/DaliEnumConstants.cs
  src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
  src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
Labels: API8, Internal API Changed
