Repository Samsung/TizenFX, pull requests merged in 2020-07, with the labels that each got.

#1479 [Feedback] Change struct array to Dictionary<string, int>
  src/Tizen.System.Feedback/Feedback/Feedback.cs
Labels: API8

#1556 [Application] Separating Language changing logic and Region changing logic
  src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Labels: API8

#1557 [API7][Application] Separating Language changing logic and Region changing logic
  src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Labels: API7

#1747 [NUI] Make Notification APIs public and fix CA warnings.
  src/Tizen.NUI.Components/Controls/Notification.cs
Labels: ACR Accepted, API8

#1755 [MediaVision] Support new inference backend engine - MLApi, One
  src/Tizen.Multimedia.Vision/MediaVision/InferenceModelConfiguration.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceType.cs
Labels: ACR Accepted, API8

#1772 [NUI] Fix lottie animation bug
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
Labels: API8

#1773 [NUI] Fix Button state issue
  src/Tizen.NUI.Components/Controls/Button.Internal.cs
Labels: API8

#1621 [MediaController] Fix metadata bug
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlMetadata.cs
Labels: API8

#1768 Revert "[NUI] Move to dali2 (#1745)"
  packaging/csapi-tizenfx.spec
  packaging/version.txt
  src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
  src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
  src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
Labels: API8, Internal API Changed

#1769 [NUI] Hide classes that will be move to specific tizen profile
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Controls/Toast.cs
  src/Tizen.NUI.Components/Style/PopupStyle.cs
  src/Tizen.NUI.Components/Style/TabStyle.cs
  src/Tizen.NUI.Components/Style/ToastStyle.cs
Labels: ACR Required, API8

#1561 [Security] Return error when the given privilege not exist
  src/Tizen.Security/Interop/Interop.Privilege.cs
  src/Tizen.Security/Tizen.Security/Privilege.cs
Labels: ACR Accepted, API8

#1770 [NUI] Fix orientaion of GridRecycleLayoutManager
  src/Tizen.NUI.Components/Controls/RecyclerView/GridRecycleLayoutManager.cs
Labels: API8

#1780 [NUI] Restore setter of LayoutManager property to public
  src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
Labels: API8

#1683 [Device][PerformanceController] Add PerformanceController API
  src/Tizen.System/Device/PerformanceControlType.cs
  src/Tizen.System/Device/PerformanceController.cs
  src/Tizen.System/Interop/Interop.Device.cs
Labels: API8, Internal API Changed

#1784 [NUI] Support implicit value in Xaml
  src/Tizen.NUI/src/internal/Xaml/ApplyPropertiesVisitor.cs
  src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
Labels: API8

#1787 [NUI] Move to dali2
  packaging/csapi-tizenfx.spec
  packaging/version.txt
  src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
  src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
  src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
Labels: API8, Internal API Changed

#1790 [NUI] Add PageFlickThreshold and ScrollAlphaFunction
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API8, Internal API Changed

#1764 [NUI] Remove unused Internal Image classes & related methods
  src/Tizen.NUI/src/internal/BufferImage.cs
  src/Tizen.NUI/src/internal/EncodedBufferImage.cs
  src/Tizen.NUI/src/internal/FrameBufferImage.cs
  src/Tizen.NUI/src/internal/GaussianBlurView.cs
  src/Tizen.NUI/src/internal/Image.cs
  src/Tizen.NUI/src/internal/ImageSignal.cs
  src/Tizen.NUI/src/internal/Interop/Interop.BufferImage.cs
  src/Tizen.NUI/src/internal/Interop/Interop.FrameBufferImage.cs
  src/Tizen.NUI/src/internal/Interop/Interop.GaussianBlurView.cs
  src/Tizen.NUI/src/internal/Interop/Interop.Image.cs
  src/Tizen.NUI/src/internal/Interop/Interop.NativeImageInterface.cs
  src/Tizen.NUI/src/internal/Interop/Interop.NinePatchImage.cs
  src/Tizen.NUI/src/internal/Interop/Interop.RenderTask.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ResourceImage.cs
  src/Tizen.NUI/src/internal/Interop/Interop.VisualFactory.cs
  src/Tizen.NUI/src/internal/NativeImage.cs
  src/Tizen.NUI/src/internal/RenderTask.cs
  src/Tizen.NUI/src/public/VisualFactory.cs
Labels: API8

#1762 [NUI] add ControlState class to support combined and custom state
  src/Tizen.NUI.Components/Controls/Button.Internal.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.DropDownItemView.cs
  src/Tizen.NUI.Components/Controls/Extension/LottieButtonExtension.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/PreloadStyle/OverlayAnimationButtonStyle.cs
  src/Tizen.NUI.Wearable/src/public/CircularProgress.cs
  src/Tizen.NUI/src/public/BaseComponents/ControlState.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/Constants.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/StateValueCollection.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
Labels: API8, Internal API Changed

#1775 [Bluetooth][TCSACR-323] Fix AvrcpControl methods document
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothAvrcpControl.cs
Labels: ACR Required, API8, Internal API Changed

#1774 [MediaTool] Add new audio/video mimetype
  src/Tizen.Multimedia/MediaTool/MediaFormatAudioMimeType.cs
  src/Tizen.Multimedia/MediaTool/MediaFormatVideoMimeType.cs
Labels: ACR Required, API8

#1779 [MediaVision] Update descriptions
  src/Tizen.Multimedia.Vision/MediaVision/InferenceModelConfiguration.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceType.cs
Labels: API8

#1795 [NUI] Fix ControlState equality issue.
  src/Tizen.NUI/src/public/BaseComponents/ControlState.cs
Labels: API8

#1794 [NUI] Fix VisualMap.OutputVisualMap
  src/Tizen.NUI/src/public/VisualMaps.cs
Labels: API8

#1796 [NUI] Change wrong comment of PositionUsesPivotPoint
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API8

#1797 [NUI] Fix Loading size property not work
  src/Tizen.NUI.Components/Controls/Loading.cs
Labels: API8

#1798 [NUI] Fix Switch selection bug.
  src/Tizen.NUI.Components/Controls/Button.Internal.cs
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/Extension/SlidingSwitchExtension.cs
  src/Tizen.NUI.Components/Controls/Extension/SwitchExtension.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
Labels: API8, Internal API Changed

#1802 [NUI] add exception code for NUIWidgetApplication
  src/Tizen.NUI/src/public/NUIWidgetApplication.cs
Labels: API8

#1800 [Build] Add tizen-arm64, tizen.6.0.0-arm64 RIDs to runtime.json
  pkg/Tizen.NET/runtime.json
Labels: API8

#1789 [NUI] Add ReleasePolicy for ImageView
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
Labels: API8, Internal API Changed

#1804 Revert "[NUI] Fix VisualMap.OutputVisualMap (#1794)"
  src/Tizen.NUI/src/public/VisualMaps.cs
Labels: API8

#1801 [NUI] Fix the issue that theme could not be changed
  src/Tizen.NUI.Components/Utils/StyleManager.cs
Labels: API8

#1778 [MetadataEditor] Supports new file formats - WAV, FLAC and OGG
  src/Tizen.Multimedia.Metadata/MetadataEditor/MetadataEditor.cs
Labels: ACR Accepted, API8

#1793 [AudioIO] Add new volume property to set/get recording volume
  src/Tizen.Multimedia.AudioIO/AudioIO/AudioCapture.cs
  src/Tizen.Multimedia.AudioIO/Interop/Interop.AudioIO.cs
Labels: ACR Accepted, API8

#1776 [MetadataEditor] Update exception description
  src/Tizen.Multimedia.Metadata/MetadataEditor/MetadataEditor.cs
  src/Tizen.Multimedia.Metadata/MetadataEditor/MetadataEditorError.cs
Labels: API8

#1799 [NUI] Fix Position type converter error when Position get 2 parameters in XAML
  src/Tizen.NUI/src/internal/XamlBinding/PositionTypeConverter.cs
  src/Tizen.NUI/src/public/XamlBinding/SizeTypeConverter.cs
Labels: API6

#1781 [MediaPlayer] add missing error code
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerError.cs
Labels: ACR Required, API8

#1782 [MediaController] Add the result code for Response and playback state enum
  src/Tizen.Multimedia.Remoting/MediaController/InternalEnums.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlEnums.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
Labels: ACR Required, API8

#1806 [NUI] Fix Size issue of Loading
  src/Tizen.NUI.Components/Controls/Loading.cs
Labels: API8

#1814 [NUI] Fix GridLayout logic
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Labels: API8

#1777 [NUI] Make Pagination class public and fix CA warnings
  src/Tizen.NUI.Components/Controls/Pagination.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultTheme.cs
  src/Tizen.NUI.Components/PreloadStyle/WearableTheme.cs
  src/Tizen.NUI.Components/Style/PaginationStyle.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PaginationSample.cs
Labels: ACR Required, API8, Internal API Changed

#1791 [NUI] Remove non-touch related deprecated APIs
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ActorSignal.cs
  src/Tizen.NUI/src/internal/Interop/Interop.Application.cs
  src/Tizen.NUI/src/internal/Interop/Interop.NDalic.cs
  src/Tizen.NUI/src/internal/Interop/Interop.PushButton.cs
  src/Tizen.NUI/src/internal/Interop/Interop.TextEditor.cs
  src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
  src/Tizen.NUI/src/internal/Interop/Interop.TextLabel.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ViewImplSignal.cs
  src/Tizen.NUI/src/internal/Interop/Interop.WindowFocusSignalType.cs
  src/Tizen.NUI/src/internal/Interop/Interop.WindowInternal.cs
  src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs
  src/Tizen.NUI/src/internal/ViewImpl.cs
  src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
  src/Tizen.NUI/src/internal/WindowFocusSignalType.cs
  src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/UIComponents/PushButton.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API8

#1815 [NUI] Skip adding cell padding to last LinearLayout item
  src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
Labels: API8

#1813 [VoiceControlManager] Add VoiceControlManager dll into platform binary
  packaging/PlatformFileList.txt
Labels: API8

#1715 [NUI] Add WindowSystem's quickpanel APIs
  packaging/PlatformFileList.txt
  src/Tizen.NUI.WindowSystem/Tizen.NUI.WindowSystem.csproj
  src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.QuickPanelClient.cs
  src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.QuickPanelService.cs
  src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.TizenRegion.cs
  src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.TizenShell.cs
  src/Tizen.NUI.WindowSystem/src/public/QuickPanelClient.cs
  src/Tizen.NUI.WindowSystem/src/public/QuickPanelService.cs
  src/Tizen.NUI.WindowSystem/src/public/TizenRegion.cs
  src/Tizen.NUI.WindowSystem/src/public/TizenShell.cs
  src/Tizen.NUI/Properties/AssemblyInfo.cs
  test/Tizen.NUI.WindowSystem.Samples/Tizen.NUI.WindowSystem.Samples.cs
  test/Tizen.NUI.WindowSystem.Samples/Tizen.NUI.WindowSystem.Samples.csproj
  test/Tizen.NUI.WindowSystem.Samples/Tizen.NUI.WindowSystem.Samples.sln
  test/Tizen.NUI.WindowSystem.Samples/shared/res/Tizen.NUI.WindowSystem.Samples.png
  test/Tizen.NUI.WindowSystem.Samples/tizen-manifest.xml
Labels: ACR Accepted, API8, Internal API Changed

#1783 [NUI] Open ScrollableBase APIs
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: ACR Accepted, API8, Internal API Changed

#1820 [Build] Fix rid generation error
  packaging/makerid.py
Labels: API8

#1821 [NUI] Sync ViewWrapper director arguments to dali-csharp-binder
  src/Tizen.NUI/src/internal/Interop/Interop.ViewWrapperImpl.cs
  src/Tizen.NUI/src/internal/ViewWrapperImpl.cs
Labels: API8

#1812 [MediaCodec] Add new codec type - Opus
  src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodec.cs
  src/Tizen.Multimedia.MediaCodec/MediaCodec/SupportedCodecType.cs
Labels: API8

#1729 [NUI] TextField rename TextField_SelectNone to be SelectNone
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
Labels: API8, Internal API Changed

#1822 [NUI] Fix ScrollableBase when velocity is 0
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API8

#1807 [NUI] Fix some typos.
  src/Tizen.NUI.Components/Controls/Button.Internal.cs
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleViewLayoutManager.cs
  src/Tizen.NUI.Components/Controls/ImageScrollBar.cs
  src/Tizen.NUI.Components/Utils/StyleManager.cs
Labels: API8

#1786 [Applications] Add app manager attach/detach window API for internal
  src/Tizen.Applications.Common/Interop/Interop.ApplicationManager.cs
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs
Labels: API8, Internal API Changed

#1805 [NUI] Remove AssemblyInfo of NUI.Components.DA.
  src/Tizen.NUI/Properties/AssemblyInfo.cs
Labels: API8

#1819 [NUI] Add TextPageUtil
  src/Tizen.NUI/src/internal/Interop/Interop.TextUtils.cs
  src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TextPageSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TextPageUtil.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/pl_PL.txt
Labels: API8, Internal API Changed

#1824 [NUI] BackKeyEvent Proptotype
  src/Tizen.NUI/src/internal/BackKeyManager.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
Labels: API8, Internal API Changed

#1816 [NUI] Support the different file name of Xaml
  src/Tizen.NUI/src/internal/Xaml/XamlLoader.cs
  src/Tizen.NUI/src/internal/XamlBinding/ResourcesExtensions.cs
  src/Tizen.NUI/src/public/XamlBinding/ContentPage.cs
Labels: API8

#1752 [NUI] Add Capture
  src/Tizen.NUI/src/internal/Disposable.cs
  src/Tizen.NUI/src/internal/Interop/Interop.Capture.cs
  src/Tizen.NUI/src/public/BaseHandle.cs
  src/Tizen.NUI/src/public/Capture.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CaptureTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DimTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Tizen.NUI.Samples.csproj
Labels: API8, Internal API Changed

#1826 [NUI] make xxxStretchProperty default value as StretchFlags.None
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Labels: API8

#1825 [NUI] respect GridLayout child margin
  src/Tizen.NUI/src/internal/Layouting/GridLocations.cs
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Labels: API8

#1828 [NUI] make GridLayout.Orientation default value as Horizontal
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Labels: API8

#1811 [NUI] Add FrameRenderedCallback, FramePresentedCallback as hidden API
  src/Tizen.NUI/src/internal/Interop/Interop.WindowInternal.cs
  src/Tizen.NUI/src/public/Window.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AddFrameRenderedCallbackTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Tizen.NUI.Samples.csproj
Labels: API8, Internal API Changed

#1831 [NUI] use correct max column/row count in validation of child column/row
  src/Tizen.NUI/src/internal/Layouting/GridLocations.cs
Labels: API8

#1833 [NUI] fix wrong total expand value in expanded size calculation
  src/Tizen.NUI/src/internal/Layouting/GridLocations.cs
Labels: API8

#1788 [NUI] Remove bindings between Style and View
  src/Tizen.NUI.Components/Controls/Button.Internal.cs
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/ButtonGroup.cs
  src/Tizen.NUI.Components/Controls/CheckBox.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/Extension/LottieButtonExtension.cs
  src/Tizen.NUI.Components/Controls/Extension/SwitchExtension.cs
  src/Tizen.NUI.Components/Controls/Loading.cs
  src/Tizen.NUI.Components/Controls/Pagination.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/RadioButton.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/SelectButton.cs
  src/Tizen.NUI.Components/Controls/Slider.Internal.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Controls/Toast.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultTheme.cs
  src/Tizen.NUI.Components/Style/ButtonStyle.cs
  src/Tizen.NUI.Components/Style/ControlStyle.cs
  src/Tizen.NUI.Components/Style/PaginationStyle.cs
  src/Tizen.NUI.Components/Style/PopupStyle.cs
  src/Tizen.NUI.Components/Style/SwitchStyle.cs
  src/Tizen.NUI.Components/Style/TabStyle.cs
  src/Tizen.NUI.Components/Utils/Selector.cs
  src/Tizen.NUI.Wearable/src/public/CircularProgress.cs
  src/Tizen.NUI.Wearable/src/public/CircularScrollbar.cs
  src/Tizen.NUI.Wearable/src/public/CircularSlider.cs
  src/Tizen.NUI.Wearable/src/public/Popup.cs
  src/Tizen.NUI.Wearable/src/public/Title.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/StateValueCollection.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/TextFieldSelectorData.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabelSelectorData.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewSelectorData.cs
  src/Tizen.NUI/src/public/Color.cs
  src/Tizen.NUI/src/public/Vector2.cs
  src/Tizen.NUI/src/public/ViewProperty/ICloneable.cs
  src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
  src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
  src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
  src/Tizen.NUI/src/public/ViewProperty/TextShadow.cs
Labels: API8, Internal API Changed

#1832 [Multimedia] Update solution files
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent.sln
  src/Tizen.Multimedia.AudioIO/Tizen.Multimedia.AudioIO.sln
  src/Tizen.Multimedia.Camera/Tizen.Multimedia.Camera.sln
  src/Tizen.Multimedia.MediaPlayer/Tizen.Multimedia.MediaPlayer.sln
  src/Tizen.Multimedia.Metadata/Tizen.Multimedia.Metadata.sln
  src/Tizen.Multimedia.Radio/Tizen.Multimedia.Radio.sln
  src/Tizen.Multimedia.Recorder/Tizen.Multimedia.Recorder.sln
  src/Tizen.Multimedia.Remoting/Tizen.Multimedia.Remoting.sln
  src/Tizen.Multimedia.StreamRecorder/Tizen.Multimedia.StreamRecorder.sln
  src/Tizen.Multimedia.Util/Tizen.Multimedia.Util.sln
Labels: API8

#1835 [NUI] Sync ViewWrapper swig connection arguments count to dali csharp…
  src/Tizen.NUI/src/internal/Interop/Interop.ViewImpl.cs
  src/Tizen.NUI/src/internal/ViewImpl.cs
Labels: API8

#1837 [NUI] Remove Style from View
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API8, Internal API Changed

#1808 [NUI] Add public types to replace nested types of Components.Slider
  src/Tizen.NUI.Components/Controls/Slider.Internal.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SliderSample.cs
Labels: ACR Required, API8

#1809 [NUI] Add public types to replace nested types of Components.Switch
  src/Tizen.NUI.Components/Controls/Switch.cs
Labels: ACR Required, API8

#1810 [NUI] Add public types to replace nested types of Components.Button
  src/Tizen.NUI.Components/Controls/Button.Internal.cs
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/Extension/ButtonExtension.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AnimatedImageViewTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ButtonSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CubeTransitionEffectSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/GridLayoutSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ItemViewDemo/ItemViewSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LoadingSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PopupSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ProgressSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PropertyNotificationTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ScrollBarSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SiblingOrderTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TabSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ToastSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WearablePopupTest.cs
Labels: ACR Required, API8, Internal API Changed

#1838 [NUI] Add ScrollEnabled to ScrollbarBase
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/ScrollbarBase.cs
  src/Tizen.NUI.Wearable/src/public/CircularScrollbar.cs
Labels: API8, Internal API Changed

#1843 [NUI] Change TextPageUtil to Tizen.NUI.Utility namespace.
  src/Tizen.NUI/src/public/Utility/TextPageUtil.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TextPageSample.cs
Labels: API8, Internal API Changed

#1839 [NUI] Change for AddFrameRenderedCallback to maintain the reference
  src/Tizen.NUI/src/public/Window.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AddFrameRenderedCallbackTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CaptureTest.cs
Labels: API8

#1850 [NUI] Create Layout only for TextLabel
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API8

#1848 [NFC][Non-ACR] Fix NFC Csharp TC failed issue
  src/Tizen.Network.Nfc/Tizen.Network.Nfc/NfcTag.cs
Labels: API7

#1849 [NFC][Non-ACR] Fix NFC Csharp TC failed issue
  src/Tizen.Network.Nfc/Tizen.Network.Nfc/NfcTag.cs
Labels: API8

#1846 [NUI] Scrollbar inherits VisualView instead of Control
  src/Tizen.NUI.Components/Controls/ScrollbarBase.cs
  src/Tizen.NUI.Components/Style/ScrollbarStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/VisualView.cs
Labels: API8, Internal API Changed

#1847 [NUI] Fix wearable style issues
  src/Tizen.NUI.Wearable/src/public/CircularProgress.cs
  src/Tizen.NUI.Wearable/src/public/CircularScrollbar.cs
  src/Tizen.NUI.Wearable/src/public/CircularSlider.cs
Labels: API8

#1853 [NUI] Add exception and null check for Button/Slider/Switch
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
Labels: API8

#1840 [Build] Add the Tizen.NUI.preload file
  packaging/PlatformFileList.txt
  packaging/preload/30.Tizen.NUI.preload
Labels: API8

#1823 [MediaController] Add new request method
  src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerClient.cs
  src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerServer.cs
  src/Tizen.Multimedia.Remoting/MediaController/CommandCompletedEventArgs.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlCommand.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlEnums.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlServer.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaController.Events.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaController.cs
  src/Tizen.Multimedia.Remoting/MediaController/MediaControllerManager.Events.cs
Labels: ACR Required, API8

#1854 [MediaPlayer] remove NotSupportedFormat exception
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerError.cs
Labels: ACR Required, API8

#1836 [NUI] Add WindowSystem softkey APIs
  src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.SoftkeyClient.cs
  src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.SoftkeyService.cs
  src/Tizen.NUI.WindowSystem/src/public/ShellEnums.cs
  src/Tizen.NUI.WindowSystem/src/public/SoftkeyClient.cs
  src/Tizen.NUI.WindowSystem/src/public/SoftkeyService.cs
  test/Tizen.NUI.WindowSystem.Samples/Tizen.NUI.WindowSystem.Samples.cs
  test/Tizen.NUI.WindowSystem.Samples/Tizen.NUI.WindowSystem.Samples.sln
  test/Tizen.NUI.WindowSystem.Samples/tizen-manifest.xml
Labels: API8, Internal API Changed

#1855 [NUI] Fix Window.FocusChanged event problem
  src/Tizen.NUI/src/public/WindowEvent.cs
Labels: API8

#1851 [NUI] Enable selectors work in View : EnableControlState
  src/Tizen.NUI.Components/Controls/Button.Internal.cs
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/SelectButton.cs
  src/Tizen.NUI/src/public/BaseComponents/ControlState.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyleBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Labels: API8, Internal API Changed

#1856 [Build] Add github actions workflow for pull request
  .github/workflows/pull_request.yaml
Labels: **NO MERGE**, API8

#1858 [Build] Use GITHUB_TOKEN in Pull Request workflow
  .github/workflows/pull_request.yaml
Labels: API8

#1859 [Build] Use github actions for building and reporting annotations
  .github/workflows/pull_request.yaml
Labels: API8

#1860 [Workflow] Add stale action to workflows
  .github/workflows/stale.yml
Labels: API8

#1861 [Workflow] Build on push event
  .github/workflows/build.yaml
  .travis.yml
Labels: API8

#1834 [NUI] Open new GridLayout APIs and Properties
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Labels: ACR Accepted, API8

#1803 [NUI] add attached property support for FlexLayout
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.FlexLayout.cs
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Labels: API8, Internal API Changed

#1864 [NUI] Fix scroll item touch issue
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API8

#1842 [NUI] remove unused class
  src/Tizen.NUI/src/public/BaseComponents/Style/BundledPipe.cs
  src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
Labels: API8

#1852 [NUI] Add CAPTURE_ALL_TOUCH_AFTER_START property
  src/Tizen.NUI/src/internal/Interop/Interop.ActorProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
Labels: API8, Internal API Changed

#1865 [NUI] Workaround : Fix TCT fail issue
  src/Tizen.NUI/src/public/WindowEvent.cs
Labels: API8

#1868 Revert "[NUI] Add CAPTURE_ALL_TOUCH_AFTER_START property (#1852)"
  src/Tizen.NUI/src/internal/Interop/Interop.ActorProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
Labels: API8, Internal API Changed

#1867 [NUI] Fix svace issues.
  src/Tizen.NUI/src/internal/Xaml/CreateValuesVisitor.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/XamlBinding/Page.cs
Labels: API8

#1874 [NUI] Fix the type convert issue when new InputField
  src/Tizen.NUI/src/public/BaseComponents/TextFieldSelectorData.cs
Labels: API8

#1875 [Applications.Alarm] Handle null parameter for AppControl
  src/Tizen.Applications.Alarm/Tizen.Applications/AlarmManager.cs
Labels: API8

#1876 [NUI] Change Text to TextSelector for Textfield
  src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
Labels: API8

#1869 [NUI] Support default focus logic for RecyclerView
  src/Tizen.NUI.Components/Controls/RecyclerView/GridRecycleLayoutManager.cs
  src/Tizen.NUI.Components/Controls/RecyclerView/LinearRecycleLayoutManager.cs
  src/Tizen.NUI.Components/Controls/RecyclerView/RecycleLayoutManager.cs
  src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
Labels: API8, Internal API Changed
