Repository Samsung/TizenFX, pull requests merged in 2020-05, with the labels that each got.

#1581 [NUI] Make instanceSet to hold notification windows and fix Window.TouchEvent bug
  src/Tizen.NUI.Components/Controls/Notification.cs
  src/Tizen.NUI/src/public/WindowEvent.cs
Labels: API8

#1588 [ElmSharp] Adds PeekInstance to PreloadedWindow
  src/ElmSharp/ElmSharp/PreloadedWindow.cs
Labels: API8, Internal API Changed

#1590 [ElmSharp] Adds PeekInstance to PreloadedWindow
  src/ElmSharp/ElmSharp/PreloadedWindow.cs
Labels: API6, Internal API Changed

#1591 [ElmSharp] Adds PeekInstance to PreloadedWindow
  src/ElmSharp/ElmSharp/PreloadedWindow.cs
Labels: API7, Internal API Changed

#1592 [NUI] Fix some API to use GetManagedBaseHandleFromNativePtr
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/internal/WidgetImpl.cs
Labels: API8

#1596 [Sensor] Initialize data for batch type sensor
  src/Tizen.Sensor/Tizen.Sensor/BatchSensor.cs
Labels: API8

#1580 [MediaVision] Add and deprecate enumerations
  src/Tizen.Multimedia.Vision/MediaVision/InferenceModelConfiguration.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceType.cs
  src/Tizen.Multimedia.Vision/Tizen.Multimedia.Vision.sln
Labels: ACR Required, API8

#1599 Returned the code on exception
  src/Tizen.Network.Stc/Tizen.Network.Stc/StcManagerImpl.cs
Labels: API8

#1554 [NUI] remove unnecessary code to assign children layout
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
Labels: API8

#1586 [NUI] remove redundant private properties for Tizen.NUI.Key
  src/Tizen.NUI/src/public/Key.cs
Labels: API8

#1585 [NUI] remove input method dependency from View.ControlState
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/Extension/ButtonExtension.cs
  src/Tizen.NUI.Components/Controls/Extension/LottieButtonExtension.cs
  src/Tizen.NUI.Components/Controls/Extension/LottieSwitchExtension.cs
  src/Tizen.NUI.Components/PreloadStyle/OverlayAnimationButtonStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Labels: API8, Internal API Changed

#1594 [NUI] Fix the issue that size receives 2 parameters from xaml
  src/Tizen.NUI/src/public/XamlBinding/SizeTypeConverter.cs
Labels: API8

#1600 [NUI] Add Title in Wearable component
  src/Tizen.NUI.Wearable/src/public/Title.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TitleSample.cs
Labels: API8, Internal API Changed

#1602 [MediaVision] Fix wrong key string value
  src/Tizen.Multimedia.Vision/MediaVision/InferenceModelConfiguration.cs
Labels: API8

#1607 [NUI.Wearable] Modify LanguageChanged bug
  src/Tizen.NUI.Wearable/src/internal/NUIWatchCoreBackend.cs
Labels: API8

#1547 [NUI] Add GetWindowId()
  src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API8, Internal API Changed

#1608 [Tizen.Network.Connection] Make callbacks to member variable
  src/Tizen.Network.Connection/Tizen.Network.Connection/ConnectionInternalManager.cs
Labels: API8

#1610 [NUI] Change suggested minimun size in Layout.
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
Labels: API8

#1620 [NUI] Modify to use NDalicPINVOKE.Lib
  src/Tizen.NUI/src/internal/Interop/Interop.TextField.cs
  src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs
Labels: API8

#1618 [Vision] Change DLLImport file
  src/Tizen.Multimedia.Vision/Interop/Interop.Libraries.cs
  src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.BarCode.cs
  src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Common.cs
  src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Face.cs
  src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Image.cs
  src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Inference.cs
  src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Surveillance.cs
Labels: API8

#1622 [Sensor] Update sensor description for better understanding.
  src/Tizen.Sensor/Tizen.Sensor/EventArgs/AutoRotationSensorDataUpdatedEventArgs.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/AutoRotationSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/HeartRateMonitorBatch.cs
  src/Tizen.Sensor/Tizen.Sensor/SensorEnumerations.cs
Labels: API8

#1623 [NUI] Update the default size of Loading
  src/Tizen.NUI.Components/Controls/Loading.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultTheme.cs
  src/Tizen.NUI.Components/PreloadStyle/WearableTheme.cs
  src/Tizen.NUI.Components/Style/Theme.cs
  src/Tizen.NUI/src/public/InputMethodContext.cs
Labels: API8

#1616 [NUI] Make a color visual of View's shadow to center aligned
  src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
Labels: API8

#1609 [NUI] Add CircularProgress to Wearable components
  src/Tizen.NUI.Wearable/src/public/CircularProgress.cs
  src/Tizen.NUI.Wearable/src/public/WearableStyle/CircularProgressStyle.cs
Labels: API8, Internal API Changed

#1553 [NUI] Refactorying FittingMode for ImageView
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/VisualConstants.cs
Labels: API8, Internal API Changed

#1613 [Bluetooth][Non-ACR] Invalid increased count issue
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapterImpl.cs
Labels: API8

#1614 [Bluetooth][Non-ACR] Invalid increased count issue
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapterImpl.cs
Labels: API7

#1630 [NUI] Fix some view properties are not overwritten when the view has …
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API8

#1632 [NUI] Scrollbar : Separate the concept of viewport size and view size.
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/ScrollbarBase.cs
  src/Tizen.NUI.Components/Style/ScrollbarStyle.cs
  src/Tizen.NUI.Wearable/src/public/CircularScrollbar.cs
  src/Tizen.NUI.Wearable/src/public/WearableStyle/CircularScrollbarStyle.cs
Labels: API8, Internal API Changed

#1633 [NUI] Update Tizen.NUI.Samples slightly
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CircularPaginationSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliDemo.cs
Labels: API8

#1626 [NUI] First version of RecyclerView
  src/Tizen.NUI.Components/Controls/RecyclerView/LayoutManager.cs
  src/Tizen.NUI.Components/Controls/RecyclerView/LinearLayoutManager.cs
  src/Tizen.NUI.Components/Controls/RecyclerView/RecycleAdapter.cs
  src/Tizen.NUI.Components/Controls/RecyclerView/RecycleItem.cs
  src/Tizen.NUI.Components/Controls/RecyclerView/RecyclerView.cs
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI.Wearable/src/internal/FishEyeLayoutManager.cs
  src/Tizen.NUI.Wearable/src/public/WearableList.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Labels: API8, Internal API Changed

#1572 [NUI] Add Wearable.Popup
  src/Tizen.NUI.Wearable/src/public/Popup.cs
  src/Tizen.NUI.Wearable/src/public/WearableStyle/PopupStyle.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples.sln
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliTableView.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WearablePopupTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/PopupTest/circle.jpg
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/PopupTest/icon.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/PopupTest/tw_bottom_btn_bg.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/PopupTest/tw_ic_popup_btn_bg.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/PopupTest/tw_ic_popup_btn_check.png
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/PopupTest/tw_ic_popup_btn_delete.png
Labels: API8, Internal API Changed

#1625 [ElmSharp] Update the SystemTime internal struct
  src/ElmSharp/Interop/Interop.Libc.cs
Labels: API7

#1627 [ElmSharp] Update the SystemTime internal struct
  src/ElmSharp/Interop/Interop.Libc.cs
Labels: API8

#1631 [ElmSharp] Update internal EcoreEventKey struct
  src/ElmSharp/ElmSharp/EcoreKeyEventArgs.cs
Labels: API8

#1638 [NUI] Add default DropdownItemStyle
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultTheme.cs
  src/Tizen.NUI.Components/Style/Theme.cs
Labels: API8

#1639 [NUI] SetProperty first then SetValue
  src/Tizen.NUI/src/internal/Xaml/ApplyPropertiesVisitor.cs
Labels: API8
