Repository Samsung/TizenFX, pull requests merged in 2020-03, with the labels that each got.

#1433 [NUI] Deprecate InputMethodContext public constructor
  src/Tizen.NUI/src/public/InputMethodContext.cs
Labels: ACR Required, API8

#1359 [Applications.Alarms] Update doxygen
  src/Tizen.Applications.Alarm/Tizen.Applications/Alarm.cs
Labels: API8

#1442 [AudioManager] Apply EditorBrowsableState.Never for deprecated API
  src/Tizen.Multimedia/AudioManager/AudioDevice.cs
  src/Tizen.Multimedia/AudioManager/AudioDeviceOptions.cs
  src/Tizen.Multimedia/AudioManager/AudioDeviceState.cs
  src/Tizen.Multimedia/AudioManager/AudioDeviceStateChangedEventArgs.cs
  src/Tizen.Multimedia/AudioManager/AudioManager.cs
Labels: ACR Required, API8

#1448 [NUI] Use padding & margin to meausre size in Layout
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
  src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
  src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
  src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
Labels: API7

#1446 [MediaCodec] Register EosReached event
  src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodec.cs
  src/Tizen.Multimedia.MediaCodec/Tizen.Multimedia.MediaCodec.sln
Labels: API6

#1445 [MediaCodec] Register EosReached event
  src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodec.cs
  src/Tizen.Multimedia.MediaCodec/Tizen.Multimedia.MediaCodec.sln
Labels: API7

#1449 [Build] Set smack labels of symbol files
  packaging/csapi-tizenfx.spec
Labels: API8

#1450 [Build] Set smack labels of symbol files
  packaging/csapi-tizenfx.spec
Labels: API6

#1444 [NUI] Fix to get bezel wheel event on wearable device by WheelEvent
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/WindowEvent.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DimTest.cs
Labels: API8

#1452 [NUI] Change PageToSnap Behavior
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API7, Internal API Changed

#1453 [NUI] Change PageToSnap Behavior
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API8, Internal API Changed

#1456 [NUI] Check the previous width and height specifications
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API8

#1457 [NUI] Check the previous width and height specifications
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API7

#1420 [Build] Add RIDs of Tizen.6.0.0 and Set RIDs to vconf automatically
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
  packaging/makerid.py
  packaging/makespec.sh
  pkg/Tizen.NET/runtime.json
Labels: API8

#1424 [WIP][Build] Add RIDs of Tizen.6.0.0 and Set RIDs to vconf automatically
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
  packaging/makerid.py
  packaging/makespec.sh
  pkg/Tizen.NET/runtime.json
Labels: API7

#1454 [Build] Set RIDs to vconf automatically
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
  packaging/makerid.py
  packaging/makespec.sh
  pkg/Tizen.NET/runtime.json
Labels: API6

#1462 [Packagemanager] Fix creating internal callback delgate
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Labels: API8

#1463 [NUI] Apply CornerRadius to View
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
  src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
  src/Tizen.NUI/src/public/VisualConstants.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ControlSample.cs
Labels: API8, Internal API Changed

#1466 [NUI] Apply CornerRadius to View
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
  src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
  src/Tizen.NUI/src/public/VisualConstants.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ControlSample.cs
Labels: API7, Internal API Changed

#1460 [NUI] Make AccessibilityManager APIs as public ones
  src/Tizen.NUI/src/internal/AccessibilityManagerEvent.cs
  src/Tizen.NUI/src/internal/AccessibilityManagerEventArgs.cs
  src/Tizen.NUI/src/internal/Interop/Interop.AccessibilityManager.cs
  src/Tizen.NUI/src/public/AccessibilityManager.cs
  src/Tizen.NUI/src/public/AccessibilityManagerEvent.cs
  src/Tizen.NUI/src/public/AccessibilityManagerEventArgs.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AccessibilityManagerSample.cs
Labels: API8, Internal API Changed

#1468 [NUI] Remove Window.Instance from the sample code
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AnimatedImageViewTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AnimatedVectorImageViewTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ButtonSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CheckBoxSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ContactCard/ContactCard.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ContactCard/ContactCardLayouter.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ContactCard/ContactCardsSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ControlSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CubeTransitionEffectSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliDemo.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliTableView.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DropDownSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FlexibleViewSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ItemViewDemo/ItemViewSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LoadingSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LottieAnimationTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PaginationSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PopupSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ProgressSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RadioButtonSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ScrollBarSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SliderSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SwitchSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TabSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ToastSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VideoViewTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Tizen.NUI.Samples.csproj
Labels: API8

#1467 [NUI] Remove Window.Instance from the sample code
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AnimatedImageViewTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AnimatedVectorImageViewTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ButtonSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CheckBoxSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ContactCard/ContactCard.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ContactCard/ContactCardLayouter.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ContactCard/ContactCardsSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ControlSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CubeTransitionEffectSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliDemo.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliTableView.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DropDownSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FlexibleViewSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ItemViewDemo/ItemViewSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LoadingSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LottieAnimationTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PaginationSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PopupSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ProgressSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/RadioButtonSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ScrollBarSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SliderSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SwitchSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/TabSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/ToastSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VideoViewTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Tizen.NUI.Samples.csproj
Labels: API7

#1393 [ElmSharp] Add ElmSharp.Wearable preloading
  src/ElmSharp.Wearable/ElmSharp.Wearable/Preload.cs
  src/ElmSharp/ElmSharp/PreloadedWindow.cs
Labels: API6, Internal API Changed

#1239 [NUI] Add object dump function
  src/Tizen.NUI/src/internal/EnumHelper.cs
  src/Tizen.NUI/src/internal/Extensions.cs
  src/Tizen.NUI/src/internal/XamlBinding/ExtentsTypeConverter.cs
  src/Tizen.NUI/src/internal/XamlBinding/PositionTypeConverter.cs
  src/Tizen.NUI/src/internal/XamlBinding/RectangleTypeConverter.cs
  src/Tizen.NUI/src/internal/XamlBinding/RotationTypeConverter.cs
  src/Tizen.NUI/src/internal/XamlBinding/VectorTypeConverter.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
  src/Tizen.NUI/src/public/Window.cs
  src/Tizen.NUI/src/public/XamlBinding/ColorTypeConverter.cs
  src/Tizen.NUI/src/public/XamlBinding/SizeTypeConverter.cs
  src/Tizen.NUI/src/public/XamlBinding/TypeConverter.cs
Labels: API8, Internal API Changed

#1469 [NUI] Add Window VisibilityChanged Event
  src/Tizen.NUI/src/internal/Interop/Interop.WindowVisibilityChangedSignal.cs
  src/Tizen.NUI/src/internal/WindowVisibilityChangedEvent.cs
  src/Tizen.NUI/src/public/WindowEvent.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples.sln
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VisibilityChangedTest.cs
Labels: API8, Internal API Changed

#1471 Revert "[NUI] Make AccessibilityManager APIs as public ones (#1460)"
  src/Tizen.NUI/src/internal/AccessibilityManager.cs
  src/Tizen.NUI/src/internal/AccessibilityManagerEvent.cs
  src/Tizen.NUI/src/internal/AccessibilityManagerEventArgs.cs
  src/Tizen.NUI/src/internal/Interop/Interop.AccessibilityManager.cs
  src/Tizen.NUI/src/public/AccessibilityManagerEvent.cs
  src/Tizen.NUI/src/public/AccessibilityManagerEventArgs.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AccessibilityManagerSample.cs
Labels: API8, Internal API Changed

#1473 [NUI] check layout owner is null when removing childLayout
  src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
Labels: API7

#1472 [NUI] check layout owner is null when removing childLayout
  src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
Labels: API8

#1474 [NUI] Add SiblingOrder Sample
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/SiblingOrderTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Tizen.NUI.Samples.csproj
Labels: API8

#1434 [NUI] Public Style apis
  src/Tizen.NUI.Components/Controls/Button.cs
  src/Tizen.NUI.Components/Controls/CheckBox.cs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/FlexibleView/FlexibleView.cs
  src/Tizen.NUI.Components/Controls/Loading.cs
  src/Tizen.NUI.Components/Controls/Pagination.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/RadioButton.cs
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
  src/Tizen.NUI.Components/Controls/SelectButton.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI.Components/Controls/Tab.cs
  src/Tizen.NUI.Components/Controls/Toast.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultButtonStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultCheckBoxStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultDropDownStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultPopupStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultProgressStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultRadioButtonStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultSliderStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultSwitchStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultTabStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultToastStyle.cs
  src/Tizen.NUI.Components/Style/ButtonStyle.cs
  src/Tizen.NUI.Components/Style/DropDownStyle.cs
  src/Tizen.NUI.Components/Style/LoadingStyle.cs
  src/Tizen.NUI.Components/Style/PaginationStyle.cs
  src/Tizen.NUI.Components/Style/PopupStyle.cs
  src/Tizen.NUI.Components/Style/ProgressStyle.cs
  src/Tizen.NUI.Components/Style/ScrollbarStyle.cs
  src/Tizen.NUI.Components/Style/SliderStyle.cs
  src/Tizen.NUI.Components/Style/SwitchStyle.cs
  src/Tizen.NUI.Components/Style/TabStyle.cs
  src/Tizen.NUI.Components/Style/ToastStyle.cs
  src/Tizen.NUI.Components/Utils/StyleBase.cs
  src/Tizen.NUI.Components/Utils/StyleManager.cs
Labels: ACR Required, API8

#1477 [NUI] Add API for changing layout sibling order
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
  src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
Labels: API8, Internal API Changed

#1478 [NUI] Add API for changing layout sibling order
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
  src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
Labels: API7, Internal API Changed

#1461 [NUI] Add Horizontal Grid
  src/Tizen.NUI/src/internal/Layouting/GridLocations.cs
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Labels: API8, Internal API Changed

#1464 [ElmSharp] Add ElmSharp.Wearable preloading
  src/ElmSharp.Wearable/ElmSharp.Wearable/Preload.cs
  src/ElmSharp/ElmSharp/PreloadedWindow.cs
Labels: API7, Internal API Changed

#1465 [ElmSharp] Add ElmSharp.Wearable preloading
  src/ElmSharp.Wearable/ElmSharp.Wearable/Preload.cs
  src/ElmSharp/ElmSharp/PreloadedWindow.cs
Labels: API8, Internal API Changed

#1482 [NUI] Make AccessibilityManager APIs as public ones
  src/Tizen.NUI/src/internal/AccessibilityActionSignal.cs
  src/Tizen.NUI/src/internal/AccessibilityFocusOvershotSignal.cs
  src/Tizen.NUI/src/internal/AccessibilityManager.cs
  src/Tizen.NUI/src/internal/AccessibilityManagerEvent.cs
  src/Tizen.NUI/src/internal/AccessibilityManagerEventArgs.cs
  src/Tizen.NUI/src/internal/Interop/Interop.AccessibilityManager.cs
  src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
  src/Tizen.NUI/src/public/Accessibility/AccessibilityManager.cs
  src/Tizen.NUI/src/public/Accessibility/AccessibilityManagerEvent.cs
  src/Tizen.NUI/src/public/Accessibility/AccessibilityManagerEventArgs.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AccessibilityManagerSample.cs
Labels: API8, Internal API Changed

#1458 [Applications.Alarm] Add a new Enum for standard period
  src/Tizen.Applications.Alarm/Tizen.Applications/AlarmManager.cs
Labels: ACR Required, API8

#1443 [StreamRecorder] Handle NotSupportedException as new feature added
  src/Tizen.Multimedia.StreamRecorder/StreamRecorder/StreamRecorder.cs
Labels: ACR Required, API7

#1485 [NUI] Add GridLaoyt Sample
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/GridLayoutSample.cs
Labels: API8

#1483 [StreamRecorder] Handle NotSupportedException as new feature added
  src/Tizen.Multimedia.StreamRecorder/StreamRecorder/StreamRecorder.cs
Labels: ACR Required, API8

#1414 [MachineLearning.Inference] new API to set/get the property
  src/Tizen.MachineLearning.Inference/Interop/Interop.Nnstreamer.cs
  src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/SingleShot.cs
Labels: ACR Required, API8

#1484 [Build] [MachineLearning.Inference] update PlatformFileList
  packaging/PlatformFileList.txt
Labels: API8

#1486 [Build] Set smack labels of symbol files in .spec.in
  packaging/csapi-tizenfx.spec.in
Labels: API8

#1487 [Build] Set smack labels of symbol files in .spec.in
  packaging/csapi-tizenfx.spec.in
Labels: API7

#1488 [Build] Set smack labels of symbol files in .spec.in
  packaging/csapi-tizenfx.spec.in
Labels: API6

#1495 [NUI] Fix scrolling
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API8

#1496 [NUI] Fix scrolling
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API7

#1498 [NUI] Add SetPositionByLayout Property
  src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
Labels: API7, Internal API Changed

#1497 [NUI] Add SetPositionByLayout Property
  src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
Labels: API8, Internal API Changed

#1499 [NUI] Remove ClearBackgound operate when setting BackgroundImage
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
Labels: API8

#1404 [MachineLearning.Inference] Pipeline class to execute neural network stream
  src/Tizen.MachineLearning.Inference/Interop/Interop.Nnstreamer.cs
  src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/Commons.cs
  src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/DataReceivedEventArgs.cs
  src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/Pipeline.cs
  src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/SingleShot.cs
  src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/StateChangedEventArgs.cs
  src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsData.cs
  src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsInfo.cs
Labels: ACR Required, API8

#1505 [API6][Applications] Update CurrentUICulture when Locale was changed
  src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Labels: API6

#1504 [API7][Application] Update CurrentUICulture when Locale was changed
  src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Labels: API7

#1503 [Applications] Update CurrentUICulture when Locale was changed
  src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Labels: API8
