Repository Samsung/TizenFX, pull requests merged in 2020-02, with the labels that each got.

#1326 [NFC] Fix TC failed issue : the SEH exception occurs
  src/Tizen.Network.Smartcard/Tizen.Network.Smartcard/SmartcardManagerImpl.cs
  src/Tizen.Network.Smartcard/Tizen.Network.Smartcard/SmartcardSession.cs
Labels: API8

#1327 [NFC] Fix TC failed issue : the SEH exception occurs
  src/Tizen.Network.Smartcard/Tizen.Network.Smartcard/SmartcardManagerImpl.cs
  src/Tizen.Network.Smartcard/Tizen.Network.Smartcard/SmartcardSession.cs
Labels: API6

#1328 [NFC] Fix TC failed issue : the SEH exception occurs
  src/Tizen.Network.Smartcard/Tizen.Network.Smartcard/SmartcardManagerImpl.cs
  src/Tizen.Network.Smartcard/Tizen.Network.Smartcard/SmartcardSession.cs
Labels: API7

#1365 [NUI] Measure whole child in GridLayout
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Labels: API8

#1364 [NUI] Measure whole child in GridLayout
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Labels: API7

#1363 [NUI] Measure whole child in GridLayout
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Labels: API6

#1360 [NUI] Fix Animation Dispose() to make local variable of Animation instance make working properly
  src/Tizen.NUI/src/public/Animation.cs
Labels: API8

#1362 [NUI] Fix Animation Dispose() to make local variable of Animation instance make working properly
  src/Tizen.NUI/src/public/Animation.cs
Labels: API6

#1361 [NUI] Fix Animation Dispose() to make local variable of Animation instance make working properly
  src/Tizen.NUI/src/public/Animation.cs
Labels: API7

#1368 [NUI] Modify Instance bug of Application
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/internal/ComponentApplication.cs
  src/Tizen.NUI/src/internal/WatchApplication.cs
  src/Tizen.NUI/src/internal/WidgetApplication.cs
  src/Tizen.NUI/src/public/NUIFrameComponent.cs
  src/Tizen.NUI/src/public/Widget.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API8

#1370 [NUI] Modify Instance bug of Application
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/internal/ComponentApplication.cs
  src/Tizen.NUI/src/internal/WatchApplication.cs
  src/Tizen.NUI/src/internal/WidgetApplication.cs
  src/Tizen.NUI/src/public/NUIFrameComponent.cs
  src/Tizen.NUI/src/public/Widget.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API7

#1369 [NUI] Modify Instance bug of Application
  src/Tizen.NUI/src/internal/Application.cs
  src/Tizen.NUI/src/internal/ComponentApplication.cs
  src/Tizen.NUI/src/internal/WatchApplication.cs
  src/Tizen.NUI/src/internal/WidgetApplication.cs
  src/Tizen.NUI/src/public/NUIFrameComponent.cs
  src/Tizen.NUI/src/public/Widget.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API6

#1374 [Application] Fix widget instance id bug (#1197)
  src/Tizen.Applications.WidgetApplication/Interop/Interop.Widget.cs
  src/Tizen.Applications.WidgetApplication/Tizen.Applications/WidgetType.cs
Labels: API6

#1373 [Application] Fix widget instance id bug (#1197)
  src/Tizen.Applications.WidgetApplication/Interop/Interop.Widget.cs
  src/Tizen.Applications.WidgetApplication/Tizen.Applications/WidgetType.cs
Labels: API7

#1375 [Notification] Change TimeStamp of SafeHanlde
  src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationBinder.cs
Labels: API8

#1378 [NUI] Add default component styles
  packaging/PlatformFileList.txt
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultButtonStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultCheckBoxStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultRadioButtonStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultSwitchStyle.cs
  src/Tizen.NUI.Components/Tizen.NUI.Components.csproj
  src/Tizen.NUI.Components/Utils/StyleManager.cs
  src/Tizen.NUI.Components/res/nui_component_default_checkbox_bg_n.png
  src/Tizen.NUI.Components/res/nui_component_default_checkbox_bg_p.png
  src/Tizen.NUI.Components/res/nui_component_default_checkbox_s.png
  src/Tizen.NUI.Components/res/nui_component_default_radiobutton_n.png
  src/Tizen.NUI.Components/res/nui_component_default_radiobutton_p.png
  src/Tizen.NUI.Components/res/nui_component_default_radiobutton_s.png
  src/Tizen.NUI.Components/res/nui_component_default_switch_thumb_d.png
  src/Tizen.NUI.Components/res/nui_component_default_switch_thumb_n.png
  src/Tizen.NUI.Components/res/nui_component_default_switch_track_d.png
  src/Tizen.NUI.Components/res/nui_component_default_switch_track_ds.png
  src/Tizen.NUI.Components/res/nui_component_default_switch_track_n.png
  src/Tizen.NUI.Components/res/nui_component_default_switch_track_s.png
Labels: API8, Internal API Changed

#1382 [NUI] Add default component styles
  packaging/PlatformFileList.txt
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultButtonStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultCheckBoxStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultRadioButtonStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultSwitchStyle.cs
  src/Tizen.NUI.Components/Tizen.NUI.Components.csproj
  src/Tizen.NUI.Components/Utils/StyleManager.cs
  src/Tizen.NUI.Components/res/nui_component_default_checkbox_bg_n.png
  src/Tizen.NUI.Components/res/nui_component_default_checkbox_bg_p.png
  src/Tizen.NUI.Components/res/nui_component_default_checkbox_s.png
  src/Tizen.NUI.Components/res/nui_component_default_radiobutton_n.png
  src/Tizen.NUI.Components/res/nui_component_default_radiobutton_p.png
  src/Tizen.NUI.Components/res/nui_component_default_radiobutton_s.png
  src/Tizen.NUI.Components/res/nui_component_default_switch_thumb_d.png
  src/Tizen.NUI.Components/res/nui_component_default_switch_thumb_n.png
  src/Tizen.NUI.Components/res/nui_component_default_switch_track_d.png
  src/Tizen.NUI.Components/res/nui_component_default_switch_track_ds.png
  src/Tizen.NUI.Components/res/nui_component_default_switch_track_n.png
  src/Tizen.NUI.Components/res/nui_component_default_switch_track_s.png
Labels: API7, Internal API Changed

#1367 [Sensor] Modify implementation using new native API
  src/Tizen.Sensor/Interop/Interop.Sensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/Accelerometer.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/AutoRotationSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/FaceDownGestureDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/GravitySensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/Gyroscope.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/GyroscopeRotationVectorSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/HeartRateMonitor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/HumiditySensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/InVehicleActivityDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/LightSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/LinearAccelerationSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/Magnetometer.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/MagnetometerRotationVectorSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/OrientationSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/Pedometer.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/PickUpGestureDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/PressureSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/ProximitySensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/RotationVectorSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/RunningActivityDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/SleepMonitor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/StationaryActivityDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/TemperatureSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/UltravioletSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/UncalibratedGyroscope.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/UncalibratedMagnetometer.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/WalkingActivityDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/WristUpGestureDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Sensor.cs
Labels: API8

#1379 [NUI] Fix visual bugs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI/src/public/Visuals/TextVisual.cs
Labels: API8

#1383 [NUI] Fix visual bugs
  src/Tizen.NUI.Components/Controls/Control.cs
  src/Tizen.NUI/src/public/Visuals/TextVisual.cs
Labels: API7

#1388 [ComponentBased] Add a property on BaseComponent
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/BaseComponent.cs
Labels: API7, Internal API Changed

#1387 [ComponentBased] Add a property on BaseComponent
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/BaseComponent.cs
Labels: API6, Internal API Changed

#1386 [ComponentBased] Add a property on BaseComponent
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/BaseComponent.cs
Labels: API8, Internal API Changed

#1389 [ComponentBased] Fix RegisterComponent Method
  src/Tizen.Applications.ComponentBased/Tizen.Applications.ComponentBased.Common/ComponentBasedApplication.cs
Labels: API8

#1376 [ElmSharp] Apply preloading on API7
  src/ElmSharp/ElmSharp/Elementary.cs
  src/ElmSharp/ElmSharp/PreloadedWindow.cs
  src/ElmSharp/ElmSharp/Window.cs
Labels: API7

#1377 [ElmSharp] Add preloading on API8
  src/ElmSharp/ElmSharp/Elementary.cs
  src/ElmSharp/ElmSharp/PreloadedWindow.cs
  src/ElmSharp/ElmSharp/Window.cs
Labels: API8

#1371 [NUI] Measure Child's Layout in FlexLayout
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Labels: API6

#1384 [NUI] Measure Child's Layout in FlexLayout
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Labels: API7

#1385 [NUI] Measure Child's Layout in FlexLayout
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Labels: API8

#1394 [Multimedia] Add ComponentBased project to Tizen.Multimedia.sln
  src/Tizen.Multimedia/Tizen.Multimedia.sln
Labels: API8

#1392 [Bluetooth][TCSACR-301] Add new SendData API
  src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothData.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothSocket.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
Labels: ACR Required, API7

#1390 [Bluetooth][TCSACR-301] Add new SendData API
  src/Tizen.Network.Bluetooth/Interop/Interop.Bluetooth.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothData.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothSocket.cs
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothStructs.cs
Labels: ACR Required, API8

#1372 [NUI] Add SafeNativePlayerHandle to pass native player handle
  src/Tizen.NUI/src/internal/Interop/Interop.VideoView.cs
  src/Tizen.NUI/src/public/BaseComponents/VideoView.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VideoViewTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Tizen.NUI.Samples.csproj
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/v.mp4
Labels: API8, Internal API Changed

#1399 [NUI] Add removed API as hidden API to pass the tizen_5.5 TCT
  src/Tizen.NUI/src/internal/KeyboardTypeSignalType.cs
  src/Tizen.NUI/src/internal/WidgetViewSignal.cs
  src/Tizen.NUI/src/public/ImfManager.cs
  src/Tizen.NUI/src/public/PropertyNotifySignal.cs
Labels: API7, Internal API Changed

#1154 [MachineLearning.Inference] Update SingleShot and its related classes
  src/Tizen.MachineLearning.Inference/Interop/Interop.Nnstreamer.cs
  src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/Commons.cs
  src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/SingleShot.cs
  src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsData.cs
  src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsInfo.cs
Labels: ACR Required, API8

#1396 [NUI] Add default components styles and fix bugs
  packaging/PlatformFileList.txt
  src/Tizen.NUI.Components/Controls/ButtonGroup.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultDropDownStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultPopupStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultProgressStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultSliderStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultToastStyle.cs
  src/Tizen.NUI.Components/Style/ToastStyle.cs
  src/Tizen.NUI.Components/Utils/StyleManager.cs
  src/Tizen.NUI.Components/res/nui_component_default_dropdown_button_icon.png
  src/Tizen.NUI.Components/res/nui_component_default_dropdown_list_bg.png
  src/Tizen.NUI.Components/res/nui_component_default_popup_shadow.png
  src/Tizen.NUI.Components/res/nui_component_default_slider_thumb_bg_p.png
  src/Tizen.NUI.Components/res/nui_component_default_slider_thumb_n.png
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/Extents.cs
  src/Tizen.NUI/src/public/Rectangle.cs
Labels: API8, Internal API Changed

#1400 [NUI] Add default components styles and etc (#1396)
  packaging/PlatformFileList.txt
  src/Tizen.NUI.Components/Controls/ButtonGroup.cs
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI.Components/Controls/Progress.cs
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultDropDownStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultPopupStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultProgressStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultSliderStyle.cs
  src/Tizen.NUI.Components/PreloadStyle/DefaultToastStyle.cs
  src/Tizen.NUI.Components/Style/ToastStyle.cs
  src/Tizen.NUI.Components/Utils/StyleManager.cs
  src/Tizen.NUI.Components/res/nui_component_default_dropdown_button_icon.png
  src/Tizen.NUI.Components/res/nui_component_default_dropdown_list_bg.png
  src/Tizen.NUI.Components/res/nui_component_default_popup_shadow.png
  src/Tizen.NUI.Components/res/nui_component_default_slider_thumb_bg_p.png
  src/Tizen.NUI.Components/res/nui_component_default_slider_thumb_n.png
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/Extents.cs
  src/Tizen.NUI/src/public/Rectangle.cs
Labels: API7, Internal API Changed

#1403 [NUI] Fix TCT crash issue
  src/Tizen.NUI/src/public/Animation.cs
Labels: API8

#1406 [NUI] Fix TCT crash issue
  src/Tizen.NUI/src/public/Animation.cs
Labels: API7

#1408 [Bundle] Separate exceptions for invalid handle
  src/Tizen.Applications.Common/Tizen.Applications/Bundle.cs
Labels: API6

#1409 [MessagePort] Fix Listen Method
  src/Tizen.Applications.MessagePort/Tizen.Applications.Messages/MessagePort.cs
Labels: API8

#1410 [MessagePort] Fix Listen Method
  src/Tizen.Applications.MessagePort/Tizen.Applications.Messages/MessagePort.cs
Labels: API6

#1411 [MessagePort] Fix Listen Method
  src/Tizen.Applications.MessagePort/Tizen.Applications.Messages/MessagePort.cs
Labels: API7

#1412 [Bundle] Separate exceptions for invalid handle
  src/Tizen.Applications.Common/Tizen.Applications/Bundle.cs
Labels: API7

#1413 [Bundle] Separate exceptions for invalid handle
  src/Tizen.Applications.Common/Tizen.Applications/Bundle.cs
Labels: API8

#1395 [AudioManager] Remove deprecated symbols
  src/Tizen.Multimedia/AudioManager/AudioDevice.cs
  src/Tizen.Multimedia/AudioManager/AudioDeviceOptions.cs
  src/Tizen.Multimedia/AudioManager/AudioDeviceRunningChangedEventArgs.cs
  src/Tizen.Multimedia/AudioManager/AudioDeviceState.cs
  src/Tizen.Multimedia/AudioManager/AudioDeviceStateChangedEventArgs.cs
  src/Tizen.Multimedia/AudioManager/AudioManager.cs
  src/Tizen.Multimedia/Interop/Interop.Device.cs
Labels: ACR Required, API8

#1397 [Applications.Common] Add a new element on ApplicationComponentType
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationComponentType.cs
Labels: ACR Required, API7

#1417 [Applications.Common] Add a new element of ApplicationComponentType
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationComponentType.cs
Labels: ACR Required, API8

#1421 [MediaCodec] Register EosReached event
  src/Tizen.Multimedia.MediaCodec/MediaCodec/MediaCodec.cs
  src/Tizen.Multimedia.MediaCodec/Tizen.Multimedia.MediaCodec.sln
Labels: API8

#1426 [NUI] Add property LayoutWithTransition to LayoutItem
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
  src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
  src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
Labels: API8, Internal API Changed

#1427 [NUI] Add property LayoutWithTransition to LayoutItem
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
  src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
  src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
Labels: API7, Internal API Changed

#1423 [ElmSharp] Fix GestureLayer native callback return type
  src/ElmSharp/ElmSharp/GestureLayer.cs
  src/ElmSharp/Interop/Interop.Elementary.GestureLayer.cs
Labels: API7

#1422 [ElmSharp] Fix GestureLayer native callback return type
  src/ElmSharp/ElmSharp/GestureLayer.cs
  src/ElmSharp/Interop/Interop.Elementary.GestureLayer.cs
Labels: API8

#1428 [NUI] Remove draft property in ScrollableBase
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API8, Internal API Changed

#1429 [NUI] Remove draft property in ScrollableBase
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API7, Internal API Changed

#1366 [ElmSharp] Add widgets for warming up at preloading step
  src/ElmSharp/ElmSharp/PreloadedWindow.cs
Labels: API6

#1418 [NUI] Fix margin bug in FlexLayout
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.FlexLayout.cs
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Labels: API8

#1419 [NUI] Fix margin bug in FlexLayout
  src/Tizen.NUI/src/internal/Layouting/Interop/Interop.FlexLayout.cs
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
Labels: API7

#1430 [NUI] Add ScrollEvent to ScrollableBase
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API8, Internal API Changed

#1431 [NUI] Add ScrollEvent to ScrollableBase
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API7, Internal API Changed

#1432 [NUI] Support Nullable type in Xaml
  src/Tizen.NUI/src/internal/Xaml/TypeConversionExtensions.cs
  src/Tizen.NUI/src/internal/Xaml/XamlLoader.cs
  src/Tizen.NUI/src/internal/Xaml/XamlParser.cs
  src/Tizen.NUI/src/internal/XamlBinding/PositionTypeConverter.cs
Labels: API8

#1258 [NUI] Add to set Available Orientations
  src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API6, Internal API Changed

#1257 [NUI] Add to set Available Orientations
  src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API7, Internal API Changed

#1256 [NUI] Add to set Available Orientations
  src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
  src/Tizen.NUI/src/public/Window.cs
Labels: API8, Internal API Changed

#1436 [Notification] Change TimeStamp of SafeHanlde
  src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationBinder.cs
Labels: API6

#1437 [NUI] Use padding & margin to meausre size in Layout
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
  src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
  src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
  src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
Labels: API8
