Repository Samsung/TizenFX, pull requests merged in 2020-01, with the labels that each got.

#1262 [NUI] Implement the old API of Popup.SetButtonText for Manual.Tests f…
  src/Tizen.NUI.Components/Controls/Popup.cs
Labels: API8

#1261 [NUI] Implement the old API of Popup.SetButtonText for Manual.Tests f…
  src/Tizen.NUI.Components/Controls/Popup.cs
Labels: API7, Internal API Changed

#1264 [NUI] Implement the old API of Popup.SetButtonText for Manual.Tests f…
  src/Tizen.NUI.Components/Controls/Popup.cs
Labels: API6

#1259 [NUI] Fix the issue that the property binding in View are not working…
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API8

#1265 [NUI] Fix the issue that the property binding in View are not working properly. (#1259)
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API6

#1266 [NUI] Fix the issue that the property binding in View are not working properly. (#1259)
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API7, Internal API Changed

#1267 [NUI] Enable BackgroundImageBorder in View
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
  src/Tizen.NUI/src/public/Rectangle.cs
Labels: API8

#1268 [NUI] Enable BackgroundImageBorder in View
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
  src/Tizen.NUI/src/public/Rectangle.cs
Labels: API7, Internal API Changed

#1269 [NUI] Enable BackgroundImageBorder in View
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
  src/Tizen.NUI/src/public/Rectangle.cs
Labels: API6

#1270 [NUI] Update Shadow property : add Clone method
  src/Tizen.NUI/src/public/Color.cs
  src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
  src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
  src/Tizen.NUI/src/public/ViewProperty/TransformablePropertyMap.cs
Labels: API8, Internal API Changed

#1271 [NUI] Update Shadow property : add Clone method
  src/Tizen.NUI/src/public/Color.cs
  src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
  src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
  src/Tizen.NUI/src/public/ViewProperty/TransformablePropertyMap.cs
Labels: API7, Internal API Changed

#1272 [NUI] Update Shadow property : add Clone method
  src/Tizen.NUI/src/public/Color.cs
  src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
  src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
  src/Tizen.NUI/src/public/ViewProperty/TransformablePropertyMap.cs
Labels: API6, Internal API Changed

#1273 [NUI] Fixed the type conversion issue which cause TCT failed
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
Labels: API8

#1275 [NUI] Fixed the type conversion issue which cause TCT failed
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
Labels: API7, Internal API Changed

#1274 [NUI] Fixed the type conversion issue which cause TCT failed
  src/Tizen.NUI.Components/Controls/Scrollbar.cs
Labels: API6

#1276 [NUI] Add Shadow properties to ViewStyle
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/ViewProperty/ICloneable.cs
  src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
  src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
  src/Tizen.NUI/src/public/ViewProperty/TransformablePropertyMap.cs
Labels: API8, Internal API Changed

#1277 [NUI] Add Shadow properties to ViewStyle
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/ViewProperty/ICloneable.cs
  src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
  src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
  src/Tizen.NUI/src/public/ViewProperty/TransformablePropertyMap.cs
Labels: API7, Internal API Changed

#1278 [NUI] Add Shadow properties to ViewStyle
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/ViewProperty/ICloneable.cs
  src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
  src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
  src/Tizen.NUI/src/public/ViewProperty/TransformablePropertyMap.cs
Labels: API6, Internal API Changed

#1255 [ElmSharp] Add more preloading components
  src/ElmSharp/ElmSharp/Elementary.cs
  src/ElmSharp/ElmSharp/PreloadedWindow.cs
  src/ElmSharp/ElmSharp/Window.cs
Labels: API6

#1281 [NUI] Fix background blank issue of Switch
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
Labels: API8

#1280 [NUI] Fix background blank issue of Switch
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
Labels: API6

#1282 [NUI] Fix background blank issue of Switch
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
Labels: API7, Internal API Changed

#1290 [NUI] Implement switch's Old background API
  src/Tizen.NUI.Components/Controls/Switch.cs
Labels: API7, Internal API Changed

#1289 [NUI] Implement switch's Old background API
  src/Tizen.NUI.Components/Controls/Switch.cs
Labels: API8

#1288 [NUI] Implement switch's Old background API
  src/Tizen.NUI.Components/Controls/Switch.cs
Labels: API6

#1279 [NUI] Fix extents issue and unified style format
  src/Tizen.NUI.Components/Style/ButtonStyle.cs
  src/Tizen.NUI.Components/Style/ControlStyle.cs
  src/Tizen.NUI.Components/Style/DropDownStyle.cs
  src/Tizen.NUI.Components/Style/ImageControlStyle.cs
  src/Tizen.NUI.Components/Style/LoadingStyle.cs
  src/Tizen.NUI.Components/Style/PaginationStyle.cs
  src/Tizen.NUI.Components/Style/PopupStyle.cs
  src/Tizen.NUI.Components/Style/ProgressStyle.cs
  src/Tizen.NUI.Components/Style/ScrollbarStyle.cs
  src/Tizen.NUI.Components/Style/SliderStyle.cs
  src/Tizen.NUI.Components/Style/SwitchStyle.cs
  src/Tizen.NUI.Components/Style/TabStyle.cs
  src/Tizen.NUI.Components/Style/ToastStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
Labels: API8

#1286 [NUI] Fix extents issue and unified style format
  src/Tizen.NUI.Components/Style/ButtonStyle.cs
  src/Tizen.NUI.Components/Style/ControlStyle.cs
  src/Tizen.NUI.Components/Style/DropDownStyle.cs
  src/Tizen.NUI.Components/Style/ImageControlStyle.cs
  src/Tizen.NUI.Components/Style/LoadingStyle.cs
  src/Tizen.NUI.Components/Style/PaginationStyle.cs
  src/Tizen.NUI.Components/Style/PopupStyle.cs
  src/Tizen.NUI.Components/Style/ProgressStyle.cs
  src/Tizen.NUI.Components/Style/ScrollbarStyle.cs
  src/Tizen.NUI.Components/Style/SliderStyle.cs
  src/Tizen.NUI.Components/Style/SwitchStyle.cs
  src/Tizen.NUI.Components/Style/TabStyle.cs
  src/Tizen.NUI.Components/Style/ToastStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
Labels: API6

#1287 [NUI] Fix extents issue and unified style format
  src/Tizen.NUI.Components/Style/ButtonStyle.cs
  src/Tizen.NUI.Components/Style/ControlStyle.cs
  src/Tizen.NUI.Components/Style/DropDownStyle.cs
  src/Tizen.NUI.Components/Style/ImageControlStyle.cs
  src/Tizen.NUI.Components/Style/LoadingStyle.cs
  src/Tizen.NUI.Components/Style/PaginationStyle.cs
  src/Tizen.NUI.Components/Style/PopupStyle.cs
  src/Tizen.NUI.Components/Style/ProgressStyle.cs
  src/Tizen.NUI.Components/Style/ScrollbarStyle.cs
  src/Tizen.NUI.Components/Style/SliderStyle.cs
  src/Tizen.NUI.Components/Style/SwitchStyle.cs
  src/Tizen.NUI.Components/Style/TabStyle.cs
  src/Tizen.NUI.Components/Style/ToastStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ImageViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextFieldStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/TextLabelStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
Labels: API7, Internal API Changed

#1296 [NUI] Fix SetMinMaxFrameByMarker()'s not working issue in AnimatedVectorImageView
  src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AnimatedVectorImageViewTest.cs
Labels: API6, Internal API Changed

#1295 [NUI] Fix SetMinMaxFrameByMarker()'s not working issue in AnimatedVectorImageView
  src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AnimatedVectorImageViewTest.cs
Labels: API7, Internal API Changed

#1294 [NUI] Fix SetMinMaxFrameByMarker()'s not working issue in AnimatedVectorImageView
  src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AnimatedVectorImageViewTest.cs
Labels: API8, Internal API Changed

#1293 [NUI] Initialize pan direction of ScrollableBase to Vertical
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API8

#1292 [NUI] Initialize pan direction of ScrollableBase to Vertical
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API7, Internal API Changed

#1291 [NUI] Initialize pan direction of ScrollableBase to Vertical
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API6

#1193 [Sensor] Add auto rotation sensor
  src/Tizen.Sensor/Tizen.Sensor/EventArgs/AutoRotationSensorDataUpdatedEventArgs.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/AutoRotationSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/SensorEnumerations.cs
Labels: ACR Required, API7

#1300 [NUI] Add ScrollEnabled property to ScrollableBase
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API8, Internal API Changed

#1298 [NUI] Add ScrollEnabled property to ScrollableBase
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API6, Internal API Changed

#1301 [NUI] Add ScrollEnabled property to ScrollableBase
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API7, Internal API Changed

#1197 [Application] Fix widget instance id bug
  src/Tizen.Applications.WidgetApplication/Interop/Interop.Widget.cs
  src/Tizen.Applications.WidgetApplication/Tizen.Applications/WidgetType.cs
Labels: API8

#1283 [NUI.Components] Remove InputField
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI.Components/Style/InputFieldStyle.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/InputFieldSample.cs
Labels: API8, Internal API Changed

#1284 [NUI.Components] Remove InputField
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI.Components/Style/InputFieldStyle.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/InputFieldSample.cs
Labels: API6, Internal API Changed

#1285 [NUI.Components] Remove InputField
  src/Tizen.NUI.Components/Controls/InputField.cs
  src/Tizen.NUI.Components/Style/InputFieldStyle.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/InputFieldSample.cs
Labels: API7, Internal API Changed

#1304 [NUI] Remove default LayoutTransition
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
Labels: API6

#1305 [NUI] Remove default LayoutTransition
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
Labels: API7

#1306 [NUI] Remove default LayoutTransition
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
Labels: API8

#1313 [NUI] Control handle state `Pressed`
  src/Tizen.NUI.Components/Controls/Control.cs
Labels: API8

#1315 [NUI] Control handle state `Pressed`
  src/Tizen.NUI.Components/Controls/Control.cs
Labels: API7

#1316 [NUI] Control handle state `Pressed`
  src/Tizen.NUI.Components/Controls/Control.cs
Labels: API6

#1318 [NUI] Fix FittingMode bug
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
Labels: API8

#1319 [NUI] Fix FittingMode bug
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
Labels: API7

#1322 [NUI] Fixed GridLayout scrolling issue
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Labels: API6

#1323 [NUI] Fixed GridLayout scrolling issue
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Labels: API7

#1324 [NUI] Fixed GridLayout scrolling issue
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI/src/public/Layouting/GridLayout.cs
Labels: API8

#1309 [NUI.Components] Fix svace issues
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
Labels: API8

#1310 [NUI.Components] Fix svace issues
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
Labels: API6

#1311 [NUI.Components] Fix svace issues
  src/Tizen.NUI.Components/Controls/DropDown.cs
  src/Tizen.NUI.Components/Controls/Popup.cs
Labels: API7

#1329 [NUI] Add/change scroll event
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API6, Internal API Changed

#1330 [NUI] Add/change scroll event
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API7, Internal API Changed

#1331 [NUI] Add/change scroll event
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API8, Internal API Changed

#1314 [NUI] Fix reparenting of Child bug
  src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
  src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
  src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
Labels: API8

#1332 [NUI] Fix reparenting of Child bug
  src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
  src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
  src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
Labels: API6

#1333 [NUI] Fix reparenting of Child bug
  src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
  src/Tizen.NUI/src/public/Layouting/LayoutGroup.cs
  src/Tizen.NUI/src/public/Layouting/LayoutItem.cs
Labels: API7

#1325 [NUI] Support Shadow Size Extents
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/ViewProperty/ICloneable.cs
  src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
  src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
  src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PopupSample.cs
Labels: API8, Internal API Changed

#1335 [NUI] Support Shadow Size Extents
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/ViewProperty/ICloneable.cs
  src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
  src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
  src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PopupSample.cs
Labels: API7, Internal API Changed

#1334 [NUI] Support Shadow Size Extents
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/ViewProperty/ICloneable.cs
  src/Tizen.NUI/src/public/ViewProperty/ImageShadow.cs
  src/Tizen.NUI/src/public/ViewProperty/Shadow.cs
  src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PopupSample.cs
Labels: API6, Internal API Changed

#1337 [NUI] Add dispose checking in key state
  src/Tizen.NUI/src/public/Key.cs
Labels: API6

#1338 [NUI] Add dispose checking in just a few methods of Timer class
  src/Tizen.NUI/src/public/Timer.cs
Labels: API6

#1339 [NUI] Add dispose checking in just a few methods of Timer class
  src/Tizen.NUI/src/public/Timer.cs
Labels: API7

#1340 [NUI] Add dispose checking in just a few methods of Timer class
  src/Tizen.NUI/src/public/Timer.cs
Labels: API8

#1341 [NUI] Fix NUI svace issue
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
Labels: API6

#1342 [NUI] Fix NUI svace issue
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
Labels: API7

#1343 [NUI] Fix NUI svace issue
  src/Tizen.NUI.Components/Controls/Popup.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
Labels: API8

#1344 [NUI] Add GaussianBlurView
  src/Tizen.NUI/src/internal/GaussianBlurView.cs
Labels: API8, Internal API Changed

#1346 [NUI] Add GaussianBlurView
  src/Tizen.NUI/src/internal/GaussianBlurView.cs
Labels: API7, Internal API Changed

#1347 [NUI] Fix AlphaMaskUrl setting order problem
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
Labels: API6

#1345 [NUI] Add GaussianBlurView
  src/Tizen.NUI/src/internal/GaussianBlurView.cs
Labels: API6, Internal API Changed

#1348 [NUI] Fix AlphaMaskUrl setting order problem
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
Labels: API7

#1349 [NUI] Fix AlphaMaskUrl setting order problem
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
Labels: API8

#1350 [NUI] Add ScrollToIndex to ScrollableBase
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API6, Internal API Changed

#1351 [NUI] Add ScrollToIndex to ScrollableBase
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API7, Internal API Changed

#1352 [NUI] Add ScrollToIndex to ScrollableBase
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
Labels: API8, Internal API Changed

#1353 [NUI] Fix Tizen.NUI.Samples crash error when it is terminated
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliDemo.cs
Labels: API8
