Repository Samsung/TizenFX, pull requests merged in 2022-12, with the labels that each got.

#4765 [NUI] Use smaller NearPlaneDistance and bigger FarPlaneDistance during Camera Transition
  src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
Labels: Devel-NUI

#4789 [Packagemanager] Use ToLowerInvariant instead of ToLower
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageType.cs
Labels: API11

#4795 [Packagemanager] Use ToLowerInvariant instead of ToLower
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageType.cs
Labels: API10

#4793 [NUI] fix group remove error.
  src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/GridLayouter.cs
  src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
Labels: Devel-NUI

#4796 [NUI] Add implicit dispose check
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/BaseHandle.cs
Labels: API8

#4790 [NUI] Fix Navigator Insert to keep pages order correctly
  src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
Labels: Devel-NUI

#4799 [Applications.Common] Improve performance
  src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Labels: API11

#4800 [Applications.Common] Improve performance
  src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Labels: API10

#4801 [Applications.Common] Fix race condition issue
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationInfo.cs
Labels: API11

#4803 [Applications.Common] Fix race condition issue
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationInfo.cs
Labels: API10

#4804 [NUI] Fix Navigator to enable multiple Pop()
  src/Tizen.NUI.Components/Controls/Navigation/Navigator.cs
Labels: Devel-NUI

#4805 [NUI] Version update 22204
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#4809 [NUI] FocusIndicator is not used in TV profile so it can be removed to reduce launching delay
  src/Tizen.NUI/src/internal/Application/Application.cs
  src/Tizen.NUI/src/public/Common/StyleManager.cs
Labels: API10

#4813 [NUI] fix for PROFILE_TV to be defined and be applied
  src/Tizen.NUI/Tizen.NUI.csproj
Labels: API10

#4816 [NUI] Not set style in PROFILE_TV
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/Theme/ThemeManager.cs
Labels: API10

#4817 [NUI][API10] Animated view's size cache into NUI
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
Labels: API10

#4811 [NUI][Tizen] Add an API for create,window event.
  src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
  src/Tizen.NUI/src/internal/WebView.cs
Labels: Internal API Changed, API8

#4819 [NUI] Fix WidthSpecification and HeightSpecification not to set Size2D
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
Labels: API10

#4820 [NUI] Fix svace issue (DF221207-00724).
  src/Tizen.NUI/src/public/Window/Window.cs
Labels: API10

#4823 [NUI] make Theme not be loaded in tv profile
  src/Tizen.NUI/Tizen.NUI.csproj
  src/Tizen.NUI/src/internal/Application/Application.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/Input/FocusManager.cs
  src/Tizen.NUI/src/public/Theme/ThemeManager.cs
Labels: API10

#4830 [NUI] Version Update 22205
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#4834 [NUI] fix the defect that the focus of VitualRemote App is stuck very rarely
  src/Tizen.NUI/src/internal/Common/Registry.cs
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
Labels: API10

#4837 Revert "[NUI] fix the defect that the focus of VitualRemote App is stuck very rarely"
  src/Tizen.NUI/src/internal/Common/Registry.cs
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
Labels: API10

#4838 [NUI] fix relative layout to fill regardless of children size.
  src/Tizen.NUI/src/internal/Layouting/RelativeLayout.cs
Labels: Devel-NUI

#4839 [NUI] add ImageUrl property on DefaultGridItem.
  src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultGridItem.cs
  src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultGridItemBindableProperty.cs
Labels: Internal API Changed, Devel-NUI

#4840 [NUI] fix DefaultGridItem image to fill available area.
  src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultGridItem.cs
Labels: Devel-NUI

#4841 [NUI][NUITizenGallery] add Animal ListView and GridView examples
  test/NUITizenGallery/Examples/CollectionViewTest/AnimalGrid.cs
  test/NUITizenGallery/Examples/CollectionViewTest/AnimalGridPage.cs
  test/NUITizenGallery/Examples/CollectionViewTest/AnimalGridPage.xaml
  test/NUITizenGallery/Examples/CollectionViewTest/AnimalList.cs
  test/NUITizenGallery/Examples/CollectionViewTest/AnimalListPage.cs
  test/NUITizenGallery/Examples/CollectionViewTest/AnimalListPage.xaml
  test/NUITizenGallery/Examples/CollectionViewTest/Animals.cs
  test/NUITizenGallery/NUITizenGallery.csproj
  test/NUITizenGallery/res/images/animals/baldeagle.jpg
  test/NUITizenGallery/res/images/animals/bear.jpg
  test/NUITizenGallery/res/images/animals/cat.jpg
  test/NUITizenGallery/res/images/animals/chicken.jpg
  test/NUITizenGallery/res/images/animals/cow.jpg
  test/NUITizenGallery/res/images/animals/deer.jpg
  test/NUITizenGallery/res/images/animals/dog.jpg
  test/NUITizenGallery/res/images/animals/duck.jpg
  test/NUITizenGallery/res/images/animals/elephant.jpg
  test/NUITizenGallery/res/images/animals/emperorpenguin.jpg
  test/NUITizenGallery/res/images/animals/giraffe.jpg
  test/NUITizenGallery/res/images/animals/horse.jpg
  test/NUITizenGallery/res/images/animals/leopard.jpg
  test/NUITizenGallery/res/images/animals/lion.jpg
  test/NUITizenGallery/res/images/animals/panda.jpg
  test/NUITizenGallery/res/images/animals/peacock.jpg
  test/NUITizenGallery/res/images/animals/pig.jpg
  test/NUITizenGallery/res/images/animals/pigeon.jpg
  test/NUITizenGallery/res/images/animals/redfox.jpg
  test/NUITizenGallery/res/images/animals/seagull.jpg
  test/NUITizenGallery/res/images/animals/squirrel.jpg
  test/NUITizenGallery/res/images/animals/tiger.jpg
  test/NUITizenGallery/res/images/animals/wolf.jpg
  test/NUITizenGallery/res/images/animals/zebra.jpg
Labels: Devel-NUI

#4808 Remove unused reference
  src/Tizen.NUI/Tizen.NUI.csproj
Labels: Devel-NUI

#4848 [NUI] Support sub node's Animation
  src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
  src/Tizen.NUI/src/public/Animation/Animation.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
Labels: Internal API Changed, API10

#4849 [NUI] Add ActionsProperty to AlertDialog to support xaml
  src/Tizen.NUI.Components/Controls/AlertDialog.cs
  src/Tizen.NUI.Components/Controls/AlertDialogBindableProperty.cs
  test/NUITizenGallery/Examples/AlertDialogTest/AlertDialogTestDialogPage.xaml
  test/NUITizenGallery/Examples/AlertDialogTest/AlertDialogTestDialogPage.xaml.cs
  test/NUITizenGallery/Examples/AlertDialogTest/AlertDialogTestPage.xaml
  test/NUITizenGallery/Examples/AlertDialogTest/AlertDialogTestPage.xaml.cs
Labels: Internal API Changed, Devel-NUI

#4851 [NUI] Version Update 22206
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#4852 Rebase master to DevelNUI
  README.md
Labels: Devel-NUI

#4853 Rebase develnui
  packaging/csapi-tizenfx.spec
  packaging/version.txt
  src/Tizen.NUI.Components/Controls/AlertDialog.cs
  src/Tizen.NUI.Components/Controls/AlertDialogBindableProperty.cs
  src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultGridItem.cs
  src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultGridItemBindableProperty.cs
  src/Tizen.NUI/Tizen.NUI.csproj
  src/Tizen.NUI/src/internal/Layouting/RelativeLayout.cs
  test/NUITizenGallery/Examples/AlertDialogTest/AlertDialogTestDialogPage.xaml
  test/NUITizenGallery/Examples/AlertDialogTest/AlertDialogTestDialogPage.xaml.cs
  test/NUITizenGallery/Examples/AlertDialogTest/AlertDialogTestPage.xaml
  test/NUITizenGallery/Examples/AlertDialogTest/AlertDialogTestPage.xaml.cs
  test/NUITizenGallery/Examples/CollectionViewTest/AnimalGrid.cs
  test/NUITizenGallery/Examples/CollectionViewTest/AnimalGridPage.cs
  test/NUITizenGallery/Examples/CollectionViewTest/AnimalGridPage.xaml
  test/NUITizenGallery/Examples/CollectionViewTest/AnimalList.cs
  test/NUITizenGallery/Examples/CollectionViewTest/AnimalListPage.cs
  test/NUITizenGallery/Examples/CollectionViewTest/AnimalListPage.xaml
  test/NUITizenGallery/Examples/CollectionViewTest/Animals.cs
  test/NUITizenGallery/NUITizenGallery.csproj
  test/NUITizenGallery/res/images/animals/baldeagle.jpg
  test/NUITizenGallery/res/images/animals/bear.jpg
  test/NUITizenGallery/res/images/animals/cat.jpg
  test/NUITizenGallery/res/images/animals/chicken.jpg
  test/NUITizenGallery/res/images/animals/cow.jpg
  test/NUITizenGallery/res/images/animals/deer.jpg
  test/NUITizenGallery/res/images/animals/dog.jpg
  test/NUITizenGallery/res/images/animals/duck.jpg
  test/NUITizenGallery/res/images/animals/elephant.jpg
  test/NUITizenGallery/res/images/animals/emperorpenguin.jpg
  test/NUITizenGallery/res/images/animals/giraffe.jpg
  test/NUITizenGallery/res/images/animals/horse.jpg
  test/NUITizenGallery/res/images/animals/leopard.jpg
  test/NUITizenGallery/res/images/animals/lion.jpg
  test/NUITizenGallery/res/images/animals/panda.jpg
  test/NUITizenGallery/res/images/animals/peacock.jpg
  test/NUITizenGallery/res/images/animals/pig.jpg
  test/NUITizenGallery/res/images/animals/pigeon.jpg
  test/NUITizenGallery/res/images/animals/redfox.jpg
  test/NUITizenGallery/res/images/animals/seagull.jpg
  test/NUITizenGallery/res/images/animals/squirrel.jpg
  test/NUITizenGallery/res/images/animals/tiger.jpg
  test/NUITizenGallery/res/images/animals/wolf.jpg
  test/NUITizenGallery/res/images/animals/zebra.jpg
Labels: Internal API Changed, API11

#4755 [NUI] Support sub node's Animation
  src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
  src/Tizen.NUI/src/public/Animation/Animation.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
Labels: Internal API Changed, Devel-NUI

#4857 [NUI] dummy patch to raise version up
  packaging/csapi-tizenfx.spec
Labels: API8

#4858 [Camera] Fix bugs for ExtraPreview
  src/Tizen.Multimedia.Camera/Camera/CameraSettings.cs
  src/Tizen.Multimedia.Camera/Interop/Interop.CameraSettings.cs
Labels: Internal API Changed, API10

#4845 [NUI] make BaseHandle.Reset() not work
  src/Tizen.NUI/src/internal/Interop/Interop.BaseHandle.cs
  src/Tizen.NUI/src/public/Common/BaseHandle.cs
Labels: API10

#4846 [NUI] make BaseHandle.Reset() not work
  src/Tizen.NUI/src/internal/Interop/Interop.BaseHandle.cs
  src/Tizen.NUI/src/public/Common/BaseHandle.cs
Labels: Devel-NUI

#4860 [NUI] fix testhub crash issue
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI/src/public/Common/PropertyNotification.cs
  src/Tizen.NUI/src/public/Events/PanGestureDetector.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DisposeWithoutEventUnsubscribedTest.cs
Labels: Internal API Changed, Devel-NUI

#4859 [NUI] fix testhub crash issue
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI/src/public/Common/PropertyNotification.cs
  src/Tizen.NUI/src/public/Events/PanGestureDetector.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DisposeWithoutEventUnsubscribedTest.cs
Labels: Internal API Changed, API10

#4856 [NUI] Support SetProperty by using string name for Animatable
  src/Tizen.NUI/src/public/Animation/Animatable.cs
Labels: Internal API Changed, Devel-NUI

#4865 [NUI] Add GetRenderThreadId() as hidden API
  src/Tizen.NUI/src/internal/Interop/Interop.Application.cs
  src/Tizen.NUI/src/public/Application/NUIApplication.cs
Labels: Internal API Changed, API10

#4863 [NUI][SVACE] Fix svace(DF221214-00106) issue.
  src/Tizen.NUI/src/internal/EXaml/Operation/GatherType.cs
Labels: Devel-NUI

#4864 [NUI][SVACE] Fix svace(DF221214-00106) issue.
  src/Tizen.NUI/src/internal/EXaml/Operation/GatherType.cs
Labels: API10

#4866 [NUI] version update
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#4850 [NUI] Pass SelectionChangedEventArgs by default as SelectionChangedCommandParameter.
  src/Tizen.NUI.Components/Controls/RecyclerView/CollectionView.cs
  test/NUITizenGallery/Examples/CollectionViewTest/AnimalGridPage.xaml
  test/NUITizenGallery/Examples/CollectionViewTest/AnimalListPage.xaml
  test/NUITizenGallery/Examples/CollectionViewTest/Animals.cs
Labels: Devel-NUI

#4862 [NUI] Add EmitScrollStartedEvent and EmitScrollFinishedEvent
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ControlDevel.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
Labels: Internal API Changed, Devel-NUI

#4847 [NUI] Fix FlexLayout OnMeasure to calculate size correctly
  src/Tizen.NUI/src/public/Layouting/FlexLayout.cs
  test/Tizen.NUI.StyleGuide/Examples/DialogAndAlertDialogExample.cs
Labels: Devel-NUI

#4869 [NUI] fix testhub fail, Add Dispose() in BaseHandle.Reset() where the body was deleted in previous patch
  src/Tizen.NUI/src/public/Common/BaseHandle.cs
Labels: API11

#4868 [NUI] fix testhub fail, Add Dispose() in BaseHandle.Reset() where the body was deleted in previous patch
  src/Tizen.NUI/src/public/Common/BaseHandle.cs
Labels: API10

#4870 [NUI] fix testhub fail, Add Dispose() in BaseHandle.Reset() where the body was deleted in previous patch
  src/Tizen.NUI/src/public/Common/BaseHandle.cs
Labels: Devel-NUI

#4872 [Bluetooth] Fix overflow issue
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapterImpl.cs
Labels: API10

#4871 [Bluetooth] Fix overflow issue
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothLeAdapterImpl.cs
Labels: API11

#4876 [NUI][API10] Reorder DeleteBaseHandle and SwigCPtrCopy = null;
  src/Tizen.NUI/src/internal/Interop/Interop.BaseHandle.cs
  src/Tizen.NUI/src/public/Common/BaseHandle.cs
Labels: API10
