Repository Samsung/TizenFX, pull requests merged in 2023-11, with the labels that each got.

#5700 [Build] Fixed an error that could not find the dotnet_resolving.info file
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
Labels: API10

#5701 [Build] Fixed an error that could not find the dotnet_resolving.info file
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
Labels: API11

#5702 [Build] Fixed an error that could not find the dotnet_resolving.info file
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
Labels: API12

#5698 [NUI.WindowSystem] Add SetSecondarySelection and UnsetSecondarySelection to fix typo
  src/Tizen.NUI.WindowSystem/src/public/KVMService.cs
  src/Tizen.NUI/src/public/Clipboard/ClipboardEvent.cs
  test/NUIClipboardDataSelected/ClipboardDataSelected.cs
  test/NUIWindowKVMSample/NUIWindowKVMSample.cs
Labels: Internal API Changed, API11

#5697 [NUI.WindowSystem] Add SetSecondarySelection and UnsetSecondarySelection to fix typo
  src/Tizen.NUI.WindowSystem/src/public/KVMService.cs
  src/Tizen.NUI/src/public/Clipboard/ClipboardEvent.cs
  test/NUIClipboardDataSelected/ClipboardDataSelected.cs
  test/NUIWindowKVMSample/NUIWindowKVMSample.cs
Labels: Internal API Changed, API12

#5671 [MediaController] Fix CustomCommand crash issue
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlCommand.cs
Labels: Internal API Changed, API11

#5707 [NUI] Do not register when BaseHandle doesn't have body
  src/Tizen.NUI/src/internal/Common/Registry.cs
  src/Tizen.NUI/src/public/Common/BaseHandle.cs
Labels: Devel-NUI

#5683 [NUI] Resolve many problems relative with BaseHandle
  src/Tizen.NUI/src/internal/Common/KeyInputFocusManager.cs
  src/Tizen.NUI/src/internal/Common/LinearConstrainer.cs
  src/Tizen.NUI/src/internal/Common/ObjectRegistry.cs
  src/Tizen.NUI/src/internal/Common/PathConstrainer.cs
  src/Tizen.NUI/src/internal/Common/RenderTaskList.cs
  src/Tizen.NUI/src/internal/Utility/Builder.cs
  src/Tizen.NUI/src/public/Accessibility/AccessibilityManager.cs
  src/Tizen.NUI/src/public/Common/PropertyCondition.cs
  src/Tizen.NUI/src/public/Common/PropertyNotification.cs
  src/Tizen.NUI/src/public/Common/StyleManager.cs
  src/Tizen.NUI/src/public/Common/TypeInfo.cs
  src/Tizen.NUI/src/public/Common/TypeRegistry.cs
  src/Tizen.NUI/src/public/Events/Hover.cs
  src/Tizen.NUI/src/public/Events/Touch.cs
  src/Tizen.NUI/src/public/Images/EncodedImageBuffer.cs
  src/Tizen.NUI/src/public/Images/PixelBuffer.cs
  src/Tizen.NUI/src/public/Input/AutofillContainer.cs
  src/Tizen.NUI/src/public/Utility/FontClient.cs
  src/Tizen.NUI/src/public/Utility/TTSPlayer.cs
  src/Tizen.NUI/src/public/Utility/Timer.cs
  src/Tizen.NUI/src/public/Visuals/VisualBase.cs
  src/Tizen.NUI/src/public/Visuals/VisualFactory.cs
  src/Tizen.NUI/src/public/Widget/WidgetView.cs
  src/Tizen.NUI/src/public/Window/Window.cs
Labels: Internal API Changed, Devel-NUI

#5675 [NUI] Remove basehandle usage at Accessibility static
  src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
Labels: Devel-NUI

#5691 [NUI][API10] Make DaliAccessibilityDetachAccessibleObject called at main thread
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Labels: Internal API Changed, API10

#5709 [Build] Create a dotnet library dir from the post script
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
Labels: API10

#5708 [NUI] Add a Window constructor using WindowData
  src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
  src/Tizen.NUI/src/public/Window/Window.cs
Labels: Devel-NUI

#5684 [NUI] Fix some SVACE issues.
  src/Tizen.NUI/src/internal/Layouting/LayoutController.cs
  src/Tizen.NUI/src/public/Window/Window.cs
Labels: Devel-NUI

#5705 [Build] Set the dotnet_core_runtime_version value to 6.0
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
Labels: API11

#5706 [Build] Set the dotnet_core_runtime_version value to 6.0
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
Labels: API12

#5710 [Build] Create a dotnet library dir from the post script
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
Labels: API11

#5711 [Build] Create a dotnet library dir from the post script
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
Labels: API12

#5713 [System] Add power internal APIs
  src/Tizen.System/Device/DeviceEventArgs.cs
  src/Tizen.System/Device/Power.cs
  src/Tizen.System/Interop/Interop.Device.cs
Labels: API10

#5699 [Multimedia] Fix ASAN crash issue
  src/Tizen.Content.MediaContent/Interop/Interop.Libc.cs
  src/Tizen.Content.MediaContent/Interop/Interop.Libraries.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/InteropHelper.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfoCommand.cs
  src/Tizen.Multimedia.Camera/Camera/CameraSettings.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerTrackInfo.cs
  src/Tizen.Multimedia.MediaPlayer/Player/StreamInfo.cs
  src/Tizen.Multimedia.Metadata/Interop/Interop.Libc.cs
  src/Tizen.Multimedia.Metadata/Interop/Interop.Libraries.cs
  src/Tizen.Multimedia.Metadata/MetadataEditor/MetadataEditor.cs
  src/Tizen.Multimedia.Metadata/MetadataExtractor/Metadata.cs
  src/Tizen.Multimedia.Metadata/MetadataExtractor/MetadataExtractor.cs
  src/Tizen.Multimedia.Metadata/MetadataExtractor/MetadataExtractorExtensions.cs
  src/Tizen.Multimedia.Remoting/Interop/Interop.MediaControllerPlaylist.cs
  src/Tizen.Multimedia.Util/ImageUtil/ImageDecoder.cs
  src/Tizen.Multimedia.Util/ImageUtil/ImageEncoder.cs
  src/Tizen.Multimedia.Util/ThumbnailExtractor/ThumbnailExtractor.cs
  src/Tizen.Multimedia.Vision/MediaVision/EngineConfiguration.cs
  src/Tizen.Multimedia.Vision/MediaVision/FaceRecognitionModel.cs
  src/Tizen.Multimedia.Vision/MediaVision/SurveillanceEngine.cs
  src/Tizen.Multimedia/AssemblyAttrs.cs
  src/Tizen.Multimedia/Common.Internal/LibcSupport.cs
  src/Tizen.Multimedia/Interop/Interop.Libc.cs
  src/Tizen.Multimedia/Interop/Interop.Libraries.cs
Labels: API12

#5718 [NUI] version up (22251)
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#5716 [Actions] Update token to fine-grained
  .github/workflows/build-branches.yml
  .github/workflows/nightly-release.yml
  .github/workflows/postback-pull-request.yml
Labels: API12

#5721 [NUI] revert 'Make DaliAccessibilityDetachAccessibleObject called at main thread' and check native object
  src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Labels: API10

#5722 [NUI] revert 'Make DaliAccessibilityDetachAccessibleObject called at main thread' and check native object
  src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Labels: API11

#5723 [NUI] revert 'Make DaliAccessibilityDetachAccessibleObject called at main thread' and check native object
  src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Labels: Devel-NUI

#5724 [NUI] revert 'Make DaliAccessibilityDetachAccessibleObject called at main thread' and check native object
  src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Labels: API12

#5725 [NUI] Add FrontBufferRendering in WindowData
  src/Tizen.NUI/src/internal/Interop/Interop.WindowData.cs
  src/Tizen.NUI/src/public/Application/WindowData.cs
Labels: Devel-NUI

#5714 [System] Add power internal APIs
  src/Tizen.System/Device/DeviceEventArgs.cs
  src/Tizen.System/Device/Power.cs
  src/Tizen.System/Interop/Interop.Device.cs
Labels: API11

#5715 [System] Add power internal APIs
  src/Tizen.System/Device/DeviceEventArgs.cs
  src/Tizen.System/Device/Power.cs
  src/Tizen.System/Interop/Interop.Device.cs
Labels: API12

#5729 [Actions] Fix Deploy to push GitHub Packages
  .github/workflows/deploy-packages.yml
Labels: API12

#5692 [TizenFX] Update nuspec dependencies
  pkg/Tizen.NET/Tizen.NET.nuspec
Labels: API12

#5726 [NUI] Supports to build ModelNode Tree
  src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.ModelNode.cs
  src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
  src/Tizen.NUI.Scene3D/src/public/ModelComponents/ModelNode.cs
  src/Tizen.NUI.Scene3D/src/public/ModelComponents/ModelPrimitive.cs
Labels: Devel-NUI

#5727 [NUI] Support to get Marker list information from lottie
  src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
  src/Tizen.NUI/src/public/Visuals/VisualConstants.cs
Labels: Devel-NUI

#5728 [NUI.XamlBuild] Remove unused event : Element.DescendantAdded / Removed
  src/Tizen.NUI.XamlBuild/src/internal/XamlBinding/Element.cs
  src/Tizen.NUI/src/public/XamlBinding/Element.cs
Labels: Devel-NUI

#5731 [NUI] Support LottieAnimationView file load asynchronously
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
Labels: Devel-NUI

#5734 [NUI] Remove build warning due to unusing API
  src/Tizen.NUI.XamlBuild/src/internal/XamlBinding/Element.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
  src/Tizen.NUI/src/public/XamlBinding/Element.cs
Labels: Devel-NUI

#5735 [NUI] Add Front Buffer Rendering Sample
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowFrontBufferRenderingSample.cs
Labels: Devel-NUI

#5629 [Applications.WidgetControl] Use Marshal.FreeHGlobal() instead of Lib…
  src/Tizen.Applications.Cion/Interop/Interop.Cion.cs
  src/Tizen.Applications.Cion/Interop/Interop.Libraries.cs
  src/Tizen.Applications.Cion/Tizen.Applications.Cion/ServerBase.cs
  src/Tizen.Applications.WidgetControl/Interop/Interop.Libc.cs
  src/Tizen.Applications.WidgetControl/Interop/Interop.Libraries.cs
  src/Tizen.Applications.WidgetControl/Tizen.Applications/WidgetControl.cs
Labels: API12

#5703 [Build] Modify the script that generates the TFM list
  packaging/500.tizenfx_upgrade.sh
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
  packaging/makerid.py
  packaging/makeruntimeversion.py
  packaging/makespec.sh
  packaging/maketfm.py
Labels: API11

#5704 [Build] Modify the script that generates the TFM list
  packaging/500.tizenfx_upgrade.sh
  packaging/csapi-tizenfx.spec
  packaging/csapi-tizenfx.spec.in
  packaging/makerid.py
  packaging/makeruntimeversion.py
  packaging/makespec.sh
  packaging/maketfm.py
Labels: API12

#5737 [NUI] Fix TotalFrame getter bug when async load
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LottieAnimationTest.cs
Labels: Devel-NUI

#5732 [System.Feedback] Change feedback theme api name index to id
  src/Tizen.System.Feedback/Feedback/Feedback.cs
  src/Tizen.System.Feedback/Interop/Interop.Feedback.cs
Labels: API10

#5733 [System.Feedback] Add internal API to support get ids
  src/Tizen.System.Feedback/Feedback/Feedback.cs
  src/Tizen.System.Feedback/Interop/Interop.Feedback.cs
Labels: API10

#5736 [NUI] DetachAccessibleObject at Dispose time well
  src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Labels: Devel-NUI

#5745 [NUI] Change SetMinAndMaxFrameByMarker behavior + Fix some async cases
  src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
Labels: Devel-NUI

#5743 [NUI] Support EncodedImageBuffer ImageType property + Upgrade Encoded…
  src/Tizen.NUI/src/internal/Interop/Interop.EncodedImageBuffer.cs
  src/Tizen.NUI/src/public/Images/EncodedImageBuffer.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/EncodedImageSample.cs
Labels: Devel-NUI

#5739 [System.Feedback] Change feedback theme api name index to id
  src/Tizen.System.Feedback/Feedback/Feedback.cs
  src/Tizen.System.Feedback/Interop/Interop.Feedback.cs
Labels: API11

#5740 [System.Feedback] Add internal API to support get ids
  src/Tizen.System.Feedback/Feedback/Feedback.cs
  src/Tizen.System.Feedback/Interop/Interop.Feedback.cs
Labels: API11

#5741 [System.Feedback] Change feedback theme api name index to id
  src/Tizen.System.Feedback/Feedback/Feedback.cs
  src/Tizen.System.Feedback/Interop/Interop.Feedback.cs
Labels: API12

#5742 [System.Feedback] Add internal API to support get ids
  src/Tizen.System.Feedback/Feedback/Feedback.cs
  src/Tizen.System.Feedback/Interop/Interop.Feedback.cs
Labels: API12

#5746 [NUI] Add AliveCount property to get currently alived View number
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Labels: Devel-NUI

#5744 [NUI.Scene3D] Fix exception when ModelNode don't have ModelNode as child
  src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
  src/Tizen.NUI.Scene3D/src/public/ModelComponents/ModelNode.cs
Labels: Devel-NUI

#5747 [NUI] Remove old frame range if we set marker + Minor fix up when marker invalid
  src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
Labels: Devel-NUI

#5749 [NUI] version up (22252)
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#5730 [Tizen.Network.WiFi] Add set auto scan mode and hidden connect apis
  src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiEnumerations.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
Labels: API10

#5753 [NUI] Add ModelPivotPoint property
  src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
Labels: API10

#5752 [NUI] Add ModelPivotPoint property
  src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
Labels: API11

#5754 [NUI] Add ModelPivotPoint property
  src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
Labels: Devel-NUI

#5755 Revert "[Actions] Update token to fine-grained"
  .github/workflows/build-branches.yml
  .github/workflows/nightly-release.yml
  .github/workflows/postback-pull-request.yml
Labels: API12

#5757 Revert "Deprecating Attach Panel APIs"
  src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/AttachPanel.cs
  src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/ContentCategory.cs
  src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/EventType.cs
  src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/ResultEventArgs.cs
  src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/StateEventArgs.cs
  src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/StateType.cs
Labels: API12

#5758 [Build] Update token used in nightly-release
  .github/workflows/nightly-release.yml
Labels: API12

#5759 [NUI] Fix some SVACE issues.
  src/Tizen.NUI.Components/Controls/RecyclerView/ItemSource/MarshalingObservableCollection.cs
  src/Tizen.NUI.Components/Controls/RecyclerView/ItemSource/ObservableGroupedSource.cs
  src/Tizen.NUI.Components/Controls/RecyclerView/ItemSource/ObservableItemSource.cs
Labels: Devel-NUI

#5760 [NUI] Change the default color of the border.
  src/Tizen.NUI/src/public/Window/DefaultBorder.cs
Labels: Devel-NUI

#5761 Revert "[Build] Update token used in nightly-release"
  .github/workflows/nightly-release.yml
Labels: API12

#5763 [Multimedia] Fix to set window size properly
  src/Tizen.Multimedia.Camera/Camera/Camera.Properties.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
  src/Tizen.Multimedia.Remoting/ScreenMirroring/ScreenMirroring.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaSource.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaStreamTrack.cs
  src/Tizen.Multimedia/Common/Display.cs
Labels: API11

#5764 [Multimedia] Fix to set window size properly
  src/Tizen.Multimedia.Camera/Camera/Camera.Properties.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
  src/Tizen.Multimedia.Remoting/ScreenMirroring/ScreenMirroring.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaSource.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaStreamTrack.cs
  src/Tizen.Multimedia/Common/Display.cs
Labels: API12

#5765 [NUI] Support RootTranslationOnly option for motion capture data
  src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.MotionData.cs
  src/Tizen.NUI.Scene3D/src/public/ModelMotion/MotionData.cs
Labels: Internal API Changed, API10

#5766 [Multimedia] Fix rotation issue for portrait mode
  src/Tizen.Multimedia.Camera/Camera/Camera.Properties.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
  src/Tizen.Multimedia.Remoting/ScreenMirroring/ScreenMirroring.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaSource.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaStreamTrack.cs
  src/Tizen.Multimedia/Common/Display.cs
Labels: API11

#5767 [Multimedia] Fix rotation issue for portrait mode
  src/Tizen.Multimedia.Camera/Camera/Camera.Properties.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
  src/Tizen.Multimedia.Remoting/ScreenMirroring/ScreenMirroring.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaSource.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaStreamTrack.cs
  src/Tizen.Multimedia/Common/Display.cs
Labels: API12

#5769 [NUI] version update (22253)
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#5775 [NUI.Scene3D][API10] Attach matched interop linker for RemoveModelPrimitive
  src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.ModelNode.cs
Labels: API10

#5774 [NUI.Scene3D][API11] Attach matched interop linker for RemoveModelPrimitive
  src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.ModelNode.cs
Labels: API11

#5773 [NUI.Scene3D] Attach matched interop linker for RemoveModelPrimitive
  src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.ModelNode.cs
Labels: Devel-NUI

#5779 NUI version 22300
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#5768 Deprecating Attach Panel APIs
  src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/AttachPanel.cs
  src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/ContentCategory.cs
  src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/EventType.cs
  src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/ResultEventArgs.cs
  src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/StateEventArgs.cs
  src/Tizen.Applications.AttachPanel/Tizen.Applications.AttachPanel/StateType.cs
Labels: ACR Required, API12
