Repository Samsung/TizenFX, pull requests merged in 2024-06, with the labels that each got.

#6151 [NUI] Add align API to InputMethodContext
  src/Tizen.NUI/src/internal/Interop/Interop.InputMethodContext.cs
  src/Tizen.NUI/src/public/Input/InputMethodContext.cs
Labels: Internal API Changed, Devel-NUI

#6150 [NUI] Unregister disposed / disposequeued BaseHandle and register again if need
  src/Tizen.NUI/src/internal/Common/Registry.cs
Labels: Devel-NUI

#6079 [NUI] Implement Visuals.VisualBase feature for View using Visual feature
  src/Tizen.NUI/src/internal/Common/VisualObjectsContainer.cs
  src/Tizen.NUI/src/internal/Interop/Interop.VisualObject.cs
  src/Tizen.NUI/src/internal/Interop/Interop.VisualObjectsContainer.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewVisuals.cs
  src/Tizen.NUI/src/public/Common/PropertyMap.cs
  src/Tizen.NUI/src/public/Visuals/VisualConstants.cs
  src/Tizen.NUI/src/public/Visuals/VisualObject/AdvancedTextVisual.cs
  src/Tizen.NUI/src/public/Visuals/VisualObject/AnimatedImageVisual.cs
  src/Tizen.NUI/src/public/Visuals/VisualObject/BorderVisual.cs
  src/Tizen.NUI/src/public/Visuals/VisualObject/ColorVisual.cs
  src/Tizen.NUI/src/public/Visuals/VisualObject/ImageVisual.cs
  src/Tizen.NUI/src/public/Visuals/VisualObject/NPatchVisual.cs
  src/Tizen.NUI/src/public/Visuals/VisualObject/TextVisual.cs
  src/Tizen.NUI/src/public/Visuals/VisualObject/VisualBase.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VisualTest.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/images/i_focus_stroke_tile_2unit.9.webp
  test/Tizen.NUI.VisualTest/Tizen.NUI.VisualTest.code-workspace
  test/Tizen.NUI.VisualTest/Tizen.NUI.VisualTest.csproj
  test/Tizen.NUI.VisualTest/Tizen.NUI.VisualTest.sln
  test/Tizen.NUI.VisualTest/VisualTest.cs
  test/Tizen.NUI.VisualTest/res/image/gallery-small-1.jpg
  test/Tizen.NUI.VisualTest/shared/res/Tizen.NUI.VisualTest.png
  test/Tizen.NUI.VisualTest/tizen-manifest.xml
Labels: Internal API Changed, Devel-NUI

#6160 [NUI][API11] Fix memory leak when DragAndDrop try to get Position
  src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs
Labels: API11

#6159 [NUI][API10] Fix memory leak when DragAndDrop try to get Position
  src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs
Labels: API10

#6161 [NUI] Fix memory leak when DragAndDrop try to get Position
  src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs
Labels: Devel-NUI

#6152 [TCSACR-584][NUI] Window.Instance is deprecated and Default is newly added
  src/Tizen.NUI/src/internal/Application/Application.cs
  src/Tizen.NUI/src/public/Window/Window.cs
Labels: ACR Required, API12

#6162 [NUI] NUI verson up (nui22327)
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#6163 [TCSACR-584] Window.Instance is deprecated and Default is newly added
  src/Tizen.NUI/src/internal/Application/Application.cs
  src/Tizen.NUI/src/public/Window/Window.cs
Labels: ACR Required, Devel-NUI

#6166 [NUI][API10] Fix worker thread handle removal issue
  src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEvent.cs
Labels: API10

#6167 [NUI][API11] Fix worker thread handle removal issue
  src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEvent.cs
Labels: API11

#6168 [NUI] Fix worker thread handle removal issue
  src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEvent.cs
Labels: Devel-NUI

#6153 [TCSACR-580][NUI] Add WeakEvent and VoiceInteractionName
  src/Tizen.NUI/src/internal/Common/WeakEventProxy.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/Common/WeakEvent.cs
Labels: ACR Required, Internal API Changed, API12

#6170 [Tizen.Network.WiFi] Add set auto scan mode and hidden connect apis
  src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiEnumerations.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
Labels: Internal API Changed, API12

#6171 [Tizen.Network.WiFi] Add set auto scan mode and hidden connect apis
  src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiEnumerations.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
Labels: Internal API Changed, API11

#6173 [NUI] NUI version up(nui22328)
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#6169 [NUI.WindowSystem] Add new API PerformDrop(target) of KVMService
  src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.KVMService.cs
  src/Tizen.NUI.WindowSystem/src/public/KVMService.cs
  test/NUIWindowKVMSample/NUIWindowKVMSample.cs
Labels: Internal API Changed, API12

#6172 [NUI] (CanvasView) Support rasterization request manually + rasteriza…
  src/Tizen.NUI/src/internal/Interop/Interop.CanvasView.cs
  src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/CanvasView.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CanvasViewSample.cs
Labels: Internal API Changed, Devel-NUI

#6176 Update deploy-documents.yml
  .github/workflows/deploy-documents-for-tizen-docs.yml
  .github/workflows/deploy-documents.yml
Labels: API12

#6165 Add BluetoothDevice constructor with remote address
  src/Tizen.Network.Bluetooth/Tizen.Network.Bluetooth/BluetoothDevice.cs
Labels: Internal API Changed, API12

#6185 [NUI] NUI version up(nui22329)
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#6188 [NUI] Remove build warning
  src/Tizen.NUI/src/internal/Utility/ItemViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/AnimatedVectorImageViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/CanvasView.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityEvent.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/Common/WeakEvent.cs
  src/Tizen.NUI/src/public/Utility/AccumulatingVelocityTrackerStrategy.cs
  src/Tizen.NUI/src/public/Utility/VelocityTracker.cs
  src/Tizen.NUI/src/public/Utility/VelocityTrackerStrategy.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/CanvasViewSample.cs
Labels: Devel-NUI

#6190 [NUI] Fix old value checking issue when IsUsingXaml = false
  src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
Labels: API12

#6183 Add ClearCacheProgressChanged EventHandler
  src/Tizen.Applications.PackageManager/Interop/Interop.PackageManager.cs
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManagerClearCacheEventArgs.cs
Labels: Internal API Changed, API12
