Repository Samsung/TizenFX, pull requests merged in 2024-01, with the labels that each got.

#5672 [MediaController] Add new API to check Response request
  src/Tizen.Multimedia.Remoting/MediaController/MediaControlCommand.cs
Labels: ACR Required, Internal API Changed, API12

#5803 [MediaVision] Change feature key of inference face recognition
  src/Tizen.Multimedia.Vision/MediaVision/DeepLearningFaceRecognizer.cs
  src/Tizen.Multimedia.Vision/MediaVision/VisionFeatures.cs
Labels: ACR Required, API11

#5802 [MediaVision] Change feature key of inference face recognition
  src/Tizen.Multimedia.Vision/MediaVision/DeepLearningFaceRecognizer.cs
  src/Tizen.Multimedia.Vision/MediaVision/VisionFeatures.cs
Labels: ACR Required, API12

#5854 [NUI.Scene3D] Add AddLight API
  src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Libraries.cs
  src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.SceneView.cs
  src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
Labels: Internal API Changed, API11

#5852 DevelNUI -> Master integration
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationViewBindableProperty.cs
  src/Tizen.NUI/src/public/Visuals/VisualConstants.cs
Labels: Internal API Changed, API12

#5837 [Metadata] Deprecate MetadataEditor module
  src/Tizen.Multimedia.Metadata/MetadataEditor/MetadataEditor.cs
Labels: ACR Required, API12

#5857 [NUI] Fix text padding issue
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: Devel-NUI

#5858 [NUI] Fix text padding issue
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API11

#5859 [NUI] Fix text padding issue
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
Labels: API10

#5839 [NUI] Fix svace issue of Marshal.Copy
  src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs
Labels: Devel-NUI

#5851 [NUI] Support NativeImageQueue creation with queue count
  src/Tizen.NUI/src/internal/Interop/Interop.NativeImageQueue.cs
  src/Tizen.NUI/src/public/Images/NativeImageQueue.cs
Labels: Internal API Changed, Devel-NUI

#5824 [NUI] Initialize C# items for ProcessorController if required
  src/Tizen.NUI/src/internal/Common/ProcessorController.cs
Labels: Devel-NUI

#5860 [NUI] Do not recreate visual when we change ImageColor only
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
Labels: API11

#5856 [NUI] Do not recreate visual when we change ImageColor only
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageViewBindableProperty.cs
Labels: Devel-NUI

#5862 [NUI.Scene3D] Revert "Add AddLight API"
  src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Libraries.cs
  src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.SceneView.cs
  src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
Labels: API11

#5864 [NUI] Fix some SVACE issues.
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI/src/internal/FrameBroker/FrameBrokerBase.cs
Labels: Devel-NUI

#5865 [NUI] Fix some SVACE issues.
  src/Tizen.NUI.Components/Controls/Slider.cs
  src/Tizen.NUI.Components/Controls/Switch.cs
  src/Tizen.NUI/src/internal/FrameBroker/FrameBrokerBase.cs
Labels: API11

#5850 [MediaContent] Deprecate underutilized fields
  src/Tizen.Content.MediaContent/Interop/Interop.AudioInfo.cs
  src/Tizen.Content.MediaContent/Interop/Interop.MediaInfo.cs
  src/Tizen.Content.MediaContent/Interop/Interop.Tag.cs
  src/Tizen.Content.MediaContent/Interop/Interop.VideoInfo.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/AudioInfo.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/Columns.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfo.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/MediaInfoCommand.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/Tag.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/TagCommand.cs
  src/Tizen.Content.MediaContent/Tizen.Content.MediaContent/VideoInfo.cs
Labels: ACR Required, ACR Accepted, API12

#5867 [NUI] Fix svace issue of Marshal.Copy
  src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs
Labels: API11

#5871 [NUI] Version up 22305.
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#5870 [Tizen.Network.WiFi] Add APIs for multi-scanning
  src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiConfiguration.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
Labels: Internal API Changed, API11

#5872 [Tizen.Network.WiFi] Add APIs for multi-scanning
  src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiConfiguration.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
Labels: Internal API Changed, API12

#5861 [NUI] Add test for new APIs on PropertyMap
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Interop/Interop.PropertyMap.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Interop/Interop.PropertyValue.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Interop/Interop.Vector.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Interop/NDalicPINVOKE.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/PropertyMapSample.cs
Labels: Devel-NUI, API12

#5879 [Actions] Update deploy packages
  .github/workflows/deploy-packages.yml
Labels: API12

#5866 [NUI] Allow to call FrameUpdate callback return value
  src/Tizen.NUI/src/internal/Interop/Interop.FrameUpdateCallbackInterface.cs
  src/Tizen.NUI/src/public/Common/FrameUpdateCallbackInterface.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FrameUpdateCallbackTest.cs
Labels: Internal API Changed, Devel-NUI

#5832 [Tizen.WebView][TCSACR-568] Remove Tizen.WebView
  src/Tizen.WebView/Interop/Interop.ChromiumEwk.BackForwardList.cs
  src/Tizen.WebView/Interop/Interop.ChromiumEwk.Context.cs
  src/Tizen.WebView/Interop/Interop.ChromiumEwk.ContextMenu.cs
  src/Tizen.WebView/Interop/Interop.ChromiumEwk.CookieManager.cs
  src/Tizen.WebView/Interop/Interop.ChromiumEwk.Error.cs
  src/Tizen.WebView/Interop/Interop.ChromiumEwk.InterceptRequest.cs
  src/Tizen.WebView/Interop/Interop.ChromiumEwk.PolicyDecision.cs
  src/Tizen.WebView/Interop/Interop.ChromiumEwk.Settings.cs
  src/Tizen.WebView/Interop/Interop.ChromiumEwk.View.cs
  src/Tizen.WebView/Interop/Interop.ChromiumEwk.cs
  src/Tizen.WebView/Interop/Interop.Eina.cs
  src/Tizen.WebView/Interop/Interop.Elementary.cs
  src/Tizen.WebView/Interop/Interop.Evas.cs
  src/Tizen.WebView/Interop/Interop.Libraries.cs
  src/Tizen.WebView/Tizen.WebView.csproj
  src/Tizen.WebView/Tizen.WebView.sln
  src/Tizen.WebView/Tizen.WebView/BackForwardList.cs
  src/Tizen.WebView/Tizen.WebView/Chromium.cs
  src/Tizen.WebView/Tizen.WebView/Context.cs
  src/Tizen.WebView/Tizen.WebView/ContextMenu.cs
  src/Tizen.WebView/Tizen.WebView/CookieManager.cs
  src/Tizen.WebView/Tizen.WebView/JavaScriptMessage.cs
  src/Tizen.WebView/Tizen.WebView/PolicyDecisionEventArgs.cs
  src/Tizen.WebView/Tizen.WebView/RequestInterceptor.cs
  src/Tizen.WebView/Tizen.WebView/Settings.cs
  src/Tizen.WebView/Tizen.WebView/SmartCallbackArgs.cs
  src/Tizen.WebView/Tizen.WebView/SmartCallbackLoadErrorArgs.cs
  src/Tizen.WebView/Tizen.WebView/WebView.cs
  src/Tizen.WebView/doc/api/Tizen.WebView.md
  test/Tizen.WebView.Test/Properties/AssemblyInfo.cs
  test/Tizen.WebView.Test/SimpleWebviewApp.cs
  test/Tizen.WebView.Test/Tizen.WebView.Test.csproj
  test/Tizen.WebView.Test/Tizen.WebView.Test.project.json
  test/Tizen.WebView.Test/shared/res/Tizen.WebView.Test.png
  test/Tizen.WebView.Test/tizen-manifest.xml
Labels: ACR Required, Internal API Changed, API12

#5883 [NUI] Version up 22306
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#5889 [NUI] Do not check theme applied flag when set ThemeChangeSensitive
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
Labels: API10

#5891 [NUI] Do not check theme applied flag when set ThemeChangeSensitive
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
Labels: API11

#5881 [StreamRecorder] Remove module
  src/Tizen.Multimedia.StreamRecorder/Interop/Interop.Libraries.cs
  src/Tizen.Multimedia.StreamRecorder/Interop/Interop.StreamRecorder.Capabilities.cs
  src/Tizen.Multimedia.StreamRecorder/Interop/Interop.StreamRecorder.Events.cs
  src/Tizen.Multimedia.StreamRecorder/Interop/Interop.StreamRecorder.Settings.cs
  src/Tizen.Multimedia.StreamRecorder/Interop/Interop.StreamRecorder.cs
  src/Tizen.Multimedia.StreamRecorder/StreamRecorder/StreamRecorder.Capabilities.cs
  src/Tizen.Multimedia.StreamRecorder/StreamRecorder/StreamRecorder.Events.cs
  src/Tizen.Multimedia.StreamRecorder/StreamRecorder/StreamRecorder.cs
  src/Tizen.Multimedia.StreamRecorder/StreamRecorder/StreamRecorderAudioOptions.cs
  src/Tizen.Multimedia.StreamRecorder/StreamRecorder/StreamRecorderBufferConsumedEventArgs.cs
  src/Tizen.Multimedia.StreamRecorder/StreamRecorder/StreamRecorderEnums.cs
  src/Tizen.Multimedia.StreamRecorder/StreamRecorder/StreamRecorderError.cs
  src/Tizen.Multimedia.StreamRecorder/StreamRecorder/StreamRecorderErrorOccurredEventArgs.cs
  src/Tizen.Multimedia.StreamRecorder/StreamRecorder/StreamRecorderOptions.cs
  src/Tizen.Multimedia.StreamRecorder/StreamRecorder/StreamRecorderStateChangedEventArgs.cs
  src/Tizen.Multimedia.StreamRecorder/StreamRecorder/StreamRecorderVideoOptions.cs
  src/Tizen.Multimedia.StreamRecorder/Tizen.Multimedia.StreamRecorder.csproj
  src/Tizen.Multimedia.StreamRecorder/Tizen.Multimedia.StreamRecorder.sln
  src/Tizen.Multimedia/AssemblyAttrs.cs
Labels: ACR Required, API12

#5894 [NUI][API10] Create Context/CookieManager when WebView is created.
  src/Tizen.NUI/src/public/WebView/WebView.cs
Labels: API10

#5892 [NUI] Fix some incorrect implements when we get Texture relative items
  src/Tizen.NUI/src/internal/Common/FrameBuffer.cs
  src/Tizen.NUI/src/internal/Transition/TransitionSet.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
  src/Tizen.NUI/src/public/Rendering/Renderer.cs
  src/Tizen.NUI/src/public/Rendering/TextureSet.cs
Labels: Devel-NUI

#5893 [NUI] Add some remarks at BaseHandle class about Dispose
  src/Tizen.NUI/src/public/Common/BaseHandle.cs
Labels: Devel-NUI

#5886 [Packagemanager] Throw an exception when failed to add event listener
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Labels: API12

#5900 [NUI] Support CornerRadius in WebView
  src/Tizen.NUI/src/public/WebView/WebView.cs
Labels: API10

#5901 [NUI][API10] DetachAccessibleObject at Dispose time well
  src/Tizen.NUI/src/internal/Interop/NDalicPINVOKE.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewAccessibility.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Labels: API10

#5898 [NUI.Gadget] Implement Unload() method
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetAssembly.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
Labels: Internal API Changed, API11

#5897 [NUI.Gadget] Implement Unload() method
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetAssembly.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
Labels: Internal API Changed, API12

#5890 [NUI] Do not check theme applied flag when set ThemeChangeSensitive
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
Labels: Devel-NUI

#5903 [NUI] Version up 22307
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#5907 [NUI] Fix LinearLayout to update its child's MeasuredSizeHeight 0 correctly
  src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
Labels: Devel-NUI

#5909 [NUI] Fix LinearLayout to update its child's MeasuredSizeHeight 0 correctly
  src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
Labels: API11

#5908 [NUI] Fix LinearLayout to update its child's MeasuredSizeHeight 0 correctly
  src/Tizen.NUI/src/public/Layouting/LinearLayout.cs
Labels: API10

#5910 [NUI] Fix CollectionView LinearLayout move overlapped issue
  src/Tizen.NUI.Components/Controls/RecyclerView/Layouter/LinearLayouter.cs
Labels: Devel-NUI

#5912 [NUI.Gadget] Modify NUIGadget implementation
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
Labels: API12

#5911 [NUI.Gadget] Modify NUIGadget implementation
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
Labels: API11

#5913 [NUI.Gadget] Change assembly load mothod
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetAssembly.cs
Labels: API11

#5914 [NUI.Gadget] Change assembly load mothod
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetAssembly.cs
Labels: API12

#5918 [NUI.Gadget] Remove Unload() method
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetAssembly.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
Labels: Internal API Changed, API12

#5917 [NUI.Gadget] Remove Unload() method
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetAssembly.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
Labels: Internal API Changed, API11

#5738 [Multimedia] Add a new constructor of Display to remove dependency of UI frameworks
  src/Tizen.Multimedia/Common/Display.cs
  src/Tizen.Multimedia/Common/IWindowProvider.cs
Labels: ACR Required, ACR Accepted, API12

#5919 [NUI] Provide a way to enable legacy DALI StyleManager
  src/Tizen.NUI/src/internal/Common/ViewImpl.cs
  src/Tizen.NUI/src/internal/Common/ViewWrapperImpl.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ImageView.cs
  src/Tizen.NUI/src/internal/Interop/Interop.StyleManager.cs
  src/Tizen.NUI/src/internal/Interop/Interop.View.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ViewImpl.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/Common/StyleManager.cs
Labels: Internal API Changed, API10

#5923 [NUI] Add methods to modify base theme for fhub and fix bugs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/Theme/ThemeManager.cs
  src/Tizen.NUI/src/public/Xaml/MarkupExtensions/SharedResourcePathExtension.cs
Labels: Internal API Changed, API10

#5924 [NUI] Add methods to modify base theme for fhub and fix bugs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/Theme/ThemeManager.cs
  src/Tizen.NUI/src/public/Xaml/MarkupExtensions/SharedResourcePathExtension.cs
Labels: Internal API Changed, API11

#5925 [NUI] Add methods to modify base theme for fhub and fix bugs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/Theme/ThemeManager.cs
  src/Tizen.NUI/src/public/Xaml/MarkupExtensions/SharedResourcePathExtension.cs
Labels: Internal API Changed, Devel-NUI

#5927 [NUI] Support FrameUpdateCallback get world transform
  src/Tizen.NUI/src/internal/Interop/Interop.FrameUpdateCallbackInterface.cs
  src/Tizen.NUI/src/public/Common/FrameUpdateCallbackInterface.cs
Labels: Internal API Changed, API11

#5929 [Packagemanager] Fix SetPackageManagerEventStatus
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Labels: API10

#5930 [Packagemanager] Fix SetPackageManagerEventStatus
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Labels: API11

#5931 [NUI] Version up 22308
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#5928 [Packagemanager] Fix SetPackageManagerEventStatus
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Labels: API12
