Repository Samsung/TizenFX, pull requests merged in 2024-12, with the labels that each got.

#6485 [NUI.Gadget] Modify NUIGadgetAssembly unload logic
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetAssembly.cs
Labels: API12

#6486 [NUI] Block native callback if window is disposed or disposing
  src/Tizen.NUI/src/public/Window/WindowEvent.cs
Labels: Devel-NUI

#6489 [NUI] Block native callback if InputMethodContext is disposed
  src/Tizen.NUI/src/public/Input/InputMethodContext.cs
Labels: API11

#6490 [NUI] Block native callback if InputMethodContext is disposed
  src/Tizen.NUI/src/public/Input/InputMethodContext.cs
Labels: API10

#6492 [NUI] Add Tizen.NUI.OneUI as friend assembly
  src/Tizen.NUI/src/internal/Common/FriendAssembly.cs
Labels: API13

#6493 [NUI] Add Tizen.NUI.OneUI as friend assembly
  src/Tizen.NUI/src/internal/Common/FriendAssembly.cs
Labels: Devel-NUI

#6498 Version Update 22352
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#6495 [Tizen.Applications.RPCPort] Add internal APIs
  src/Tizen.Applications.Common/Interop/Interop.RPCPort.cs
  src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs
Labels: Internal API Changed, API13

#6494 [NUI] Prepare extra space to View to attach objects from external
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Labels: Devel-NUI

#6502 [NUI] Access managed fields only when explicit view disposal
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Labels: Devel-NUI

#6504 [NUI] Remove DynamicProperty callback if URL changed + Make more thread safe enough
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LottieAnimationViewDynamicPropertyTest.cs
Labels: Devel-NUI

#6491 [NUI][API13] Update Tizen.NUI.Samples theme shader to the latest
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/res/style/demo-theme.json
Labels: Devel-NUI

#6506 [NUI][API12] Remove DynamicProperty callback if URL changed + Make more thread safe enough
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LottieAnimationViewDynamicPropertyTest.cs
Labels: API12

#6507 [NUI][API11] Remove DynamicProperty callback if URL changed + Make more thread safe enough
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LottieAnimationViewDynamicPropertyTest.cs
Labels: API11

#6508 [NUI][API10] Remove DynamicProperty callback if URL changed + Make more thread safe enough
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/LottieAnimationViewDynamicPropertyTest.cs
Labels: API10

#6509 [NUI] Version Update
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#6510 main -> DevelNUI
  src/Tizen.Applications.Common/Interop/Interop.RPCPort.cs
  src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs
Labels: Internal API Changed, Devel-NUI

#6512 [NUI] the exception occurring is replaced with an error log
  src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs
Labels: API12, quick review is required

#6513 [NUI] Support PropertyValue set/get without create new Vector2/3/4
  src/Tizen.NUI/src/internal/Interop/Interop.PropertyValue.cs
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
  src/Tizen.NUI/src/public/Common/PropertyValue.cs
Labels: Devel-NUI

#6514 [NUI][API12] Support PropertyValue set/get without create new Vector2/3/4
  src/Tizen.NUI/src/internal/Interop/Interop.PropertyValue.cs
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
  src/Tizen.NUI/src/public/Common/PropertyValue.cs
Labels: API12

#6481 [Network.WiFi] Implement API to get MAC of TDLS connected peer
  src/Tizen.Network.WiFi/Interop/Interop.Libraries.cs
  src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
Labels: Internal API Changed, API13

#6472 [Network.WiFi] Implement API to get MAC of TDLS connected peer
  src/Tizen.Network.WiFi/Interop/Interop.Libraries.cs
  src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
Labels: Internal API Changed, API11

#6480 [Network.WiFi] Implement API to get MAC of TDLS connected peer
  src/Tizen.Network.WiFi/Interop/Interop.Libraries.cs
  src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManager.cs
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiManagerImpl.cs
Labels: Internal API Changed, API12

#6516 [NUI] Add View.OffScreenRendering property
  src/Tizen.NUI/src/internal/Interop/Interop.ViewProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEnum.cs
Labels: Internal API Changed, Devel-NUI

#6518 [NUI] Add WebView FeedMouseWheel as hidden api
  src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
  src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
  src/Tizen.NUI/src/public/WebView/WebView.cs
Labels: Internal API Changed, API12, quick review is required

#6496 [NUI] Notify background change with magic keyword
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
Labels: Devel-NUI

#6523 [NUI] Support RemoveIdle API for NUIApplication + Use unified idler callback
  src/Tizen.NUI/src/internal/Application/Application.cs
  src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
  src/Tizen.NUI/src/public/Application/NUIApplication.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FlushApplicationMessageSample.cs
Labels: Internal API Changed, Devel-NUI

#6524 [NUI][API12] Support RemoveIdle API for NUIApplication + Use unified idler callback
  src/Tizen.NUI/src/internal/Application/Application.cs
  src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
  src/Tizen.NUI/src/public/Application/NUIApplication.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FlushApplicationMessageSample.cs
Labels: Internal API Changed, API12

#6525 [Tizen.Applications] Fix wrong descriptions
  src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
Labels: API13

#6528 [NUI] fix SVACE issue
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
Labels: API12, quick review is required

#6520 [NUI] Create ImageVisual synchronously if AlphaMaskURL use generated ImageUrl
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/Visuals/VisualObject/ImageVisual.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/EncodedImageSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VisualTest.cs
Labels: Internal API Changed, Devel-NUI

#6533 [NUI] Add NUI FLUX friend assembly
  src/Tizen.NUI/src/internal/Common/FriendAssembly.cs
Labels: Devel-NUI, quick review is required

#6534 [Tizen.Applications] Fix wrong description
  src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
Labels: Devel-NUI

#6531 [NUI] BindableObject creates property dictionary on demand
  src/Tizen.NUI/src/public/XamlBinding/BindableObject.cs
Labels: Devel-NUI

#6532 [NUI] Optimize static field of Color class
  src/Tizen.NUI/src/internal/NativeBinding/NDalic.cs
  src/Tizen.NUI/src/public/Application/NUIApplication.cs
  src/Tizen.NUI/src/public/Common/Color.cs
Labels: Devel-NUI

#6530 [NUI] Refactoring ControlState to use bitmask
  src/Tizen.NUI/src/internal/Common/ControlStateUtility.cs
  src/Tizen.NUI/src/public/BaseComponents/ControlState.cs
Labels: Devel-NUI
