Repository Samsung/TizenFX, pull requests merged in 2024-09, with the labels that each got.

#6295 [NUI] Supports window blur with some parameters
  src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
  src/Tizen.NUI/src/internal/Interop/Interop.WindowBlurInfo.cs
  src/Tizen.NUI/src/public/Common/NUIConstants.cs
  src/Tizen.NUI/src/public/Window/Window.cs
  src/Tizen.NUI/src/public/Window/WindowBlurInfo.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowTest1.cs
Labels: Internal API Changed, Devel-NUI

#6288 [NUI] Fix TableView TC fail issue again in proper way
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Labels: Devel-NUI

#6289 [TCSACR-596][NUI] Add missing privilege comments
  src/Tizen.NUI/src/public/Window/Window.cs
Labels: ACR Accepted, Devel-NUI

#6268 [NUI.WindowSystem] introduce the Screensaver service feature
  src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.ScreensaverService.cs
  src/Tizen.NUI.WindowSystem/src/public/ScreensaverService.cs
  test/Tizen.NUI.WindowSystem.Samples/Tizen.NUI.WindowSystem.Samples.cs
Labels: Internal API Changed, API12

#6279 [MediaVision] Deprecate all legacy APIs
  src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Face.cs
  src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Image.cs
  src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Inference.cs
  src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Surveillance.cs
  src/Tizen.Multimedia.Vision/MediaVision/DeepLearningFaceRecognizer.cs
  src/Tizen.Multimedia.Vision/MediaVision/EyeCondition.cs
  src/Tizen.Multimedia.Vision/MediaVision/FaceDetectionConfiguration.cs
  src/Tizen.Multimedia.Vision/MediaVision/FaceDetectionResult.cs
  src/Tizen.Multimedia.Vision/MediaVision/FaceDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/FaceRecognitionConfiguration.cs
  src/Tizen.Multimedia.Vision/MediaVision/FaceRecognitionModel.cs
  src/Tizen.Multimedia.Vision/MediaVision/FaceRecognitionModelType.cs
  src/Tizen.Multimedia.Vision/MediaVision/FaceRecognitionResult.cs
  src/Tizen.Multimedia.Vision/MediaVision/FaceRecognizer.cs
  src/Tizen.Multimedia.Vision/MediaVision/FaceTracker.cs
  src/Tizen.Multimedia.Vision/MediaVision/FaceTrackingModel.cs
  src/Tizen.Multimedia.Vision/MediaVision/FaceTrackingResult.cs
  src/Tizen.Multimedia.Vision/MediaVision/FacialExpression.cs
  src/Tizen.Multimedia.Vision/MediaVision/FacialLandmarkDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/ImageClassificationResult.cs
  src/Tizen.Multimedia.Vision/MediaVision/ImageClassifier.cs
  src/Tizen.Multimedia.Vision/MediaVision/ImageFillConfiguration.cs
  src/Tizen.Multimedia.Vision/MediaVision/ImageObject.cs
  src/Tizen.Multimedia.Vision/MediaVision/ImageRecognitionConfiguration.cs
  src/Tizen.Multimedia.Vision/MediaVision/ImageRecognitionResult.cs
  src/Tizen.Multimedia.Vision/MediaVision/ImageRecognizer.cs
  src/Tizen.Multimedia.Vision/MediaVision/ImageTracker.cs
  src/Tizen.Multimedia.Vision/MediaVision/ImageTrackingConfiguration.cs
  src/Tizen.Multimedia.Vision/MediaVision/ImageTrackingModel.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceModelConfiguration.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceType.cs
  src/Tizen.Multimedia.Vision/MediaVision/MovementDetectedEventArgs.cs
  src/Tizen.Multimedia.Vision/MediaVision/MovementDetectionConfiguration.cs
  src/Tizen.Multimedia.Vision/MediaVision/MovementDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/ObjectDetectionResult.cs
  src/Tizen.Multimedia.Vision/MediaVision/ObjectDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/PersonAppearanceDetectedEventArgs.cs
  src/Tizen.Multimedia.Vision/MediaVision/PersonAppearanceDetectionConfiguration.cs
  src/Tizen.Multimedia.Vision/MediaVision/PersonAppearanceDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/PersonRecognitionConfiguration.cs
  src/Tizen.Multimedia.Vision/MediaVision/PersonRecognitionInfo.cs
  src/Tizen.Multimedia.Vision/MediaVision/PersonRecognizedEventArgs.cs
  src/Tizen.Multimedia.Vision/MediaVision/PersonRecognizer.cs
  src/Tizen.Multimedia.Vision/MediaVision/PoseLandmarkDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/SurveillanceConfiguration.cs
  src/Tizen.Multimedia.Vision/MediaVision/SurveillanceEngine.cs
  src/Tizen.Multimedia.Vision/MediaVision/SurveillanceSource.cs
Labels: ACR Required, API12

#6301 Update deploy documents workflow
  .github/workflows/deploy-documents-for-tizen-docs.yml
  .github/workflows/deploy-documents.yml
Labels: API12

#6304 Update deploy-documents-for-tizen-docs.yml
  .github/workflows/deploy-documents-for-tizen-docs.yml
Labels: API12

#6305 [NUI] Bind FrameUpdateCallback native release API
  src/Tizen.NUI/src/internal/Common/EventThreadCallback.cs
  src/Tizen.NUI/src/internal/Common/ProcessorController.cs
  src/Tizen.NUI/src/internal/Interop/Interop.EventThreadCallback.cs
  src/Tizen.NUI/src/internal/Interop/Interop.FrameUpdateCallbackInterface.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ProcessorController.cs
  src/Tizen.NUI/src/public/Common/FrameUpdateCallbackInterface.cs
Labels: Internal API Changed, Devel-NUI

#6306 Version Update (22339)
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#6312 [Tizen.Applications]Enhancement of API description
  src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
Labels: API12

#6299 [NUI] Add more comments
  src/Tizen.NUI/src/public/Accessibility/Accessibility.cs
  src/Tizen.NUI/src/public/Animation/AlphaFunction.cs
  src/Tizen.NUI/src/public/Animation/Animatable.cs
  src/Tizen.NUI/src/public/Animation/Animation.cs
  src/Tizen.NUI/src/public/Animation/KeyFrames.cs
Labels: Devel-NUI

#6309 [NUI] Add WebAuthDisplayQR and Response for QR code passkey in WebView
  src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
  src/Tizen.NUI/src/internal/WebView/WebViewWebAuthDisplayQREventArgs.cs
  src/Tizen.NUI/src/public/WebView/WebView.cs
Labels: Internal API Changed, API10

#6303 [NUI] Deprecate Dali::Property constructor with componentwise
  src/Tizen.NUI/src/internal/Interop/Interop.Property.cs
  src/Tizen.NUI/src/public/Common/Property.cs
  test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Common/TSProperty.cs
Labels: Devel-NUI

#6314 [NUI] Revert "[NUI] Add WebAuthDisplayQR and Response for QR code passkey in WebView"
  src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
  src/Tizen.NUI/src/internal/WebView/WebViewWebAuthDisplayQREventArgs.cs
  src/Tizen.NUI/src/public/WebView/WebView.cs
Labels: Internal API Changed, API10

#6294 [NUI] Add multi-mimetype feature for Drag and Drop
  src/Tizen.NUI/src/internal/Interop/Interop.DragAndDrop.cs
  src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs
  src/Tizen.NUI/src/public/DragAndDrop/DragEvent.cs
  test/NUIDnDMultiWindow/NUIDnDMultiWindow.cs
  test/NUIDnDSource/NUIDnDSource.cs
Labels: Internal API Changed, Devel-NUI

#6320 [NUI] Add missing IsUsingXaml check to Text
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
Labels: Devel-NUI

#6322 Update deprecated actions
  .github/workflows/build-pull-request.yml
  .github/workflows/deploy-documents-for-tizen-docs.yml
  .github/workflows/deploy-documents.yml
Labels: API12

#6324 Update deprecated actions for DevelNUI
  .github/workflows/build-pull-request.yml
  .github/workflows/deploy-documents-for-tizen-docs.yml
  .github/workflows/deploy-documents.yml
Labels: Devel-NUI

#6321 [NUI] version up (nui22340)
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#6325 [NUI] rebase master
  src/Tizen.Applications.Common/Tizen.Applications/AppControl.cs
Labels: Devel-NUI

#6313 [TCSACR-598][InputMethod] Remove deprecated APIs
  src/Tizen.Uix.InputMethod/Interop/Interop.InputMethod.cs
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod.csproj
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/EditorWindow.cs
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
Labels: ACR Required, API12

#6315 [TCSACR-599][InputMethod] Deprecate RotationChanged event
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/InputMethodEditor.cs
  src/Tizen.Uix.InputMethod/Tizen.Uix.InputMethod/RotationChangedEventArgs.cs
Labels: ACR Required, API12

#6292 [MetadataExtractor] Add a StitchedContent360 metadata API
  src/Tizen.Multimedia.Metadata/MetadataExtractor/Metadata.cs
  src/Tizen.Multimedia.Metadata/MetadataExtractor/MetadataExtractorAttr.cs
Labels: ACR Required, API12

#6329 [AudioManager] Add new SoundEffect APIs
  src/Tizen.Multimedia/AudioManager/AudioStreamPolicy.cs
  src/Tizen.Multimedia/AudioManager/SoundEffect.cs
  src/Tizen.Multimedia/Interop/Interop.StreamPolicy.cs
Labels: ACR Required, ACR Accepted, API12

#6284 [WebRTC] Add descrition and payload APIs
  src/Tizen.Multimedia.Remoting/Interop/Interop.WebRTC.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaSource.cs
  src/Tizen.Multimedia.Remoting/WebRTC/WebRTC.cs
Labels: ACR Required, ACR Accepted, API12

#6298 [NUI] AddPrecompileShader() for precompile shader
  src/Tizen.NUI/src/internal/Interop/Interop.VisualFactory.cs
  src/Tizen.NUI/src/public/Visuals/VisualFactory.cs
Labels: Internal API Changed, Devel-NUI

#6328 [System] Add handling code for internal APIs
  src/Tizen.System/Device/DeviceEventArgs.cs
Labels: ACR Required, Internal API Changed, API12

#6316 [MediaVision] Add new inference APIs
  src/Tizen.Multimedia.Vision/Interop/Interop.Libraries.cs
  src/Tizen.Multimedia.Vision/Interop/Interop.MediaVision.Inference.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceFaceDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceFaceDetectorResult.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceFacialLandmarkDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceFacialLandmarkDetectorResult.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceImageClassifier.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceImageClassifierResult.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceObjectDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceObjectDetectorResult.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferencePoseLandmarkDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferencePoseLandmarkDetectorResult.cs
Labels: ACR Required, API12

#6331 [MediaVision] Check instance is disposed
  src/Tizen.Multimedia.Vision/MediaVision/InferenceFaceDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceFacialLandmarkDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceImageClassifier.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferenceObjectDetector.cs
  src/Tizen.Multimedia.Vision/MediaVision/InferencePoseLandmarkDetector.cs
Labels: API12

#6296 [Tizen.Core] Add new API for providing a new main loop model
  src/Tizen.Core/Interop/Interop.Libraries.cs
  src/Tizen.Core/Interop/Interop.TizenCore.cs
  src/Tizen.Core/Tizen.Core.csproj
  src/Tizen.Core/Tizen.Core.sln
  src/Tizen.Core/Tizen.Core/Channel.cs
  src/Tizen.Core/Tizen.Core/ChannelObject.cs
  src/Tizen.Core/Tizen.Core/ChannelReceivedEventArgs.cs
  src/Tizen.Core/Tizen.Core/ChannelReceiver.cs
  src/Tizen.Core/Tizen.Core/ChannelSender.cs
  src/Tizen.Core/Tizen.Core/Event.cs
  src/Tizen.Core/Tizen.Core/EventObject.cs
  src/Tizen.Core/Tizen.Core/EventReceivedEventArgs.cs
  src/Tizen.Core/Tizen.Core/Log.cs
  src/Tizen.Core/Tizen.Core/Task.cs
  src/Tizen.Core/Tizen.Core/TizenCore.cs
  src/Tizen.Core/doc/api/Tizen.Core.md
Labels: ACR Required, API12

#6333 [Core] Fix a bug about releasing the task
  src/Tizen.Core/Interop/Interop.TizenCore.cs
Labels: API12

#6311 [WebAuthn] Add WebAuthn API
  src/Tizen.Security.WebAuthn/Interop/Interop.Libweabuthn.cs
  src/Tizen.Security.WebAuthn/Interop/Interop.Types.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn.csproj
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn.sln
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticationExtension.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticationSelectionCriteria.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/Authenticator.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticatorAssertionResponse.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticatorAttestationResponse.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticatorStorage.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/ClientData.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/Enums/AttestationPref.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/Enums/AuthenticatorAttachment.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/Enums/AuthenticatorTransport.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/Enums/CoseAlgorithm.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/Enums/HashAlogithm.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/Enums/PubkeyCredHint.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/Enums/PubkeyCredType.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/Enums/ResidentKeyRequirement.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/Enums/UserVerificationRequirement.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/Enums/WauthnError.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/ErrorFactory.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/GetAssertionCallbacks.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/HybridLinkedData.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/MakeCredentialCallbacks.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/NullSafeMarshal.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredAssertion.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredAttestation.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredCreationOptions.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredDescriptor.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredParam.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredRequestOptions.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/RelyingPartyEntity.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/UnmanagedMemory.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/UserEntity.cs
  src/Tizen.Security.WebAuthn/doc/api/Tizen.Security.WebAuthn.md
Labels: ACR Required, API12

#6335 [Tizen.Core] Fix double free issues
  src/Tizen.Core/Tizen.Core/ChannelObject.cs
  src/Tizen.Core/Tizen.Core/Event.cs
  src/Tizen.Core/Tizen.Core/Task.cs
Labels: API12

#6336 [Tizen.Core] Fix memory leak
  src/Tizen.Core/Tizen.Core/ChannelObject.cs
Labels: API12

#6337 [Tizen.Core] Fix managing native handle of Event
  src/Tizen.Core/Tizen.Core/Event.cs
  src/Tizen.Core/Tizen.Core/Task.cs
Labels: API12

#6342 [NUI] Add Outline Offset and BlurRadius at struct Outline
  src/Tizen.NUI/src/public/BaseComponents/TextConstants.cs
  src/Tizen.NUI/src/public/BaseComponents/TextMapHelper.cs
Labels: Internal API Changed, Devel-NUI

#6339 [NUI] Add comments (2nd patch)
  src/Tizen.NUI/src/public/Animation/Path.cs
  src/Tizen.NUI/src/public/Animation/TransitionOptions.cs
  src/Tizen.NUI/src/public/Application/NUIApplication.cs
  src/Tizen.NUI/src/public/Application/NUIWidgetApplication.cs
  src/Tizen.NUI/src/public/ApplicationAnimation/ApplicationTransitionManager.cs
  src/Tizen.NUI/src/public/BaseComponents/CameraView.cs
  src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/Selector.cs
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
  src/Tizen.NUI/src/public/BaseComponents/TableView.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditor.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditorBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
  src/Tizen.NUI/src/public/BaseComponents/TextField.cs
  src/Tizen.NUI/src/public/BaseComponents/TextFieldBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabel.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabelBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/ColorStop.cs
  src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/PathCommands.cs
  src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Picture.cs
  src/Tizen.NUI/src/public/BaseComponents/VectorGraphics/Shape.cs
  src/Tizen.NUI/src/public/BaseComponents/VideoView.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
Labels: Internal API Changed, Devel-NUI

#6348 [Core] Remove wrong descriptions
  src/Tizen.Core/Tizen.Core/Task.cs
Labels: API12

#6351 [NUI.Scene3D] Fix miss used method in SceneView
  src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
Labels: Devel-NUI

#6353 [NUI] Supports window set bottom
  src/Tizen.NUI/src/internal/Interop/Interop.Window.cs
  src/Tizen.NUI/src/public/Window/Window.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/WindowTest1.cs
Labels: Internal API Changed, Devel-NUI

#6345 [NUI] Support ImageView and ImageVisual the SamplingMode
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/Visuals/VisualConstants.cs
  src/Tizen.NUI/src/public/Visuals/VisualObject/ImageVisual.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VisualTest.cs
Labels: Internal API Changed, Devel-NUI

#6347 [WebRTC] Improve documentation
  src/Tizen.Multimedia.Remoting/WebRTC/MediaCameraSource.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaCustomSource.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaFileSource.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaMicrophoneSource.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaNullSource.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaPacketBufferStatusChangedEventArgs.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaPacketSource.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaPacketSourceConfiguration.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaScreenSource.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaStreamTrack.cs
  src/Tizen.Multimedia.Remoting/WebRTC/MediaTestSource.cs
  src/Tizen.Multimedia.Remoting/WebRTC/WebRTC.cs
  src/Tizen.Multimedia.Remoting/WebRTC/WebRTCDataChannelErrorOccurredEventArgs.cs
  src/Tizen.Multimedia.Remoting/WebRTC/WebRTCEnums.cs
  src/Tizen.Multimedia.Remoting/WebRTC/WebRTCFrameEncodedEventArgs.cs
  src/Tizen.Multimedia.Remoting/WebRTC/WebRTCTrackAddedEventArgs.cs
Labels: docs, API12

#6355 [Core] Modify exceptions
  src/Tizen.Core/Tizen.Core/ChannelReceiver.cs
  src/Tizen.Core/Tizen.Core/ChannelSender.cs
  src/Tizen.Core/Tizen.Core/Task.cs
Labels: API12

#6360 [NUI] Version 2.3.42
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#6366 [Applications.Preference] Enhance API descriptions
  src/Tizen.Applications.Preference/Tizen.Applications/Preference.cs
  src/Tizen.Applications.Preference/Tizen.Applications/PreferenceChangedEventArgs.cs
Labels: API12

#6367 [Applications.Common] Enhance API descriptions
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationComponentType.cs
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationLaunchedEventArgs.cs
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationManager.cs
  src/Tizen.Applications.Common/Tizen.Applications/ApplicationRunningContext.cs
  src/Tizen.Applications.Common/Tizen.Applications/Bundle.cs
  src/Tizen.Applications.Common/Tizen.Applications/CoreApplication.cs
Labels: API12

#6319 [TCSACR-602][Shortcut] Deprecate Shortcut apis
  src/Tizen.Applications.Shortcut/Tizen.Applications.Shortcut.csproj
  src/Tizen.Applications.Shortcut/Tizen.Applications.Shortcut/HomeShortcutInfo.cs
  src/Tizen.Applications.Shortcut/Tizen.Applications.Shortcut/ShortcutEnumerations.cs
  src/Tizen.Applications.Shortcut/Tizen.Applications.Shortcut/ShortcutInfo.cs
  src/Tizen.Applications.Shortcut/Tizen.Applications.Shortcut/ShortcutManager.cs
  src/Tizen.Applications.Shortcut/Tizen.Applications.Shortcut/WidgetShortcutInfo.cs
  src/Tizen.Applications.Shortcut/Tizen.Applications.ShortcutEvent/HomeShortcutAddedInfo.cs
  src/Tizen.Applications.Shortcut/Tizen.Applications.ShortcutEvent/ShortcutAddedInfo.cs
  src/Tizen.Applications.Shortcut/Tizen.Applications.ShortcutEvent/ShortcutDeletedInfo.cs
  src/Tizen.Applications.Shortcut/Tizen.Applications.ShortcutEvent/ShortcutEventEnumerations.cs
  src/Tizen.Applications.Shortcut/Tizen.Applications.ShortcutEvent/ShortcutEventManager.cs
  src/Tizen.Applications.Shortcut/Tizen.Applications.ShortcutEvent/ShortcutTemplate.cs
  src/Tizen.Applications.Shortcut/Tizen.Applications.ShortcutEvent/WidgetShortcutAddedInfo.cs
Labels: ACR Required, API12

#6369 [Applications.Service] Enhance API descriptions
  src/Tizen.Applications.Service/Tizen.Applications/ServiceApplication.cs
Labels: API12

#6372 [Content.MimeType] Enhance API descriptions
  src/Tizen.Content.MimeType/Tizen.Content.MimeType/MimeUtil.cs
Labels: API12

#6371 [Applications.UI] Enhance API descriptions
  src/Tizen.Applications.UI/Tizen.Applications/CoreUIApplication.cs
Labels: API12

#6374 [ComponentBased.ComponentManager] Enhance API descriptions
  src/Tizen.Applications.ComponentBased.ComponentManager/Tizen.Applications/ComponentInfo.cs
  src/Tizen.Applications.ComponentBased.ComponentManager/Tizen.Applications/ComponentManager.cs
  src/Tizen.Applications.ComponentBased.ComponentManager/Tizen.Applications/ComponentRunningContext.cs
Labels: API12

#6370 [Applications.RPCPort] Enhance API descriptions
  src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Parcel.cs
  src/Tizen.Applications.Common/Tizen.Applications.RPCPort/Port.cs
  src/Tizen.Applications.Common/Tizen.Applications.RPCPort/ProxyBase.cs
  src/Tizen.Applications.Common/Tizen.Applications.RPCPort/StubBase.cs
Labels: API12

#6377 [System.MediaKey] Enhance API descriptions
  src/Tizen.System.MediaKey/Tizen.System/MediaKey.cs
Labels: API12

#6379 [NUI.Gadget] Export NUIGadgetAssembly class for inhouse developers
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetAssembly.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
Labels: Internal API Changed, API12

#6354 [System.Information] Elaborate API description
  src/Tizen.System.Information/Common/Information.cs
  src/Tizen.System.Information/Usage/ProcessCpuUsage.cs
  src/Tizen.System.Information/Usage/ProcessMemoryUsage.cs
  src/Tizen.System.Information/Usage/SystemCpuUsage.cs
  src/Tizen.System.Information/Usage/SystemMemoryUsage.cs
Labels: API12

#6380 Tizen.Sensor: Update description of sensor class/methods
  src/Tizen.Sensor/Tizen.Sensor/BatchSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/Accelerometer.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/ActivityDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/AutoRotationSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/FaceDownGestureDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/GravitySensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/Gyroscope.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/GyroscopeRotationVectorSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/HeartRateMonitor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/HeartRateMonitorBatch.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/HeartRateMonitorLEDGreenBatch.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/HumiditySensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/InVehicleActivityDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/LightSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/LinearAccelerationSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/Magnetometer.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/MagnetometerRotationVectorSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/OrientationSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/Pedometer.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/PickUpGestureDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/PressureSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/ProximitySensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/RotationVectorSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/RunningActivityDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/SleepMonitor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/StationaryActivityDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/TemperatureSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/UltravioletSensor.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/UncalibratedGyroscope.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/UncalibratedMagnetometer.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/WalkingActivityDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Plugins/WristUpGestureDetector.cs
  src/Tizen.Sensor/Tizen.Sensor/Sensor.cs
Labels: API12

#6384 Tizen.Log: update descriptions of log class/methods
  src/Tizen.Log/Tizen/Log.cs
Labels: API12

#6378 [Tizen.Core] Enhance API descriptions
  src/Tizen.Core/Tizen.Core/Channel.cs
  src/Tizen.Core/Tizen.Core/ChannelObject.cs
  src/Tizen.Core/Tizen.Core/ChannelReceivedEventArgs.cs
  src/Tizen.Core/Tizen.Core/ChannelReceiver.cs
  src/Tizen.Core/Tizen.Core/ChannelSender.cs
  src/Tizen.Core/Tizen.Core/Event.cs
  src/Tizen.Core/Tizen.Core/EventObject.cs
  src/Tizen.Core/Tizen.Core/EventReceivedEventArgs.cs
  src/Tizen.Core/Tizen.Core/Task.cs
Labels: API12

#6381 [NUI] Support Tbm dependency image source
  src/Tizen.NUI/src/internal/Interop/Interop.NativeImageQueue.cs
  src/Tizen.NUI/src/internal/Interop/Interop.NativeImageSource.cs
  src/Tizen.NUI/src/public/Images/NativeImageQueue.cs
  src/Tizen.NUI/src/public/Images/NativeImageSource.cs
  src/Tizen.NUI/src/public/Images/TbmQueueImageSource.cs
  src/Tizen.NUI/src/public/Images/TbmSurfaceImageSource.cs
Labels: Internal API Changed, Devel-NUI

#6375 [NUI.Gadget] Enhance API descriptions
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadget.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetLifecycleChangedEventArgs.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetResourceManager.cs
Labels: Internal API Changed, API12

#6388 Add doxygen for Tizen.System.SystemSettings
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettings.cs
  src/Tizen.System.SystemSettings/Tizen.System.SystemSettings/SystemSettingsEnums.cs
Labels: API12
