Repository Samsung/TizenFX, pull requests merged in 2024-11, with the labels that each got.

#6431 [Tizen.Security.SecureRepository] Add missing documentation descriptions
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Manager.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Pkcs12.cs
Labels: API12

#6437 [WiFi] Fix heap-buffer-use-after-free issue on ASAN
  src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs
Labels: API12

#6418 [NUI] Support Squircle feature : CornerSquareness Property for View and Visual
  src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.SceneView.cs
  src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
  src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/ViewProperty/BackgroundExtraData.cs
  src/Tizen.NUI/src/public/ViewProperty/ShadowBase.cs
  src/Tizen.NUI/src/public/Visuals/VisualConstants.cs
  src/Tizen.NUI/src/public/Visuals/VisualObject/ColorVisual.cs
  src/Tizen.NUI/src/public/Visuals/VisualObject/ImageVisual.cs
  src/Tizen.NUI/src/public/WebView/WebView.cs
  test/NUITizenGallery/Examples/ShadowFrameTest/ShadowFrameTest1Page.xaml
  test/NUITizenGallery/Examples/ShadowFrameTest/ShadowFrameTest1Page.xaml.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/VisualTest.cs
  test/Tizen.NUI.Scene3D.Sample/Scene3DSample.cs
Labels: Internal API Changed, Devel-NUI

#6436 [NUI] Remove build warnings at DragAndDrop + TextConstants
  src/Tizen.NUI/src/public/BaseComponents/TextConstants.cs
  src/Tizen.NUI/src/public/DragAndDrop/DragAndDrop.cs
Labels: Devel-NUI

#6438 [NUI] Version up to 2.3.48
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#6441 [WebAuthn] Enhance code documentation
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticationExtension.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticationSelectionCriteria.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/Authenticator.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticatorAssertionResponse.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticatorAttestationResponse.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/ClientData.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/GetAssertionCallbacks.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/HybridLinkedData.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/MakeCredentialCallbacks.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredAssertion.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredAttestation.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredCreationOptions.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredDescriptor.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredParam.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredRequestOptions.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/RelyingPartyEntity.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/UserEntity.cs
Labels: ACR Required, API12

#6446 Update deprecated actions
  .github/workflows/build-pull-request.yml
  .github/workflows/deploy-documents-for-tizen-docs.yml
  .github/workflows/deploy-documents.yml
Labels: API11

#6449 [NUI] verion up 2.3.49
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#6450 Rebase master NUI version up 2.3.49
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticationExtension.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticationSelectionCriteria.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/Authenticator.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticatorAssertionResponse.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticatorAttestationResponse.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/ClientData.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/GetAssertionCallbacks.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/HybridLinkedData.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/MakeCredentialCallbacks.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredAssertion.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredAttestation.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredCreationOptions.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredDescriptor.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredParam.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/PubkeyCredRequestOptions.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/RelyingPartyEntity.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/UserEntity.cs
Labels: ACR Required, Devel-NUI

#6451 [NUI] Version Update (22349)
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: API12

#6453 [NUI] Ensure UnmanagedType.U1 mark add for bool return type
  src/Tizen.NUI/src/internal/Common/VersionCheck.cs
  src/Tizen.NUI/src/internal/Interop/Interop.DragAndDrop.cs
  src/Tizen.NUI/src/internal/Interop/Interop.NativeImageQueue.cs
  src/Tizen.NUI/src/internal/Interop/Interop.PropertyMap.cs
  src/Tizen.NUI/src/internal/Interop/Interop.VisualFactory.cs
  src/Tizen.NUI/src/internal/Utility/EnvironmentVariable.cs
Labels: Devel-NUI

#6442 Introduce the new InputGesture feature
  src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.InputGesture.cs
  src/Tizen.NUI.WindowSystem/src/public/EdgeDragEventArgs.cs
  src/Tizen.NUI.WindowSystem/src/public/EdgeSwipeEventArgs.cs
  src/Tizen.NUI.WindowSystem/src/public/InputGesture.cs
  src/Tizen.NUI.WindowSystem/src/public/PalmCoverEventArgs.cs
  src/Tizen.NUI.WindowSystem/src/public/TapEventArgs.cs
  test/Tizen.NUI.WindowSystem.InputGesture/Tizen.NUI.WindowSystem.InputGesture.cs
  test/Tizen.NUI.WindowSystem.InputGesture/Tizen.NUI.WindowSystem.InputGesture.csproj
  test/Tizen.NUI.WindowSystem.InputGesture/shared/res/Tizen.NUI.WindowSystem.InputGesture.png
  test/Tizen.NUI.WindowSystem.InputGesture/tizen-manifest.xml
  test/Tizen.NUI.WindowSystem.InputGesture/tizen_dotnet_project.yaml
Labels: Internal API Changed, API12

#6445 Introduce the new InputGesture feature
  src/Tizen.NUI.WindowSystem/src/internal/Interop/Interop.InputGesture.cs
  src/Tizen.NUI.WindowSystem/src/public/EdgeDragEventArgs.cs
  src/Tizen.NUI.WindowSystem/src/public/EdgeSwipeEventArgs.cs
  src/Tizen.NUI.WindowSystem/src/public/InputGesture.cs
  src/Tizen.NUI.WindowSystem/src/public/PalmCoverEventArgs.cs
  src/Tizen.NUI.WindowSystem/src/public/TapEventArgs.cs
  test/Tizen.NUI.WindowSystem.InputGesture/Tizen.NUI.WindowSystem.InputGesture.cs
  test/Tizen.NUI.WindowSystem.InputGesture/Tizen.NUI.WindowSystem.InputGesture.csproj
  test/Tizen.NUI.WindowSystem.InputGesture/shared/res/Tizen.NUI.WindowSystem.InputGesture.png
  test/Tizen.NUI.WindowSystem.InputGesture/tizen-manifest.xml
  test/Tizen.NUI.WindowSystem.InputGesture/tizen_dotnet_project.yaml
Labels: Internal API Changed, API11

#6452 [NUI] Geometry Touch / Gesture Event
  src/Tizen.NUI/src/internal/Interop/Interop.Application.cs
  src/Tizen.NUI/src/internal/Interop/Interop.GestureDetector.cs
  src/Tizen.NUI/src/public/Application/NUIApplication.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
  src/Tizen.NUI/src/public/Events/GestureDetector.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FeedGestureSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FeedNestedPanGestureSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FeedNestedPanGestureSampleVertical.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FeedTapAndLongPressGestureSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/FeedTapAndPanGestureSample.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/GeometryTouchEvent.cs
Labels: Internal API Changed, Devel-NUI

#6454 [NUI.Gadget] Use bin directory
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetAssembly.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
Labels: Internal API Changed, API12

#6330 [Telephony] Reinforce API documents
  src/Tizen.Telephony/Tizen.Telephony/CallHandle.cs
  src/Tizen.Telephony/Tizen.Telephony/ChangeNotificationEventArgs.cs
  src/Tizen.Telephony/Tizen.Telephony/Modem.cs
  src/Tizen.Telephony/Tizen.Telephony/Network.cs
  src/Tizen.Telephony/Tizen.Telephony/Sim.cs
Labels: ACR Required, Stale, API12

#6456 [NUI] Block native callback if view is disposed or disposing
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/TextEditorEvent.cs
  src/Tizen.NUI/src/public/BaseComponents/TextFieldEvent.cs
  src/Tizen.NUI/src/public/BaseComponents/TextLabelEvent.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewEvent.cs
Labels: Devel-NUI

#6457 [NUI] Version Update(22350)
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#6460 [Tizen.System.Device] Add battery power source property
  src/Tizen.System/Device/Battery.cs
  src/Tizen.System/Interop/Interop.Device.cs
Labels: ACR Required, API12

#6461 [Tizen.System.Device] Add battery power source property
  src/Tizen.System/Device/Battery.cs
  src/Tizen.System/Interop/Interop.Device.cs
Labels: ACR Required, API12

#6443 [Tizen.Applications.Alarm] Enhance API descriptions
  src/Tizen.Applications.Alarm/Tizen.Applications/Alarm.cs
  src/Tizen.Applications.Alarm/Tizen.Applications/AlarmManager.cs
Labels: API12

#6358 [Packagemanager] Enhance API descriptions
  src/Tizen.Applications.PackageManager/Tizen.Applications/PackageManager.cs
Labels: API12

#6447 [Applications.Alarm] Add an internal API
  src/Tizen.Applications.Alarm/Interop/Interop.Alarm.cs
  src/Tizen.Applications.Alarm/Tizen.Applications/AlarmManager.cs
Labels: Internal API Changed, API12

#6419 [NUI] Remove the legacy code of AccessibilityManager
  src/Tizen.NUI.Components/Controls/Button.Internal.cs
  src/Tizen.NUI.Components/Controls/Loading.cs
  src/Tizen.NUI.Components/Controls/RecyclerView/Item/DefaultTitleItem.cs
  src/Tizen.NUI.Components/Controls/RecyclerView/Item/RecyclerViewItem.Internal.cs
  src/Tizen.NUI.Components/Controls/ScrollableBase.cs
  src/Tizen.NUI/src/internal/Accessibility/AccessibilityActionSignal.cs
  src/Tizen.NUI/src/internal/Accessibility/AccessibilityFocusOvershotSignal.cs
  src/Tizen.NUI/src/internal/Common/ViewImpl.cs
  src/Tizen.NUI/src/internal/Common/ViewWrapperImpl.cs
  src/Tizen.NUI/src/internal/Interop/Interop.AccessibilityManager.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ViewImplSignal.cs
  src/Tizen.NUI/src/internal/NativeBinding/SWIGTYPE_p_Dali__SignalT_bool_fDali__Toolkit__AccessibilityManager_R_Dali__TouchEvent_const_RF_t.cs
  src/Tizen.NUI/src/public/Accessibility/AccessibilityManager.cs
  src/Tizen.NUI/src/public/Accessibility/AccessibilityManagerEvent.cs
  src/Tizen.NUI/src/public/Accessibility/AccessibilityManagerEventArgs.cs
  src/Tizen.NUI/src/public/BaseComponents/CustomView.cs
  src/Tizen.NUI/src/public/CustomView/ViewWrapper.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/AccessibilityManagerSample.cs
  test/Tizen.NUI.Tests/Tizen.NUI.Components.Devel.Tests/testcase/Controls/TSScrollableBase.cs
  test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Accessibility/TSAccessibilityActionSignal.cs
  test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Accessibility/TSAccessibilityFocusOvershotSignal.cs
  test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/internal/Common/TSViewImpl.cs
  test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Accessibility/TSAccessibilityManager.cs
  test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Accessibility/TSAccessibilityManagerEvent.cs
  test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/Accessibility/TSAccessibilityManagerEventArgs.cs
  test/Tizen.NUI.Tests/Tizen.NUI.Devel.Tests/testcase/public/BaseComponents/TSCustomView.cs
Labels: Internal API Changed, Devel-NUI

#6455 [WiFi] Fix heap-buffer-use-after-free issue on ASAN
  src/Tizen.Network.WiFi/Interop/Interop.WiFi.cs
Labels: API12

#6464 [NUI] Add APIs for setting IME position, cursor theme name.
  src/Tizen.NUI/src/internal/Interop/Interop.WebSettings.cs
  src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
  src/Tizen.NUI/src/internal/WebView/WebSettings.cs
  src/Tizen.NUI/src/public/WebView/WebView.cs
Labels: Internal API Changed, API12

#6463 [NUI] Add APIs for setting IME position, cursor theme name.
  src/Tizen.NUI/src/internal/Interop/Interop.WebSettings.cs
  src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
  src/Tizen.NUI/src/internal/WebView/WebSettings.cs
  src/Tizen.NUI/src/public/WebView/WebView.cs
Labels: Internal API Changed

#6467 [NUI] Version Update(22351)
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#6473 [NUI] Match ViewImpl Connector parameter with csharp binder
  src/Tizen.NUI/src/internal/Common/ViewImpl.cs
  src/Tizen.NUI/src/internal/Common/ViewWrapperImpl.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ViewImpl.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ViewWrapperImpl.cs
Labels: Devel-NUI

#6475 [NUI] Match ViewImpl Connector parameter with csharp binder
  src/Tizen.NUI/src/internal/Common/ViewImpl.cs
  src/Tizen.NUI/src/internal/Common/ViewWrapperImpl.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ViewImpl.cs
  src/Tizen.NUI/src/internal/Interop/Interop.ViewWrapperImpl.cs
Labels: API12

#6482 Update actions for main branch
  .github/workflows/build-branches.yml
  .github/workflows/build-pull-request.yml
  .github/workflows/check-api-level.yml
  .github/workflows/deploy-packages.yml
  .github/workflows/nightly-release.yml
Labels: API13
