Repository Samsung/TizenFX, pull requests merged in 2024-10, with the labels that each got.

#6392 [WebRTC] Fix DataChannel event bug
  src/Tizen.Multimedia.Remoting/WebRTC/WebRTCDataChannel.Events.cs
  src/Tizen.Multimedia.Remoting/WebRTC/WebRTCDataChannel.cs
Labels: API12

#6357 [MediaPlayer] Improve documentation
  src/Tizen.Multimedia.MediaPlayer/Player/AdaptiveVariants.cs
  src/Tizen.Multimedia.MediaPlayer/Player/AudioDataDecodedEventArgs.cs
  src/Tizen.Multimedia.MediaPlayer/Player/AudioEffect.cs
  src/Tizen.Multimedia.MediaPlayer/Player/AudioOffload.cs
  src/Tizen.Multimedia.MediaPlayer/Player/EqualizerBand.cs
  src/Tizen.Multimedia.MediaPlayer/Player/MediaBufferSource.cs
  src/Tizen.Multimedia.MediaPlayer/Player/MediaStreamBufferStatusChangedEventArgs.cs
  src/Tizen.Multimedia.MediaPlayer/Player/MediaStreamConfiguration.cs
  src/Tizen.Multimedia.MediaPlayer/Player/MediaStreamSeekingOccurredEventArgs.cs
  src/Tizen.Multimedia.MediaPlayer/Player/MediaStreamSource.cs
  src/Tizen.Multimedia.MediaPlayer/Player/MediaUriSource.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlaybackInterruptedEventArgs.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.Properties.cs
  src/Tizen.Multimedia.MediaPlayer/Player/Player.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerDisplaySettings.cs
  src/Tizen.Multimedia.MediaPlayer/Player/PlayerEnums.cs
  src/Tizen.Multimedia.MediaPlayer/Player/SubtitleUpdatedEventArgs.cs
  src/Tizen.Multimedia.MediaPlayer/Player/VideoFrameDecodedEventArgs.cs
Labels: docs, API12

#6310 [NUI] Add WebAuthDisplayQR, Response and MediaPermission
  src/Tizen.NUI/src/internal/Interop/Interop.WebUserMediaPermissionRequest.cs
  src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
  src/Tizen.NUI/src/internal/WebView/WebUserMediaPermissionRequest.cs
  src/Tizen.NUI/src/internal/WebView/WebViewUserMediaPermissionRequestEventArgs.cs
  src/Tizen.NUI/src/internal/WebView/WebViewWebAuthDisplayQREventArgs.cs
  src/Tizen.NUI/src/public/WebView/WebView.cs
Labels: Internal API Changed, Devel-NUI

#6391 [Notification] Add PairingType for do not disturb app
  src/Tizen.Applications.Notification/Interop/Interop.Notification.cs
  src/Tizen.Applications.Notification/Tizen.Applications.Notifications/Notification.cs
  src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationBinder.cs
  src/Tizen.Applications.Notification/Tizen.Applications.Notifications/NotificationManager.cs
Labels: Internal API Changed, API12

#6394 [Notification] fix notification when pairing type is set
  src/Tizen.Applications.Notification/Tizen.Applications.Notifications/Notification.cs
  src/Tizen.Applications.NotificationEventListener/Tizen.Applications.NotificationEventListener/NotificationEventArgsBinder.cs
Labels: API12

#6395 [AudioIO] Add new internal API for play audio with repetitions
  src/Tizen.Multimedia.AudioIO/Interop/Interop.WavPlayer.cs
  src/Tizen.Multimedia.AudioIO/WavPlayer/WavPlayer.cs
Labels: Internal API Changed, API12

#6396 [NUI] Add WidgetComponent for ComponentBasedApplication
  src/Tizen.NUI/src/internal/Common/NUIWindowProxy.cs
  src/Tizen.NUI/src/public/Application/NUIComponentApplication.cs
  src/Tizen.NUI/src/public/Application/NUIWidgetComponent.cs
  test/Tizen.NUI.WidgetViewTest/4.WidgetComponentTest/NUIWidgetComponentApplication/NUIWidgetComponentApplication.cs
  test/Tizen.NUI.WidgetViewTest/4.WidgetComponentTest/NUIWidgetComponentApplication/NUIWidgetComponentApplication.csproj
  test/Tizen.NUI.WidgetViewTest/4.WidgetComponentTest/NUIWidgetComponentApplication/shared/res/NUIWidgetComponentApplication.png
  test/Tizen.NUI.WidgetViewTest/4.WidgetComponentTest/NUIWidgetComponentApplication/tizen-manifest.xml
  test/Tizen.NUI.WidgetViewTest/4.WidgetComponentTest/Tizen.NUI.WidgetViewTest/SimpleWidgetViewApp.cs
  test/Tizen.NUI.WidgetViewTest/4.WidgetComponentTest/Tizen.NUI.WidgetViewTest/Tizen.NUI.WidgetViewTest.csproj
  test/Tizen.NUI.WidgetViewTest/4.WidgetComponentTest/Tizen.NUI.WidgetViewTest/Tizen.NUI.WidgetViewTest.sln
  test/Tizen.NUI.WidgetViewTest/4.WidgetComponentTest/Tizen.NUI.WidgetViewTest/shared/res/Tizen.NUI.WidgetViewTest.png
  test/Tizen.NUI.WidgetViewTest/4.WidgetComponentTest/Tizen.NUI.WidgetViewTest/tizen-manifest.xml
Labels: Internal API Changed, Devel-NUI

#6398 [NUI] Version 2.3.44
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#6382 [NUI.Scene3D] Support SceneView CornerRadius and Borderline Property applied
  src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.SceneView.cs
  src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/WebView/WebView.cs
  test/Tizen.NUI.Scene3D.Sample/Scene3DSample.cs
Labels: Internal API Changed, Devel-NUI

#6397 [Tizen.Network.WiFi] Fix heap-use-after-free issue on ASAN image
  src/Tizen.Network.WiFi/Tizen.Network.WiFi/WiFiConfiguration.cs
Labels: API12

#6403 [NUI] Revert ApplyCornerRadius access level as internal
  src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/WebView/WebView.cs
Labels: Internal API Changed, Devel-NUI

#6404 [NUI] Revert ApplyCornerRadius access level as internal
  src/Tizen.NUI.Scene3D/src/public/Controls/SceneView.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/WebView/WebView.cs
Labels: Internal API Changed, API12

#6406 [NUI] Add WebAuthDisplayQR and Response for QR code passkey in WebView
  src/Tizen.NUI/src/internal/Interop/Interop.WebView.cs
  src/Tizen.NUI/src/internal/WebView/WebViewWebAuthDisplayQREventArgs.cs
  src/Tizen.NUI/src/public/WebView/WebView.cs
Labels: Internal API Changed, API10

#6352 [AudioManager] Improve documentation
  src/Tizen.Multimedia/AudioManager/AudioDevice.cs
  src/Tizen.Multimedia/AudioManager/AudioDeviceConnectionChangedEventArgs.cs
  src/Tizen.Multimedia/AudioManager/AudioDeviceIoDirection.cs
  src/Tizen.Multimedia/AudioManager/AudioDeviceRunningChangedEventArgs.cs
  src/Tizen.Multimedia/AudioManager/AudioDeviceType.cs
  src/Tizen.Multimedia/AudioManager/AudioDucking.cs
  src/Tizen.Multimedia/AudioManager/AudioDuckingStateChangedEventArgs.cs
  src/Tizen.Multimedia/AudioManager/AudioManager.cs
  src/Tizen.Multimedia/AudioManager/AudioPolicyException.cs
  src/Tizen.Multimedia/AudioManager/AudioSampleFormat.cs
  src/Tizen.Multimedia/AudioManager/AudioStreamBehaviors.cs
  src/Tizen.Multimedia/AudioManager/AudioStreamFocusChangedReason.cs
  src/Tizen.Multimedia/AudioManager/AudioStreamFocusOptions.cs
  src/Tizen.Multimedia/AudioManager/AudioStreamFocusState.cs
  src/Tizen.Multimedia/AudioManager/AudioStreamPolicy.cs
  src/Tizen.Multimedia/AudioManager/SoundEffect.cs
Labels: API12

#6402 Deprecating Tizen.Account.SyncManager CancelSyncCallback() API
  src/Tizen.Account.SyncManager/Tizen.Account.SyncManager/SyncAdapter.cs
Labels: ACR Required, API12

#6409 [NUI] Add remove WebContext callbacks when disposed
  src/Tizen.NUI/src/internal/WebView/WebContext.cs
  src/Tizen.NUI/src/public/WebView/WebView.cs
Labels: Devel-NUI

#6410 [NUI] Fix SVACE issues
  src/Tizen.NUI/src/internal/Common/EnumHelper.cs
  src/Tizen.NUI/src/internal/EXaml/Operation/AddToDictionary.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
  src/Tizen.NUI/src/public/CustomView/CustomViewRegistry.cs
Labels: Devel-NUI

#6413 [NUI] Fix Animation issue for Background and BoxShadow color
  src/Tizen.NUI/src/internal/Common/PropertyHelper.cs
Labels: Devel-NUI

#6414 [NUI] Version up to 2.3.45
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#6346 [Tizen.Security.SecureRepository] Enhancements of API description
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Certificate.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/CertificateManager.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/AesCbcCipherParameters.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/AesCfbCipherParameters.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/AesCipherParameters.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/AesCtrCipherParameters.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/AesGcmCipherParameters.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/Cipher.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/CipherAlgorithmType.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/CipherParameterName.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/CipherParameters.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/DsaSignatureParameters.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/EcdsaSignatureParameters.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/HashAlgorithm.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/RsaOaepCipherParameters.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/RsaSignatureParameters.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/Signature.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/SignatureAlgorithmType.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/SignatureParameterName.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Crypto/SignatureParameters.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/DataFormat.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/DataManager.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/EllipticCurveType.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Key.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/KeyManager.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/KeyType.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Manager.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/OcspStatus.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Pkcs12.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Pkcs12Manager.cs
  src/Tizen.Security.SecureRepository/Tizen.Security.SecureRepository/Policy.cs
Labels: API12

#6420 Revert "Deprecating Tizen.Account.SyncManager CancelSyncCallback() API"
  src/Tizen.Account.SyncManager/Tizen.Account.SyncManager/SyncAdapter.cs
Labels: ACR Required, API12

#6344 [Tizen.Security] Enhancements of API description
  src/Tizen.Security/Tizen.Security/Privilege.cs
Labels: API12

#6389 [WebAuthn] Enable concurrent Authenticator requests where supported by the native API
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn.csproj
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/Authenticator.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticatorAssertionResponse.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticatorGetAssertionStorage.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticatorMakeCredentialStorage.cs
  src/Tizen.Security.WebAuthn/Tizen.Security.WebAuthn/AuthenticatorStorage.cs
Labels: API12

#6417 [NUI.Gadget] Modify loading assembly of NUIGadget
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetAssembly.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetManager.cs
Labels: Internal API Changed, API12

#6427 [NUI.Gadget] Fix a description typo
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
Labels: API12

#6408 [Network.WiFiDirect] Implement API for creating group with SSID
  src/Tizen.Network.WiFiDirect/Interop/Interop.WiFiDirect.cs
  src/Tizen.Network.WiFiDirect/Tizen.Network.WiFiDirect/WiFiDirectManager.cs
  src/Tizen.Network.WiFiDirect/Tizen.Network.WiFiDirect/WiFiDirectManagerImpl.cs
Labels: Internal API Changed, API12

#6426 [NUI] Relocate RenderEffect files
  src/Tizen.NUI/src/internal/Interop/Interop.BackgroundBlurEffect.cs
  src/Tizen.NUI/src/internal/Interop/Interop.RenderEffect.cs
  src/Tizen.NUI/src/public/RenderEffects/RenderEffect.cs
  src/Tizen.NUI/src/public/Utility/RenderEffect.cs
Labels: Devel-NUI

#6430 [Tizen.NUI.Gadget] Change visibility of the NUIGadgetInfo.Assembly to public
  src/Tizen.NUI.Gadget/Tizen.NUI/NUIGadgetInfo.cs
Labels: Internal API Changed, API12

#6429 [NUI] Modified the WebView to hold the instances of WebContext and WebCookieManager
  src/Tizen.NUI/src/public/WebView/WebView.cs
Labels: Devel-NUI

#6432 [NUI] Version up to 2.3.47
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI
