Repository Samsung/TizenFX, pull requests merged in 2024-03, with the labels that each got.

#5982 [NUI] Fix SVACE issue
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
Labels: Devel-NUI

#5983 [NoACR][MachineLearning.Inference] Fix bug using wrong handle
  src/Tizen.MachineLearning.Inference/Tizen.MachineLearning.Inference/TensorsData.cs
Labels: API11

#5974 [NUI] Fix SVACE issue of null in ViewStyle.
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
Labels: API11

#5984 [NUI] Version up 22313
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#5990 [NUI] Version up 22314
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#5991 [NUI] Version up 22314
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: API12

#5987 [NUI.Scene3D] Add CastShadow and ReceiveShadow for Model and ModelNode
  src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.Model.cs
  src/Tizen.NUI.Scene3D/src/internal/Interop/Interop.ModelNode.cs
  src/Tizen.NUI.Scene3D/src/public/Controls/Model.cs
  src/Tizen.NUI.Scene3D/src/public/ModelComponents/ModelNode.cs
Labels: Internal API Changed, Devel-NUI

#5989 [NUI] Add State property of NUIApplication
  src/Tizen.NUI/src/public/Application/NUIApplication.cs
Labels: Internal API Changed, Devel-NUI

#5977 [NUI] Do not remove once event when ImageView is dispose
  src/Tizen.NUI/src/public/BaseComponents/AnimatedImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/ImageView.cs
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewInternal.cs
Labels: Devel-NUI

#5969 [NUI] Make DisposeRecursively() full search of children list even if Disposed
  src/Tizen.NUI/src/public/Common/Container.cs
Labels: Devel-NUI

#5963 [NUI] Unified native singletone class instance getter
  src/Tizen.NUI/src/internal/Common/KeyInputFocusManager.cs
  src/Tizen.NUI/src/public/Accessibility/AccessibilityManager.cs
  src/Tizen.NUI/src/public/Clipboard/Clipboard.cs
  src/Tizen.NUI/src/public/Common/StyleManager.cs
  src/Tizen.NUI/src/public/Common/TypeRegistry.cs
  src/Tizen.NUI/src/public/Input/FocusManager.cs
  src/Tizen.NUI/src/public/Utility/FontClient.cs
  src/Tizen.NUI/src/public/Utility/TTSPlayer.cs
  src/Tizen.NUI/src/public/Visuals/VisualFactory.cs
Labels: Internal API Changed, Devel-NUI

#5965 [NUI] Resolve the potential issue when DisposeQueued handle get
  src/Tizen.NUI/src/internal/Common/Registry.cs
Labels: Devel-NUI

#5996 [NUI.Scene3D] Add Rotation constructor using pitch,yaw,roll
  src/Tizen.NUI/src/internal/Interop/Interop.Rotation.cs
  src/Tizen.NUI/src/public/Common/Rotation.cs
Labels: Internal API Changed, API10

#5997 [NUI][API10] Fix some incorrect implements when we get Texture relative items
  src/Tizen.NUI/src/internal/Common/FrameBuffer.cs
  src/Tizen.NUI/src/internal/Transition/TransitionSet.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
  src/Tizen.NUI/src/public/Rendering/Renderer.cs
  src/Tizen.NUI/src/public/Rendering/TextureSet.cs
Labels: API10

#5998 [NUI] WeakEvent : Improve clean-up condition
  src/Tizen.NUI/src/internal/Common/WeakEvent.cs
Labels: Devel-NUI

#5999 [NUI] WeakEvent : Improve clean-up condition
  src/Tizen.NUI/src/internal/Common/WeakEvent.cs
Labels: API10

#6000 [NUI] WeakEvent : Improve clean-up condition
  src/Tizen.NUI/src/internal/Common/WeakEvent.cs
Labels: API11

#6003 [NUI][API11] Fix some memory leak codes what already fixed at API12
  src/Tizen.NUI.Wearable/src/public/Title.cs
  src/Tizen.NUI/src/internal/Common/FrameBuffer.cs
  src/Tizen.NUI/src/internal/FrameBroker/FrameBrokerBase.cs
  src/Tizen.NUI/src/internal/Transition/TransitionSet.cs
  src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewPublicMethods.cs
  src/Tizen.NUI/src/public/Common/BaseHandle.cs
  src/Tizen.NUI/src/public/Rendering/Renderer.cs
  src/Tizen.NUI/src/public/Rendering/TextureSet.cs
  src/Tizen.NUI/src/public/Rendering/VertexBuffer.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DisposeTest.cs
Labels: API11

#6004 [NUI][API10] Fix some memory leak codes what already fixed at API12
  src/Tizen.NUI.Wearable/src/public/Title.cs
  src/Tizen.NUI/src/internal/FrameBroker/FrameBrokerBase.cs
  src/Tizen.NUI/src/public/BaseComponents/DirectRenderingGLView.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewAccessibilityWrappers.cs
  src/Tizen.NUI/src/public/Common/BaseHandle.cs
  src/Tizen.NUI/src/public/Rendering/VertexBuffer.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DisposeTest.cs
Labels: API10

#6005 [NUI] Add IsUsingXaml
  src/Tizen.NUI/src/internal/Application/NUICoreBackend.cs
  src/Tizen.NUI/src/public/Application/NUIApplication.cs
  src/Tizen.NUI/src/public/BaseComponents/View.cs
  src/Tizen.NUI/src/public/BaseComponents/ViewBindableProperty.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/DaliDemo/DaliDemo.cs
  test/Tizen.NUI.Samples/Tizen.NUI.Samples/Samples/IsUsingXamlTest.cs
Labels: Internal API Changed, API11

#6006 [NUI] Move WeakEvent to public and remove unused WeakEventHandler class
  src/Tizen.NUI/src/internal/Common/WeakEventHandler.cs
  src/Tizen.NUI/src/public/Common/WeakEvent.cs
Labels: Internal API Changed, API11

#6008 [NUI][API10] Fix SVACE issue (ViewStyle.cs CopyFrom null check)
  src/Tizen.NUI/src/public/BaseComponents/Style/ViewStyle.cs
Labels: API10

#6010 [NUI] Version up 22315
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#6013 [NUI] WeakEvent : Modify invoke param type
  src/Tizen.NUI/src/public/Common/WeakEvent.cs
Labels: Internal API Changed, API11

#6016 [NUI] Version up 22316
  packaging/csapi-tizenfx.spec
  packaging/version.txt
Labels: Devel-NUI

#6018 [NUI] change Tizen.NUI.State as Tizen.NUI.NUIApplication.States because it is NUIApplication state
  src/Tizen.NUI/src/public/Application/NUIApplication.cs
Labels: Internal API Changed, API12

#6014 Add Tizen.AIAvatar project
  src/Tizen.AIAvatar/Tizen.AIAvatar.csproj
  src/Tizen.AIAvatar/src/Extensions/AvatarExtension.cs
  src/Tizen.AIAvatar/src/Extensions/AvatarScene.cs
  src/Tizen.AIAvatar/src/Extensions/SceneViewExtension.cs
  src/Tizen.AIAvatar/src/internal/Avatar/AIAvatar.cs
  src/Tizen.AIAvatar/src/internal/Avatar/Interop.SceneView.cs
  src/Tizen.AIAvatar/src/internal/Avatar/Utils.cs
  src/Tizen.AIAvatar/src/internal/BlendShapeInfo/BlendShapeInfo.cs
  src/Tizen.AIAvatar/src/internal/BlendShapeInfo/BlendShapeModelInfo.cs
  src/Tizen.AIAvatar/src/internal/BlendShapeInfo/BlendShapeValue.cs
  src/Tizen.AIAvatar/src/internal/BlendShapeInfo/BlendShapeVisemeInfo.cs
  src/Tizen.AIAvatar/src/internal/Common/IRestClient.cs
  src/Tizen.AIAvatar/src/internal/Common/RestClient.cs
  src/Tizen.AIAvatar/src/internal/Common/RestClientFactory.cs
  src/Tizen.AIAvatar/src/internal/DefaultAvatar/DefaultAvatarProperties.cs
  src/Tizen.AIAvatar/src/internal/LipSync/LipInfo.cs
  src/Tizen.AIAvatar/src/internal/LipSync/Models/ISingleShotModel.cs
  src/Tizen.AIAvatar/src/internal/LipSync/Models/SoftmaxLinqExtension.cs
  src/Tizen.AIAvatar/src/internal/LipSync/Models/TFVowel6.cs
  src/Tizen.AIAvatar/src/internal/LipSync/Viseme.cs
  src/Tizen.AIAvatar/src/internal/Multimedia/AudioPlayer.cs
  src/Tizen.AIAvatar/src/internal/Multimedia/AudioRecorder.cs
  src/Tizen.AIAvatar/src/internal/Multimedia/RecordBufferChangedEventArgs.cs
  src/Tizen.AIAvatar/src/internal/Uix/TTSLipSyncer.cs
  src/Tizen.AIAvatar/src/internal/Uix/UtteranceText.cs
  src/Tizen.AIAvatar/src/public/Avatar/Animations/AnimationModule/AnimationModule.cs
  src/Tizen.AIAvatar/src/public/Avatar/Animations/AnimationModule/AsyncLipSyncer.cs
  src/Tizen.AIAvatar/src/public/Avatar/Animations/AnimationModule/AvatarMotions.cs
  src/Tizen.AIAvatar/src/public/Avatar/Animations/AnimationModule/BlendShapePlayer.cs
  src/Tizen.AIAvatar/src/public/Avatar/Animations/AnimationModule/EyeBlinker.cs
  src/Tizen.AIAvatar/src/public/Avatar/Animations/AnimationModule/JointTransformer.cs
  src/Tizen.AIAvatar/src/public/Avatar/Animations/AnimationModule/LipSyncer.cs
  src/Tizen.AIAvatar/src/public/Avatar/Animations/AnimationModule/MotionPlayer.cs
  src/Tizen.AIAvatar/src/public/Avatar/Animations/AnimationModuleData/IAnimationModuleData.cs
  src/Tizen.AIAvatar/src/public/Avatar/Animations/AnimationModuleData/LipSyncData.cs
  src/Tizen.AIAvatar/src/public/Avatar/Animations/AnimationModuleData/MotionBehaviorData.cs
  src/Tizen.AIAvatar/src/public/Avatar/Animations/AvatarMotionChangedEventArgs.cs
  src/Tizen.AIAvatar/src/public/Avatar/Animations/AvatarMotionState.cs
  src/Tizen.AIAvatar/src/public/Avatar/AudioOptions.cs
  src/Tizen.AIAvatar/src/public/Avatar/Avatar.cs
  src/Tizen.AIAvatar/src/public/Avatar/Common/BlendShapeType.cs
  src/Tizen.AIAvatar/src/public/Avatar/Common/JointType.cs
  src/Tizen.AIAvatar/src/public/Avatar/Common/NodeType.cs
  src/Tizen.AIAvatar/src/public/Avatar/Controller/AvatarLLM.cs
  src/Tizen.AIAvatar/src/public/Avatar/Controller/AvatarMic.cs
  src/Tizen.AIAvatar/src/public/Avatar/Controller/AvatarTTS.cs
  src/Tizen.AIAvatar/src/public/Avatar/Info/AnimationInfo.cs
  src/Tizen.AIAvatar/src/public/Avatar/Info/AvatarInfo.cs
  src/Tizen.AIAvatar/src/public/Avatar/Info/VoiceInfo.cs
  src/Tizen.AIAvatar/src/public/Avatar/Properties/AvatarBlendShapeIndex.cs
  src/Tizen.AIAvatar/src/public/Avatar/Properties/AvatarJointTransformIndex.cs
  src/Tizen.AIAvatar/src/public/Avatar/Properties/AvatarProperties.cs
  src/Tizen.AIAvatar/src/public/Avatar/Properties/AvatarPropertyMapper.cs
Labels: Internal API Changed, API12

#6023 [Tizen.System.Storage] Register eventhandler if it is already existed
  src/Tizen.System.Storage/Storage/Storage.cs
  src/Tizen.System.Storage/Storage/StorageManager.cs
Labels: API10

#6019 [NUI] change Tizen.NUI.State as Tizen.NUI.NUIApplication.States because it is NUIApplication state
  src/Tizen.NUI/src/public/Application/NUIApplication.cs
Labels: Internal API Changed, Devel-NUI

#6026 [NUI] Fix manual TCT crash issue only on TV target
  src/Tizen.NUI.Components/Controls/Control.cs
Labels: API12

#6033 [NUI] Fix LottieAnimationView not to reference disposed delegate
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
Labels: Devel-NUI

#6034 [NUI] Fix LottieAnimationView not to reference disposed delegate
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
Labels: API11

#6035 [NUI] Fix LottieAnimationView not to reference disposed delegate
  src/Tizen.NUI/src/public/BaseComponents/LottieAnimationView.cs
Labels: API10

#6036 [Tizen.System.Storage] Register eventhandler if it is already existed
  src/Tizen.System.Storage/Storage/Storage.cs
  src/Tizen.System.Storage/Storage/StorageManager.cs
Labels: API12

#6037 [Tizen.System.Storage] Register eventhandler if it is already existed
  src/Tizen.System.Storage/Storage/Storage.cs
  src/Tizen.System.Storage/Storage/StorageManager.cs
Labels: API11
